Energy Grid Optimization & Analysis (EGOA): egoa::BlockCutTree< GraphType > Class Template Reference
egoa::BlockCutTree< GraphType > Class Template Reference final
Block-cut tree related classes and functions
A block-cut tree.
#include <BlockCutTree.hpp>
Classes
class Block
A block.
class CutVertex
Class for cut-vertices.
Public Types
using TGraph = GraphType
Public Member Functions
Basic Properties
Types::count NumberOfBlocks () const
The number of blocks in the block-cut tree.
Types::count NumberOfCutVertices () const
The number of cut-vertices in the block-cut tree.
TGraph const & Graph () const
The underlying graph of the block-cut tree.
Topology
std::vector< Types::blockId > const & BlocksOfVertex (Types::vertexId id) const
All identifiers of the blocks a vertex belongs to.
Types::blockId BlockOfEdge (Types::edgeId id) const
The identifiers of the block an edge belongs to.
bool IsCutVertex (Types::vertexId id) const
Whether a vertex is a cut-vertex.
Block const & BlockAt (Types::blockId id) const
The block with identifier id.
CutVertex const & CutVertexAt (Types::vertexId id) const
The cut-vertex with identifier id.
Static Public Member Functions
static BlockCutTree Build (TGraph const &graph)
Builds a BlockCutTree for a given graph.
Private Member Functions
BlockCutTree (TGraph const &graph)
Private Attributes
Members
std::reference_wrapper< TGraph const > graph_
The underlying graph.
std::vector< Block > blocks_
The blocks in the block-cut tree ordered by their component identifiers.
std::vector< CutVertex > cutVertices_
The cut-vertices in the graph.
std::vector< Types::blockId > blockOfEdge_
For each edge the block it belongs to.
std::vector< std::vector< Types::blockId > > blocksOfVertex_
For each vertex the blocks it belongs to.
Types::count numberOfCutVertices_
The number of cut-vertices.
Friends
class egoa::internal::BlockCutTreeBuilder< TGraph >
Detailed Description
template<typename GraphType>
class egoa::BlockCutTree< GraphType >
A block-cut tree.
The block-cut tree is unrooted.
Todo:
Example how a block-cut tree is constructed and how it can be used.
Template Parameters
GraphType The type of the underlying graph.
Definition at line 52 of file BlockCutTree.hpp.
Member Typedef Documentation
TGraph
template<typename GraphType > using egoa::BlockCutTree< GraphType >::TGraph = GraphType
Definition at line 57 of file BlockCutTree.hpp.
Constructor & Destructor Documentation
BlockCutTree()
template<typename GraphType > egoa::BlockCutTree< GraphType >::BlockCutTree (TGraph const & graph) inline private
Definition at line 60 of file BlockCutTree.hpp.
Member Function Documentation
BlockAt()
template<typename GraphType > Block const & egoa::BlockCutTree< GraphType >::BlockAt (Types::blockId id) const inline
The block with identifier id.
Parameters
[in] id The identifier of the block.
Returns
The block with identifier id.
Definition at line 158 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::blocks_.
BlockOfEdge()
template<typename GraphType > Types::blockId egoa::BlockCutTree< GraphType >::BlockOfEdge (Types::edgeId id) const inline
The identifiers of the block an edge belongs to.
Parameters
[in] id The identifier of the edge.
Returns
The block identifier.
Definition at line 136 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::blockOfEdge_.
BlocksOfVertex()
template<typename GraphType > std::vector< Types::blockId > const & egoa::BlockCutTree< GraphType >::BlocksOfVertex (Types::vertexId id) const inline
All identifiers of the blocks a vertex belongs to.
Parameters
[in] id The identifier of the vertex.
Returns
A vector containing all identifiers of the blocks a vertex belongs to.
Definition at line 125 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::blocksOfVertex_.
Build()
template<typename GraphType > static BlockCutTree egoa::BlockCutTree< GraphType >::Build (TGraph const & graph) inline static
Builds a BlockCutTree for a given graph.
Parameters
graph The graph.
Returns
The BlockCutTree.
Definition at line 78 of file BlockCutTree.hpp.
References egoa::internal::BlockCutTreeBuilder< GraphType >::Build().
CutVertexAt()
template<typename GraphType > CutVertex const & egoa::BlockCutTree< GraphType >::CutVertexAt (Types::vertexId id) const inline
The cut-vertex with identifier id.
Precondition
The vertex with identifier id is a cut-vertex.
Parameters
[in] id The identifier of the cut-vertex.
Returns
The cut-vertex object with identifier id.
Definition at line 171 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::cutVertices_, and egoa::BlockCutTree< GraphType >::IsCutVertex().
Graph()
template<typename GraphType > TGraph const & egoa::BlockCutTree< GraphType >::Graph () const inline
The underlying graph of the block-cut tree.
Returns
The underlying graph.
Definition at line 109 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::graph_.
IsCutVertex()
template<typename GraphType > bool egoa::BlockCutTree< GraphType >::IsCutVertex (Types::vertexId id) const inline
Whether a vertex is a cut-vertex.
Parameters
[in] id The identifier of the vertex.
Returns
true if the vertex is a cut-vertex, false otherwise.
Definition at line 147 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::BlocksOfVertex().
NumberOfBlocks()
template<typename GraphType > Types::count egoa::BlockCutTree< GraphType >::NumberOfBlocks () const inline
The number of blocks in the block-cut tree.
Returns
The number of blocks.
Definition at line 91 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::blocks_.
NumberOfCutVertices()
template<typename GraphType > Types::count egoa::BlockCutTree< GraphType >::NumberOfCutVertices () const inline
The number of cut-vertices in the block-cut tree.
Returns
The number of cut-vertices.
Definition at line 100 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::numberOfCutVertices_.
Friends And Related Symbol Documentation
egoa::internal::BlockCutTreeBuilder< TGraph >
template<typename GraphType > friend class egoa::internal::BlockCutTreeBuilder< TGraph > friend
Definition at line 182 of file BlockCutTree.hpp.
Member Data Documentation
blockOfEdge_
template<typename GraphType > std::vector<Types::blockId> egoa::BlockCutTree< GraphType >::blockOfEdge_ private
For each edge the block it belongs to.
Note that each edge belongs to exactly one block.
Definition at line 325 of file BlockCutTree.hpp.
blocks_
template<typename GraphType > std::vector<Block> egoa::BlockCutTree< GraphType >::blocks_ private
The blocks in the block-cut tree ordered by their component identifiers.
Definition at line 311 of file BlockCutTree.hpp.
blocksOfVertex_
template<typename GraphType > std::vector<std::vector<Types::blockId> > egoa::BlockCutTree< GraphType >::blocksOfVertex_ private
For each vertex the blocks it belongs to.
A vertex is a cut-vertex if and only if it belongs to more than one block. For cut-vertices the first block is the parent block and the remaining blocks are the child blocks. For the root, all blocks are child blocks.
Definition at line 335 of file BlockCutTree.hpp.
cutVertices_
template<typename GraphType > std::vector<CutVertex> egoa::BlockCutTree< GraphType >::cutVertices_ private
The cut-vertices in the graph.
The cut-vertex with identifier id is at position id in the vector. The positions that do not correspond to cut-vertices contain empty objects.
Definition at line 319 of file BlockCutTree.hpp.
graph_
template<typename GraphType > std::reference_wrapper<TGraph const> egoa::BlockCutTree< GraphType >::graph_ private
The underlying graph.
A reference_wrapper is stored instead of a reference to make the block-cut tree assignable.
Definition at line 306 of file BlockCutTree.hpp.
numberOfCutVertices_
template<typename GraphType > Types::count egoa::BlockCutTree< GraphType >::numberOfCutVertices_ private
The number of cut-vertices.
This is stored explicitly because cutVertices_ contains an entry for all vertices.
Definition at line 343 of file BlockCutTree.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Graphs/BlockCutTree.hpp