Energy Grid Optimization & Analysis (EGOA): egoa::Bucket< PriorityQueue > Class Template Reference
egoa::Bucket< PriorityQueue > Class Template Reference
Class for bucket data structure.
#include <Bucket.hpp>
Public Types
using TPriorityQueue = PriorityQueue
using TElement = typename TPriorityQueue::TElement
using TBucket = Bucket< TPriorityQueue >
using TIterator = std::iterator< std::input_iterator_tag, TElement, Types::largeNumber, Types::largeNumber const *, Types::largeNumber >
Public Member Functions
bool HasElement (TElement const &newElement, TElement &existingElement)
void Clear () noexcept
Clear the bucket.
bool Empty () const
Determines if the bucket is empty.
bool EmptyQueue () const
Determines if there are no unprocessed elements in the bucket.
Types::count Size () const
Constructors and Destructor
Bucket ()
Constructs the object.
Comparators for Unprocessed Bucket Elements
Parameters
rhs The right hand side bucket.
Precondition
Neither of the bucket queues is allowed to be empty. Check status of the queue by using EmptyQueue().
Returns
true if the element with an optimal key is <, >, <=, >= than the rhs bucket, false otherwise.
See also
EmptyQueue()
bool operator< (TBucket const &rhs) const
bool operator> (TBucket const &rhs) const
bool operator<= (TBucket const &rhs) const
bool operator>= (TBucket const &rhs) const
Merge an Element into the Bucket
Note that the valid flag for the processed labels might change in some special cases. However, this flag is ignored for processed labels.
Parameters
newElement The new element to merge into the bucket.
Precondition
Note that the element will be moved if the return type is true.
Template Parameters
Domination The domination sense such as weak, strict, or none.
Returns
true if the newElement is added into the bucket, false otherwise (meaning it was dominated in some sense defined by Domination).
template<DominationCriterion Domination = DominationCriterion::weak>
bool Merge (TElement &&newElement)
template<DominationCriterion Domination = DominationCriterion::weak>
bool Merge (TElement &newElement)
template<DominationCriterion Domination = DominationCriterion::weak>
bool Merge (TElement const &newElement)
Element Accessors
bool HasElementAt (Types::index index)
Determines if it has a processed element at position index.
TElement & ElementAt (Types::index index)
Processed element at a certain position index.
TElement & operator[] (Types::index index)
Processed element at a certain position index.
TElement & operator[] (Types::index index) const
Processed element at a certain position index.
TElement const & Top () const
Returns the first valid and unprocessed element.
std::vector< TElement > Optima () const
All elements with an optimum value.
Modifiers
Types::index Pop ()
Pop the first valid element.
std::pair< TElement, Types::index > DeleteTop ()
Delete and return the first valid element.
Comparator Accessors.
...
bucket_.Comparator([](int a, int b) { return a < b; });
...
Precondition
If the comparator is changed to a non standard comparator you have to make sure that the elements comply these conditions, e.g., changing the comparator to "<" implicitly requires that no duplicates are allowed.
Returns
Comparator function pointer.
std::function< bool(TElement const &, TElement const &) > const & Comparator () const
void Comparator (std::function< bool(TElement const &, TElement const &)> comparator)
Element Loops
template<ExecutionPolicy Policy, typename FUNCTION >
void for_all_elements (FUNCTION function)
The for loop over all elements in the bucket.
template<ExecutionPolicy Policy, typename FUNCTION >
void for_all_elements (FUNCTION function) const
The for loop over all elements in the bucket with const access.
template<ExecutionPolicy Policy, typename FUNCTION >
void for_all_processed_elements (FUNCTION function)
The for loop over all processed elements in the bucket.
template<ExecutionPolicy Policy, typename FUNCTION >
void for_all_processed_elements (FUNCTION function) const
The for loop over all processed elements in the bucket.
template<ExecutionPolicy Policy, typename FUNCTION >
void for_all_unprocessed_elements (FUNCTION function)
The for loop over all unprocessed elements in the bucket.
template<ExecutionPolicy Policy, typename FUNCTION >
void for_all_unprocessed_elements (FUNCTION function) const
The for loop over all unprocessed elements in the bucket.
template<ExecutionPolicy Policy, typename FUNCTION >
Types::real for_all_optima (FUNCTION function)
The for loop over all elements with optimal value.
template<ExecutionPolicy Policy, typename FUNCTION >
Types::real for_all_optima (FUNCTION function) const
The for loop over all elements with optimal value with const access.
Private Member Functions
Add an Element
Types::index MoveToProcessed (TElement &&element)
Move element to processed elements.
void Insert (TElement &&element)
Insert an element.
Number of Elements
Types::count NumberOfProcessedElements () const noexcept
Number of processed elements.
Types::count NumberOfUnprocessedElements () const noexcept
Number of valid unprocessed elements.
Domination
template<DominationCriterion Domination>
bool Dominates (TElement const &lhs, TElement const &rhs) const
Checks if lhs dominates rhs in a certain sense.
Ensuring Invariants
void PopInvalidUnprocessedElements ()
Pops invalid unprocessed elements until unprocessedElements_ is empty or the top element is valid.
Private Attributes
std::vector< TElement > processedElements_
TPriorityQueue unprocessedElements_
Types::count numberOfValidUnprocessedElements_
Detailed Description
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >>
class egoa::Bucket< PriorityQueue >
Class for bucket data structure.
egoa::Bucket<egoa::BinaryHeap<int>, int> bucket;
Template Parameters
PriorityQueue Type of the priority queue used within the bucket, e.g., BinaryHeap. The PriorityQueue has to provide the following interface.
Function Description
Top Returns the top element.
Search Search for the first match.
Insert, operator+=, Emplace Inserts one or more elements.
BuildWith Builds a heap.
DeleteTop, Pop Deletes the top element.
Clear Clears the heap.
ChangeKey Changes the key of one element.
DecreaseKey Decreases the key of an element.
Empty, Size Capacity operations.
Comparator, Maximize, Minimize Comparators.
operator==, operator!=, Equality operators.
IsEqualTo | swap | Swap two heaps. operator<< | Writes the heap into an output stream.
Definition at line 65 of file Bucket.hpp.
Member Typedef Documentation
TBucket
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> using egoa::Bucket< PriorityQueue >::TBucket = Bucket< TPriorityQueue >
Definition at line 70 of file Bucket.hpp.
TElement
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> using egoa::Bucket< PriorityQueue >::TElement = typename TPriorityQueue::TElement
Definition at line 69 of file Bucket.hpp.
TIterator
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> using egoa::Bucket< PriorityQueue >::TIterator = std::iterator< std::input_iterator_tag , TElement , Types::largeNumber , Types::largeNumber const * , Types::largeNumber>
Definition at line 71 of file Bucket.hpp.
TPriorityQueue
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> using egoa::Bucket< PriorityQueue >::TPriorityQueue = PriorityQueue
Definition at line 68 of file Bucket.hpp.
Constructor & Destructor Documentation
Bucket()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> egoa::Bucket< PriorityQueue >::Bucket () inline
Constructs the object.
Definition at line 84 of file Bucket.hpp.
Member Function Documentation
Clear()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> void egoa::Bucket< PriorityQueue >::Clear () inline noexcept
Clear the bucket.
Definition at line 423 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::numberOfValidUnprocessedElements_, egoa::Bucket< PriorityQueue >::processedElements_, and egoa::Bucket< PriorityQueue >::unprocessedElements_.
Comparator() [1/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> std::function< bool(TElement const &, TElement const &) > const & egoa::Bucket< PriorityQueue >::Comparator () const inline
Definition at line 451 of file Bucket.hpp.
Comparator() [2/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> void egoa::Bucket< PriorityQueue >::Comparator (std::function< bool(TElement const &, TElement const &)> comparator) inline
Definition at line 456 of file Bucket.hpp.
DeleteTop()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> std::pair< TElement, Types::index > egoa::Bucket< PriorityQueue >::DeleteTop () inline
Delete and return the first valid element.
Returns the first unprocessed valid label and removes it from the set of unprocessed labels. The first unprocessed label is the one with the smallest key (e.g. for VoltageAngleDifferenceLabel the key would be the susceptance norm times the minimum capacity).
Precondition
The queue—meaning the unprocessed items—is not allowed to be empty.
Returns
The element with a optimal key.
Definition at line 410 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::EmptyQueue(), egoa::Bucket< PriorityQueue >::Pop(), and egoa::Bucket< PriorityQueue >::processedElements_.
Dominates()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<DominationCriterion Domination> bool egoa::Bucket< PriorityQueue >::Dominates (TElement const & lhs, TElement const & rhs) const inline private
Checks if lhs dominates rhs in a certain sense.
Parameters
lhs The left hand side element.
rhs The right hand side element.
Template Parameters
Domination The domination sense such as weak, strict, or none.
Returns
true if the lhs dominates the rhs, false otherwise.
Definition at line 770 of file Bucket.hpp.
ElementAt()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> TElement & egoa::Bucket< PriorityQueue >::ElementAt (Types::index index) inline
Processed element at a certain position index.
Parameters
[in] index The position of a processed element.
Precondition
There are processed elements and #HasElementAt(index) is true.
Returns
The processed element at the position index.
Definition at line 258 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::HasElementAt(), egoa::Bucket< PriorityQueue >::NumberOfProcessedElements(), and egoa::Bucket< PriorityQueue >::processedElements_.
Empty()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> bool egoa::Bucket< PriorityQueue >::Empty () const inline
Determines if the bucket is empty.
Returns
true if empty, false otherwise.
Definition at line 469 of file Bucket.hpp.
References egoa::PriorityQueue< Type >::Empty(), egoa::Bucket< PriorityQueue >::processedElements_, and egoa::Bucket< PriorityQueue >::unprocessedElements_.
EmptyQueue()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> bool egoa::Bucket< PriorityQueue >::EmptyQueue () const inline
Determines if there are no unprocessed elements in the bucket.
Returns
true if empty, false otherwise.
Definition at line 479 of file Bucket.hpp.
References egoa::PriorityQueue< Type >::Empty(), and egoa::Bucket< PriorityQueue >::unprocessedElements_.
for_all_elements() [1/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<ExecutionPolicy Policy, typename FUNCTION > void egoa::Bucket< PriorityQueue >::for_all_elements (FUNCTION function) inline
The for loop over all elements in the bucket.
Loop over all processed and unprocessed elements.
Parameters
[in] function The function, e.g., lambda function.
[](TElement & element)
{
    // Do something with the element object.
}
Template Parameters
Policy true if the loop is run in parallel using OpenMP, false otherwise.
FUNCTION The function pointer.
Definition at line 512 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::PopInvalidUnprocessedElements().
for_all_elements() [2/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<ExecutionPolicy Policy, typename FUNCTION > void egoa::Bucket< PriorityQueue >::for_all_elements (FUNCTION function) const inline
The for loop over all elements in the bucket with const access.
Loop over all processed and unprocessed elements.
Parameters
[in] function The function, e.g., lambda function.
[](TElement const & element)
{
    // Do something with the element object.
}
Template Parameters
Policy true if the loop is run in parallel using OpenMP, false otherwise.
FUNCTION The function pointer.
Definition at line 539 of file Bucket.hpp.
for_all_optima() [1/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<ExecutionPolicy Policy, typename FUNCTION > Types::real egoa::Bucket< PriorityQueue >::for_all_optima (FUNCTION function) inline
The for loop over all elements with optimal value.
Loop over all unprocessed elements having an optimal value.
Parameters
[in] function The function, e.g., lambda function.
[](TElement & element)
{
    // Do something with the element object.
}
Template Parameters
Policy true if the loop is run in parallel using OpenMP, false otherwise.
FUNCTION The function pointer.
Definition at line 667 of file Bucket.hpp.
for_all_optima() [2/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<ExecutionPolicy Policy, typename FUNCTION > Types::real egoa::Bucket< PriorityQueue >::for_all_optima (FUNCTION function) const inline
The for loop over all elements with optimal value with const access.
Loop over all unprocessed elements having an optimal value.
Parameters
[in] function The function, e.g., lambda function
[](TElement const & element)
{
    // Do something with the element object.
}
Template Parameters
Policy true if the loop is run in parallel using OpenMP, false otherwise.
FUNCTION The function pointer.
Definition at line 693 of file Bucket.hpp.
for_all_processed_elements() [1/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<ExecutionPolicy Policy, typename FUNCTION > void egoa::Bucket< PriorityQueue >::for_all_processed_elements (FUNCTION function) inline
The for loop over all processed elements in the bucket.
Parameters
[in] function The function, e.g., lambda function
[](TElement & element)
{
    // Do something with the element object.
}
Template Parameters
Policy true if the loop is run in parallel using OpenMP, false otherwise.
FUNCTION The function pointer.
Definition at line 563 of file Bucket.hpp.
for_all_processed_elements() [2/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<ExecutionPolicy Policy, typename FUNCTION > void egoa::Bucket< PriorityQueue >::for_all_processed_elements (FUNCTION function) const inline
The for loop over all processed elements in the bucket.
Parameters
[in] function The function, e.g., lambda function
[](TElement const & element)
{
    Do something with the element object.
}
Template Parameters
Policy true if the loop is run in parallel using OpenMP, false otherwise.
FUNCTION The function pointer.
Definition at line 587 of file Bucket.hpp.
for_all_unprocessed_elements() [1/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<ExecutionPolicy Policy, typename FUNCTION > void egoa::Bucket< PriorityQueue >::for_all_unprocessed_elements (FUNCTION function) inline
The for loop over all unprocessed elements in the bucket.
If the function returns true the loop will be continued, if false this emulates a break.
Parameters
[in] function The function, e.g., lambda function.
[](TElement & element)
{
    // Do something with the element object.
}
Template Parameters
Policy true if the loop is run in parallel using OpenMP, false otherwise.
FUNCTION The function pointer.
Definition at line 614 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::PopInvalidUnprocessedElements().
for_all_unprocessed_elements() [2/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<ExecutionPolicy Policy, typename FUNCTION > void egoa::Bucket< PriorityQueue >::for_all_unprocessed_elements (FUNCTION function) const inline
The for loop over all unprocessed elements in the bucket.
If the function returns true the loop will be continued, if false this emulates a break.
Parameters
[in] function The function, e.g., lambda function.
[](TElement const & element)
{
    // Do something with the element object.
}
Template Parameters
Policy true if the loop is run in parallel using OpenMP, false otherwise.
FUNCTION The function pointer.
Definition at line 642 of file Bucket.hpp.
HasElement()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> bool egoa::Bucket< PriorityQueue >::HasElement (TElement const & newElement, TElement & existingElement) inline
Todo:
Think about it
Definition at line 208 of file Bucket.hpp.
HasElementAt()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> bool egoa::Bucket< PriorityQueue >::HasElementAt (Types::index index) inline
Determines if it has a processed element at position index.
Parameters
[in] index The position of an element
Returns
true if it has an element at that position, false otherwise.
Definition at line 242 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::NumberOfProcessedElements().
Insert()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> void egoa::Bucket< PriorityQueue >::Insert (TElement && element) inline private
Insert an element.
Parameters
element The element.
Definition at line 726 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::unprocessedElements_.
Merge() [1/3]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<DominationCriterion Domination = DominationCriterion::weak> bool egoa::Bucket< PriorityQueue >::Merge (TElement && newElement) inline
Definition at line 158 of file Bucket.hpp.
Merge() [2/3]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<DominationCriterion Domination = DominationCriterion::weak> bool egoa::Bucket< PriorityQueue >::Merge (TElement & newElement) inline
Definition at line 193 of file Bucket.hpp.
Merge() [3/3]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> template<DominationCriterion Domination = DominationCriterion::weak> bool egoa::Bucket< PriorityQueue >::Merge (TElement const & newElement) inline
Definition at line 201 of file Bucket.hpp.
MoveToProcessed()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> Types::index egoa::Bucket< PriorityQueue >::MoveToProcessed (TElement && element) inline private
Move element to processed elements.
After moving it to the list of processed elements its identifier corresponds to the index.
Parameters
element The element to move to unprocessed elements.
Precondition
Function
See also
Pop().
Definition at line 714 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::processedElements_.
NumberOfProcessedElements()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> Types::count egoa::Bucket< PriorityQueue >::NumberOfProcessedElements () const inline private noexcept
Number of processed elements.
Returns
The number of processed elements.
Definition at line 740 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::processedElements_.
NumberOfUnprocessedElements()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> Types::count egoa::Bucket< PriorityQueue >::NumberOfUnprocessedElements () const inline private noexcept
Number of valid unprocessed elements.
Returns
The number of valid unprocessed elements.
Definition at line 750 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::numberOfValidUnprocessedElements_.
operator<()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> bool egoa::Bucket< PriorityQueue >::operator< (TBucket< PriorityQueue > const & rhs) const inline
Definition at line 109 of file Bucket.hpp.
operator<=()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> bool egoa::Bucket< PriorityQueue >::operator<= (TBucket< PriorityQueue > const & rhs) const inline
Definition at line 123 of file Bucket.hpp.
operator>()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> bool egoa::Bucket< PriorityQueue >::operator> (TBucket< PriorityQueue > const & rhs) const inline
Definition at line 116 of file Bucket.hpp.
operator>=()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> bool egoa::Bucket< PriorityQueue >::operator>= (TBucket< PriorityQueue > const & rhs) const inline
Definition at line 130 of file Bucket.hpp.
operator[]() [1/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> TElement & egoa::Bucket< PriorityQueue >::operator[] (Types::index index) inline
Processed element at a certain position index.
Parameters
[in] index The position of a processed element.
Precondition
There are processed elements and #HasElementAt(index) is true.
Returns
The processed element at the position index.
Definition at line 277 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::HasElementAt(), egoa::Bucket< PriorityQueue >::NumberOfProcessedElements(), and egoa::Bucket< PriorityQueue >::processedElements_.
operator[]() [2/2]
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> TElement & egoa::Bucket< PriorityQueue >::operator[] (Types::index index) const inline
Processed element at a certain position index.
Parameters
[in] index The position of a processed element.
Precondition
There are processed elements and #HasElementAt(index) is true.
Returns
The processed element at the position index.
Definition at line 296 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::HasElementAt(), egoa::Bucket< PriorityQueue >::NumberOfProcessedElements(), and egoa::Bucket< PriorityQueue >::processedElements_.
Optima()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> std::vector< TElement > egoa::Bucket< PriorityQueue >::Optima () const inline
All elements with an optimum value.
Get all elements that have an optimum value, e.g. for the VoltageAngleDifferenceLabel an optimum corresponds to the minimum delta theta value of the path.
Note
This function does not change the bucket. All elements stay in the queue. The equality check depends on the element equality check.
Todo:
Is this loop sufficient for unprocessed labels only?
Returns
Vector of elements with optimum value
Definition at line 336 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::processedElements_, and egoa::Bucket< PriorityQueue >::unprocessedElements_.
Pop()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> Types::index egoa::Bucket< PriorityQueue >::Pop () inline
Pop the first valid element.
Returns the first unprocessed valid label and removes it from the set of unprocessed labels. The first unprocessed label is the one with the smallest key (e.g. for VoltageAngleDifferenceLabel the key would be the susceptance norm).
Precondition
The queue—meaning the unprocessed items—is not allowed to be empty.
Returns
The element with a optimal key.
Definition at line 385 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::EmptyQueue(), egoa::Bucket< PriorityQueue >::MoveToProcessed(), egoa::Bucket< PriorityQueue >::numberOfValidUnprocessedElements_, egoa::Bucket< PriorityQueue >::PopInvalidUnprocessedElements(), and egoa::Bucket< PriorityQueue >::unprocessedElements_.
PopInvalidUnprocessedElements()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> void egoa::Bucket< PriorityQueue >::PopInvalidUnprocessedElements () inline private
Pops invalid unprocessed elements until unprocessedElements_ is empty or the top element is valid.
Definition at line 785 of file Bucket.hpp.
References egoa::PriorityQueue< Type >::Empty(), egoa::PriorityQueue< Type >::Top(), and egoa::Bucket< PriorityQueue >::unprocessedElements_.
Size()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> Types::count egoa::Bucket< PriorityQueue >::Size () const inline
Definition at line 484 of file Bucket.hpp.
Top()
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> TElement const & egoa::Bucket< PriorityQueue >::Top () const inline
Returns the first valid and unprocessed element.
Top returns an unprocessed element that has an optimal key (e.g. for VoltageAngleDifferenceLabel the key would be the susceptance norm).
Precondition
The queue is not empty meaning EmptyQueue() is false.
Returns
The element with an optimal key.
Definition at line 315 of file Bucket.hpp.
References egoa::Bucket< PriorityQueue >::EmptyQueue(), egoa::PriorityQueue< Type >::Top(), and egoa::Bucket< PriorityQueue >::unprocessedElements_.
Member Data Documentation
numberOfValidUnprocessedElements_
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> Types::count egoa::Bucket< PriorityQueue >::numberOfValidUnprocessedElements_ private
The number of valid unprocessed elements.
Definition at line 806 of file Bucket.hpp.
processedElements_
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> std::vector<TElement> egoa::Bucket< PriorityQueue >::processedElements_ private
The processed elements that do not change their status and stay valid
Definition at line 804 of file Bucket.hpp.
unprocessedElements_
template<typename PriorityQueue = BinaryHeap<VoltageAngleDifferenceLabel<Edges::Edge<Edges::ElectricalProperties> > >> TPriorityQueue egoa::Bucket< PriorityQueue >::unprocessedElements_ private
The unprocessed elements that might change their status, e.g., to invalid
Definition at line 805 of file Bucket.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Container/Queues/Bucket.hpp