Energy Grid Optimization & Analysis (EGOA): egoa::DynamicGraph< VertexProperties, EdgeProperties > Class Template Reference
egoa::DynamicGraph< VertexProperties, EdgeProperties > Class Template Reference
A graph data structure that supports adding and removing vertices and edges.
#include <DynamicGraph.hpp>
Classes
class OmittingVectorView
A view on a vector, in which some elements are invalid.
Public Types
using TGraph = DynamicGraph< VertexProperties, EdgeProperties >
using TVertexProperties = VertexProperties
using TVertex = Vertices::Vertex< TVertexProperties >
using TVertexId = Types::vertexId
using TEdgeProperties = EdgeProperties
using TEdge = Edges::Edge< TEdgeProperties >
using TEdgeId = Types::edgeId
using TVerticesView = OmittingVectorView< TVertex, false >
using TConstVerticesView = OmittingVectorView< TVertex, true >
using TEdgesView = OmittingVectorView< TEdge, false >
using TConstEdgesView = OmittingVectorView< TEdge, true >
Public Member Functions
DynamicGraph (Types::name name="")
The constructor.
Getter and setter
Types::name Name () const
The name of the graph.
Types::count NumberOfVertices () const
The number of vertices in the graph.
Types::count NumberOfEdges () const
The number of edges in the graph.
Vertex related methods
TVerticesView Vertices ()
A view on the vertices.
TConstVerticesView Vertices () const
A view on the vertices.
bool VertexExists (Types::vertexId id) const
Whether a vertex with identifier id exists in the graph.
TVertex & VertexAt (Types::vertexId id)
The vertex with identifier id.
TVertex const & VertexAt (Types::vertexId id) const
The vertex with identifier id.
TVertex & VertexAt (int id)=delete
TVertex & VertexAt (char id)=delete
const TVertex & VertexAt (int id) const =delete
const TVertex & VertexAt (char id) const =delete
Types::vertexId VertexId (TVertex const &vertex) const
The vertex identifier of a vertex object.
Types::vertexId AddVertex (TVertexProperties &properties)
Adds a vertex.
Types::vertexId AddVertex (TVertexProperties const &properties)
Adds a vertex.
Types::vertexId AddVertex (TVertexProperties &&properties)
Adds a vertex.
void RemoveVertexAt (Types::vertexId id)
Remove a vertex and all incident edges.
template<typename FUNCTION >
auto MapVertices (FUNCTION function) const -> std::vector< decltype(function(std::declval< Types::vertexId >(), std::declval< TVertex >()))>
Applies function to all vertices and collects the result in a vector.
std::vector< Types::vertexId > NeighborsOf (Types::vertexId id) const
Neighbors of a vertex.
void NeighborsOf (Types::vertexId id, std::vector< Types::vertexId > &vertexIds) const
Neighbors of a vertex.
Types::count InDegreeAt (Types::vertexId id) const
The indegree of the vertex with identifier id.
Types::count OutDegreeAt (Types::vertexId id) const
The outdegree of the vertex with identifier id.
Types::count DegreeAt (Types::vertexId id) const
The degree of the vertex with identifier id.
std::vector< Types::edgeId > const & InEdgeIdsAt (Types::vertexId id) const
The identifiers of all incoming edges.
std::vector< Types::edgeId > const & OutEdgeIdsAt (Types::vertexId id) const
The identifiers of all outgoing edges.
std::vector< Types::edgeId > EdgeIdsAt (Types::vertexId id) const
All edge identifiers of edges incident to a vertex.
void EdgeIdsAt (Types::vertexId id, std::vector< Types::edgeId > &edgeIds) const
All edge identifiers of edges incident to a vertex are added to the end of the vector edgeIds.
Edge Related Methods
TEdgesView Edges ()
A view on the edges.
TConstEdgesView Edges () const
A view on the edges.
bool EdgeExists (Types::edgeId id) const
Whether an edge with identifier id exists.
TEdge & EdgeAt (Types::edgeId id)
The edge with identifier id.
TEdge const & EdgeAt (Types::edgeId id) const
The edge with identifier id.
Types::edgeId EdgeId (Types::vertexId source, Types::vertexId target) const
Searches for the identifier of the edge .
TEdge & Edge (Types::vertexId source, Types::vertexId target)
Searches for an edge .
const TEdge & Edge (Types::vertexId source, Types::vertexId target) const
Searches for an edge .
Types::edgeId AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties &properties)
Adds an edge to the set of edges .
Types::edgeId AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties const &properties)
Adds an edge to the set of edges .
Types::edgeId AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties &&properties)
Adds an edge to the set of edges .
void RemoveEdgeAt (Types::edgeId id)
Removes the edge with identifier id.
void RemoveAllIncidentEdgesAt (Types::vertexId id)
Removes all incident edges at the vertex with identifier id.
template<typename FUNCTION >
auto MapEdges (FUNCTION function) const -> std::vector< decltype(function(std::declval< Types::edgeId >(), std::declval< TEdge >()))>
Applies function to all edges and collects the result in a vector.
TEdge & EdgeAt (int index)=delete
TEdge & EdgeAt (char index)=delete
const TEdge & EdgeAt (int index) const =delete
const TEdge & EdgeAt (char index) const =delete
Types::edgeId EdgeId (int source, int target) const =delete
Types::edgeId EdgeId (char source, char target) const =delete
Types::edgeId EdgeId (int source, char target) const =delete
Types::edgeId EdgeId (char source, int target) const =delete
TEdge & Edge (int source, int target)=delete
TEdge & Edge (char source, char target)=delete
TEdge & Edge (char source, int target)=delete
TEdge & Edge (int source, char target)=delete
const TEdge & Edge (int source, int target) const =delete
const TEdge & Edge (char source, char target) const =delete
const TEdge & Edge (int source, char target) const =delete
const TEdge & Edge (char source, int target) const =delete
Update Methods
void UpdateVertices ()
Update vertices.
void UpdateEdges ()
Deletes all edges that were marked as deleted.
Graph Properties
Types::count MinDegree (Types::vertexId &id) const
The minimum degree of the graph .
Types::count MinDegree () const
The minimum degree of the graph .
Types::count MaxDegree (Types::vertexId &id) const
The maximum degree of the graph .
Types::count MaxDegree () const
The maximum degree of the graph .
Vertex Loops
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertex_identifiers (FUNCTION function) const
The for loop over all vertex identifiers in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertices (FUNCTION function)
The for loop over all vertex objects in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertices (FUNCTION function) const
The for loop over all vertex objects in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertex_tuples (FUNCTION function)
The for loop over all pairs of vertex identifiers and vertex objects in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertex_tuples (FUNCTION function) const
The for loop over all pairs of vertex identifiers and vertex objects in the graph.
Edge loops
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edge_identifiers (FUNCTION function) const
The for loop over all indentifiers of edges in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges (FUNCTION function)
The for loop over all edges in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges (FUNCTION function) const
The for loop over all edges in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edge_tuples (FUNCTION function)
The for loop over all pairs of edge identifiers and edge objects in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edge_tuples (FUNCTION function) const
The for loop over all pairs of edge identifiers and edge objects in the graph.
Neighborhood Loops
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges_at (TVertex const &vertex, FUNCTION function)
The for loop over all edges at a vertex object.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges_at (TVertex const &vertex, FUNCTION function) const
The for loop over all edges at a vertex object.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges_at (Types::vertexId vertexId, FUNCTION function)
The for loop over all edges at a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges_at (Types::vertexId vertexId, FUNCTION function) const
The for loop over all edges at a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_in_edges_at (TVertex const &vertex, FUNCTION function)
The for loop over all incoming edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_in_edges_at (TVertex const &vertex, FUNCTION function) const
The for loop over all incoming edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_in_edges_at (Types::vertexId vertexId, FUNCTION function)
The for loop over all incoming edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_in_edges_at (Types::vertexId vertexId, FUNCTION function) const
The for loop over all incoming edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_out_edges_at (TVertex const &vertex, FUNCTION function)
The for loop over all outgoing edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_out_edges_at (TVertex const &vertex, FUNCTION function) const
The for loop over all outgoing edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_out_edges_at (Types::vertexId vertexId, FUNCTION function)
The for loop over all outgoing edges.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_out_edges_at (Types::vertexId vertexId, FUNCTION function) const
The for loop over all outgoing edges.
Private Attributes
Types::name name_
std::vector< TVertex > vertices_
std::vector< bool > vertexExists_
Types::count numberOfVertices_ = 0
std::vector< TEdge > edges_
std::vector< bool > edgeExists_
Types::count numberOfEdges_ = 0
std::vector< std::vector< Types::edgeId > > inEdgeIds_
std::vector< std::vector< Types::edgeId > > outEdgeIds_
Detailed Description
template<typename VertexProperties, typename EdgeProperties>
class egoa::DynamicGraph< VertexProperties, EdgeProperties >
A graph data structure that supports adding and removing vertices and edges.
Both VertexProperties and EdgeProperties must be able to store an identifier, which can be accessed in the following way. Here, vertex and constVertex are objects of type VertexProperties and VertexProperties const, respectively, and vId is of type Types::vertexId. Similarly, edge and constEdge are objects of type EdgeProperties and EdgeProperties const, respectively, and eId is of type Types::edgeId.
Operation Effect
vertex.Identifier() = vId;
The identifier of vertex is set to vId.
Types::vertexId vId = constVertex.Identifier();
vId is set to the identifier of vertex.
edge.Identifier() = eId;
The identifier of edge is set to eId.
Types::edgeId eId = constEdge.Identifier();
eId is set to the identifier of edge.
Types::vertexId vId = constEdge.Source();
vId is set to the identifier of the source of edge.
Types::vertexId vId = constEdge.Target();
vId is set to the identifier of the target of edge.
Template Parameters
VertexProperties The type of the vertices.
EdgeProperties The type of the edges.
Definition at line 50 of file DynamicGraph.hpp.
Member Typedef Documentation
TConstEdgesView
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TConstEdgesView = OmittingVectorView<TEdge, true>
Definition at line 68 of file DynamicGraph.hpp.
TConstVerticesView
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TConstVerticesView = OmittingVectorView<TVertex, true>
Definition at line 66 of file DynamicGraph.hpp.
TEdge
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TEdge = Edges::Edge<TEdgeProperties>
Definition at line 62 of file DynamicGraph.hpp.
TEdgeId
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TEdgeId = Types::edgeId
Definition at line 63 of file DynamicGraph.hpp.
TEdgeProperties
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TEdgeProperties = EdgeProperties
Definition at line 61 of file DynamicGraph.hpp.
TEdgesView
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TEdgesView = OmittingVectorView<TEdge, false>
Definition at line 67 of file DynamicGraph.hpp.
TGraph
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TGraph = DynamicGraph<VertexProperties, EdgeProperties>
Definition at line 55 of file DynamicGraph.hpp.
TVertex
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TVertex = Vertices::Vertex<TVertexProperties>
Definition at line 58 of file DynamicGraph.hpp.
TVertexId
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TVertexId = Types::vertexId
Definition at line 59 of file DynamicGraph.hpp.
TVertexProperties
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TVertexProperties = VertexProperties
Definition at line 57 of file DynamicGraph.hpp.
TVerticesView
template<typename VertexProperties , typename EdgeProperties > using egoa::DynamicGraph< VertexProperties, EdgeProperties >::TVerticesView = OmittingVectorView<TVertex, false>
Definition at line 65 of file DynamicGraph.hpp.
Constructor & Destructor Documentation
DynamicGraph()
template<typename VertexProperties , typename EdgeProperties > egoa::DynamicGraph< VertexProperties, EdgeProperties >::DynamicGraph (Types::name name = "") inline explicit
The constructor.
Parameters
[in] name The name of the graph. The default value is "".
Definition at line 75 of file DynamicGraph.hpp.
Member Function Documentation
AddEdge() [1/3]
template<typename VertexProperties , typename EdgeProperties > Types::edgeId egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties && properties) inline
Adds an edge to the set of edges .
Precondition
Source and target of the edge are existing vertices.
Parameters
[in] source The source vertex identifier.
[in] target The target vertex identifier.
properties The vertex properties.
Returns
The edge identifier.
Definition at line 689 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::edgeExists_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::edges_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfEdges_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::outEdgeIds_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
AddEdge() [2/3]
template<typename VertexProperties , typename EdgeProperties > Types::edgeId egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties & properties) inline
Adds an edge to the set of edges .
The identifier of the edge passed as argument is set to the ID of the edge in the graph.
Precondition
Source and target of the edge are existing vertices.
Parameters
edge The edge object.
Returns
The edge identifier.
Definition at line 649 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddEdge(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
AddEdge() [3/3]
template<typename VertexProperties , typename EdgeProperties > Types::edgeId egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties const & properties) inline
Adds an edge to the set of edges .
Precondition
Source and target of the edge are existing vertices.
Parameters
[in] source The source vertex identifier.
[in] target The target vertex identifier.
properties The vertex properties.
Returns
The edge identifier.
Definition at line 669 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddEdge(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
AddVertex() [1/3]
template<typename VertexProperties , typename EdgeProperties > Types::vertexId egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddVertex (TVertexProperties && properties) inline
Adds a vertex.
Parameters
properties The vertex properties.
Returns
The identifier of the vertex.
Definition at line 228 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfVertices_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::outEdgeIds_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertexExists_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertices_.
AddVertex() [2/3]
template<typename VertexProperties , typename EdgeProperties > Types::vertexId egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddVertex (TVertexProperties & properties) inline
Adds a vertex.
The identifier of the vertex passed as argument is set to the identifier of the vertex in the graph.
Parameters
properties The vertex properties.
Returns
The identifier of the vertex.
Definition at line 204 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddVertex(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
AddVertex() [3/3]
template<typename VertexProperties , typename EdgeProperties > Types::vertexId egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddVertex (TVertexProperties const & properties) inline
Adds a vertex.
Parameters
properties The vertex properties.
Returns
The identifier of the vertex.
Definition at line 216 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::AddVertex(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
DegreeAt()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::DegreeAt (Types::vertexId id) const inline
The degree of the vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The number of incident edges.
Definition at line 389 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::InDegreeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::OutDegreeAt(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
Edge() [1/2]
template<typename VertexProperties , typename EdgeProperties > TEdge & egoa::DynamicGraph< VertexProperties, EdgeProperties >::Edge (Types::vertexId source, Types::vertexId target) inline
Searches for an edge .
Precondition
Both source and target are identifiers of existing vertices, and there is an edge from source to target.
Parameters
[in] source The source vertex of the edge .
[in] target The target vertex of the edge .
Returns
The edge .
Definition at line 602 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeId(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
Edge() [2/2]
template<typename VertexProperties , typename EdgeProperties > const TEdge & egoa::DynamicGraph< VertexProperties, EdgeProperties >::Edge (Types::vertexId source, Types::vertexId target) const inline
Searches for an edge .
Precondition
Both source and target are identifiers of existing vertices, and there is an edge from source to target.
Parameters
[in] source The source vertex of the edge .
[in] target The target vertex of the edge .
Returns
The edge .
Definition at line 627 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeId(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
EdgeAt() [1/2]
template<typename VertexProperties , typename EdgeProperties > TEdge & egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeAt (Types::edgeId id) inline
The edge with identifier id.
Precondition
The edge with identifier id exists.
Parameters
[in] id The edge identifier.
Returns
The edge object with identifier id.
Definition at line 528 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeExists(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::edges_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
EdgeAt() [2/2]
template<typename VertexProperties , typename EdgeProperties > TEdge const & egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeAt (Types::edgeId id) const inline
The edge with identifier id.
Precondition
The edge with identifier id exists.
Parameters
[in] id The edge identifier.
Returns
The edge object with identifier id.
Definition at line 543 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeExists(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::edges_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
EdgeExists()
template<typename VertexProperties , typename EdgeProperties > bool egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeExists (Types::edgeId id) const inline
Whether an edge with identifier id exists.
Time complexity: .
Parameters
[in] id The edge identifier.
Returns
true if an edge with identifier id exists, false otherwise.
Definition at line 514 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::edgeExists_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
EdgeId()
template<typename VertexProperties , typename EdgeProperties > Types::edgeId egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeId (Types::vertexId source, Types::vertexId target) const inline
Searches for the identifier of the edge .
If no such edge exists, Const::NONE is returned.
Precondition
Both source and target are identifiers of existing vertices.
Parameters
[in] source The source vertex of the edge .
[in] target The target vertex of the edge .
Returns
The edge identifier, or Const::NONE if the edge does not exist.
Definition at line 564 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::InDegreeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::OutDegreeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::outEdgeIds_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
EdgeIdsAt() [1/2]
template<typename VertexProperties , typename EdgeProperties > std::vector< Types::edgeId > egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeIdsAt (Types::vertexId id) const inline
All edge identifiers of edges incident to a vertex.
The order of the identifiers is unspecified.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The edge identifiers at a vertex id.
Definition at line 435 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeIdsAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
EdgeIdsAt() [2/2]
template<typename VertexProperties , typename EdgeProperties > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeIdsAt (Types::vertexId id, std::vector< Types::edgeId > & edgeIds) const inline
All edge identifiers of edges incident to a vertex are added to the end of the vector edgeIds.
The order of the identifiers is unspecified.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex id
edgeIds The vector to which the edge identifiers are appended.
Definition at line 454 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::InEdgeIdsAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::OutEdgeIdsAt(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
Edges() [1/2]
template<typename VertexProperties , typename EdgeProperties > TEdgesView egoa::DynamicGraph< VertexProperties, EdgeProperties >::Edges () inline
A view on the edges.
The edges can be modified via this view.
        If an edge is added or removed, the view is still valid but
        the iterators obtained via this view are invalid.
        If the graph is destroyed, all views are invalid and calling
        member functions on them has undefined behavior.
Definition at line 481 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::edgeExists_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::edges_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfEdges_.
Edges() [2/2]
template<typename VertexProperties , typename EdgeProperties > TConstEdgesView egoa::DynamicGraph< VertexProperties, EdgeProperties >::Edges () const inline
A view on the edges.
The edges cannot be modified via this view.
        If an edge is added or removed, the view is still valid but
        the iterators obtained via this view are invalid.
        If the graph is destroyed, all views are invalid and calling
        member functions on them has undefined behavior.
Definition at line 498 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::edgeExists_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::edges_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfEdges_.
for_all_edge_identifiers()
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_edge_identifiers (FUNCTION function) const inline
The for loop over all indentifiers of edges in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept one argument of type Types::edgeId, e.g.,
[](Types::edgeId edgeId)
{
    // Do something with the edge identifier.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1235 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edge_tuples() [1/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_edge_tuples (FUNCTION function) inline
The for loop over all pairs of edge identifiers and edge objects in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept two arguments of types Types::edgeId and TEdge, e.g.,
[](Types::edgeId edgeId, TEdge & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1308 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edge_tuples() [2/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_edge_tuples (FUNCTION function) const inline
The for loop over all pairs of edge identifiers and edge objects in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept two arguments of types Types::edgeId and TEdge, e.g.,
[](Types::edgeId edgeId, TEdge const & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1333 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges() [1/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_edges (FUNCTION function) inline
The for loop over all edges in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept one argument of type TEdge, e.g.,
[](TEdge & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy..
FUNCTION The type of the function object.
Definition at line 1259 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges() [2/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_edges (FUNCTION function) const inline
The for loop over all edges in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept one argument of type TEdge, e.g.,
[](TEdge const & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1283 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges_at() [1/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_edges_at (TVertex const & vertex, FUNCTION function) inline
The for loop over all edges at a vertex object.
This is a loop over incoming and outgoing edges.
Parameters
[in] vertex The vertex object
[in] function The function object that is called for all edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1364 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges_at() [2/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_edges_at (TVertex const & vertex, FUNCTION function) const inline
The for loop over all edges at a vertex object.
This is a loop over incoming and outgoing edges.
Parameters
[in] vertex The vertex object
[in] function The function object that is called for all edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge const & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1390 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges_at() [3/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_edges_at (Types::vertexId vertexId, FUNCTION function) inline
The for loop over all edges at a vertex.
This is a loop over incoming and outgoing edges.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for all edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1419 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
for_all_edges_at() [4/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_edges_at (Types::vertexId vertexId, FUNCTION function) const inline
The for loop over all edges at a vertex.
This is a loop over incoming and outgoing edges.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for all edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge const & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1449 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
for_all_vertex_identifiers()
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers (FUNCTION function) const inline
The for loop over all vertex identifiers in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept one argument of type Types::vertexId e.g.,
[](Types::vertexId vertexId)
{
    // Do something with the vertex identifier.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1106 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_vertex_tuples() [1/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_tuples (FUNCTION function) inline
The for loop over all pairs of vertex identifiers and vertex objects in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept two arguments of types Types::vertexId and TVertex, e.g.,
[](Types::vertexId id, TVertex const & vertex)
{
    // Do something with the vertex identifier and object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1180 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_vertex_tuples() [2/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_tuples (FUNCTION function) const inline
The for loop over all pairs of vertex identifiers and vertex objects in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept two arguments of types Types::vertexId and TVertex, e.g.,
[](Types::vertexId id, TVertex const & vertex)
{
    // Do something with the vertex identifier and object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1206 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_vertices() [1/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertices (FUNCTION function) inline
The for loop over all vertex objects in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept one argument of type TVertex e.g.,
[](TVertex & vertex)
{
    // Do something with the vertex object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1130 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_vertices() [2/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertices (FUNCTION function) const inline
The for loop over all vertex objects in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept one argument of type TVertex e.g.,
[](TVertex const & vertex)
{
    // Do something with the vertex object.
}
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1154 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_in_edges_at() [1/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_in_edges_at (TVertex const & vertex, FUNCTION function) inline
The for loop over all incoming edges of a vertex.
Parameters
[in] vertex The vertex object
[in] function The function object that is called for all incoming edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incoming edges at vertexId
Definition at line 1477 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_in_edges_at() [2/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_in_edges_at (TVertex const & vertex, FUNCTION function) const inline
The for loop over all incoming edges of a vertex.
Parameters
[in] vertex The vertex object
[in] function The function object that is called for all incoming edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge const & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incoming edges at vertexId
Definition at line 1503 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_in_edges_at() [3/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_in_edges_at (Types::vertexId vertexId, FUNCTION function) inline
The for loop over all incoming edges of a vertex.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The identifier of the vertex
[in] function The function object that is called for all incoming edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incoming edges at vertexId.
Definition at line 1532 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
for_in_edges_at() [4/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_in_edges_at (Types::vertexId vertexId, FUNCTION function) const inline
The for loop over all incoming edges of a vertex.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The identifier of the vertex
[in] function The function object that is called for all incoming edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge const & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incoming edges at vertexId.
Definition at line 1562 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
for_out_edges_at() [1/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_out_edges_at (TVertex const & vertex, FUNCTION function) inline
The for loop over all outgoing edges of a vertex.
Parameters
[in] vertex The vertex object.
[in] function The function object that is called for all outgoing edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all outgoing edges of vertex.
Definition at line 1590 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_out_edges_at() [2/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_out_edges_at (TVertex const & vertex, FUNCTION function) const inline
The for loop over all outgoing edges of a vertex.
Parameters
[in] vertex The vertex object.
[in] function The function object that is called for all outgoing edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge const & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all outgoing edges of vertex.
Definition at line 1617 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_out_edges_at() [3/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_out_edges_at (Types::vertexId vertexId, FUNCTION function) inline
The for loop over all outgoing edges.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for all outgoing edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all outgoing edges of vertex.
Definition at line 1646 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
for_out_edges_at() [4/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_out_edges_at (Types::vertexId vertexId, FUNCTION function) const inline
The for loop over all outgoing edges.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for all outgoing edges at the vertex. It must accept one argument of type TEdge, e.g.,
[](TEdge const & edge)
{
    // Do something with the edge object.
}
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all outgoing edges of vertex.
Definition at line 1676 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
InDegreeAt()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::InDegreeAt (Types::vertexId id) const inline
The indegree of the vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The number of incoming edges.
Definition at line 359 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::InEdgeIdsAt(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
InEdgeIdsAt()
template<typename VertexProperties , typename EdgeProperties > std::vector< Types::edgeId > const & egoa::DynamicGraph< VertexProperties, EdgeProperties >::InEdgeIdsAt (Types::vertexId id) const inline
The identifiers of all incoming edges.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The identifiers of the incoming edges at vertex id.
Definition at line 404 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::inEdgeIds_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
MapEdges()
template<typename VertexProperties , typename EdgeProperties > template<typename FUNCTION > auto egoa::DynamicGraph< VertexProperties, EdgeProperties >::MapEdges (FUNCTION function) const -> std::vector<decltype(function(std::declval<Types::edgeId>(), std::declval<TEdge>()))> inline
Applies function to all edges and collects the result in a vector.
Parameters
[in] function The function that is applied to all edges.
TResult function(Types::edgeId, TEdge)
Template Parameters
FUNCTION The type of the function object.
Returns
A vector containing the results of the applications of function to all edges.
Definition at line 799 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
MapVertices()
template<typename VertexProperties , typename EdgeProperties > template<typename FUNCTION > auto egoa::DynamicGraph< VertexProperties, EdgeProperties >::MapVertices (FUNCTION function) const -> std::vector<decltype(function(std::declval<Types::vertexId>(), std::declval<TVertex>()))> inline
Applies function to all vertices and collects the result in a vector.
Parameters
[in] function The function that is applied to all edges.
TResult function(Types::vertexId, TVertex)
Template Parameters
FUNCTION The type of the function object.
Returns
A vector containing the results of the applications of function to all vertices.
Definition at line 277 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
MaxDegree() [1/2]
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::MaxDegree () const inline
The maximum degree of the graph .
The maximum number of edges incident to any vertex in the graph. If the graph is empty, 0 is returned.
Returns
The maximum degree.
Definition at line 1076 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::MaxDegree().
MaxDegree() [2/2]
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::MaxDegree (Types::vertexId & id) const inline
The maximum degree of the graph .
The maximum number of edges incident to any vertex in the graph. If the graph is empty, 0 is returned.
Parameters
[in/out] id The vertex identifier with the maximum degree. If there are multiple vertices with the maximum degree, the one with the smallest identifier is returned. If the graph is empty, id is set to Const::NONE.
Returns
The maximum degree.
Definition at line 1050 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::DegreeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::NumberOfVertices(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::Vertices().
MinDegree() [1/2]
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::MinDegree () const inline
The minimum degree of the graph .
The minimum number of edges incident to any vertex in the graph. If the graph is empty, 0 is returned.
Returns
The minimum degree.
Definition at line 1031 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::MinDegree().
MinDegree() [2/2]
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::MinDegree (Types::vertexId & id) const inline
The minimum degree of the graph .
The minimum number of edges incident to any vertex in the graph. If the graph is empty, 0 is returned.
Parameters
[in/out] id The vertex identifier with the minimum degree. If there are multiple vertices with the minimum degree, the one with the smallest identifier is returned. If the graph is empty, id is set to Const::NONE.
Returns
The minimum degree.
Definition at line 1004 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::DegreeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::NumberOfVertices(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::Vertices().
Name()
template<typename VertexProperties , typename EdgeProperties > Types::name egoa::DynamicGraph< VertexProperties, EdgeProperties >::Name () const inline
The name of the graph.
Definition at line 85 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::name_.
NeighborsOf() [1/2]
template<typename VertexProperties , typename EdgeProperties > std::vector< Types::vertexId > egoa::DynamicGraph< VertexProperties, EdgeProperties >::NeighborsOf (Types::vertexId id) const inline
Neighbors of a vertex.
A vector containing the identifiers of the neighbors of the given vertex is returned. The order of the neighbors is unspecified.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The id of a vertex
Returns
The vertex identifiers of all neighbors.
Definition at line 305 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::NeighborsOf(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
NeighborsOf() [2/2]
template<typename VertexProperties , typename EdgeProperties > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::NeighborsOf (Types::vertexId id, std::vector< Types::vertexId > & vertexIds) const inline
Neighbors of a vertex.
The neighbors of the vertex are appended to the vector vertexId. The order of the neighbors is unspecified.
Time complexity: .
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
vertexIds The vector to which the identifiers of the neighbors are appended.
Definition at line 327 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::InEdgeIdsAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::OutEdgeIdsAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertices_.
NumberOfEdges()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::NumberOfEdges () const inline
The number of edges in the graph.
Definition at line 93 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfEdges_.
NumberOfVertices()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::NumberOfVertices () const inline
The number of vertices in the graph.
Definition at line 89 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfVertices_.
OutDegreeAt()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::OutDegreeAt (Types::vertexId id) const inline
The outdegree of the vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The number of outgoing edges.
Definition at line 374 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::OutEdgeIdsAt(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
OutEdgeIdsAt()
template<typename VertexProperties , typename EdgeProperties > std::vector< Types::edgeId > const & egoa::DynamicGraph< VertexProperties, EdgeProperties >::OutEdgeIdsAt (Types::vertexId id) const inline
The identifiers of all outgoing edges.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The identifiers of the outgoing edges at vertex id.
Definition at line 419 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::outEdgeIds_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
RemoveAllIncidentEdgesAt()
template<typename VertexProperties , typename EdgeProperties > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::RemoveAllIncidentEdgesAt (Types::vertexId id) inline
Removes all incident edges at the vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
Parameters
id The identifier of the vertex.
Definition at line 747 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeExists(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::edgeExists_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfEdges_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::outEdgeIds_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists().
RemoveEdgeAt()
template<typename VertexProperties , typename EdgeProperties > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::RemoveEdgeAt (Types::edgeId id) inline
Removes the edge with identifier id.
Precondition
There is an edge with identifier id in the graph.
Parameters
id The identifier of the edge.
Definition at line 722 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeExists(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::edgeExists_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfEdges_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::outEdgeIds_.
RemoveVertexAt()
template<typename VertexProperties , typename EdgeProperties > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::RemoveVertexAt (Types::vertexId id) inline
Remove a vertex and all incident edges.
Precondition
There is a vertex with identifier id in the graph.
Parameters
id The identifier of the vertex to remove.
Definition at line 253 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfVertices_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::RemoveAllIncidentEdgesAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertexExists_.
UpdateEdges()
template<typename VertexProperties , typename EdgeProperties > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::UpdateEdges () inline
Deletes all edges that were marked as deleted.
Afterwards, the edges use the identifiers between 0 and .
    Time complexity: @f$O(1)@f$ if no edge is marked as deleted,
                     @f$O(|\edges|)@f$ otherwise. Here,
                     @f$\edges@f$ includes both active
                     edges and edges that were marked as
                     deleted.
Definition at line 918 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::edgeExists_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::Edges(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::edges_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::NumberOfEdges(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::outEdgeIds_.
UpdateVertices()
template<typename VertexProperties , typename EdgeProperties > void egoa::DynamicGraph< VertexProperties, EdgeProperties >::UpdateVertices () inline
Update vertices.
Shrink vertex array
Definition at line 842 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::NumberOfVertices(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::outEdgeIds_, egoa::Edges::Edge< PropertiesType >::source_, egoa::Edges::Edge< PropertiesType >::target_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertexExists_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertices_.
VertexAt() [1/2]
template<typename VertexProperties , typename EdgeProperties > TVertex & egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexAt (Types::vertexId id) inline
The vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
param[in] id The identifier of the vertex.
Returns
The vertex object.
Definition at line 155 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertices_.
VertexAt() [2/2]
template<typename VertexProperties , typename EdgeProperties > TVertex const & egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexAt (Types::vertexId id) const inline
The vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
param[in] id The identifier of the vertex.
Returns
The vertex object.
Definition at line 170 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertices_.
VertexExists()
template<typename VertexProperties , typename EdgeProperties > bool egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexExists (Types::vertexId id) const inline
Whether a vertex with identifier id exists in the graph.
Parameters
[in] id The identifier of the vertex.
Returns
true if a vertex with identifier id exists, false otherwise.
Definition at line 141 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertexExists_.
VertexId()
template<typename VertexProperties , typename EdgeProperties > Types::vertexId egoa::DynamicGraph< VertexProperties, EdgeProperties >::VertexId (TVertex const & vertex) const inline
The vertex identifier of a vertex object.
Calls vertex.Identifier().
Parameters
vertex The vertex.
Returns
The vertex identifier.
Definition at line 190 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
Vertices() [1/2]
template<typename VertexProperties , typename EdgeProperties > TVerticesView egoa::DynamicGraph< VertexProperties, EdgeProperties >::Vertices () inline
A view on the vertices.
The vertices can be modified via this view.
        If a vertex is added or removed, the view is still valid but
        the iterators obtained via this view are invalid.
        If the graph is destroyed, all views are invalid and calling
        member functions on them has undefined behavior.
Definition at line 109 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfVertices_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertexExists_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertices_.
Vertices() [2/2]
template<typename VertexProperties , typename EdgeProperties > TConstVerticesView egoa::DynamicGraph< VertexProperties, EdgeProperties >::Vertices () const inline
A view on the vertices.
The vertices cannot be modified via this view.
        If a vertex is added or removed, the view is still valid but
        the iterators obtained via this view are invalid.
        If the graph is destroyed, all views are invalid and calling
        member functions on them has undefined behavior.
Definition at line 126 of file DynamicGraph.hpp.
References egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfVertices_, egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertexExists_, and egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertices_.
Member Data Documentation
edgeExists_
template<typename VertexProperties , typename EdgeProperties > std::vector<bool> egoa::DynamicGraph< VertexProperties, EdgeProperties >::edgeExists_ private
Exists edge for lazy updating
Definition at line 1820 of file DynamicGraph.hpp.
edges_
template<typename VertexProperties , typename EdgeProperties > std::vector<TEdge> egoa::DynamicGraph< VertexProperties, EdgeProperties >::edges_ private
Vector of edges
Definition at line 1819 of file DynamicGraph.hpp.
inEdgeIds_
template<typename VertexProperties , typename EdgeProperties > std::vector< std::vector<Types::edgeId> > egoa::DynamicGraph< VertexProperties, EdgeProperties >::inEdgeIds_ private
Ids of the incoming edges per vertex
Definition at line 1823 of file DynamicGraph.hpp.
name_
template<typename VertexProperties , typename EdgeProperties > Types::name egoa::DynamicGraph< VertexProperties, EdgeProperties >::name_ private
Name of the graph
Definition at line 1813 of file DynamicGraph.hpp.
numberOfEdges_
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfEdges_ = 0 private
Number of edges
Definition at line 1821 of file DynamicGraph.hpp.
numberOfVertices_
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::DynamicGraph< VertexProperties, EdgeProperties >::numberOfVertices_ = 0 private
Number of vertices
Definition at line 1817 of file DynamicGraph.hpp.
outEdgeIds_
template<typename VertexProperties , typename EdgeProperties > std::vector< std::vector<Types::edgeId> > egoa::DynamicGraph< VertexProperties, EdgeProperties >::outEdgeIds_ private
Ids of the outgoing edges per vertex
Definition at line 1824 of file DynamicGraph.hpp.
vertexExists_
template<typename VertexProperties , typename EdgeProperties > std::vector<bool> egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertexExists_ private
Exists vertex for lazy updating
Definition at line 1816 of file DynamicGraph.hpp.
vertices_
template<typename VertexProperties , typename EdgeProperties > std::vector<TVertex> egoa::DynamicGraph< VertexProperties, EdgeProperties >::vertices_ private
Vector of vertices
Definition at line 1815 of file DynamicGraph.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Graphs/DynamicGraph.hpp