Energy Grid Optimization & Analysis (EGOA): egoa::BinaryHeap< ElementType > Class Template Reference
egoa::BinaryHeap< ElementType > Class Template Reference
Class for binary heap data structure.
#include <BinaryHeap.hpp>
Classes
class HeapIterator
Class for a heap iterator.
Public Types
using TElement = ElementType
The type of the elements in the heap.
Public Member Functions
Constructors and Destructor
BinaryHeap ()
Constructs an empty Min-heap.
BinaryHeap (std::vector< TElement > const &elements)
Constructs a Min-heap of an vector.
Element Access
TElement const & Top () const
The top element.
Types::index Search (TElement const &element) const
Searches for the first match.
Element Insertion
BinaryHeap & operator+= (TElement const &rhs)
Inserts an element into the heap.
BinaryHeap & operator+= (TElement &&rhs)
Inserts an element into the heap.
void Insert (TElement const &element)
Inserts an element into the heap.
void Insert (TElement &&element)
Inserts an element into the heap.
template<typename InputIt >
void Insert (InputIt first, InputIt last)
Inserts the elements from the range [first, last).
void Insert (std::vector< TElement > const &elements)
Inserts the elements from the vector.
template<typename... Args>
void Emplace (Args &&... args)
Emplaces an element to the heap.
void BuildWith (std::vector< TElement > const &elements)
Builds a heap.
Modifiers
void Pop ()
Deletes the top element.
TElement DeleteTop ()
Deletes the top element.
void Clear ()
Clears the heap.
void ChangeKey (Types::index index, TElement const &element)
Changes the key of one element.
void DecreaseKey (Types::index index, TElement const &element)
Decreases the key of one element.
Capacity
bool Empty () const
Checks if BinaryHeap is empty.
Types::count Size () const
Number of elements in the heap.
Comparator
std::function< bool(TElement const &, TElement const &) > const & Comparator () const
The comparator.
void Comparator (std::function< bool(TElement const &, TElement const &)> comparator)
Changes the comparator.
void Maximize ()
Changes the comparator to construct a max-heap.
void Minimize ()
Changes the comparator to construct a min-heap.
Iterators
HeapIterator begin () const noexcept
An iterator pointing to the top element of the heap.
HeapIterator end () const noexcept
An interator pointing behind the last element.
Loops
template<ExecutionPolicy Policy, typename FUNCTION >
void for_all_elements (FUNCTION function)
Iterates over all elements in the heap.
template<ExecutionPolicy Policy, typename FUNCTION >
void for_all_elements (FUNCTION function) const
Iterates over all elements in the heap.
Private Member Functions
Accessors
TElement & ElementAt (Types::index index)
TElement const & ElementAt (Types::index index) const
TElement & ParentElementAt (Types::index index)
TElement const & ParentElementAt (Types::index index) const
TElement & RightElementAt (Types::index index)
TElement const & RightElementAt (Types::index index) const
TElement & LeftElementAt (Types::index index)
TElement const & LeftElementAt (Types::index index) const
Types::index LeftChildIdOf (Types::index index) const
Types::index RightChildIdOf (Types::index index) const
bool HasChildren (Types::index index) const
bool HasLeftChild (Types::index index) const
bool HasRightChild (Types::index index) const
Types::index ParentIdOf (Types::index index) const
bool HasParent (Types::index index) const
TElement & Front ()
The top element.
TElement const & Front () const
The top element.
TElement & Back ()
The last element.
TElement const & Back () const
The last element.
Types::index MaximumIndex () const
Maximum index of the heap.
Heap Property Methods
void MakeHeapProperty ()
Makes a heap property.
bool ComplyHeapProperty (Types::index index) const
Checks if the heap complies with the heap property at element index.
bool ComplyHeapProperty () const
Checks if the heap complies with the heap property.
Sifts
void SiftUp ()
Sift the last element up.
void SiftUp (Types::index index)
Sift up.
void SiftDown ()
Sift down the element at the root.
void SiftDown (Types::index index)
Sift down the element at index.
Swappability
Types::index SelectSwappableChildAt (Types::index index) const
Selects the smallest child, where smallest is measured according to the comparator.
Private Attributes
std::vector< TElement > heap_
std::function< bool(TElement const &a, TElement const &b)> comparator_
Friends
Output
std::ostream & operator<< (std::ostream &outputStream, BinaryHeap const &heap)
Writes the heap into an output stream.
Operators
bool operator== (BinaryHeap const &rhs) const
Check if two heaps are equivalent.
bool operator!= (BinaryHeap const &rhs) const
Check if two heaps are not equivalent.
template<bool IsIdentical>
bool IsEqualTo (BinaryHeap const &rhs) const
Determines if equal to.
void swap (BinaryHeap< TElement > &lhs, BinaryHeap< TElement > &rhs)
Swap two BinaryHeaps.
Detailed Description
template<typename ElementType>
class egoa::BinaryHeap< ElementType >
Class for binary heap data structure.
The methods have the following worst case time complexities:
Function Time Complexity
Top
Insertion (Emplace, Push)
MakeHeap
DeleteTop, Pop
Delete
ChangeKey
Union (not implemented yet)
The comparator must implement a strict total order on the elements, e.g., std::less<TElement>.
BinaryHeap<int> heap;
heap.Maximize();
heap += 1;
heap.Insert(3);
heap.Push(5);
heap.Emplace(9);
std::cout << heap << std::endl;
Template Parameters
ElementType Type of the elements contained by the heap.
Definition at line 94 of file BinaryHeap.hpp.
Member Typedef Documentation
TElement
template<typename ElementType > using egoa::BinaryHeap< ElementType >::TElement = ElementType
The type of the elements in the heap.
Definition at line 100 of file BinaryHeap.hpp.
Constructor & Destructor Documentation
BinaryHeap() [1/2]
template<typename ElementType > egoa::BinaryHeap< ElementType >::BinaryHeap () inline
Constructs an empty Min-heap.
Parameters
elements The elements
Definition at line 110 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Minimize().
BinaryHeap() [2/2]
template<typename ElementType > egoa::BinaryHeap< ElementType >::BinaryHeap (std::vector< TElement > const & elements) inline explicit
Constructs a Min-heap of an vector.
Parameters
elements The elements
Definition at line 120 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::BuildWith(), and egoa::BinaryHeap< ElementType >::Minimize().
Member Function Documentation
Back() [1/2]
template<typename ElementType > TElement & egoa::BinaryHeap< ElementType >::Back () inline private
The last element.
Returns
The last element, which is at the back of heap_.
Definition at line 706 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Empty().
Back() [2/2]
template<typename ElementType > TElement const & egoa::BinaryHeap< ElementType >::Back () const inline private
The last element.
Returns
The last element, which is at the back of heap_.
Definition at line 717 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Empty().
begin()
template<typename ElementType > HeapIterator egoa::BinaryHeap< ElementType >::begin () const inline noexcept
An iterator pointing to the top element of the heap.
Returns
An iterator pointing to the top element.
Definition at line 599 of file BinaryHeap.hpp.
BuildWith()
template<typename ElementType > void egoa::BinaryHeap< ElementType >::BuildWith (std::vector< TElement > const & elements) inline
Builds a heap.
Note
This will overwrite the existing content.
Parameters
[in] elements The elements with which to build the heap
Definition at line 274 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::MakeHeapProperty().
ChangeKey()
template<typename ElementType > void egoa::BinaryHeap< ElementType >::ChangeKey (Types::index index, TElement const & element) inline
Changes the key of one element.
The key of the element may be increased or decreased (or remain unchanged).
Precondition
index < Size()
Parameters
[in] index The index of which the key shall be changed.
[in] element The element with a new key.
Definition at line 339 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), egoa::BinaryHeap< ElementType >::SiftDown(), egoa::BinaryHeap< ElementType >::SiftUp(), and egoa::BinaryHeap< ElementType >::Size().
Clear()
template<typename ElementType > void egoa::BinaryHeap< ElementType >::Clear () inline
Clears the heap.
Definition at line 324 of file BinaryHeap.hpp.
Comparator() [1/2]
template<typename ElementType > std::function< bool(TElement const &, TElement const &) > const & egoa::BinaryHeap< ElementType >::Comparator () const inline
The comparator.
Returns
The comparator.
Definition at line 410 of file BinaryHeap.hpp.
Comparator() [2/2]
template<typename ElementType > void egoa::BinaryHeap< ElementType >::Comparator (std::function< bool(TElement const &, TElement const &)> comparator) inline
Changes the comparator.
The comparator must represent a strict total order on the elements.
...
heap_.Comparator([](int a, int b) { return a < b; });
...
See also
TestBinaryHeapWithVectorOfInteger::TEST_F(TestBinaryHeapWithVectorOfInteger,ChangeComparatorToLess)
Parameters
[in] comparator The comparator
Definition at line 429 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::MakeHeapProperty().
ComplyHeapProperty() [1/2]
template<typename ElementType > bool egoa::BinaryHeap< ElementType >::ComplyHeapProperty () const inline private
Checks if the heap complies with the heap property.
Returns
true if the heap complies the heap property, false otherwise.
Definition at line 786 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), and egoa::BinaryHeap< ElementType >::Size().
ComplyHeapProperty() [2/2]
template<typename ElementType > bool egoa::BinaryHeap< ElementType >::ComplyHeapProperty (Types::index index) const inline private
Checks if the heap complies with the heap property at element index.
Parameters
[in] index The index of the element.
Returns
true if the heap complies with the heap property at element index and false otherwise.
Definition at line 771 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Comparator(), and egoa::BinaryHeap< ElementType >::Size().
DecreaseKey()
template<typename ElementType > void egoa::BinaryHeap< ElementType >::DecreaseKey (Types::index index, TElement const & element) inline
Decreases the key of one element.
This only supports decreasing the key (according to the comparator) but not increasing it. That is, Comparator()(oldElement, element) is false.
Precondition
index < Size() && !Comparator()(oldElement, element), where oldElement denotes the element at position index, which is replaced.
Parameters
[in] index The index of which the key shall be decreased.
element The new element.
Definition at line 363 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), egoa::BinaryHeap< ElementType >::SiftUp(), and egoa::BinaryHeap< ElementType >::Size().
DeleteTop()
template<typename ElementType > TElement egoa::BinaryHeap< ElementType >::DeleteTop () inline
Deletes the top element.
Precondition
The heap is not empty.
Returns
The top element.
Definition at line 303 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Back(), egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), egoa::BinaryHeap< ElementType >::Front(), egoa::BinaryHeap< ElementType >::SiftDown(), egoa::BinaryHeap< ElementType >::Size(), and egoa::BinaryHeap< ElementType >::swap.
ElementAt() [1/2]
template<typename ElementType > TElement & egoa::BinaryHeap< ElementType >::ElementAt (Types::index index) inline private
Definition at line 659 of file BinaryHeap.hpp.
ElementAt() [2/2]
template<typename ElementType > TElement const & egoa::BinaryHeap< ElementType >::ElementAt (Types::index index) const inline private
Definition at line 660 of file BinaryHeap.hpp.
Emplace()
template<typename ElementType > template<typename... Args> void egoa::BinaryHeap< ElementType >::Emplace (Args &&... args) inline
Emplaces an element to the heap.
Parameters
args The arguments of a constructor of TElement.
Definition at line 259 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), and egoa::BinaryHeap< ElementType >::SiftUp().
Empty()
template<typename ElementType > bool egoa::BinaryHeap< ElementType >::Empty () const inline
Checks if BinaryHeap is empty.
Returns
TRUE if empty and FALSE otherwise.
Definition at line 383 of file BinaryHeap.hpp.
end()
template<typename ElementType > HeapIterator egoa::BinaryHeap< ElementType >::end () const inline noexcept
An interator pointing behind the last element.
Returns
An interator pointing behind the last element.
Definition at line 606 of file BinaryHeap.hpp.
for_all_elements() [1/2]
template<typename ElementType > template<ExecutionPolicy Policy, typename FUNCTION > void egoa::BinaryHeap< ElementType >::for_all_elements (FUNCTION function) inline
Iterates over all elements in the heap.
Parameters
[in] function The function object that is called for all elements in the heap. It must accept one argument of type TElement, e.g.,
[](TElement & element) { ... }
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 627 of file BinaryHeap.hpp.
for_all_elements() [2/2]
template<typename ElementType > template<ExecutionPolicy Policy, typename FUNCTION > void egoa::BinaryHeap< ElementType >::for_all_elements (FUNCTION function) const inline
Iterates over all elements in the heap.
Parameters
[in] function The function object that is called for all elements in the heap. It must accept one argument of type TElement, e.g.,
[](TElement const & element) { ... }
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 648 of file BinaryHeap.hpp.
Front() [1/2]
template<typename ElementType > TElement & egoa::BinaryHeap< ElementType >::Front () inline private
The top element.
Returns
The top element, which is at the front of heap_.
Definition at line 684 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Empty().
Front() [2/2]
template<typename ElementType > TElement const & egoa::BinaryHeap< ElementType >::Front () const inline private
The top element.
Returns
The top element, which is at the front of heap_.
Definition at line 695 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Empty().
HasChildren()
template<typename ElementType > bool egoa::BinaryHeap< ElementType >::HasChildren (Types::index index) const inline private
Definition at line 673 of file BinaryHeap.hpp.
HasLeftChild()
template<typename ElementType > bool egoa::BinaryHeap< ElementType >::HasLeftChild (Types::index index) const inline private
Definition at line 674 of file BinaryHeap.hpp.
HasParent()
template<typename ElementType > bool egoa::BinaryHeap< ElementType >::HasParent (Types::index index) const inline private
Definition at line 677 of file BinaryHeap.hpp.
HasRightChild()
template<typename ElementType > bool egoa::BinaryHeap< ElementType >::HasRightChild (Types::index index) const inline private
Definition at line 675 of file BinaryHeap.hpp.
Insert() [1/4]
template<typename ElementType > template<typename InputIt > void egoa::BinaryHeap< ElementType >::Insert (InputIt first, InputIt last) inline
Inserts the elements from the range [first, last).
Parameters
[in] first Iterator pointing to the first element to add.
[in] last Iterator pointing behind the last element to add.
Template Parameters
InputIt The type of the iterators. It must satisfy the requirements of input iterators.
Definition at line 231 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty().
Insert() [2/4]
template<typename ElementType > void egoa::BinaryHeap< ElementType >::Insert (std::vector< TElement > const & elements) inline
Inserts the elements from the vector.
Parameters
elements The elements to insert
Definition at line 247 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), and egoa::BinaryHeap< ElementType >::Insert().
Insert() [3/4]
template<typename ElementType > void egoa::BinaryHeap< ElementType >::Insert (TElement && element) inline
Inserts an element into the heap.
Parameters
element The element.
Definition at line 215 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty().
Insert() [4/4]
template<typename ElementType > void egoa::BinaryHeap< ElementType >::Insert (TElement const & element) inline
Inserts an element into the heap.
Parameters
element The element.
Definition at line 204 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty().
IsEqualTo()
template<typename ElementType > template<bool IsIdentical> bool egoa::BinaryHeap< ElementType >::IsEqualTo (BinaryHeap< ElementType > const & rhs) const inline
Determines if equal to.
Parameters
rhs The right hand side binary heap object
Template Parameters
IsIdentical If true it determines if equal—in sense of order—to the @rhs binary heap, if false it checks if the heap has the same elements.
Returns
true if equal to rhs, false otherwise.
Definition at line 503 of file BinaryHeap.hpp.
LeftChildIdOf()
template<typename ElementType > Types::index egoa::BinaryHeap< ElementType >::LeftChildIdOf (Types::index index) const inline private
Definition at line 671 of file BinaryHeap.hpp.
LeftElementAt() [1/2]
template<typename ElementType > TElement & egoa::BinaryHeap< ElementType >::LeftElementAt (Types::index index) inline private
Definition at line 668 of file BinaryHeap.hpp.
LeftElementAt() [2/2]
template<typename ElementType > TElement const & egoa::BinaryHeap< ElementType >::LeftElementAt (Types::index index) const inline private
Definition at line 669 of file BinaryHeap.hpp.
MakeHeapProperty()
template<typename ElementType > void egoa::BinaryHeap< ElementType >::MakeHeapProperty () inline private
Makes a heap property.
This works even if the heap is empty.
        The counter starts at @f$ n / 2 - 1 @f$ since the
        leafs fulfill the heap property. Thus, starting at
        the second level is sufficient. Roughly speaking,
        each layer @p l contains twice as many elements
        than the previous layer meaning @f$2^l@f$ elements.
        Dividing by 2 brings us to the previous layer
        @f$2^{l-1}@f$. As we start at 0, the value has to
        be reduced by 1.
Definition at line 751 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), and egoa::BinaryHeap< ElementType >::SiftDown().
Maximize()
template<typename ElementType > void egoa::BinaryHeap< ElementType >::Maximize () inline
Changes the comparator to construct a max-heap.
The comparator is set to std::greater<TElement>() and the heap is updated to respect the new comparator.
Definition at line 441 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Comparator().
MaximumIndex()
template<typename ElementType > Types::index egoa::BinaryHeap< ElementType >::MaximumIndex () const inline private
Maximum index of the heap.
Returns
The maximum index.
Definition at line 728 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Empty().
Minimize()
template<typename ElementType > void egoa::BinaryHeap< ElementType >::Minimize () inline
Changes the comparator to construct a min-heap.
The comparator is set to std::less<TElement>() and the heap is updated to respect the new comparator.
Definition at line 451 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Comparator().
operator!=()
template<typename ElementType > bool egoa::BinaryHeap< ElementType >::operator!= (BinaryHeap< ElementType > const & rhs) const inline
Check if two heaps are not equivalent.
Equivalent means that they contain the same elements when the order of the elements is ignored.
Parameters
rhs The right hand side heap.
Returns
true if the heaps do not contain the same elements, false if they contain the same elements where the order does not matter.
Definition at line 486 of file BinaryHeap.hpp.
operator+=() [1/2]
template<typename ElementType > BinaryHeap & egoa::BinaryHeap< ElementType >::operator+= (TElement && rhs) inline
Inserts an element into the heap.
Parameters
element The element.
Returns
*this.
Definition at line 190 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), and egoa::BinaryHeap< ElementType >::SiftUp().
operator+=() [2/2]
template<typename ElementType > BinaryHeap & egoa::BinaryHeap< ElementType >::operator+= (TElement const & rhs) inline
Inserts an element into the heap.
Parameters
element The element.
Returns
*this.
Definition at line 174 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), and egoa::BinaryHeap< ElementType >::SiftUp().
operator==()
template<typename ElementType > bool egoa::BinaryHeap< ElementType >::operator== (BinaryHeap< ElementType > const & rhs) const inline
Check if two heaps are equivalent.
Equivalent means that they contain the same elements when the order of the elements is ignored.
Parameters
rhs The right hand side heap.
Returns
true if the heaps are equivalent, false if they do not have the same element.
Definition at line 470 of file BinaryHeap.hpp.
ParentElementAt() [1/2]
template<typename ElementType > TElement & egoa::BinaryHeap< ElementType >::ParentElementAt (Types::index index) inline private
Definition at line 662 of file BinaryHeap.hpp.
ParentElementAt() [2/2]
template<typename ElementType > TElement const & egoa::BinaryHeap< ElementType >::ParentElementAt (Types::index index) const inline private
Definition at line 663 of file BinaryHeap.hpp.
ParentIdOf()
template<typename ElementType > Types::index egoa::BinaryHeap< ElementType >::ParentIdOf (Types::index index) const inline private
Definition at line 676 of file BinaryHeap.hpp.
Pop()
template<typename ElementType > void egoa::BinaryHeap< ElementType >::Pop () inline
Deletes the top element.
Precondition
The heap is not empty.
Definition at line 289 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), egoa::BinaryHeap< ElementType >::DeleteTop(), and egoa::BinaryHeap< ElementType >::Size().
RightChildIdOf()
template<typename ElementType > Types::index egoa::BinaryHeap< ElementType >::RightChildIdOf (Types::index index) const inline private
Definition at line 672 of file BinaryHeap.hpp.
RightElementAt() [1/2]
template<typename ElementType > TElement & egoa::BinaryHeap< ElementType >::RightElementAt (Types::index index) inline private
Definition at line 665 of file BinaryHeap.hpp.
RightElementAt() [2/2]
template<typename ElementType > TElement const & egoa::BinaryHeap< ElementType >::RightElementAt (Types::index index) const inline private
Definition at line 666 of file BinaryHeap.hpp.
Search()
template<typename ElementType > Types::index egoa::BinaryHeap< ElementType >::Search (TElement const & element) const inline
Searches for the first match.
Parameters
[in] element The element to search for.
Returns
Index of the element, or if not available Const::none.
Definition at line 151 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty().
SelectSwappableChildAt()
template<typename ElementType > Types::index egoa::BinaryHeap< ElementType >::SelectSwappableChildAt (Types::index index) const inline private
Selects the smallest child, where smallest is measured according to the comparator.
If the elements needs to be swapped with a child, then it is the child at the position returned by this method.
Parameters
[in] index The current index.
Returns
The index of the child that has the best key.
Definition at line 884 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Comparator().
SiftDown() [1/2]
template<typename ElementType > void egoa::BinaryHeap< ElementType >::SiftDown () inline private
Sift down the element at the root.
Definition at line 839 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Empty(), and egoa::BinaryHeap< ElementType >::SiftDown().
SiftDown() [2/2]
template<typename ElementType > void egoa::BinaryHeap< ElementType >::SiftDown (Types::index index) inline private
Sift down the element at index.
Moves an element down the tree until the heap property holds
Parameters
[in] index The index of the element that shall be sifted down.
Definition at line 851 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Comparator(), egoa::BinaryHeap< ElementType >::SelectSwappableChildAt(), egoa::BinaryHeap< ElementType >::Size(), and egoa::BinaryHeap< ElementType >::swap.
SiftUp() [1/2]
template<typename ElementType > void egoa::BinaryHeap< ElementType >::SiftUp () inline private
Sift the last element up.
Definition at line 807 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Empty(), egoa::BinaryHeap< ElementType >::MaximumIndex(), and egoa::BinaryHeap< ElementType >::SiftUp().
SiftUp() [2/2]
template<typename ElementType > void egoa::BinaryHeap< ElementType >::SiftUp (Types::index index) inline private
Sift up.
The element will be shifted upwards the tree while the
Parameters
[in] index The index of the element tha shall be sifted up.
Definition at line 819 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::Comparator(), egoa::BinaryHeap< ElementType >::Size(), and egoa::BinaryHeap< ElementType >::swap.
Size()
template<typename ElementType > Types::count egoa::BinaryHeap< ElementType >::Size () const inline
Number of elements in the heap.
Returns
The size of the heap
Definition at line 393 of file BinaryHeap.hpp.
Top()
template<typename ElementType > TElement const & egoa::BinaryHeap< ElementType >::Top () const inline
The top element.
Precondition
The heap must not be empty.
Returns
The element with minimum key according to the comparator.
Definition at line 137 of file BinaryHeap.hpp.
References egoa::BinaryHeap< ElementType >::ComplyHeapProperty(), and egoa::BinaryHeap< ElementType >::Empty().
Friends And Related Symbol Documentation
operator<<
template<typename ElementType > std::ostream & operator<< (std::ostream & outputStream, BinaryHeap< ElementType > const & heap) friend
Writes the heap into an output stream.
Parameters
outputStream The stream to write data to, e.g., std::cout.
heap The heap.
Returns
The resulting output stream.
Definition at line 534 of file BinaryHeap.hpp.
swap
template<typename ElementType > void swap (BinaryHeap< TElement > & lhs, BinaryHeap< TElement > & rhs) friend
Swap two BinaryHeaps.
Parameters
lhs The left hand side BinaryHeaps
rhs The right hand side BinaryHeaps
Definition at line 515 of file BinaryHeap.hpp.
Member Data Documentation
comparator_
template<typename ElementType > std::function<bool(TElement const & a, TElement const & b)> egoa::BinaryHeap< ElementType >::comparator_ private
Definition at line 914 of file BinaryHeap.hpp.
heap_
template<typename ElementType > std::vector<TElement> egoa::BinaryHeap< ElementType >::heap_ private
Definition at line 913 of file BinaryHeap.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Container/Queues/BinaryHeap.hpp