Energy Grid Optimization & Analysis (EGOA): egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > Class Template Reference
egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > Class Template Reference
Class for Voltage Angle Difference label.
#include <VoltageAngleDifferenceLabel.hpp>
Public Types
using TLabel = SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >
using TVertexId = Types::vertexId
using TElement = ElementType
using TVertexSet = VertexSetContainer
Public Types inherited from egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >
using TVertexId = Types::vertexId
using TElement = ElementType
using TVertexSet = VertexSetContainer
Public Types inherited from egoa::Label< ElementType, VertexSetContainer, PointerType >
using TVertexId = Types::vertexId
using TElement = ElementType
using TVertexSet = VertexSetContainer
using TPointer = PointerType
using TLabel = Label< TElement, TVertexSet, TPointer >
Public Member Functions
Constructors and Destructor
VoltageAngleDifferenceLabel ()
Constructs the voltage angle difference label object.
VoltageAngleDifferenceLabel (Types::vertexId vertexId)
Constructs the voltage angle difference label object.
VoltageAngleDifferenceLabel (Types::vertexId vertexId, Types::real susceptanceNorm, Types::real minimumCapacity)
Constructs the voltage angle difference label object.
VoltageAngleDifferenceLabel (Types::vertexId vertexId, Types::real susceptanceNorm, Types::real minimumCapacity, TVertexSet vertexSet)
Constructs the voltage angle difference label object.
VoltageAngleDifferenceLabel (VoltageAngleDifferenceLabel const &label)=default
Copy constructor.
~VoltageAngleDifferenceLabel ()
Destroys the object.
Domination Operators
bool operator< (VoltageAngleDifferenceLabel const &rhs) const
Strict domination using less than.
bool operator<= (VoltageAngleDifferenceLabel const &rhs) const
Weak domination using less or equal than.
bool operator> (VoltageAngleDifferenceLabel const &rhs) const
Strict domination using greater than.
bool operator>= (VoltageAngleDifferenceLabel const &rhs) const
Weak domination using greater or equal than.
Comparison Operators
bool operator== (VoltageAngleDifferenceLabel const &rhs) const
Equality check.
bool operator!= (VoltageAngleDifferenceLabel const &rhs) const
Inequality check.
Getter and Setter
Types::real MinimumCapacity () const
Getter for the minimum capacity.
Types::real & MinimumCapacity ()
Setter for the minimum capacity.
Types::real Value () const
Voltage angle difference value.
Public Member Functions inherited from egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >
SusceptanceNormLabel ()
Constructs the Susceptance Norm label object.
SusceptanceNormLabel (Types::vertexId vertexId)
Constructs the Susceptance Norm label object.
SusceptanceNormLabel (Types::vertexId vertexId, Types::real susceptanceNorm)
Constructs the Susceptance Norm label object.
SusceptanceNormLabel (Types::vertexId vertexId, Types::real susceptanceNorm, TVertexSet vertexSet)
Constructs the Susceptance Norm label object.
SusceptanceNormLabel (SusceptanceNormLabel const &label)=default
Copy constructor.
~SusceptanceNormLabel ()
Destroys the susceptance norm label object.
TVertexSet const & VertexSet () const
Getter of the set of all visited vertices from the source.
TVertexSet & VertexSet ()
Getter of the set of all visited vertices from the source.
Types::real SusceptanceNorm () const
Getter and setter for the susceptance norm.
Types::real & SusceptanceNorm ()
Getter and setter for the susceptance norm.
Types::real Value () const
Susceptance norm label value.
bool operator< (SusceptanceNormLabel const &rhs) const
Strict domination using less than.
bool operator<= (SusceptanceNormLabel const &rhs) const
Weak domination using less or equal than.
bool operator> (SusceptanceNormLabel const &rhs) const
Strict domination using greater than.
bool operator>= (SusceptanceNormLabel const &rhs) const
Weak domination using greater or equal than.
bool operator== (SusceptanceNormLabel const &rhs) const
Equality check.
bool operator!= (SusceptanceNormLabel const &rhs) const
Inequality check.
SusceptanceNormLabel & operator+= (TElement const &rhs)
In place addition.
Public Member Functions inherited from egoa::Label< ElementType, VertexSetContainer, PointerType >
Label (Types::vertexId vertexId)
Constructs the label object.
Label (Label const &label)=default
Copy constructor.
~Label ()
Destroys the label object.
Types::labelId Index () const
Getter for the label identifier.
Types::labelId & Index ()
Setter for the label identifier.
bool Valid () const
Getter for the valid flag.
bool & Valid ()
Setter for the valid flag.
Types::vertexId Vertex () const
Getter for the value of the label.
Types::vertexId & Vertex ()
Setter for the vertex identifier.
TPointer PreviousVertex () const
Getter for the previous vertex.
TPointer & PreviousVertex ()
Setter for the previous vertex.
TPointer PreviousLabel () const
Getter and setter for the previous label.
TPointer & PreviousLabel ()
Setter for the previous label.
Static Public Member Functions
static VoltageAngleDifferenceLabel SourceLabel (Types::vertexId vertexId)
Generate source label.
Static Public Member Functions inherited from egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >
static SusceptanceNormLabel SourceLabel (Types::vertexId vertexId)
Generate source label.
Private Attributes
Types::real minimumCapacity_
Friends
std::ostream & operator<< (std::ostream &os, VoltageAngleDifferenceLabel const &rhs)
Output stream.
Concatenation Operators
VoltageAngleDifferenceLabel & operator+= (TElement const &rhs)
In place addition.
bool operator+ (VoltageAngleDifferenceLabel const &lhs, TVertexId const &vertexId)
Addition operators testing for cycles.
std::pair< TVertexSet, bool > operator+ (TVertexId const &vertexId, VoltageAngleDifferenceLabel const &rhs)
Addition operators testing for cycles.
std::pair< VoltageAngleDifferenceLabel, bool > operator+ (TElement const &edge, VoltageAngleDifferenceLabel const &rhs)
Addition operators testing for cycles.
std::pair< VoltageAngleDifferenceLabel, bool > operator+ (VoltageAngleDifferenceLabel const &lhs, TElement const &edge)
Addition operators testing for cycles.
Detailed Description
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId>
class egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >
Class for Voltage Angle Difference label.
The voltage angle difference label consists of the susceptance norm and the minimum capacity of a path. The value is defined by
where is the susceptance norm with , and with the thermal limit . For more information see Section 3 in the paper The Maximum Transmission Switching Flow Problem.
Template Parameters
ElementType An edge providing access to the susceptance, e.g., an electrical edge.
See also
Edge::ElectricalEdge representing an ElementType interface.
BucketElement representing an minimum interface requirement for a bucket.
Label representing the base's base class.
SusceptanceNormLabel representing the base class.
Definition at line 42 of file VoltageAngleDifferenceLabel.hpp.
Member Typedef Documentation
TElement
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> using egoa::Label< ElementType, VertexSetContainer, PointerType >::TElement = ElementType
Some element to cover such as an edge.
Definition at line 49 of file Label.hpp.
TLabel
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> using egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::TLabel = SusceptanceNormLabel<ElementType, VertexSetContainer, PointerType>
Definition at line 45 of file VoltageAngleDifferenceLabel.hpp.
TVertexId
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> using egoa::Label< ElementType, VertexSetContainer, PointerType >::TVertexId = Types::vertexId
The vertex identifier type used in LabelStruct.
Definition at line 48 of file Label.hpp.
TVertexSet
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> using egoa::Label< ElementType, VertexSetContainer, PointerType >::TVertexSet = VertexSetContainer
A hash map of TVertex.
Definition at line 50 of file Label.hpp.
Constructor & Destructor Documentation
VoltageAngleDifferenceLabel() [1/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::VoltageAngleDifferenceLabel () inline
Constructs the voltage angle difference label object.
The label and vertex identifier and previous label and vertex identifiers are set to Const::NONE. The valid flag is set to true. Note that the susceptance norm is set to and the minimum capacity to infinity representing the initial label .
Parameters
[in] vertexId The vertex identifier.
Definition at line 67 of file VoltageAngleDifferenceLabel.hpp.
VoltageAngleDifferenceLabel() [2/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::VoltageAngleDifferenceLabel (Types::vertexId vertexId) inline
Constructs the voltage angle difference label object.
The label identifier and previous label/vertex identifiers are set to Const::NONE. The valid flag is set to true. Note that the susceptance norm is set to and the minimum capacity to infinity representing the initial label .
Parameters
[in] vertexId The vertex identifier.
Definition at line 82 of file VoltageAngleDifferenceLabel.hpp.
VoltageAngleDifferenceLabel() [3/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::VoltageAngleDifferenceLabel (Types::vertexId vertexId, Types::real susceptanceNorm, Types::real minimumCapacity) inline
Constructs the voltage angle difference label object.
The label identifier and previous label/vertex identifiers are set to Const::NONE. The valid flag is set to true.
Parameters
[in] vertexId The vertex identifier.
[in] susceptanceNorm The susceptance norm .
[in] minimumCapacity The minimum capacity .
Definition at line 96 of file VoltageAngleDifferenceLabel.hpp.
VoltageAngleDifferenceLabel() [4/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::VoltageAngleDifferenceLabel (Types::vertexId vertexId, Types::real susceptanceNorm, Types::real minimumCapacity, TVertexSet vertexSet) inline
Constructs the voltage angle difference label object.
The label identifier and previous label/vertex identifiers are set to Const::NONE. The valid flag is set to true.
Parameters
[in] vertexId The vertex identifier.
[in] susceptanceNorm The susceptance norm .
[in] minimumCapacity The minimum capacity .
[in] vertexSet The vertex set of visited vertices.
Definition at line 114 of file VoltageAngleDifferenceLabel.hpp.
VoltageAngleDifferenceLabel() [5/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::VoltageAngleDifferenceLabel (VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & label) default
Copy constructor.
Parameters
label The voltage angle difference label.
~VoltageAngleDifferenceLabel()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::~VoltageAngleDifferenceLabel () inline
Destroys the object.
Definition at line 132 of file VoltageAngleDifferenceLabel.hpp.
Member Function Documentation
MinimumCapacity() [1/2]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> Types::real & egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity () inline
Setter for the minimum capacity.
Returns
The minimum capacity .
Definition at line 396 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::minimumCapacity_.
MinimumCapacity() [2/2]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> Types::real egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity () const inline
Getter for the minimum capacity.
Returns
The minimum capacity .
Definition at line 386 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::minimumCapacity_.
operator!=()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::operator!= (VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Inequality check.
Parameters
rhs The right hand side.
Returns
true if lhs != rhs, false otherwise.
Definition at line 246 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity(), and egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
operator+=()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> VoltageAngleDifferenceLabel & egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::operator+= (TElement const & rhs) inline
In place addition.
Parameters
rhs The right hand side representing a TElement.
Returns
The voltage angle difference label with added TElement.
Definition at line 364 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity(), egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm(), and egoa::Label< ElementType, VertexSetContainer, PointerType >::Vertex().
operator<()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::operator< (VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Strict domination using less than.
Parameters
rhs The right hand side.
Returns
true if lhs < rhs, false otherwise.
Definition at line 161 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity(), and egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
operator<=()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::operator<= (VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Weak domination using less or equal than.
Parameters
rhs The right hand side.
Returns
true if lhs <= rhs, false otherwise.
Definition at line 177 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity(), and egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
operator==()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::operator== (VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Equality check.
Parameters
rhs The right hand side.
Returns
true if lhs == rhs, false otherwise.
Definition at line 230 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity(), and egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
operator>()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::operator> (VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Strict domination using greater than.
Parameters
rhs The right hand side.
Returns
true if lhs > rhs, false otherwise.
Definition at line 193 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity(), and egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
operator>=()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::operator>= (VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Weak domination using greater or equal than.
Parameters
rhs The right hand side.
Returns
true if lhs >= rhs, false otherwise.
Definition at line 209 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity(), and egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
SourceLabel()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> static VoltageAngleDifferenceLabel egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::SourceLabel (Types::vertexId vertexId) inline static
Generate source label.
Parameters
[in] vertexId The vertex identifier.
Returns
The voltage angle difference source label.
Definition at line 142 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::VoltageAngleDifferenceLabel().
Value()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> Types::real egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::Value () const inline
Voltage angle difference value.
Represents the total voltage angle difference (also known as delta theta or theta difference) on a path . It is calculated by
where is the label's vertex.
Returns
The voltage angle difference value .
Definition at line 416 of file VoltageAngleDifferenceLabel.hpp.
References egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::MinimumCapacity(), and egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
Friends And Related Symbol Documentation
operator+ [1/4]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> std::pair< VoltageAngleDifferenceLabel, bool > operator+ (TElement const & edge, VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & rhs) friend
Addition operators testing for cycles.
Parameters
edge The edge.
rhs The susceptance norm label VoltageAngleDifferenceLabel.
Returns
A pair of a VoltageAngleDifferenceLabel and boolean. The boolean is true if the element could be added without creating a cycle, false otherwise.
Definition at line 317 of file VoltageAngleDifferenceLabel.hpp.
operator+ [2/4]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> std::pair< TVertexSet, bool > operator+ (TVertexId const & vertexId, VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & rhs) friend
Addition operators testing for cycles.
Parameters
vertexId The vertex identifier.
rhs The right hand side representing a VoltageAngleDifferenceLabel.
Returns
A pair of a hash map and boolean. The boolean is true if the element could be added without creating a cycle, false otherwise.
Definition at line 292 of file VoltageAngleDifferenceLabel.hpp.
operator+ [3/4]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> std::pair< VoltageAngleDifferenceLabel, bool > operator+ (VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & lhs, TElement const & edge) friend
Addition operators testing for cycles.
Parameters
lhs The susceptance norm label VoltageAngleDifferenceLabel.
edge The edge.
Returns
A pair of a LabelStruct and boolean. The boolean is true if the element could be added without creating a cycle, false otherwise.
Definition at line 347 of file VoltageAngleDifferenceLabel.hpp.
operator+ [4/4]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool operator+ (VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & lhs, TVertexId const & vertexId) friend
Addition operators testing for cycles.
A cycle is created if and only if the vertex is already in the set of visited vertices vertexSet.
Parameters
lhs The left hand side representing a VoltageAngleDifferenceLabel.
vertexId The vertex identifier.
Returns
true if the element could be added without creating a cycle, false otherwise.
Definition at line 270 of file VoltageAngleDifferenceLabel.hpp.
operator<<
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> std::ostream & operator<< (std::ostream & os, VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType > const & rhs) friend
Output stream.
Parameters
os The output stream such as std::cout.
rhs The right hand side voltage angle difference label.
Returns
The output stream.
Definition at line 431 of file VoltageAngleDifferenceLabel.hpp.
Member Data Documentation
minimumCapacity_
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> Types::real egoa::VoltageAngleDifferenceLabel< ElementType, VertexSetContainer, PointerType >::minimumCapacity_ private
The minimum capacity on a path .
Definition at line 439 of file VoltageAngleDifferenceLabel.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Labels/VoltageAngleDifferenceLabel.hpp