Energy Grid Optimization & Analysis (EGOA): egoa::Prim< GraphType > Class Template Reference
egoa::Prim< GraphType > Class Template Reference final
An implementation of Prim's algorithm for finding minimum spanning trees.
#include <Prim.hpp>
Public Member Functions
Prim (TGraph &graph, TComparator comparator)
virtual void Run () override
Prim's algorithm @detail Prim's algorithm is quite similar to Dijkstra's algorithm. Prim runs in O(|E| log |V|) using binary heaps. While using Fibonacci heaps the running time is then in O(|E| + |V| log |V|). The latter is an improvement while |V| << |E|.
Public Member Functions inherited from egoa::MST< GraphType >
MST (TGraph &graph, TComparator comparator)
Subgraph< TGraph > const & Result () const
Returns the caluclated spanning tree after Run() has been called.
Private Types
using TSpanningTree = MST< GraphType >
using TGraph = GraphType
using TEdge = typename TGraph::TEdge
using TComparator = std::function< bool(Types::edgeId, Types::edgeId)>
Additional Inherited Members
Protected Types inherited from egoa::MST< GraphType >
using TGraph = GraphType
using TEdge = typename TGraph::TEdge
using TComparator = std::function< bool(Types::edgeId, Types::edgeId)>
Protected Member Functions inherited from egoa::MST< GraphType >
void SetResult (std::vector< Types::edgeId > &&edges)
Builds a subgraph object representing the spanning tree given by the edges.
GraphType const & Graph () const
GraphType & Graph ()
TComparator const & Comparator () const
Detailed Description
template<typename GraphType>
class egoa::Prim< GraphType >
An implementation of Prim's algorithm for finding minimum spanning trees.
Prim<TGraph> prim(graph, comparator);
prim.Run();
Subgraph<TGraph> spanningTree = prim.Result();
Template Parameters
GraphType The type of the graph.
WeightType The type of the edge weights.
Definition at line 30 of file Prim.hpp.
Member Typedef Documentation
TComparator
template<typename GraphType > using egoa::MST< GraphType >::TComparator = std::function<bool(Types::edgeId, Types::edgeId)> private
Definition at line 42 of file MST.hpp.
TEdge
template<typename GraphType > using egoa::MST< GraphType >::TEdge = typename TGraph::TEdge private
Definition at line 41 of file MST.hpp.
TGraph
template<typename GraphType > using egoa::MST< GraphType >::TGraph = GraphType private
Definition at line 40 of file MST.hpp.
TSpanningTree
template<typename GraphType > using egoa::Prim< GraphType >::TSpanningTree = MST<GraphType> private
Definition at line 32 of file Prim.hpp.
Constructor & Destructor Documentation
Prim()
template<typename GraphType > egoa::Prim< GraphType >::Prim (TGraph & graph, TComparator comparator) inline
Definition at line 38 of file Prim.hpp.
~Prim()
template<typename GraphType > virtual egoa::Prim< GraphType >::~Prim () inline virtual
Definition at line 43 of file Prim.hpp.
Member Function Documentation
Run()
template<typename GraphType > virtual void egoa::Prim< GraphType >::Run () inline override virtual
Prim's algorithm @detail Prim's algorithm is quite similar to Dijkstra's algorithm. Prim runs in O(|E| log |V|) using binary heaps. While using Fibonacci heaps the running time is then in O(|E| + |V| log |V|). The latter is an improvement while |V| << |E|.
Steps:
While not all vertices are in the MST component
Relax the incident edges to u if necessary
Choose the edge that has the minimum weight between the grown MST component and the non-MST component, i.e., no cycle will be created
Precondition
This algorithm assumes that the vertex identifiers all lie in the interval [0, NumberOfVertices() - 1].
Implements egoa::MST< GraphType >.
Definition at line 62 of file Prim.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ChangeKey(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::DeleteTop(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Insert(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::KeyOf(), and egoa::MST< GraphType >::SetResult().
The documentation for this class was generated from the following file:
include/Algorithms/SpanningTree/Prim.hpp