Energy Grid Optimization & Analysis (EGOA): egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType > Class Template Reference
egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType > Class Template Reference
Class for betweenness centrality.
#include <BetweennessCentrality.hpp>
Public Types
using TGraph = GraphType
using TVertex = typename TGraph::TVertex
using TVertexId = typename TGraph::TVertexId
using TEdge = typename TGraph::TEdge
using TEdgeId = typename TGraph::TEdgeId
using TAlgorithm = PathFindingAlgorithm
using TMeasurementCollection = MeasurementCollection
using TMeasurementRow = typename TMeasurementCollection::TRow
Public Member Functions
Constructors and Destructor
BetweennessCentrality (TGraph const &graph)
Constructs the betweenness centrality object.
~BetweennessCentrality ()
Destroys the object.
Execute the Betweenness Centrality Algorithm
void Run ()
Run the betweenness centrality.
Getter and Setter
std::vector< Types::real > const & TotalRelativeNumberOfPaths () const
Getter for the total relative number of paths per edge.
std::vector< Types::count > const & TotalNumberOfPaths () const
Getter for the total number of paths per edge.
TAlgoHandling & Algorithm ()
Setter for the algorithm.
TAlgoHandling const & Algorithm () const
Getter for the algorithm.
TMeasurementCollection const & Collection () const
Getter for the measurement collection.
TMeasurementCollection & Collection ()
Setter for the measurement collection.
Modifier
void Clear ()
Clears the measurement collection.
Protected Types
using TAlgoHandling = TAlgorithm
using TNumberOfPaths = std::vector< Types::count >
using TRelativeNumberOfPaths = std::vector< Types::real >
Protected Member Functions
Total Number of Paths
void JoinThreadBasedResults (TNumberOfPaths const &numberOfPaths, TRelativeNumberOfPaths const &relativeNumberOfPaths, Types::real const &m_BNormalization)
Join the thread based result from OpenMP.
void TotalNumberOfPaths (TNumberOfPaths &numberOfPaths, TRelativeNumberOfPaths &relativeNumberOfPaths)
Total number of paths.
Protected Modifiers
void Clear (TNumberOfPaths &numberOfPaths, TRelativeNumberOfPaths &relativeNumberOfPaths)
Clear all.
Private Attributes
Types::count countersSize_
TGraph const & graph_
TAlgoHandling algo_
TMeasurementCollection collection_
std::vector< Types::real > totalRelativeNumberOfPaths_
std::vector< Types::count > totalNumberOfPaths_
Detailed Description
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges>
class egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >
Class for betweenness centrality.
This algorithm measures the centrality of a graph based on a path finding algorithm, e.g., the shortest path, or dominating theta path. The betweenness centrality is defined by
where is the number of between and that use the edge , is the total number of from the source to a sink , and is a normalizing constant.
Precondition
The template parameter used for GraphType should have an interface similar to StaticGraph or DynamicGraph. However, the minimum requirements on the graph type are
for_all_vertex_identifiers<IsParallel>, and
see the minimum requirement of the PathFindingAlgorithm, e.g., DominatingThetaPath.
Template Parameters
GraphType The graph should at least provide the same interface as the StaticGraph.
PathFindingAlgorithm The path finding algorithm that is used within the betweenness centrality algorithm such as DTP.
MeasurementCollection The collection used for the measurements such as IO::DtpRuntimeCollection.
CentralityCounterType The centrality counter decides whether to count edges or vertices.
See also
StaticGraph
DominatingThetaPath
IO::DtpRuntimeCollection
CentralityCounter < Distinguish between counting edges or vertices.
Definition at line 67 of file BetweennessCentrality.hpp.
Member Typedef Documentation
TAlgoHandling
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TAlgoHandling = TAlgorithm protected
Definition at line 87 of file BetweennessCentrality.hpp.
TAlgorithm
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TAlgorithm = PathFindingAlgorithm
The path finding algorithm in use for the Betweenness Centrality such as DTP.
Definition at line 77 of file BetweennessCentrality.hpp.
TEdge
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TEdge = typename TGraph::TEdge
The edge type.
Definition at line 74 of file BetweennessCentrality.hpp.
TEdgeId
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TEdgeId = typename TGraph::TEdgeId
The edge identifier type.
Definition at line 75 of file BetweennessCentrality.hpp.
TGraph
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TGraph = GraphType
The graph type.
Definition at line 71 of file BetweennessCentrality.hpp.
TMeasurementCollection
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TMeasurementCollection = MeasurementCollection
The collection used for the measurements such as IO::DtpRuntimeCollection.
Definition at line 78 of file BetweennessCentrality.hpp.
TMeasurementRow
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TMeasurementRow = typename TMeasurementCollection::TRow
The row type of the collection used for the measurements.
Definition at line 79 of file BetweennessCentrality.hpp.
TNumberOfPaths
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TNumberOfPaths = std::vector<Types::count> protected
Definition at line 88 of file BetweennessCentrality.hpp.
TRelativeNumberOfPaths
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TRelativeNumberOfPaths = std::vector<Types::real> protected
Definition at line 89 of file BetweennessCentrality.hpp.
TVertex
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TVertex = typename TGraph::TVertex
The vertex type.
Definition at line 72 of file BetweennessCentrality.hpp.
TVertexId
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> using egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TVertexId = typename TGraph::TVertexId
The vertex identifier type.
Definition at line 73 of file BetweennessCentrality.hpp.
Constructor & Destructor Documentation
BetweennessCentrality()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::BetweennessCentrality (TGraph const & graph) inline
Constructs the betweenness centrality object.
Parameters
graph The const graph.
Definition at line 101 of file BetweennessCentrality.hpp.
~BetweennessCentrality()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::~BetweennessCentrality () inline
Destroys the object.
Definition at line 114 of file BetweennessCentrality.hpp.
Member Function Documentation
Algorithm() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> TAlgoHandling & egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Algorithm () inline
Setter for the algorithm.
Returns
The algorithm.
Definition at line 211 of file BetweennessCentrality.hpp.
References egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::algo_.
Algorithm() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> TAlgoHandling const & egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Algorithm () const inline
Getter for the algorithm.
Returns
The algorithm.
Definition at line 221 of file BetweennessCentrality.hpp.
References egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::algo_.
Clear() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> void egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Clear () inline
Clears the measurement collection.
Definition at line 254 of file BetweennessCentrality.hpp.
References egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::collection_, and egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::graph_.
Clear() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> void egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Clear (TNumberOfPaths & numberOfPaths, TRelativeNumberOfPaths & relativeNumberOfPaths) inline protected
Clear all.
Parameters
numberOfPaths The number of paths.
relativeNumberOfPaths The relative number of paths.
Definition at line 375 of file BetweennessCentrality.hpp.
References egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Clear().
Collection() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> TMeasurementCollection & egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Collection () inline
Setter for the measurement collection.
Returns
A vector of measurements.
Definition at line 241 of file BetweennessCentrality.hpp.
References egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::collection_.
Collection() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> TMeasurementCollection const & egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Collection () const inline
Getter for the measurement collection.
Returns
A vector of measurements.
Definition at line 231 of file BetweennessCentrality.hpp.
References egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::collection_.
JoinThreadBasedResults()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> void egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::JoinThreadBasedResults (TNumberOfPaths const & numberOfPaths, TRelativeNumberOfPaths const & relativeNumberOfPaths, Types::real const & m_BNormalization) inline protected
Join the thread based result from OpenMP.
This method abstracts the usage of OpenMP.
Parameters
numberOfPaths The number of paths.
relativeNumberOfPaths The relative number of paths.
m_BNormalization The normalization factor, e.g., for the the normalization factor is defined by .
Definition at line 286 of file BetweennessCentrality.hpp.
Run()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> void egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Run () inline
Run the betweenness centrality.
If OpenMP is available this method will run in parallel. Note that standard container are thread safe while writing writing on their own dedicated object. However, this is not true when the object is a boolean. For more information see https://en.cppreference.com/w/cpp/container .
Definition at line 132 of file BetweennessCentrality.hpp.
References egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Algorithm(), egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Clear(), egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Collection(), egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::graph_, egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::JoinThreadBasedResults(), and egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TotalNumberOfPaths().
TotalNumberOfPaths() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> std::vector< Types::count > const & egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TotalNumberOfPaths () const inline
Getter for the total number of paths per edge.
Returns
The total number of paths per edge.
Definition at line 200 of file BetweennessCentrality.hpp.
TotalNumberOfPaths() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> void egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TotalNumberOfPaths (TNumberOfPaths & numberOfPaths, TRelativeNumberOfPaths & relativeNumberOfPaths) inline protected
Total number of paths.
This method abstracts the usage of the CentralityCounter and OpenMP.
Parameters
numberOfPaths The number of paths.
relativeNumberOfPaths The relative number of paths.
Definition at line 342 of file BetweennessCentrality.hpp.
References egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::Algorithm().
TotalRelativeNumberOfPaths()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> std::vector< Types::real > const & egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::TotalRelativeNumberOfPaths () const inline
Getter for the total relative number of paths per edge.
Returns
The total relative number of paths per edge.
Definition at line 189 of file BetweennessCentrality.hpp.
Member Data Documentation
algo_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> TAlgoHandling egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::algo_ private
Multiple path finding algorithm are used for the parallelization.
Definition at line 393 of file BetweennessCentrality.hpp.
collection_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> TMeasurementCollection egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::collection_ private
The collection of measurements.
Definition at line 394 of file BetweennessCentrality.hpp.
countersSize_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> Types::count egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::countersSize_ private
Definition at line 391 of file BetweennessCentrality.hpp.
graph_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> TGraph const& egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::graph_ private
The graph on which the DTP is calculated.
Definition at line 392 of file BetweennessCentrality.hpp.
totalNumberOfPaths_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> std::vector<Types::count> egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::totalNumberOfPaths_ private
Definition at line 397 of file BetweennessCentrality.hpp.
totalRelativeNumberOfPaths_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >, typename PathFindingAlgorithm = DominatingThetaPath<GraphType>, typename MeasurementCollection = IO::DtpRuntimeCollection, CentralityCounter CentralityCounterType = CentralityCounter::counterAtEdges> std::vector<Types::real> egoa::BetweennessCentrality< GraphType, PathFindingAlgorithm, MeasurementCollection, CentralityCounterType >::totalRelativeNumberOfPaths_ private
Definition at line 396 of file BetweennessCentrality.hpp.
The documentation for this class was generated from the following file:
include/Algorithms/Centralities/BetweennessCentrality.hpp