Energy Grid Optimization & Analysis (EGOA): egoa::BlockCutTree< GraphType >::Block Class Reference
egoa::BlockCutTree< GraphType >::Block Class Reference final
Block-cut tree related classes and functions
A block.
#include <BlockCutTree.hpp>
Public Member Functions
Block (Types::blockId identifier, Subgraph< TGraph const > subgraph, std::vector< Types::vertexId > cutVertices)
Types::blockId Identifier () const
The identifier of the block.
egoa::Subgraph< TGraph const > const & Subgraph () const
The subgraph forming the block.
std::vector< Types::vertexId > const & CutVertices () const
The cut-vertices of the block.
bool IsLeaf () const
Whether the block is a leaf of the block-cut tree.
bool IsBridge () const
Whether the block is a bridge.
Private Attributes
Types::blockId identifier_
egoa::Subgraph< TGraph const > subgraph_
Types::vertexId parent_
std::vector< Types::vertexId > cutVertices_
Friends
class egoa::internal::BlockCutTreeBuilder< TGraph >
Detailed Description
template<typename GraphType>
class egoa::BlockCutTree< GraphType >::Block
A block.
Definition at line 182 of file BlockCutTree.hpp.
Constructor & Destructor Documentation
Block()
template<typename GraphType > egoa::BlockCutTree< GraphType >::Block::Block (Types::blockId identifier, Subgraph< TGraph const > subgraph, std::vector< Types::vertexId > cutVertices) inline
Definition at line 184 of file BlockCutTree.hpp.
Member Function Documentation
CutVertices()
template<typename GraphType > std::vector< Types::vertexId > const & egoa::BlockCutTree< GraphType >::Block::CutVertices () const inline
The cut-vertices of the block.
Returns
A vector containing the identifiers of the cut-vertices.
Definition at line 215 of file BlockCutTree.hpp.
Identifier()
template<typename GraphType > Types::blockId egoa::BlockCutTree< GraphType >::Block::Identifier () const inline
The identifier of the block.
Returns
The identifier of the block.
Definition at line 197 of file BlockCutTree.hpp.
IsBridge()
template<typename GraphType > bool egoa::BlockCutTree< GraphType >::Block::IsBridge () const inline
Whether the block is a bridge.
Bridges are blocks that consist of only one edge.
Returns
true if the block represents a bridge, false otherwise.
Definition at line 235 of file BlockCutTree.hpp.
References egoa::Subgraph< GraphType >::Edges(), and egoa::BlockCutTree< GraphType >::Block::Subgraph().
IsLeaf()
template<typename GraphType > bool egoa::BlockCutTree< GraphType >::Block::IsLeaf () const inline
Whether the block is a leaf of the block-cut tree.
Returns
true if the block is a leaf, false otherwise.
Definition at line 224 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::Block::CutVertices().
Subgraph()
template<typename GraphType > egoa::Subgraph< TGraph const > const & egoa::BlockCutTree< GraphType >::Block::Subgraph () const inline
The subgraph forming the block.
Returns
The subgraph forming the block.
Definition at line 206 of file BlockCutTree.hpp.
Friends And Related Symbol Documentation
egoa::internal::BlockCutTreeBuilder< TGraph >
template<typename GraphType > friend class egoa::internal::BlockCutTreeBuilder< TGraph > friend
Definition at line 235 of file BlockCutTree.hpp.
Member Data Documentation
cutVertices_
template<typename GraphType > std::vector<Types::vertexId> egoa::BlockCutTree< GraphType >::Block::cutVertices_ private
Definition at line 245 of file BlockCutTree.hpp.
identifier_
template<typename GraphType > Types::blockId egoa::BlockCutTree< GraphType >::Block::identifier_ private
Definition at line 242 of file BlockCutTree.hpp.
parent_
template<typename GraphType > Types::vertexId egoa::BlockCutTree< GraphType >::Block::parent_ private
Definition at line 244 of file BlockCutTree.hpp.
subgraph_
template<typename GraphType > egoa::Subgraph<TGraph const> egoa::BlockCutTree< GraphType >::Block::subgraph_ private
Definition at line 243 of file BlockCutTree.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Graphs/BlockCutTree.hpp