Energy Grid Optimization & Analysis (EGOA): egoa::Vertices::LoadProperties< VertexType > Class Template Reference
egoa::Vertices::LoadProperties< VertexType > Class Template Reference
Class having all load properties.
#include <LoadProperties.hpp>
Public Member Functions
Constructors and Destructor
LoadProperties ()
Constructs the object.
LoadProperties (Types::name name)
Constructs the object.
Real power
Types::name & Name ()
Getter for the name of the vertex.
Types::name Name () const
Getter and setter for the name of the vertex.
TVertexType & Type ()
Getter for the type of the vertex.
TVertexType const & Type () const
Getter and setter for the type of the vertex.
Types::real RealPowerLoad () const
Getter for the real power demand set point in per unit (p.u.) nominal power (MW).
Types::real & RealPowerLoad ()
Getter and setter for the real power demand set point in per unit (p.u.) nominal power (MW).
TBound RealPowerLoadBound () const
Getter for the real power demand bound in per unit (p.u.) nominal power (MW).
TBound & RealPowerLoadBound ()
Getter and setter for the real power demand bound in per unit (p.u.) nominal power (MW).
Reactive Power Demand
Types::real ReactivePowerLoad () const
Getter for the reactive power demand in per unit (p.u.) nominal power (MVAr).
Types::real & ReactivePowerLoad ()
Getter for the reactive power demand in per unit (p.u.) nominal power (MVAr).
TBound ReactivePowerLoadBound () const
Getter for the reactive power demand bound in per unit (p.u.) nominal power (MVAr).
TBound & ReactivePowerLoadBound ()
Getter and setter for the reactive power demand bound in per unit (p.u.) nominal power (MVAr).
Comparators
bool operator!= (LoadProperties const &rhs) const
Inequality comparator.
bool operator== (LoadProperties const &rhs) const
Equality comparator.
Private Types
using TVertexType = VertexType
using TBound = Bound< Types::real >
Private Attributes
General Information Members
Types::name name_
TVertexType type_
Real Power Members
Types::real realPowerLoad_
TBound realPowerLoadBound_
Reactive Power Members
Types::real reactivePowerLoad_
TBound reactivePowerLoadBound_
Detailed Description
template<class VertexType = Vertices::IeeeBusType>
class egoa::Vertices::LoadProperties< VertexType >
Class having all load properties.
Template Parameters
VertexType Represents the type specification, e.g., IeeeBusType.
Precondition
The vertex type should provide the option load.
Definition at line 24 of file LoadProperties.hpp.
Member Typedef Documentation
TBound
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::LoadProperties< VertexType >::TBound = Bound<Types::real> private
Definition at line 28 of file LoadProperties.hpp.
TVertexType
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::LoadProperties< VertexType >::TVertexType = VertexType private
Definition at line 27 of file LoadProperties.hpp.
Constructor & Destructor Documentation
LoadProperties() [1/2]
template<class VertexType = Vertices::IeeeBusType> egoa::Vertices::LoadProperties< VertexType >::LoadProperties () inline
Constructs the object.
Definition at line 38 of file LoadProperties.hpp.
LoadProperties() [2/2]
template<class VertexType = Vertices::IeeeBusType> egoa::Vertices::LoadProperties< VertexType >::LoadProperties (Types::name name) inline
Constructs the object.
Parameters
[in] name The name of the vertex.
Definition at line 52 of file LoadProperties.hpp.
Member Function Documentation
Name() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::name & egoa::Vertices::LoadProperties< VertexType >::Name () inline
Getter for the name of the vertex.
Returns
The name of the vertex.
Definition at line 71 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::name_.
Name() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::name egoa::Vertices::LoadProperties< VertexType >::Name () const inline
Getter and setter for the name of the vertex.
Returns
The name of the vertex.
Definition at line 81 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::name_.
operator!=()
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::LoadProperties< VertexType >::operator!= (LoadProperties< VertexType > const & rhs) const inline
Inequality comparator.
Parameters
rhs The right hand side LoadProperties.
Returns
true if both vertices are not equal, false otherwise.
Definition at line 240 of file LoadProperties.hpp.
operator==()
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::LoadProperties< VertexType >::operator== (LoadProperties< VertexType > const & rhs) const inline
Equality comparator.
Parameters
rhs The right hand side LoadProperties.
Returns
true if both vertices are equal, false otherwise.
Definition at line 253 of file LoadProperties.hpp.
References egoa::Bound< BoundType >::Maximum(), egoa::Bound< BoundType >::Minimum(), egoa::Vertices::LoadProperties< VertexType >::Name(), egoa::Vertices::LoadProperties< VertexType >::ReactivePowerLoad(), egoa::Vertices::LoadProperties< VertexType >::ReactivePowerLoadBound(), egoa::Vertices::LoadProperties< VertexType >::RealPowerLoad(), egoa::Vertices::LoadProperties< VertexType >::RealPowerLoadBound(), and egoa::Vertices::LoadProperties< VertexType >::Type().
ReactivePowerLoad() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::LoadProperties< VertexType >::ReactivePowerLoad () inline
Getter for the reactive power demand in per unit (p.u.) nominal power (MVAr).
Returns
The reactive power demand in per unit (p.u.) nominal power (MVAr).
Definition at line 193 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::reactivePowerLoad_.
ReactivePowerLoad() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::LoadProperties< VertexType >::ReactivePowerLoad () const inline
Getter for the reactive power demand in per unit (p.u.) nominal power (MVAr).
Returns
The reactive power demand in per unit (p.u.) nominal power (MVAr).
Definition at line 179 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::reactivePowerLoad_.
ReactivePowerLoadBound() [1/2]
template<class VertexType = Vertices::IeeeBusType> TBound & egoa::Vertices::LoadProperties< VertexType >::ReactivePowerLoadBound () inline
Getter and setter for the reactive power demand bound in per unit (p.u.) nominal power (MVAr).
Returns
The reactive power demand demand bound in per unit (p.u.) nominal power (MVAr).
Definition at line 222 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::reactivePowerLoadBound_.
ReactivePowerLoadBound() [2/2]
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::LoadProperties< VertexType >::ReactivePowerLoadBound () const inline
Getter for the reactive power demand bound in per unit (p.u.) nominal power (MVAr).
Returns
The reactive power demand bound in per unit (p.u.) nominal power (MVAr).
Definition at line 207 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::reactivePowerLoadBound_.
RealPowerLoad() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::LoadProperties< VertexType >::RealPowerLoad () inline
Getter and setter for the real power demand set point in per unit (p.u.) nominal power (MW).
Returns
The real power demand set point in per unit (p.u.) nominal power (MW).
Definition at line 132 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::realPowerLoad_.
RealPowerLoad() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::LoadProperties< VertexType >::RealPowerLoad () const inline
Getter for the real power demand set point in per unit (p.u.) nominal power (MW).
Returns
The real power demand set point in per unit (p.u.) nominal power (MW).
Definition at line 119 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::realPowerLoad_.
RealPowerLoadBound() [1/2]
template<class VertexType = Vertices::IeeeBusType> TBound & egoa::Vertices::LoadProperties< VertexType >::RealPowerLoadBound () inline
Getter and setter for the real power demand bound in per unit (p.u.) nominal power (MW).
Returns
The real power demand bound in per unit (p.u.) nominal power (MW).
Definition at line 160 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::realPowerLoadBound_.
RealPowerLoadBound() [2/2]
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::LoadProperties< VertexType >::RealPowerLoadBound () const inline
Getter for the real power demand bound in per unit (p.u.) nominal power (MW).
Returns
The real power demand bound in per unit (p.u.) nominal power (MW).
Definition at line 146 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::realPowerLoadBound_.
Type() [1/2]
template<class VertexType = Vertices::IeeeBusType> TVertexType & egoa::Vertices::LoadProperties< VertexType >::Type () inline
Getter for the type of the vertex.
Returns
The type of the vertex.
Definition at line 91 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::type_.
Type() [2/2]
template<class VertexType = Vertices::IeeeBusType> TVertexType const & egoa::Vertices::LoadProperties< VertexType >::Type () const inline
Getter and setter for the type of the vertex.
Returns
The type of the vertex.
Definition at line 101 of file LoadProperties.hpp.
References egoa::Vertices::LoadProperties< VertexType >::type_.
Member Data Documentation
name_
template<class VertexType = Vertices::IeeeBusType> Types::name egoa::Vertices::LoadProperties< VertexType >::name_ private
The name of the vertex.
Definition at line 274 of file LoadProperties.hpp.
reactivePowerLoad_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::LoadProperties< VertexType >::reactivePowerLoad_ private
The reactive power demand .
Definition at line 288 of file LoadProperties.hpp.
reactivePowerLoadBound_
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::LoadProperties< VertexType >::reactivePowerLoadBound_ private
The real power demand bound .
Definition at line 291 of file LoadProperties.hpp.
realPowerLoad_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::LoadProperties< VertexType >::realPowerLoad_ private
The real power demand .
Definition at line 280 of file LoadProperties.hpp.
realPowerLoadBound_
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::LoadProperties< VertexType >::realPowerLoadBound_ private
The real power demand bound .
Definition at line 281 of file LoadProperties.hpp.
type_
template<class VertexType = Vertices::IeeeBusType> TVertexType egoa::Vertices::LoadProperties< VertexType >::type_ private
The type of the vertex.
Definition at line 275 of file LoadProperties.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Graphs/Vertices/LoadProperties.hpp