Energy Grid Optimization & Analysis (EGOA): egoa::IeeeCdfMatlabParser< GraphType > Class Template Reference
egoa::IeeeCdfMatlabParser< GraphType > Class Template Reference final
Public Member Functions
IeeeCdfMatlabParser (std::istream &input_stream)
bool read (TNetwork &network)
Private Types
using TElectricalVertex = typename GraphType::TVertex
using TVertexProperties = typename TElectricalVertex::TProperties
using TVertex = typename GraphType::TVertex
using TVertexType = typename TVertexProperties::TVertexType
using TGeneratorProperties = Vertices::GeneratorProperties< TVertexType >
using TLoadProperties = Vertices::LoadProperties< TVertexType >
using TElectricalEdge = typename GraphType::TEdge
using TEdgeProperties = typename TElectricalEdge::TProperties
using TBound = Bound<>
using TNetwork = PowerGrid< GraphType >
Private Member Functions
void init ()
void readBaseMva (TNetwork &network)
Read base MVA from an m-file in IEEE Common Data Format.
void readCaseName (TNetwork &network)
Read the name of the case.
void readBusMatrix (TNetwork &network)
Read the bus matrix.
void readBranchMatrix (TNetwork &network)
Read the branch matrix.
void readGeneratorMatrix (TNetwork &network)
Read generator matrix.
bool readNetwork (TNetwork &network)
Gammelig.
Static Private Member Functions
static void toUpper (std::string &str)
static void toLower (std::string &str)
Private Attributes
std::istream & input_stream_
bool initialized_
std::unordered_map< Types::name, Types::index > mapVertexName2Id_
const Types::string genericTimestamp_ = "0000-00-00 00:00:00"
const Types::real genericWeighting_ = 1.0
Detailed Description
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >>
class egoa::IeeeCdfMatlabParser< GraphType >
Definition at line 37 of file IeeeCdfMatlabParser.hpp.
Member Typedef Documentation
TBound
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TBound = Bound<> private
Definition at line 49 of file IeeeCdfMatlabParser.hpp.
TEdgeProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TEdgeProperties = typename TElectricalEdge::TProperties private
Definition at line 48 of file IeeeCdfMatlabParser.hpp.
TElectricalEdge
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TElectricalEdge = typename GraphType::TEdge private
Definition at line 47 of file IeeeCdfMatlabParser.hpp.
TElectricalVertex
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TElectricalVertex = typename GraphType::TVertex private
Definition at line 39 of file IeeeCdfMatlabParser.hpp.
TGeneratorProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TGeneratorProperties = Vertices::GeneratorProperties<TVertexType> private
Definition at line 45 of file IeeeCdfMatlabParser.hpp.
TLoadProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TLoadProperties = Vertices::LoadProperties<TVertexType> private
Definition at line 46 of file IeeeCdfMatlabParser.hpp.
TNetwork
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TNetwork = PowerGrid<GraphType> private
Definition at line 50 of file IeeeCdfMatlabParser.hpp.
TVertex
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TVertex = typename GraphType::TVertex private
Definition at line 41 of file IeeeCdfMatlabParser.hpp.
TVertexProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TVertexProperties = typename TElectricalVertex::TProperties private
Definition at line 40 of file IeeeCdfMatlabParser.hpp.
TVertexType
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> using egoa::IeeeCdfMatlabParser< GraphType >::TVertexType = typename TVertexProperties::TVertexType private
Definition at line 43 of file IeeeCdfMatlabParser.hpp.
Constructor & Destructor Documentation
IeeeCdfMatlabParser()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> egoa::IeeeCdfMatlabParser< GraphType >::IeeeCdfMatlabParser (std::istream & input_stream) inline explicit
Definition at line 498 of file IeeeCdfMatlabParser.hpp.
Member Function Documentation
init()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> void egoa::IeeeCdfMatlabParser< GraphType >::init () inline private
Definition at line 61 of file IeeeCdfMatlabParser.hpp.
read()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> bool egoa::IeeeCdfMatlabParser< GraphType >::read (TNetwork & network) inline
Definition at line 504 of file IeeeCdfMatlabParser.hpp.
readBaseMva()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> void egoa::IeeeCdfMatlabParser< GraphType >::readBaseMva (TNetwork & network) inline private
Read base MVA from an m-file in IEEE Common Data Format.
This value is necessary for the per Unit system.
Parameters
[in,out] network The parameter base MVA is changed in this method.
Definition at line 71 of file IeeeCdfMatlabParser.hpp.
readBranchMatrix()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> void egoa::IeeeCdfMatlabParser< GraphType >::readBranchMatrix (TNetwork & network) inline private
Read the branch matrix.
While reading each row of the matrix a arc is created and added to the network with edge.Conductance() = G not in data (, with) edge.Susceptance() = B not in data (, with) edge.Resistance() = r (or R for resistance) edge.Reactance() = x (or X for reactance) edge.Charge() = b (for charge) edge.ThermalLimit() = rateA (Standard line capacity/thermal line limit) edge.ThermalLimitB() = rateB (Emergency line capacity/thermal line limit) edge.ThermalLimitC() = rateC (Emergency line capacity/thermal line limit) edge.TapRatio() = ratio (tap ratio) edge.AngleShift() = angle.pi/180 (angle is transformed into radian rad, since) edge.cc = not in data () edge.dd = not in data () edge.Status() = status edge.ThetaBound().Minimum() = angmin.pi/180 (angle is transformed into radian rad, since) edge.ThetaBound().Maximum() = angmax.pi/180 (angle is transformed into radian rad, since)
IGNORE: rateB, rateC
Parameters
[in,out] network Netowork with all arcs
Definition at line 270 of file IeeeCdfMatlabParser.hpp.
readBusMatrix()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> void egoa::IeeeCdfMatlabParser< GraphType >::readBusMatrix (TNetwork & network) inline private
Read the bus matrix.
While reading each line of the matrix a vertex is created and added to the network with vertex.Name() = bus_i, vertex.Type() = type, vertex.RealPowerLoad() = Pd / base_mva, vertex.ReactivePowerLoad() = Qd / base_mva, vertex.ShuntConductance() = Gs / base_mva, vertex.ShuntSusceptance() = Bs / base_mva, vertex.Area() = area, vertex.VoltageMagnitude() = Vm, vertex.VoltageAngleSnapshot() = Va, vertex.BaseKV = baseKV, vertex.Zone() = zone, vertex.MaximumVoltage() = Vmax, vertex.MinimumVoltage() = Vmin.
Parameters
[in,out] network Add all buses to the network
Definition at line 120 of file IeeeCdfMatlabParser.hpp.
readCaseName()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> void egoa::IeeeCdfMatlabParser< GraphType >::readCaseName (TNetwork & network) inline private
Read the name of the case.
The name of the power grid, e.g. case14 for the 14 bus system.
Parameters
[in,out] network The parameter changes the name of the network
Definition at line 88 of file IeeeCdfMatlabParser.hpp.
readGeneratorMatrix()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> void egoa::IeeeCdfMatlabParser< GraphType >::readGeneratorMatrix (TNetwork & network) inline private
Read generator matrix.
While reading each row of the matrix a generator is created and added to the network vertex.Name() = bus vertex.RealPower() = Pg / base_mva, vertex.ReactivePower() = Qg / base_mva, vertex.ReactivePowerBound().Maximum() = Qmax / base_mva, vertex.ReactivePowerBound().Minimum() = Qmin / base_mva, vertex.VoltageMagnitude() = Vg vertex.Mbase() = mBase vertex.Status() = status vertex.RealPowerBound().Maximum() = Pmax / base_mva, vertex.RealPowerBound().Minimum() = Pmin / base_mva, vertex.Pc1() = Pc1 vertex.Pc2() = Pc2 vertex.Qc1Bound().Minimum() = Qc1min vertex.Qc1Bound().Maximum() = Qc1max vertex.Qc2Bound().Minimum() = Qc2min vertex.Qc2Bound().Maximum() = Qc2max vertex.RampAgc() = ramp_agc vertex.Ramp10() = ramp_10 vertex.Ramp30() = ramp_30 vertex.RampQ() = ramp_q vertex.Apf() = apf
Parameters
[in,out] network Network with all generator
Definition at line 386 of file IeeeCdfMatlabParser.hpp.
readNetwork()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> bool egoa::IeeeCdfMatlabParser< GraphType >::readNetwork (TNetwork & network) inline private
Gammelig.
Todo:
add both possible function types
Gammelig
Parameters
network Gammelig
Definition at line 486 of file IeeeCdfMatlabParser.hpp.
References egoa::IeeeCdfMatlabParser< GraphType >::readBaseMva(), egoa::IeeeCdfMatlabParser< GraphType >::readBranchMatrix(), egoa::IeeeCdfMatlabParser< GraphType >::readBusMatrix(), egoa::IeeeCdfMatlabParser< GraphType >::readCaseName(), and egoa::IeeeCdfMatlabParser< GraphType >::readGeneratorMatrix().
toLower()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> static void egoa::IeeeCdfMatlabParser< GraphType >::toLower (std::string & str) inline static private
Definition at line 57 of file IeeeCdfMatlabParser.hpp.
toUpper()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> static void egoa::IeeeCdfMatlabParser< GraphType >::toUpper (std::string & str) inline static private
Definition at line 53 of file IeeeCdfMatlabParser.hpp.
Member Data Documentation
genericTimestamp_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> const Types::string egoa::IeeeCdfMatlabParser< GraphType >::genericTimestamp_ = "0000-00-00 00:00:00" private
Definition at line 513 of file IeeeCdfMatlabParser.hpp.
genericWeighting_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> const Types::real egoa::IeeeCdfMatlabParser< GraphType >::genericWeighting_ = 1.0 private
Definition at line 514 of file IeeeCdfMatlabParser.hpp.
initialized_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> bool egoa::IeeeCdfMatlabParser< GraphType >::initialized_ private
Definition at line 510 of file IeeeCdfMatlabParser.hpp.
input_stream_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> std::istream& egoa::IeeeCdfMatlabParser< GraphType >::input_stream_ private
Definition at line 509 of file IeeeCdfMatlabParser.hpp.
mapVertexName2Id_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType > , Edges::ElectricalProperties >> std::unordered_map<Types::name, Types::index> egoa::IeeeCdfMatlabParser< GraphType >::mapVertexName2Id_ private
Definition at line 511 of file IeeeCdfMatlabParser.hpp.
The documentation for this class was generated from the following file:
include/IO/Parser/IeeeCdfMatlabParser.hpp