Energy Grid Optimization & Analysis (EGOA): egoa::PowerGridIO< GraphType > Class Template Reference
egoa::PowerGridIO< GraphType > Class Template Reference
Class for power grid io.
#include <PowerGridIO.hpp>
Public Types
Reader function pointer
using ReaderFunctionStreamBased = bool(*)(PowerGrid< GraphType > &, std::istream &)
using ReaderFunctionStringBased = bool(*)(PowerGrid< GraphType > &, std::string const &)
using ReaderFunctionStreamBasedPowerGridAndCandidateNetwork = bool(*)(PowerGrid< GraphType > &, GraphType &, std::string const &)
Writer function pointer
using WriterFunctionStreamBased = bool(*)(PowerGrid< GraphType > const &, std::ostream &)
using WriterFunctionStreamBasedtionStringBased = bool(*)(PowerGrid< GraphType > const &, std::string const &)
Static Public Member Functions
General reader
static bool read (PowerGrid< GraphType > &network, std::istream &input_stream)
Function to read a power grid.
static bool read (PowerGrid< GraphType > &network, GraphType &candidateNetwork, std::string const &filename)
Function to read a power grid.
static bool read (PowerGrid< GraphType > &network, std::string const &filename, ReaderFunctionStreamBased reader=PowerGridIO< GraphType >::read)
Function to read a power grid.
static bool read (PowerGrid< GraphType > &network, std::string const &filename, ReaderFunctionStringBased reader=PowerGridIO< GraphType >::read)
Function to read a power grid.
static bool read (PowerGrid< GraphType > &network, GraphType &candidateNetwork, std::string const &filename, ReaderFunctionStreamBasedPowerGridAndCandidateNetwork reader=PowerGridIO< GraphType >::read)
Function to read a power grid.
General writer
static bool write (PowerGrid< GraphType > const &network, std::ostream &outputStream, WriterFunctionStreamBased writer=PowerGridIO< GraphType >::write)
Function to write a power grid.
static bool write (PowerGrid< GraphType > const &network, std::string const &filename, WriterFunctionStreamBasedtionStringBased writer=PowerGridIO< GraphType >::write)
Function to write a power grid.
IEEE CDF MATLAB DATA
static bool readIeeeCdfMatlab (PowerGrid< GraphType > &network, std::istream &input_stream)
Reads an IEEE CDF Matlab file.
static bool writeIeeeCdfMatlab (PowerGrid< GraphType > const &network, std::ostream &output_stream)
Writes an IEEE CDF Matlab file.
PYPSA DATA
static bool ReadPyPsa (PowerGrid< GraphType > &network, std::string const &filename)
Reads a PyPsa file.
static bool ReadPyPsa (PowerGrid< GraphType > &network, GraphType &candidateNetwork, std::string const &filename)
Reads a PyPsa file.
GeoJson
For more information on GeoJson see GeoJson and RFC7946.
static bool WriteGeoJson (PowerGrid< GraphType > const &network, std::string const &filename)
Write the network into a GeoJson format.
static bool WriteGeoJson (PowerGrid< GraphType > const &network, std::ostream &outputStream)
Write the network into a GeoJson format.
Graph modeling language (GML)
For more information on GML see GML.
static bool ReadGraphGml (PowerGrid< GraphType > &network, std::istream &input_stream)
Reads a graph from a gml file.
static bool WriteGraphGml (PowerGrid< GraphType > const &network, std::ostream &output_stream)
Writes a graph into a gml file.
static bool WriteGraphGml (PowerGrid< GraphType > const &network, std::string const &filename)
Writes a graph into a gml file.
Graph DOT
static bool WriteGraphDot (PowerGrid< GraphType > const &network, std::ostream &outputStream)
Writes a graph dot.
static bool WriteGraphDot (PowerGrid< GraphType > const &network, std::string const &filename)
static std::string Stroke2DotStyle (Stroke::Name const &stroke)
Convert a stroke into a dot style stroke.
Static Public Attributes
Vector of reader function pointers
static std::vector< ReaderFunctionStreamBased > const streamReaders
static std::vector< ReaderFunctionStringBased > const fileReaders
static std::vector< ReaderFunctionStreamBasedPowerGridAndCandidateNetwork > const streamReadersPowerGridAndCandidateNetwork
Vector of writer function pointers
static std::vector< WriterFunctionStreamBased > const streamWriters
static std::vector< WriterFunctionStreamBasedtionStringBased > const fileWriters
Private Types
using TGraph = GraphType
using TElectricalVertex = typename TGraph::TVertex
using TElectricalEdge = typename TGraph::TEdge
Static Private Attributes
static char indentChar_
static int indentWidth_
Detailed Description
template<typename GraphType>
class egoa::PowerGridIO< GraphType >
Class for power grid io.
Template Parameters
GraphType The graph .
Definition at line 33 of file PowerGridIO.hpp.
Member Typedef Documentation
ReaderFunctionStreamBased
template<typename GraphType > using egoa::PowerGridIO< GraphType >::ReaderFunctionStreamBased = bool (*)(PowerGrid< GraphType> & , std::istream &)
Definition at line 46 of file PowerGridIO.hpp.
ReaderFunctionStreamBasedPowerGridAndCandidateNetwork
template<typename GraphType > using egoa::PowerGridIO< GraphType >::ReaderFunctionStreamBasedPowerGridAndCandidateNetwork = bool (*)(PowerGrid< GraphType> & , GraphType & , std::string const &)
Definition at line 50 of file PowerGridIO.hpp.
ReaderFunctionStringBased
template<typename GraphType > using egoa::PowerGridIO< GraphType >::ReaderFunctionStringBased = bool (*)(PowerGrid< GraphType> & , std::string const &)
Definition at line 48 of file PowerGridIO.hpp.
TElectricalEdge
template<typename GraphType > using egoa::PowerGridIO< GraphType >::TElectricalEdge = typename TGraph::TEdge private
Definition at line 38 of file PowerGridIO.hpp.
TElectricalVertex
template<typename GraphType > using egoa::PowerGridIO< GraphType >::TElectricalVertex = typename TGraph::TVertex private
Definition at line 37 of file PowerGridIO.hpp.
TGraph
template<typename GraphType > using egoa::PowerGridIO< GraphType >::TGraph = GraphType private
Definition at line 36 of file PowerGridIO.hpp.
WriterFunctionStreamBased
template<typename GraphType > using egoa::PowerGridIO< GraphType >::WriterFunctionStreamBased = bool (*)(PowerGrid<GraphType> const & , std::ostream &)
Definition at line 58 of file PowerGridIO.hpp.
WriterFunctionStreamBasedtionStringBased
template<typename GraphType > using egoa::PowerGridIO< GraphType >::WriterFunctionStreamBasedtionStringBased = bool (*)(PowerGrid<GraphType> const & , std::string const &)
Definition at line 60 of file PowerGridIO.hpp.
Member Function Documentation
read() [1/5]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::read (PowerGrid< GraphType > & network, GraphType & candidateNetwork, std::string const & filename) inline static
Function to read a power grid.
Parameters
network The network .
candidateNetwork The candidate network .
filename The filename from which the data is read.
Returns
true if the reading was successful, false otherwise.
Definition at line 119 of file PowerGridIO.hpp.
read() [2/5]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::read (PowerGrid< GraphType > & network, GraphType & candidateNetwork, std::string const & filename, ReaderFunctionStreamBasedPowerGridAndCandidateNetwork reader = PowerGridIO<GraphType>::read) inline static
Function to read a power grid.
Parameters
network The network .
candidateNetwork The candidate network .
filename The filename from which the data is read.
[in] reader The reader, e.g., ReadPyPsa.
Returns
true if the reading was successful, false otherwise.
Definition at line 185 of file PowerGridIO.hpp.
read() [3/5]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::read (PowerGrid< GraphType > & network, std::istream & input_stream) inline static
Function to read a power grid.
Parameters
network The network .
input_stream The stream from which the data is read.
Returns
true if the reading was successful, false otherwise.
Definition at line 93 of file PowerGridIO.hpp.
read() [4/5]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::read (PowerGrid< GraphType > & network, std::string const & filename, ReaderFunctionStreamBased reader = PowerGridIO<GraphType>::read) inline static
Function to read a power grid.
Parameters
network The network .
filename The filename from which the data is read.
[in] reader The reader, e.g., ReadPyPsa.
Returns
true if the reading was successful, false otherwise.
Definition at line 145 of file PowerGridIO.hpp.
read() [5/5]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::read (PowerGrid< GraphType > & network, std::string const & filename, ReaderFunctionStringBased reader = PowerGridIO<GraphType>::read) inline static
Function to read a power grid.
Parameters
network The network .
filename The filename from which we read the data.
[in] reader The reader, e.g., ReadPyPsa.
Returns
true if the reading was successful, false otherwise.
Definition at line 165 of file PowerGridIO.hpp.
ReadGraphGml()
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::ReadGraphGml (PowerGrid< GraphType > & network, std::istream & input_stream) inline static
Reads a graph from a gml file.
Parameters
network The network .
input_stream The input stream to read data from, e.g., a file.
Returns
@true if the reading was successful, @false otherwise.
Definition at line 383 of file PowerGridIO.hpp.
readIeeeCdfMatlab()
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::readIeeeCdfMatlab (PowerGrid< GraphType > & network, std::istream & input_stream) inline static
Reads an IEEE CDF Matlab file.
Parameters
network The network .
input_stream The input stream to read data from, e.g., a file.
Returns
true if the reading was successful, false otherwise.
Definition at line 252 of file PowerGridIO.hpp.
ReadPyPsa() [1/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::ReadPyPsa (PowerGrid< GraphType > & network, GraphType & candidateNetwork, std::string const & filename) inline static
Reads a PyPsa file.
Parameters
network The network .
candidateNetwork The candidate network .
filename The filename
Returns
true if the reading was successful, false otherwise.
Definition at line 313 of file PowerGridIO.hpp.
References egoa::PyPsaParser< GraphType >::read().
ReadPyPsa() [2/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::ReadPyPsa (PowerGrid< GraphType > & network, std::string const & filename) inline static
Reads a PyPsa file.
Parameters
network The network .
filename The filename
Returns
true if the reading was successful, false otherwise.
Definition at line 294 of file PowerGridIO.hpp.
References egoa::PyPsaParser< GraphType >::read().
Stroke2DotStyle()
template<typename GraphType > static std::string egoa::PowerGridIO< GraphType >::Stroke2DotStyle (Stroke::Name const & stroke) inline static
Convert a stroke into a dot style stroke.
Parameters
stroke The stroke.
Returns
The dot style stroke.
Definition at line 721 of file PowerGridIO.hpp.
write() [1/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::write (PowerGrid< GraphType > const & network, std::ostream & outputStream, WriterFunctionStreamBased writer = PowerGridIO<GraphType>::write) inline static
Function to write a power grid.
Parameters
network The network .
filename The filename to which the data is written.
[in] writer The writer.
Returns
true if the writing was successful, false otherwise.
Definition at line 210 of file PowerGridIO.hpp.
write() [2/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::write (PowerGrid< GraphType > const & network, std::string const & filename, WriterFunctionStreamBasedtionStringBased writer = PowerGridIO<GraphType>::write) inline static
Function to write a power grid.
Parameters
network The network .
filename The filename
[in] writer The writer, e.g., WriteGeoJson.
Returns
true if the writing was successful, false otherwise.
Definition at line 229 of file PowerGridIO.hpp.
WriteGeoJson() [1/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::WriteGeoJson (PowerGrid< GraphType > const & network, std::ostream & outputStream) inline static
Write the network into a GeoJson format.
Parameters
network The network .
outputStream The stream to which the data is written.
Returns
true if the reading was successful, false otherwise.
Definition at line 358 of file PowerGridIO.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::write().
WriteGeoJson() [2/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::WriteGeoJson (PowerGrid< GraphType > const & network, std::string const & filename) inline static
Write the network into a GeoJson format.
Parameters
network The network .
filename The file to which the data is written.
Returns
true if the reading was successful, false otherwise.
Definition at line 340 of file PowerGridIO.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::write().
WriteGraphDot() [1/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::WriteGraphDot (PowerGrid< GraphType > const & network, std::ostream & outputStream) inline static
Writes a graph dot.
Parameters
network The network
outputStream The stream to write data to
Returns
@true if the writing was successful, @false otherwise.
Todo:
Improve and put in its own file.
Definition at line 631 of file PowerGridIO.hpp.
References egoa::PowerGridIO< GraphType >::Stroke2DotStyle().
WriteGraphDot() [2/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::WriteGraphDot (PowerGrid< GraphType > const & network, std::string const & filename) inline static
Definition at line 672 of file PowerGridIO.hpp.
WriteGraphGml() [1/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::WriteGraphGml (PowerGrid< GraphType > const & network, std::ostream & output_stream) inline static
Writes a graph into a gml file.
Parameters
network The network .
output_stream The output stream to write data to, e.g., a file.
Returns
true if the writing was successful, false otherwise.
Definition at line 402 of file PowerGridIO.hpp.
WriteGraphGml() [2/2]
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::WriteGraphGml (PowerGrid< GraphType > const & network, std::string const & filename) inline static
Writes a graph into a gml file.
Parameters
network The network .
filename The filename to write the data.
Returns
true if the writing was successful, false otherwise.
Definition at line 419 of file PowerGridIO.hpp.
writeIeeeCdfMatlab()
template<typename GraphType > static bool egoa::PowerGridIO< GraphType >::writeIeeeCdfMatlab (PowerGrid< GraphType > const & network, std::ostream & output_stream) inline static
Writes an IEEE CDF Matlab file.
Parameters
network The network .
output_stream The output stream to write data to, e.g., a file.
Returns
true if the writing was successful, false otherwise.
Definition at line 271 of file PowerGridIO.hpp.
Member Data Documentation
fileReaders
template<typename GraphType > const std::vector< typename PowerGridIO< GraphType >::ReaderFunctionStringBased > egoa::PowerGridIO< GraphType >::fileReaders static
Initial value:
= {
    PowerGridIO<GraphType>::ReadPyPsa
}
Definition at line 68 of file PowerGridIO.hpp.
fileWriters
template<typename GraphType > const std::vector< typename PowerGridIO< GraphType >::WriterFunctionStreamBasedtionStringBased > egoa::PowerGridIO< GraphType >::fileWriters static
Initial value:
= {
    PowerGridIO<GraphType>::WriteGraphGml
    , PowerGridIO<GraphType>::WriteGraphDot
    , PowerGridIO<GraphType>::WriteGeoJson
}
Definition at line 75 of file PowerGridIO.hpp.
indentChar_
template<typename GraphType > char egoa::PowerGridIO< GraphType >::indentChar_ static private
Character used for indentation.
Definition at line 736 of file PowerGridIO.hpp.
indentWidth_
template<typename GraphType > int egoa::PowerGridIO< GraphType >::indentWidth_ static private
Number of indent characters used for indentation.
Definition at line 737 of file PowerGridIO.hpp.
streamReaders
template<typename GraphType > const std::vector< typename PowerGridIO< GraphType >::ReaderFunctionStreamBased > egoa::PowerGridIO< GraphType >::streamReaders static
Initial value:
= {
    PowerGridIO<GraphType>::readIeeeCdfMatlab
}
Definition at line 67 of file PowerGridIO.hpp.
streamReadersPowerGridAndCandidateNetwork
template<typename GraphType > const std::vector< typename PowerGridIO< GraphType >::ReaderFunctionStreamBasedPowerGridAndCandidateNetwork > egoa::PowerGridIO< GraphType >::streamReadersPowerGridAndCandidateNetwork static
Initial value:
= {
    PowerGridIO<GraphType>::ReadPyPsa
}
Definition at line 69 of file PowerGridIO.hpp.
streamWriters
template<typename GraphType > const std::vector< typename PowerGridIO< GraphType >::WriterFunctionStreamBased > egoa::PowerGridIO< GraphType >::streamWriters static
Initial value:
= {
    PowerGridIO<GraphType>::writeIeeeCdfMatlab
    , PowerGridIO<GraphType>::WriteGraphDot
    , PowerGridIO<GraphType>::WriteGeoJson
}
Definition at line 74 of file PowerGridIO.hpp.
The documentation for this class was generated from the following files:
include/IO/PowerGridIO.hpp
src/IO/PowerGridIO.cpp