Energy Grid Optimization & Analysis (EGOA): egoa::StaticGraph< VertexProperties, EdgeProperties > Class Template Reference
egoa::StaticGraph< VertexProperties, EdgeProperties > Class Template Reference
A graph data structure that supports adding vertices and edges.
#include <StaticGraph.hpp>
Public Types
using TGraph = StaticGraph< VertexProperties, EdgeProperties >
using TVertexProperties = VertexProperties
using TVertex = Vertices::Vertex< TVertexProperties >
using TVertexId = Types::vertexId
using TEdgeProperties = EdgeProperties
using TEdge = Edges::Edge< TEdgeProperties >
using TEdgeId = Types::edgeId
using TVerticesView = VectorView< TVertex, false >
using TConstVerticesView = VectorView< TVertex, true >
using TEdgesView = VectorView< TEdge, false >
using TConstEdgesView = VectorView< TEdge, true >
Public Member Functions
Constructors and Destructor
StaticGraph (Types::name name)
Getter and Setter
Types::name Name () const
Name of the graph.
Types::count NumberOfVertices () const
Number of vertices .
Types::count NumberOfEdges () const
Number of edges .
Vertex Related Methods
TVerticesView Vertices ()
A view on the vertices.
TConstVerticesView Vertices () const
A view on the vertices.
bool VertexExists (Types::vertexId id) const
Whether a vertex with identifier id exists in the graph.
TVertex & VertexAt (Types::vertexId id)
The vertex with identifier id.
TVertex const & VertexAt (Types::vertexId id) const
The vertex with identifier id.
TVertex & VertexAt (int id)=delete
TVertex & VertexAt (char id)=delete
TVertex const & VertexAt (int id) const =delete
TVertex const & VertexAt (char id) const =delete
Types::vertexId VertexId (TVertex const &vertex) const
The vertex identifier of a vertex object.
Types::vertexId AddVertex (TVertexProperties const &properties)
Adds a vertex.
Types::vertexId AddVertex (TVertexProperties &&properties)
Adds a vertex.
template<typename FUNCTION >
auto MapVertices (FUNCTION function) const -> std::vector< decltype(function(std::declval< Types::vertexId >(), std::declval< TVertex >()))>
Applies function to all vertices and collects the result in a vector.
std::vector< Types::vertexId > NeighborsOf (Types::vertexId id) const
Neighbors of a vertex.
void NeighborsOf (Types::vertexId id, std::vector< Types::vertexId > &vertexIds) const
Neighbors of a vertex.
Types::count InDegreeAt (Types::vertexId id) const
The indegree of the vertex with identifier id.
Types::count OutDegreeAt (Types::vertexId id) const
The outdegree of the vertex with identifier id.
Types::count DegreeAt (Types::vertexId id) const
The degree of the vertex with identifier id.
std::vector< Types::edgeId > const & InEdgeIdsAt (Types::vertexId id) const
The identifiers of all incoming edges.
std::vector< Types::edgeId > const & OutEdgeIdsAt (Types::vertexId id) const
The identifiers of all outgoing edges.
std::vector< Types::edgeId > EdgeIdsAt (Types::vertexId id) const
All edge identifiers of edges incident to a vertex.
void EdgeIdsAt (Types::vertexId id, std::vector< Types::edgeId > &edgeIds) const
All edge identifiers of edges incident to a vertex are added to the end of the vector edgeIds.
Edge related methods
TEdgesView Edges ()
A view on the edges.
TConstEdgesView Edges () const
A view on the edges.
bool EdgeExists (Types::edgeId id) const
Whether an edge with the identifier id exists in the graph.
TEdge & EdgeAt (Types::edgeId id)
The edge with identifier id.
TEdge const & EdgeAt (Types::edgeId id) const
The edge with identifier id.
Types::edgeId EdgeId (Types::vertexId source, Types::vertexId target) const
Searches for the identifier of the edge .
TEdge & Edge (Types::vertexId source, Types::vertexId target)
Searches for an edge .
TEdge const & Edge (Types::vertexId source, Types::vertexId target) const
Searches for an edge .
Types::edgeId AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties const &properties)
Adds an edge to the set of edges .
Types::edgeId AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties &&properties)
Adds an edge to the set of edges .
template<typename FUNCTION >
auto MapEdges (FUNCTION function) const -> std::vector< decltype(function(std::declval< Types::edgeId >(), std::declval< TEdge >()))>
Applies function to all edges and collects the result in a vector.
TEdge & EdgeAt (int index)=delete
TEdge & EdgeAt (char index)=delete
TEdge const & EdgeAt (int index) const =delete
TEdge const & EdgeAt (char index) const =delete
Types::edgeId EdgeId (int source, int target) const =delete
Types::edgeId EdgeId (char source, char target) const =delete
Types::edgeId EdgeId (int source, char target) const =delete
Types::edgeId EdgeId (char source, int target) const =delete
TEdge & Edge (int source, int target)=delete
TEdge & Edge (char source, char target)=delete
TEdge & Edge (char source, int target)=delete
TEdge & Edge (int source, char target)=delete
TEdge const & Edge (int source, int target) const =delete
TEdge const & Edge (char source, char target) const =delete
TEdge const & Edge (int source, char target) const =delete
TEdge const & Edge (char source, int target) const =delete
Graph Properties
Types::count MinDegree (Types::vertexId &id) const
The minimum degree of the graph .
Types::count MinDegree () const
The minimum degree of the graph .
Types::count MaxDegree (Types::vertexId &id) const
The maximum degree of the graph .
Types::count MaxDegree () const
The maximum degree of the graph .
Vertex Loops
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertex_identifiers (FUNCTION function) const
The for loop over all vertex identifiers in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertices (FUNCTION function)
The for loop over all vertex objects in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertices (FUNCTION function) const
The for loop over all vertex objects in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertex_tuples (FUNCTION function)
The for loop over all pairs of vertex identifiers and vertex objects in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_vertex_tuples (FUNCTION function) const
The for loop over all pairs of vertex identifiers and vertex objects in the graph.
Edge Loops
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edge_identifiers (FUNCTION function) const
The for loop over all identifiers of edges in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges (FUNCTION function)
The for loop over all edges in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges (FUNCTION function) const
The for loop over all edges in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edge_tuples (FUNCTION function)
The for loop over all pairs of edge identifiers and edge objects in the graph.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edge_tuples (FUNCTION function) const
The for loop over all pairs of edge identifiers and edge objects in the graph.
Neighborhood Loops
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges_at (TVertex const &vertex, FUNCTION function)
The for loop over all edges at a vertex object.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges_at (TVertex const &vertex, FUNCTION function) const
The for loop over all edges at a vertex object.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges_at (Types::vertexId const vertexId, FUNCTION function)
The for loop over all edges at a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_all_edges_at (Types::vertexId const vertexId, FUNCTION function) const
The for loop over all edges at a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_in_edges_at (TVertex const &vertex, FUNCTION function)
The for loop over all incoming edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_in_edges_at (TVertex const &vertex, FUNCTION function) const
The for loop over all incoming edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_in_edges_at (Types::vertexId vertexId, FUNCTION function)
The for loop over all incoming edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_in_edges_at (Types::vertexId vertexId, FUNCTION function) const
The for loop over all incoming edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_out_edges_at (TVertex const &vertex, FUNCTION function)
The for loop over all outgoing edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_out_edges_at (TVertex const &vertex, FUNCTION function) const
The for loop over all outgoing edges of a vertex.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_out_edges_at (Types::vertexId vertexId, FUNCTION function)
The for loop over all outgoing edges.
template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION >
void for_out_edges_at (Types::vertexId vertexId, FUNCTION function) const
The for loop over all outgoing edges.
Private Attributes
Types::name name_
std::vector< TVertex > vertices_
std::vector< TEdge > edges_
std::vector< std::vector< Types::edgeId > > inEdgeIds_
std::vector< std::vector< Types::edgeId > > outEdgeIds_
Output
void DumpBuses (std::ostream &outputStream) const
Dumps buses.
void DumpBranches (std::ostream &outputStream) const
Dumps branches.
std::ostream & operator<< (std::ostream &outputStream, StaticGraph const &rhs)
Write the static graph to an output stream.
Detailed Description
template<typename VertexProperties, typename EdgeProperties>
class egoa::StaticGraph< VertexProperties, EdgeProperties >
A graph data structure that supports adding vertices and edges.
Both VertexProperties and EdgeProperties must be able to store an identifier, which can be accessed in the following way. Here, vertex and constVertex are objects of type VertexProperties and VertexProperties const, respectively, and vId is of type Types::vertexId. Similarly, edge and constEdge are objects of type EdgeProperties and EdgeProperties const, respectively, and eId is of type Types::edgeId.
Operation Effect
vertex.Identifier() = vId;
The identifier of vertex is set to vId.
Types::vertexId vId = constVertex.Identifier();
vId is set to the identifier of vertex.
edge.Identifier() = eId;
The identifier of edge is set to eId.
Types::edgeId eId = constEdge.Identifier();
eId is set to the identifier of edge.
Types::vertexId vId = constEdge.Source();
vId is set to the identifier of the source of edge.
Types::vertexId vId = constEdge.Target();
vId is set to the identifier of the target of edge.
Template Parameters
VertexProperties Type of a vertex, e.g., ElectricalVertex.
EdgeProperties Type of an edge, e.g., ElectricalEdge.
Definition at line 52 of file StaticGraph.hpp.
Member Typedef Documentation
TConstEdgesView
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TConstEdgesView = VectorView<TEdge, true>
Definition at line 69 of file StaticGraph.hpp.
TConstVerticesView
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TConstVerticesView = VectorView<TVertex, true>
Definition at line 67 of file StaticGraph.hpp.
TEdge
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TEdge = Edges::Edge<TEdgeProperties>
Definition at line 63 of file StaticGraph.hpp.
TEdgeId
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TEdgeId = Types::edgeId
Definition at line 64 of file StaticGraph.hpp.
TEdgeProperties
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TEdgeProperties = EdgeProperties
Definition at line 62 of file StaticGraph.hpp.
TEdgesView
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TEdgesView = VectorView<TEdge, false>
Definition at line 68 of file StaticGraph.hpp.
TGraph
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TGraph = StaticGraph<VertexProperties , EdgeProperties>
Definition at line 55 of file StaticGraph.hpp.
TVertex
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TVertex = Vertices::Vertex<TVertexProperties>
Definition at line 59 of file StaticGraph.hpp.
TVertexId
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TVertexId = Types::vertexId
Definition at line 60 of file StaticGraph.hpp.
TVertexProperties
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TVertexProperties = VertexProperties
Definition at line 58 of file StaticGraph.hpp.
TVerticesView
template<typename VertexProperties , typename EdgeProperties > using egoa::StaticGraph< VertexProperties, EdgeProperties >::TVerticesView = VectorView<TVertex, false>
Definition at line 66 of file StaticGraph.hpp.
Constructor & Destructor Documentation
StaticGraph() [1/2]
template<typename VertexProperties , typename EdgeProperties > egoa::StaticGraph< VertexProperties, EdgeProperties >::StaticGraph () inline
Definition at line 75 of file StaticGraph.hpp.
StaticGraph() [2/2]
template<typename VertexProperties , typename EdgeProperties > egoa::StaticGraph< VertexProperties, EdgeProperties >::StaticGraph (Types::name name) inline explicit
Definition at line 79 of file StaticGraph.hpp.
Member Function Documentation
AddEdge() [1/2]
template<typename VertexProperties , typename EdgeProperties > Types::edgeId egoa::StaticGraph< VertexProperties, EdgeProperties >::AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties && properties) inline
Adds an edge to the set of edges .
Precondition
Source and target of the edge are existing vertices.
Parameters
[in] source The source vertex identifier.
[in] target The target vertex identifier.
properties The vertex properties.
Returns
The edge identifier.
Definition at line 672 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::edges_, egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::StaticGraph< VertexProperties, EdgeProperties >::NumberOfEdges(), egoa::StaticGraph< VertexProperties, EdgeProperties >::outEdgeIds_, and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
AddEdge() [2/2]
template<typename VertexProperties , typename EdgeProperties > Types::edgeId egoa::StaticGraph< VertexProperties, EdgeProperties >::AddEdge (Types::vertexId source, Types::vertexId target, TEdgeProperties const & properties) inline
Adds an edge to the set of edges .
Precondition
Source and target of the edge are existing vertices.
Parameters
[in] source The source vertex identifier.
[in] target The target vertex identifier.
properties The vertex properties.
Returns
The edge identifier.
Definition at line 652 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::AddEdge(), egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
AddVertex() [1/2]
template<typename VertexProperties , typename EdgeProperties > Types::vertexId egoa::StaticGraph< VertexProperties, EdgeProperties >::AddVertex (TVertexProperties && properties) inline
Adds a vertex.
Parameters
properties The vertex properties.
Returns
The identifier of the vertex.
Definition at line 241 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::StaticGraph< VertexProperties, EdgeProperties >::NumberOfVertices(), egoa::StaticGraph< VertexProperties, EdgeProperties >::outEdgeIds_, and egoa::StaticGraph< VertexProperties, EdgeProperties >::vertices_.
AddVertex() [2/2]
template<typename VertexProperties , typename EdgeProperties > Types::vertexId egoa::StaticGraph< VertexProperties, EdgeProperties >::AddVertex (TVertexProperties const & properties) inline
Adds a vertex.
Parameters
properties The vertex properties.
Returns
The identifier of the vertex.
Definition at line 229 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::AddVertex(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
DegreeAt()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::StaticGraph< VertexProperties, EdgeProperties >::DegreeAt (Types::vertexId id) const inline
The degree of the vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The number of incident edges.
Definition at line 389 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::InDegreeAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::OutDegreeAt(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
DumpBranches()
template<typename VertexProperties , typename EdgeProperties > void egoa::StaticGraph< VertexProperties, EdgeProperties >::DumpBranches (std::ostream & outputStream) const inline
Dumps branches.
Parameters
outputStream The stream to write data to
Definition at line 860 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexAt().
DumpBuses()
template<typename VertexProperties , typename EdgeProperties > void egoa::StaticGraph< VertexProperties, EdgeProperties >::DumpBuses (std::ostream & outputStream) const inline
Dumps buses.
Parameters
outputStream The stream to write data to
Definition at line 844 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
Edge() [1/2]
template<typename VertexProperties , typename EdgeProperties > TEdge & egoa::StaticGraph< VertexProperties, EdgeProperties >::Edge (Types::vertexId source, Types::vertexId target) inline
Searches for an edge .
Precondition
Both source and target are identifiers of existing vertices, and there is an edge from source to target.
Parameters
[in] source The source vertex of the edge .
[in] target The target vertex of the edge .
Returns
The edge .
Definition at line 606 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeId(), egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
Edge() [2/2]
template<typename VertexProperties , typename EdgeProperties > TEdge const & egoa::StaticGraph< VertexProperties, EdgeProperties >::Edge (Types::vertexId source, Types::vertexId target) const inline
Searches for an edge .
Precondition
Both source and target are identifiers of existing vertices, and there is an edge from source to target.
Parameters
[in] source The source vertex of the edge .
[in] target The target vertex of the edge .
Returns
The edge .
Definition at line 630 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeId(), egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
EdgeAt() [1/2]
template<typename VertexProperties , typename EdgeProperties > TEdge & egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeAt (Types::edgeId id) inline
The edge with identifier id.
Precondition
The edge with identifier id exists.
Parameters
[in] id The edge identifier.
Returns
The edge object with identifier id.
Definition at line 533 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeExists(), egoa::StaticGraph< VertexProperties, EdgeProperties >::edges_, and egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
EdgeAt() [2/2]
template<typename VertexProperties , typename EdgeProperties > TEdge const & egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeAt (Types::edgeId id) const inline
The edge with identifier id.
Precondition
The edge with identifier id exists.
Parameters
[in] id The edge identifier.
Returns
The edge object with identifier id.
Definition at line 548 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeExists(), egoa::StaticGraph< VertexProperties, EdgeProperties >::edges_, and egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
EdgeExists()
template<typename VertexProperties , typename EdgeProperties > bool egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeExists (Types::edgeId id) const inline
Whether an edge with the identifier id exists in the graph.
Parameters
[in] id The edge identifier
Returns
true if an edge with identifier id exists, false otherwise.
Definition at line 519 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::NumberOfEdges().
EdgeId()
template<typename VertexProperties , typename EdgeProperties > Types::edgeId egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeId (Types::vertexId source, Types::vertexId target) const inline
Searches for the identifier of the edge .
If no such edge exists, Const::NONE is returned.
Precondition
Both source and target are identifiers of existing vertices.
Parameters
[in] source The source vertex of the edge .
[in] target The target vertex of the edge .
Returns
The edge identifier, or Const::NONE if the edge does not exist.
Definition at line 569 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::InDegreeAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::inEdgeIds_, egoa::StaticGraph< VertexProperties, EdgeProperties >::OutDegreeAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::outEdgeIds_, and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
EdgeIdsAt() [1/2]
template<typename VertexProperties , typename EdgeProperties > std::vector< Types::edgeId > egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeIdsAt (Types::vertexId id) const inline
All edge identifiers of edges incident to a vertex.
The order of the identifiers is unspecified.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The edge identifiers at a vertex id.
Definition at line 435 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeIdsAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
EdgeIdsAt() [2/2]
template<typename VertexProperties , typename EdgeProperties > void egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeIdsAt (Types::vertexId id, std::vector< Types::edgeId > & edgeIds) const inline
All edge identifiers of edges incident to a vertex are added to the end of the vector edgeIds.
The order of the identifiers is unspecified.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex id
edgeIds The vector to which the edge identifiers are appended.
Definition at line 456 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::InEdgeIdsAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::OutEdgeIdsAt(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
Edges() [1/2]
template<typename VertexProperties , typename EdgeProperties > TEdgesView egoa::StaticGraph< VertexProperties, EdgeProperties >::Edges () inline
A view on the edges.
The edges can be modified via this view.
        If an edge is added, the view is still valid but
        the iterators obtained via this view are
        invalidated.
        If the graphs is destroyed, all view are
        invalidated and calling any member function on them
        has undefined behavior.
Returns
A view on the edges
Definition at line 486 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::edges_.
Edges() [2/2]
template<typename VertexProperties , typename EdgeProperties > TConstEdgesView egoa::StaticGraph< VertexProperties, EdgeProperties >::Edges () const inline
A view on the edges.
The edges cannot be modified via this view.
        If an edge is added, the view is still valid but
        the iterators obtained via this view are
        invalidated.
        If the graphs is destroyed, all view are
        invalidated and calling any member function on them
        has undefined behavior.
Returns
A view on the edges
Definition at line 505 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::edges_.
for_all_edge_identifiers()
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_edge_identifiers (FUNCTION function) const inline
The for loop over all identifiers of edges in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept one argument of type Types::edgeId, e.g.,
for_all_edge_identifiers (
    []( Types::edgeId edgeId )
    {
        // Do something with the edge identifier.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1061 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edge_tuples() [1/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_edge_tuples (FUNCTION function) inline
The for loop over all pairs of edge identifiers and edge objects in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept two arguments of types Types::edgeId and TEdge, e.g.,
for_all_edge_tuples (
    []( Types::edgeId edgeId, TEdge & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1141 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edge_tuples() [2/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_edge_tuples (FUNCTION function) const inline
The for loop over all pairs of edge identifiers and edge objects in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept two arguments of types Types::edgeId and TEdge, e.g.,
for_all_edge_tuples (
    []( Types::edgeId edgeId, TEdge const & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1169 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges() [1/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_edges (FUNCTION function) inline
The for loop over all edges in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept one argument of type TEdge, e.g.,
for_all_edges (
    []( TEdge & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy..
FUNCTION The type of the function object.
Definition at line 1087 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges() [2/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_edges (FUNCTION function) const inline
The for loop over all edges in the graph.
Parameters
[in] function The function object that is called for all edges. It must accept one argument of type TEdge, e.g.,
for_all_edges (
    []( TEdge const & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1113 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges_at() [1/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_edges_at (TVertex const & vertex, FUNCTION function) inline
The for loop over all edges at a vertex object.
This is a loop over incoming and outgoing edges.
Parameters
[in] vertex The vertex object
[in] function The function object that is called for all edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_all_edges_at<ExecutionPolicy::sequential>(vertex
    , []( TEdge & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incident edges at vertexId.
Definition at line 1202 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges_at() [2/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_edges_at (TVertex const & vertex, FUNCTION function) const inline
The for loop over all edges at a vertex object.
This is a loop over incoming and outgoing edges.
Parameters
[in] vertex The vertex object
[in] function The function object that is called for all edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_all_edges_at<ExecutionPolicy::sequential>(vertex
    , []( TEdge const & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incident edges at vertexId.
Definition at line 1232 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_edges_at() [3/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_edges_at (Types::vertexId const vertexId, FUNCTION function) inline
The for loop over all edges at a vertex.
This is a loop over incoming and outgoing edges.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for all edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_all_edges_at (vertexId
    , []( TEdge & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incident edges at vertexId.
Definition at line 1264 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
for_all_edges_at() [4/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_edges_at (Types::vertexId const vertexId, FUNCTION function) const inline
The for loop over all edges at a vertex.
This is a loop over incoming and outgoing edges.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for all edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_all_edges_at (vertexId
    , []( TEdge const & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incident edges at vertexId.
Definition at line 1298 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
for_all_vertex_identifiers()
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers (FUNCTION function) const inline
The for loop over all vertex identifiers in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept one argument of type Types::vertexId, e.g.,
for_all_vertex_identifiers (
    []( Types::vertexId vertexId )
    {
        // Do something with the vertex identifier.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 923 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_vertex_tuples() [1/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_tuples (FUNCTION function) inline
The for loop over all pairs of vertex identifiers and vertex objects in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept two arguments of types Types::vertexId and TVertex, e.g.,
for_all_vertex_tuples (
    []( Types::vertexId id, TVertex const & vertex )
    {
        // Do something with the vertex identifier and object
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1003 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_vertex_tuples() [2/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_tuples (FUNCTION function) const inline
The for loop over all pairs of vertex identifiers and vertex objects in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept two arguments of types Types::vertexId and TVertex, e.g.,
for_all_vertex_tuples (
    []( Types::vertexId id, TVertex const & vertex )
    {
        // Do something with the vertex identifier and object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 1030 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_vertices() [1/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertices (FUNCTION function) inline
The for loop over all vertex objects in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept one argument of type TVertex, e.g.,
for_all_vertices (
    []( TVertex & vertex )
    {
        // Do something with the vertex object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 949 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_all_vertices() [2/2]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertices (FUNCTION function) const inline
The for loop over all vertex objects in the graph.
Parameters
[in] function The function object that is called for all vertices. It must accept one argument of type TVertex, e.g.,
for_all_vertices (
    []( TVertex const & vertex )
    {
        // Do something with the vertex object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 975 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_in_edges_at() [1/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_in_edges_at (TVertex const & vertex, FUNCTION function) inline
The for loop over all incoming edges of a vertex.
Parameters
[in] vertex The vertex object.
[in] function The function object that is called for all incoming edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_all_edges_at (vertex
    , []( TEdge const & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy, e.g., ExecutionPolicy::sequential.
FUNCTION The function object that is called for all incident incoming edges at vertexId.
Definition at line 1328 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_in_edges_at() [2/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_in_edges_at (TVertex const & vertex, FUNCTION function) const inline
The for loop over all incoming edges of a vertex.
Parameters
[in] vertex The vertex object
[in] function The function object that is called for all incoming edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_in_edges_at (vertex
    , []( TEdge const & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incoming edges at vertexId.
Definition at line 1357 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_in_edges_at() [3/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_in_edges_at (Types::vertexId vertexId, FUNCTION function) inline
The for loop over all incoming edges of a vertex.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The identifier of the vertex
[in] function The function object that is called for all incoming edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_in_edges_at (vertexId
    , []( TEdge & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incoming edges at vertexId
Definition at line 1387 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
for_in_edges_at() [4/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_in_edges_at (Types::vertexId vertexId, FUNCTION function) const inline
The for loop over all incoming edges of a vertex.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The identifier of the vertex
[in] function The function object that is called for all incoming edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_in_edges_at (vertexId
    , []( TEdge const & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all incoming edges at vertexId
Definition at line 1418 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
for_out_edges_at() [1/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_out_edges_at (TVertex const & vertex, FUNCTION function) inline
The for loop over all outgoing edges of a vertex.
Parameters
[in] vertex The vertex object.
[in] function The function object that is called for all outgoing edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_out_edges_at (vertex
    , []( TEdge & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy
FUNCTION The function object that is called for all outgoing edges of vertex
Definition at line 1447 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_out_edges_at() [2/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_out_edges_at (TVertex const & vertex, FUNCTION function) const inline
The for loop over all outgoing edges of a vertex.
Parameters
[in] vertex The vertex object.
[in] function The function object that is called for all outgoing edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_out_edges_at (vertex
    , []( TEdge const & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all outgoing edges of vertex
Definition at line 1475 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
for_out_edges_at() [3/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_out_edges_at (Types::vertexId vertexId, FUNCTION function) inline
The for loop over all outgoing edges.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for all outgoing edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_out_edges_at (vertexId
    , []( TEdge & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all outgoing edges of vertex.
Definition at line 1507 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
for_out_edges_at() [4/4]
template<typename VertexProperties , typename EdgeProperties > template<ExecutionPolicy Policy = ExecutionPolicy::sequential, typename FUNCTION > void egoa::StaticGraph< VertexProperties, EdgeProperties >::for_out_edges_at (Types::vertexId vertexId, FUNCTION function) const inline
The for loop over all outgoing edges.
Precondition
There is a vertex with identifier vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for all outgoing edges at the vertex. It must accept one argument of type TEdge, e.g.,
for_out_edges_at (vertexId
    []( TEdge const & edge )
    {
        // Do something with the edge object.
    }
);
Template Parameters
Policy The execution policy.
FUNCTION The function object that is called for all outgoing edges of vertex.
Definition at line 1540 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
InDegreeAt()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::StaticGraph< VertexProperties, EdgeProperties >::InDegreeAt (Types::vertexId id) const inline
The indegree of the vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The number of incoming edges.
Definition at line 359 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::InEdgeIdsAt(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
InEdgeIdsAt()
template<typename VertexProperties , typename EdgeProperties > std::vector< Types::edgeId > const & egoa::StaticGraph< VertexProperties, EdgeProperties >::InEdgeIdsAt (Types::vertexId id) const inline
The identifiers of all incoming edges.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The identifiers of the incoming edges at vertex id.
Definition at line 404 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::inEdgeIds_, and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
MapEdges()
template<typename VertexProperties , typename EdgeProperties > template<typename FUNCTION > auto egoa::StaticGraph< VertexProperties, EdgeProperties >::MapEdges (FUNCTION function) const -> std::vector<decltype(function(std::declval<Types::edgeId>(), std::declval<TEdge>()))> inline
Applies function to all edges and collects the result in a vector.
Parameters
[in] function The function that is applied to all edges.
TResult function(Types::edgeId, TEdge)
Template Parameters
FUNCTION The type of the function object.
Returns
A vector containing the results of the applications of function to all edges.
Definition at line 708 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
MapVertices()
template<typename VertexProperties , typename EdgeProperties > template<typename FUNCTION > auto egoa::StaticGraph< VertexProperties, EdgeProperties >::MapVertices (FUNCTION function) const -> std::vector<decltype(function(std::declval<Types::vertexId>(), std::declval<TVertex>()))> inline
Applies function to all vertices and collects the result in a vector.
Parameters
[in] function The function that is applied to all edges.
TResult function (Types::vertexId, TVertex)
Template Parameters
FUNCTION The type of the function object.
Returns
A vector containing the results of the applications of function to all vertices.
Definition at line 272 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
MaxDegree() [1/2]
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::StaticGraph< VertexProperties, EdgeProperties >::MaxDegree () const inline
The maximum degree of the graph .
The maximum number of edges incident to any vertex in the graph. If the graph is empty, 0 is returned.
Returns
The maximum degree.
Definition at line 828 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::MaxDegree().
MaxDegree() [2/2]
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::StaticGraph< VertexProperties, EdgeProperties >::MaxDegree (Types::vertexId & id) const inline
The maximum degree of the graph .
The maximum number of edges incident to any vertex in the graph. If the graph is empty, 0 is returned.
Parameters
[in/out] id The vertex identifier with the maximum degree. If there are multiple vertices with the maximum degree, the one with the smallest identifier is returned. If the graph is empty, id is set to Const::NONE.
Returns
The maximum degree.
Definition at line 803 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::DegreeAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::NumberOfVertices(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::vertices_.
MinDegree() [1/2]
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::StaticGraph< VertexProperties, EdgeProperties >::MinDegree () const inline
The minimum degree of the graph .
The minimum number of edges incident to any vertex in the graph. If the graph is empty, 0 is returned.
Returns
The minimum degree.
Definition at line 783 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::MinDegree().
MinDegree() [2/2]
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::StaticGraph< VertexProperties, EdgeProperties >::MinDegree (Types::vertexId & id) const inline
The minimum degree of the graph .
The minimum number of edges incident to any vertex in the graph. If the graph is empty, 0 is returned.
Parameters
id The vertex identifier with the minimum degree. If there are multiple vertices with the minimum degree, the one with the smallest identifier is returned. If the graph is empty, id is set to Const::NONE.
Returns
The minimum degree.
Definition at line 758 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::DegreeAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::NumberOfVertices(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::vertices_.
Name()
template<typename VertexProperties , typename EdgeProperties > Types::name egoa::StaticGraph< VertexProperties, EdgeProperties >::Name () const inline
Name of the graph.
Returns
The name of the graph.
Definition at line 93 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::name_.
NeighborsOf() [1/2]
template<typename VertexProperties , typename EdgeProperties > std::vector< Types::vertexId > egoa::StaticGraph< VertexProperties, EdgeProperties >::NeighborsOf (Types::vertexId id) const inline
Neighbors of a vertex.
A vector containing the identifiers of the neighbors of the given vertex is returned. The order of the neighbors is unspecified.
Precondition
The vertex with identifier id exists.
Parameters
[in] id The id of a vertex.
Returns
The vertex identifiers of all neighbors.
Definition at line 300 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::NeighborsOf(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
NeighborsOf() [2/2]
template<typename VertexProperties , typename EdgeProperties > void egoa::StaticGraph< VertexProperties, EdgeProperties >::NeighborsOf (Types::vertexId id, std::vector< Types::vertexId > & vertexIds) const inline
Neighbors of a vertex.
The neighbors of the vertex are appended to the vector vertexId. The order of the neighbors is unspecified.
Time complexity: .
Precondition
The vertex with identifier id exists.
Parameters
[in] id The vertex identifier.
vertexIds The vector to which the identifiers of the neighbors are appended.
Definition at line 323 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::EdgeAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::InEdgeIdsAt(), egoa::StaticGraph< VertexProperties, EdgeProperties >::NumberOfVertices(), egoa::StaticGraph< VertexProperties, EdgeProperties >::OutEdgeIdsAt(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
NumberOfEdges()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::StaticGraph< VertexProperties, EdgeProperties >::NumberOfEdges () const inline
Number of edges .
Returns
The number of edges .
Definition at line 113 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::edges_.
NumberOfVertices()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::StaticGraph< VertexProperties, EdgeProperties >::NumberOfVertices () const inline
Number of vertices .
Returns
The number of vertices .
Definition at line 103 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::vertices_.
OutDegreeAt()
template<typename VertexProperties , typename EdgeProperties > Types::count egoa::StaticGraph< VertexProperties, EdgeProperties >::OutDegreeAt (Types::vertexId id) const inline
The outdegree of the vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The number of outgoing edges.
Definition at line 374 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::OutEdgeIdsAt(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
OutEdgeIdsAt()
template<typename VertexProperties , typename EdgeProperties > std::vector< Types::edgeId > const & egoa::StaticGraph< VertexProperties, EdgeProperties >::OutEdgeIdsAt (Types::vertexId id) const inline
The identifiers of all outgoing edges.
Precondition
There is a vertex with identifier id in the graph.
Parameters
[in] id The vertex identifier.
Returns
The identifiers of the outgoing edges at vertex id.
Definition at line 419 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::outEdgeIds_, and egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists().
VertexAt() [1/2]
template<typename VertexProperties , typename EdgeProperties > TVertex & egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexAt (Types::vertexId id) inline
The vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
param[in] id The identifier of the vertex.
Returns
The vertex object.
Definition at line 182 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::vertices_.
VertexAt() [2/2]
template<typename VertexProperties , typename EdgeProperties > TVertex const & egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexAt (Types::vertexId id) const inline
The vertex with identifier id.
Precondition
There is a vertex with identifier id in the graph.
param[in] id The identifier of the vertex.
Returns
The vertex object.
Definition at line 197 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers(), egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists(), and egoa::StaticGraph< VertexProperties, EdgeProperties >::vertices_.
VertexExists()
template<typename VertexProperties , typename EdgeProperties > bool egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexExists (Types::vertexId id) const inline
Whether a vertex with identifier id exists in the graph.
Parameters
[in] id The identifier of the vertex.
Returns
true if a vertex with identifier id exists, false otherwise.
Definition at line 168 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::NumberOfVertices().
VertexId()
template<typename VertexProperties , typename EdgeProperties > Types::vertexId egoa::StaticGraph< VertexProperties, EdgeProperties >::VertexId (TVertex const & vertex) const inline
The vertex identifier of a vertex object.
Calls vertex.Identifier().
Parameters
[in] vertex The vertex.
Returns
The vertex identifier.
Definition at line 217 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::for_all_vertex_identifiers().
Vertices() [1/2]
template<typename VertexProperties , typename EdgeProperties > TVerticesView egoa::StaticGraph< VertexProperties, EdgeProperties >::Vertices () inline
A view on the vertices.
If a vertex is added, the view is still valid but the iterators obtained via this view are invalidated.
If the graphs is destroyed, all views are invalidated and calling any member function on them has undefined behavior.
Returns
A view on the vertices
Definition at line 136 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::vertices_.
Vertices() [2/2]
template<typename VertexProperties , typename EdgeProperties > TConstVerticesView egoa::StaticGraph< VertexProperties, EdgeProperties >::Vertices () const inline
A view on the vertices.
The vertices can be modified via this view.
        If a vertex is added, the view is still valid but
        the iterators obtained via this view are
        invalidated.
        If the graphs is destroyed, all views are
        invalidated and calling any member function on them
        has undefined behavior.
Returns
A view on the vertices.
Definition at line 155 of file StaticGraph.hpp.
References egoa::StaticGraph< VertexProperties, EdgeProperties >::vertices_.
Friends And Related Symbol Documentation
operator<<
template<typename VertexProperties , typename EdgeProperties > std::ostream & operator<< (std::ostream & outputStream, StaticGraph< VertexProperties, EdgeProperties > const & rhs) friend
Write the static graph to an output stream.
Parameters
outputStream The stream to write data to, e.g., std::cout.
rhs The right hand side static graph.
Returns
The output stream.
Definition at line 881 of file StaticGraph.hpp.
Member Data Documentation
edges_
template<typename VertexProperties , typename EdgeProperties > std::vector<TEdge> egoa::StaticGraph< VertexProperties, EdgeProperties >::edges_ private
Vector of edges
Definition at line 1555 of file StaticGraph.hpp.
inEdgeIds_
template<typename VertexProperties , typename EdgeProperties > std::vector< std::vector<Types::edgeId> > egoa::StaticGraph< VertexProperties, EdgeProperties >::inEdgeIds_ private
Ids of the incoming edges per vertex
Definition at line 1557 of file StaticGraph.hpp.
name_
template<typename VertexProperties , typename EdgeProperties > Types::name egoa::StaticGraph< VertexProperties, EdgeProperties >::name_ private
Name of the graph, e.g., bus14
Definition at line 1551 of file StaticGraph.hpp.
outEdgeIds_
template<typename VertexProperties , typename EdgeProperties > std::vector< std::vector<Types::edgeId> > egoa::StaticGraph< VertexProperties, EdgeProperties >::outEdgeIds_ private
Ids of the outgoing edges per vertex
Definition at line 1558 of file StaticGraph.hpp.
vertices_
template<typename VertexProperties , typename EdgeProperties > std::vector<TVertex> egoa::StaticGraph< VertexProperties, EdgeProperties >::vertices_ private
Vector of vertices
Definition at line 1553 of file StaticGraph.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Graphs/StaticGraph.hpp