Energy Grid Optimization & Analysis (EGOA): egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination > Class Template Reference
egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination > Class Template Reference final
Class for dominating theta path.
#include <DominatingThetaPath.hpp>
Public Types
using TGraph = GraphType
using TVertex = typename GraphType::TVertex
using TVertexId = typename GraphType::TVertexId
using TEdge = typename GraphType::TEdge
using TEdgeId = typename GraphType::TEdgeId
using TLabel = LabelType
using TQueue = QueueType
using TLabelSet = LabelSetType
Public Member Functions
Constructors and Destructor
DominatingThetaPath (TGraph const &graph)
Constructs the object.
DominatingThetaPath (TGraph const &graph, TVertexId source)
Constructs the object.
Execute the DTP Algorithm
void Run ()
Run the DTP algorithm.
Access information
Types::real Result (Subgraph< TGraph const > &resultSubgraph, TVertexId const target)
Extracts the subgraph formed by the DTPs from the source to the given target.
Types::real Result (std::vector< std::vector< TVertexId > > &parent, TVertexId const target)
Extract result graph and value.
Types::count NumberOfLabels ()
Current number of labels.
Modifiers
void Source (TVertexId source)
Set the source.
void Clear ()
Clear all data structures.
IO::DtpRuntimeRow & Statistic ()
Setter for the statistic.
IO::DtpRuntimeRow const & Statistic () const
Getter for the statistic.
Compute Path Numbers
void TotalNumberOfPathsThroughVertex (std::vector< Types::count > &numberOfPathsPerVertex, std::vector< Types::real > &relativeNumberOfPathsPerVertex)
Total number of paths through a vertex.
void NumberOfPathsThroughVertex (TVertexId target, std::vector< Types::count > &numberOfPathsPerVertex, std::vector< Types::real > &relativeNumberOfPathsPerVertex)
Number of paths at each vertex.
void TotalNumberOfPathsThroughEdge (std::vector< Types::count > &numberOfPathsPerEdge, std::vector< Types::real > &relativeNumberOfPathsPerEdge)
Total number of paths through an edge.
void NumberOfPathsThroughEdge (TVertexId target, std::vector< Types::count > &numberOfPathsPerEdge, std::vector< Types::real > &relativeNumberOfPathsPerEdge)
Number of paths through an edge.
Private Member Functions
Accessors
TVertexId VertexIdOf (TLabel const &label) const
Access vertex identifier of a label.
TLabelSet const & LabelSetAt (TVertexId const vertexId) const
Getter for the set of labels of a vertex .
TLabelSet & LabelSetAt (TVertexId const vertexId)
Setter for the set of labels of a vertex .
TLabel & LabelAt (TVertexId const vertexId, Types::labelId const labelId)
The label at a vertex with vertexId and the label's identifier labelId.
Label Set L(v) and Queue Q Operators
bool QueueEmpty () const
Check if the main queue is empty.
void Insert (TLabel const &label)
Adds a label to the main queue.
void UpdateQueueWith (TLabel const &newLabel)
Update queue with new label .
TLabel QueueDeleteMinimum ()
Delete the minimum key from the queue .
bool LabelSetEmptyAt (TVertexId const vertexId) const
Check if a label set is empty at vertex .
bool LabelSetEmptyAt (TLabel const &label) const
Check if a label set is empty at vertex .
Types::labelId UpdateLabelSet (TLabelSet &labelSet)
Update a label set at a vertex .
Types::labelId UpdateLabelSetAt (TVertexId vertexId)
Update a label set at a vertex.
Label operations
void SetParentOf (TLabel &label, TLabel const &previousLabel)
Sets the parent of label to previousLabel .
bool MergeLabelAt (TVertexId vertexId, TLabel &label)
Merge label with the set of labels. at vertex .
bool ProduceCycle (TLabel &label, std::pair< TLabel, bool > &&pair)
Check if the new label produces a cycle.
Private Attributes
TGraph const & graph_
std::vector< TLabelSet > labelSets_
TQueue queue_
IO::DtpRuntimeRow dtpRuntimeRow_
Detailed Description
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict>
class egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >
Class for dominating theta path.
Todo:
Usage example
Template Parameters
GraphType The graph type, e.g., StaticGraph<Vertices::ElectricalProperties, Edges::ElectricalProperties>.
LabelType The label type such as Label, SusceptanceNormLabel, and VoltageAngleDifferenceLabel.
QueueType The priority queue type such as BinaryHeap.
LabelSetType The label set type representing the bucket Bucket.
Domination The domination criterion DominationCriterion, e.g., DominationCriterion::strict.
See also
StaticGraph
Label, SusceptanceNormLabel, VoltageAngleDifferenceLabel
BinaryHeap
Bucket
Definition at line 58 of file DominatingThetaPath.hpp.
Member Typedef Documentation
TEdge
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> using egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TEdge = typename GraphType::TEdge
The edge type.
Definition at line 65 of file DominatingThetaPath.hpp.
TEdgeId
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> using egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TEdgeId = typename GraphType::TEdgeId
The edge identifier type.
Definition at line 66 of file DominatingThetaPath.hpp.
TGraph
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> using egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TGraph = GraphType
The graph type.
Definition at line 62 of file DominatingThetaPath.hpp.
TLabel
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> using egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TLabel = LabelType
The label type.
Definition at line 68 of file DominatingThetaPath.hpp.
TLabelSet
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> using egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TLabelSet = LabelSetType
The label set type represented by a bucket.
Definition at line 70 of file DominatingThetaPath.hpp.
TQueue
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> using egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TQueue = QueueType
The priority queue type.
Definition at line 69 of file DominatingThetaPath.hpp.
TVertex
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> using egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TVertex = typename GraphType::TVertex
The vertex type.
Definition at line 63 of file DominatingThetaPath.hpp.
TVertexId
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> using egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TVertexId = typename GraphType::TVertexId
The vertex identifier type.
Definition at line 64 of file DominatingThetaPath.hpp.
Constructor & Destructor Documentation
DominatingThetaPath() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::DominatingThetaPath (TGraph const & graph) inline
Constructs the object.
Parameters
graph The graph structure.
Definition at line 82 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::dtpRuntimeRow_, and egoa::IO::DtpRuntimeRow::NameOfProblem.
DominatingThetaPath() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::DominatingThetaPath (TGraph const & graph, TVertexId source) inline
Constructs the object.
Parameters
graph The graph structure.
[in] source The source's vertex identifier.
Definition at line 98 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Clear(), and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Source().
Member Function Documentation
Clear()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Clear () inline
Clear all data structures.
Definition at line 336 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::dtpRuntimeRow_, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::graph_, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_, and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::queue_.
Insert()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Insert (TLabel const & label) inline private
Adds a label to the main queue.
Precondition
A precondition to that method is that the label set of the label's label vertex was updated. Thus, this method should only be called by UpdateLabelSet() or UpdateLabelSetAt().
Parameters
label The label.
Definition at line 602 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::queue_.
LabelAt()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> TLabel & egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelAt (TVertexId const vertexId, Types::labelId const labelId) inline private
The label at a vertex with vertexId and the label's identifier labelId.
Parameters
[in] vertexId The vertex identifier of vertex .
[in] labelId The label identifier of label .
Returns
The label .
Definition at line 569 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
LabelSetAt() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> TLabelSet & egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelSetAt (TVertexId const vertexId) inline private
Setter for the set of labels of a vertex .
Parameters
[in] vertexId The vertex identifier.
Returns
The set of labels for the vertex.
Definition at line 554 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
LabelSetAt() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> TLabelSet const & egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelSetAt (TVertexId const vertexId) const inline private
Getter for the set of labels of a vertex .
Parameters
[in] vertexId The vertex identifier.
Returns
The set of labels for the vertex.
Definition at line 539 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
LabelSetEmptyAt() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> bool egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelSetEmptyAt (TLabel const & label) const inline private
Check if a label set is empty at vertex .
Parameters
label The label .
Returns
True if the label set is empty, False otherwise.
Definition at line 677 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelSetEmptyAt(), and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::VertexIdOf().
LabelSetEmptyAt() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> bool egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelSetEmptyAt (TVertexId const vertexId) const inline private
Check if a label set is empty at vertex .
Parameters
[in] vertexId The vertex identifier of vertex .
Returns
True if the label set is empty, False otherwise.
Definition at line 662 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
MergeLabelAt()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> bool egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::MergeLabelAt (TVertexId vertexId, TLabel & label) inline private
Merge label with the set of labels. at vertex .
Checks if the new label is dominated by any label in and delete dominated labels. If is dominated by another label it is marked as invalid.
Parameters
[in] vertexId The vertex with set of labels .
labelStruct The label that should be merged into the set of labels .
Returns
True if the merging was successful, False otherwise.
Definition at line 765 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
NumberOfLabels()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> Types::count egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::NumberOfLabels () inline
Current number of labels.
Returns
Total number of labels
Definition at line 300 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
NumberOfPathsThroughEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::NumberOfPathsThroughEdge (TVertexId target, std::vector< Types::count > & numberOfPathsPerEdge, std::vector< Types::real > & relativeNumberOfPathsPerEdge) inline
Number of paths through an edge.
Note that this should not be used for a normal Dijkstra implementation as the labels are always optimal. However, here the labels are not always possible and we do nod see a faster implementation to calculate the number of paths faster.
Parameters
[in] target The target for which we count the paths.
numberOfPaths The number of paths (note that this field will be resized).
relativeNumberOfPathsPerEdge The edge score per thread (if we run the algorithm parallel).
Todo:
Use DAG property of label paths.
Definition at line 471 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::graph_, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelAt(), egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelSetAt(), and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
NumberOfPathsThroughVertex()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::NumberOfPathsThroughVertex (TVertexId target, std::vector< Types::count > & numberOfPathsPerVertex, std::vector< Types::real > & relativeNumberOfPathsPerVertex) inline
Number of paths at each vertex.
This methods counts the number of paths through a vertex. However, a label path counts only once, which is realized by the marked flag.
Parameters
[in] target The target for which we count the paths.
numberOfPaths The number of paths. (Note that this field will be resized to the number of vertices in the graph if not already done.)
Todo:
Use DAG property of label paths.
Definition at line 402 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::graph_, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelAt(), egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelSetAt(), and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
ProduceCycle()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> bool egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::ProduceCycle (TLabel & label, std::pair< TLabel, bool > && pair) inline private
Check if the new label produces a cycle.
The term std::get<1>(pair) just says if the vertex could be inserted into the set of vertices. If True it does not produce a cycle, otherwise (meaning False) it produces a cycle. The latter means that the vertex was already in the set of vertices. Thus, the term (meaning std::get<1>(pair)) is negated.
Parameters
label The new label .
pair The pair should be used with "label + edge" or "edge + label".
Returns
True if the new label produces a cycle, False otherwise.
Definition at line 785 of file DominatingThetaPath.hpp.
QueueDeleteMinimum()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> TLabel egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::QueueDeleteMinimum () inline private
Delete the minimum key from the queue .
Remove the top element of the queue and push the top element of the same bucket to the queue (forward top element to the main queue).
Returns
Label that has the minimum key
See also
TQueue
Definition at line 639 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelSetEmptyAt(), egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::queue_, and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::UpdateLabelSetAt().
QueueEmpty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> bool egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::QueueEmpty () const inline private
Check if the main queue is empty.
Returns
True if the main queue is empty, False otherwise.
Definition at line 588 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::queue_.
Result() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> Types::real egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Result (std::vector< std::vector< TVertexId > > & parent, TVertexId const target) inline
Extract result graph and value.
The path is constructed from source to sink for each label that is optimal at the target. Note that the optimality is defined by the labels in the label set.
Parameters
parent The parent pointer.
[in] target The target vertex t.
Returns
The optimal value.
Definition at line 260 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::graph_, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelAt(), and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
Result() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> Types::real egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Result (Subgraph< TGraph const > & resultSubgraph, TVertexId const target) inline
Extracts the subgraph formed by the DTPs from the source to the given target.
Parameters
[out] resultSubgraph The resulting subgraph formed by all DTPs from the source to the target.
[in] target The target vertex.
Returns
The voltage angle difference from the source to the target vertex.
Definition at line 191 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::graph_, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::LabelAt(), and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_.
Run()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Run () inline
Run the DTP algorithm.
Definition at line 114 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::dtpRuntimeRow_, egoa::IO::DtpRuntimeRow::GlobalElapsedMilliseconds, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::graph_, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::MergeLabelAt(), egoa::IO::DtpRuntimeRow::Name, egoa::IO::DtpRuntimeRow::NumberOfEdges, egoa::IO::DtpRuntimeRow::NumberOfEdgesProducingNoCycle, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::NumberOfLabels(), egoa::IO::DtpRuntimeRow::NumberOfLabels, egoa::IO::DtpRuntimeRow::NumberOfRelaxedEdges, egoa::IO::DtpRuntimeRow::NumberOfScannedEdges, egoa::IO::DtpRuntimeRow::NumberOfVertices, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::ProduceCycle(), egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::QueueDeleteMinimum(), egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::QueueEmpty(), egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::SetParentOf(), and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::UpdateQueueWith().
SetParentOf()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::SetParentOf (TLabel & label, TLabel const & previousLabel) inline private
Sets the parent of label to previousLabel .
Parameters
label The current label .
previousLabel The previous label
Definition at line 742 of file DominatingThetaPath.hpp.
Source()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Source (TVertexId source) inline
Set the source.
Parameters
[in] source The source
Definition at line 321 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Clear(), egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::dtpRuntimeRow_, egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Insert(), egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_, and egoa::IO::DtpRuntimeRow::SourceId.
Statistic() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> IO::DtpRuntimeRow & egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Statistic () inline
Setter for the statistic.
Returns
The current statistic representing a row.
Definition at line 352 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::dtpRuntimeRow_.
Statistic() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> IO::DtpRuntimeRow const & egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Statistic () const inline
Getter for the statistic.
Returns
The current statistic representing a row.
Definition at line 362 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::dtpRuntimeRow_.
TotalNumberOfPathsThroughEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TotalNumberOfPathsThroughEdge (std::vector< Types::count > & numberOfPathsPerEdge, std::vector< Types::real > & relativeNumberOfPathsPerEdge) inline
Total number of paths through an edge.
Parameters
numberOfPathsPerEdge The total number of paths per edge.
relativeNumberOfPathsPerEdge The total relative number of paths per edge.
Definition at line 444 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::graph_, and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::NumberOfPathsThroughEdge().
TotalNumberOfPathsThroughVertex()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::TotalNumberOfPathsThroughVertex (std::vector< Types::count > & numberOfPathsPerVertex, std::vector< Types::real > & relativeNumberOfPathsPerVertex) inline
Total number of paths through a vertex.
Parameters
numberOfPathsPerVertex The total number of paths per vertex.
relativeNumberOfPathsPerVertex The total relative number of paths per vertex.
Definition at line 378 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::graph_, and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::NumberOfPathsThroughVertex().
UpdateLabelSet()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> Types::labelId egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::UpdateLabelSet (TLabelSet & labelSet) inline private
Update a label set at a vertex .
Remove a label associated with a vertex from the queue has to trigger an update (#labelSet.Pop()) of the label set at a vertex .
Precondition
As a precondition QueueDeleteMinimum() has to be called.
Parameters
labelSet The label set at a vertex .
Definition at line 697 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Insert().
UpdateLabelSetAt()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> Types::labelId egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::UpdateLabelSetAt (TVertexId vertexId) inline private
Update a label set at a vertex.
Removing a label associated with a vertex from the queue has to trigger an update (#labelSet.Pop()) of the label bucket at vertex .
Precondition
As a precondition QueueDeleteMinimum() has do be called.
Parameters
[in] vertexId The vertex identifier of vertex .
See also
DominatingThetaPath::UpdateBucket
Definition at line 724 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_, and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::UpdateLabelSet().
UpdateQueueWith()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> void egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::UpdateQueueWith (TLabel const & newLabel) inline private
Update queue with new label .
If there is no label of the label's vertex the label will be added to the queue. However, if the new label is better than the existing one the key is changed to the new label . Otherwise, nothing is happening.
Parameters
newLabel The new label .
Definition at line 618 of file DominatingThetaPath.hpp.
References egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::Insert(), and egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::queue_.
VertexIdOf()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> TVertexId egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::VertexIdOf (TLabel const & label) const inline private
Access vertex identifier of a label.
Parameters
label The label
Returns
The vertex identifier.
Definition at line 526 of file DominatingThetaPath.hpp.
Member Data Documentation
dtpRuntimeRow_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> IO::DtpRuntimeRow egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::dtpRuntimeRow_ private
To measure quality and time information.
Definition at line 799 of file DominatingThetaPath.hpp.
graph_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> TGraph const& egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::graph_ private
The graph on which the DTP is calculated.
Definition at line 795 of file DominatingThetaPath.hpp.
labelSets_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> std::vector<TLabelSet> egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::labelSets_ private
At each vertex there is a set of labels .
Definition at line 796 of file DominatingThetaPath.hpp.
queue_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >, typename LabelType = VoltageAngleDifferenceLabel< typename GraphType::TEdge >, typename QueueType = MappingBinaryHeap< typename GraphType::TVertexId, LabelType >, typename LabelSetType = Bucket< BinaryHeap< LabelType > >, DominationCriterion Domination = DominationCriterion::strict> TQueue egoa::DominatingThetaPath< GraphType, LabelType, QueueType, LabelSetType, Domination >::queue_ private
The priority queue .
Definition at line 797 of file DominatingThetaPath.hpp.
The documentation for this class was generated from the following file:
include/Algorithms/PathFinding/DominatingThetaPath.hpp