Energy Grid Optimization & Analysis (EGOA): egoa::IO::GeoJsonWriter< GraphType > Class Template Reference
egoa::IO::GeoJsonWriter< GraphType > Class Template Reference final
Public Member Functions
Constructors and destructor
GeoJsonWriter (Types::count indent=4, bool readable=true)
Constructs a new instance.
Write Graph
bool WriteGraph (std::ostream &os, TGraph const &graph)
Writes a graph.
Writer
bool write (TNetwork const &network, std::string const &filename)
Write GeoJSON using the filename.
bool write (TNetwork const &network, std::ostream &outputStream)
Write GeoJSON using the output stream.
Private Types
using TGraph = GraphType
using TNetwork = PowerGrid< GraphType >
using TVertex = typename TGraph::TVertex
using TVertexProperties = typename TGraph::TVertexProperties
using TVertexType = typename TVertexProperties::TVertexType
using TGeneratorProperties = typename TNetwork::TGeneratorProperties
using TLoadProperties = typename TNetwork::TLoadProperties
using TEdge = typename TGraph::TEdge
using TEdgeProperties = typename TGraph::TEdgeProperties
using TBound = Bound<>
Private Member Functions
Auxiliary
void Indent (std::ostream &os, Types::count depth=1)
Add indent to the output stream.
void NewLine (std::ostream &os)
Add new line to the output stream.
bool Readable ()
Write a readable GeoJson.
Writer Methods
void WriteHeader (std::ostream &os)
Writes a header.
void WriteFooter (std::ostream &os, Types::count indent=0)
Writes a footer.
void WriteFeatureBegin (std::ostream &os, Types::count indent=1)
Writes a feature begin.
void WriteFeatureEnd (std::ostream &os, bool last=false, Types::count indent=1)
Writes a feature end.
void WritePropertiesBegin (std::ostream &os, Types::count indent=2)
Writes a properties begin.
void WriteVertexProperties (std::ostream &os, TVertexProperties const &vertexProperty, Types::count indent=2)
Writes vertex properties.
void WriteEdgeProperties (std::ostream &os, TEdgeProperties const &edgeProperty, Types::count indent=2)
Writes edge properties.
template<typename T >
void PropertyTemplate (std::ostream &os, std::string lhs, T const &rhs, bool last=false, Types::count indent=2)
Standard JSON key : value pair template.
void WritePropertiesEnd (std::ostream &os, bool last=false, Types::count indent=2)
Writes a properties end.
void WriteFeatureCollection (std::ostream &os)
Writes a feature collection.
void WriteFeaturesBegin (std::ostream &os)
Writes a features begin.
void WriteFeaturesEnd (std::ostream &os, bool last=false, Types::count indent=0)
Writes a features end.
void WriteGeometry (std::ostream &os, Types::count indent=2)
Writes a geometry.
Point Writer
void WriteVertices (std::ostream &os, TGraph const &graph, bool last=false, Types::count indent=1)
Writes points.
void WriteGenerators (std::ostream &os, TNetwork const &network, bool last=false, Types::count indent=1)
Writes points.
void WritePoint (std::ostream &os, Types::real xCoordinate, Types::real yCoordinate, Types::count indent=2)
Writes a GeoJson point.
void WritePoint (std::ostream &os, TGraph const &graph, Types::vertexId vertexId, Types::count indent=2)
Writes a GeoJson point.
void WritePoint (std::ostream &os, TVertex const &vertex, Types::count indent=2)
Writes a GeoJson point.
void WritePointCoordinate (std::ostream &os, Types::real xCoordinate, Types::real yCoordinate, Types::count indent=2)
Writes a point coordinate.
void WritePointCoordinate (std::ostream &os, TGraph const &graph, Types::vertexId vertexId)
Writes a point coordinate.
void WritePointCoordinate (std::ostream &os, TVertex const &vertex)
Writes a point coordinate.
Line Writer
void WriteLines (std::ostream &os, TGraph const &graph, bool last=false, Types::count indent=2)
Writes lines.
void WriteLinesGeometryObject (std::ostream &os, TVertex const &sourceVertex, TVertex const &targetVertex, Types::count indent=2)
Writes a lines geometry object.
void WriteLineHeader (std::ostream &os, Types::count indent=3)
Writes a line header.
void WriteLineContent (std::ostream &os, TVertex const &sourceVertex, TVertex const &targetVertex, Types::count indent=4)
Writes a line content.
void WriteLineFooter (std::ostream &os, Types::count indent=2)
Writes a line footer.
Private Attributes
Types::count const indent_
bool readable_
Detailed Description
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >>
class egoa::IO::GeoJsonWriter< GraphType >
Definition at line 27 of file GeojsonWriter.hpp.
Member Typedef Documentation
TBound
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TBound = Bound<> private
Definition at line 44 of file GeojsonWriter.hpp.
TEdge
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TEdge = typename TGraph::TEdge private
Definition at line 40 of file GeojsonWriter.hpp.
TEdgeProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TEdgeProperties = typename TGraph::TEdgeProperties private
Definition at line 41 of file GeojsonWriter.hpp.
TGeneratorProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TGeneratorProperties = typename TNetwork::TGeneratorProperties private
Definition at line 37 of file GeojsonWriter.hpp.
TGraph
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TGraph = GraphType private
Definition at line 31 of file GeojsonWriter.hpp.
TLoadProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TLoadProperties = typename TNetwork::TLoadProperties private
Definition at line 38 of file GeojsonWriter.hpp.
TNetwork
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TNetwork = PowerGrid<GraphType> private
Definition at line 32 of file GeojsonWriter.hpp.
TVertex
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TVertex = typename TGraph::TVertex private
Definition at line 34 of file GeojsonWriter.hpp.
TVertexProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TVertexProperties = typename TGraph::TVertexProperties private
Definition at line 35 of file GeojsonWriter.hpp.
TVertexType
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> using egoa::IO::GeoJsonWriter< GraphType >::TVertexType = typename TVertexProperties::TVertexType private
Definition at line 36 of file GeojsonWriter.hpp.
Constructor & Destructor Documentation
GeoJsonWriter()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> egoa::IO::GeoJsonWriter< GraphType >::GeoJsonWriter (Types::count indent = 4, bool readable = true) inline explicit
Constructs a new instance.
Parameters
filename The filename.
[in] indent If true the file has a proper layout, otherwise its representation is compact.
Definition at line 59 of file GeojsonWriter.hpp.
~GeoJsonWriter()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> egoa::IO::GeoJsonWriter< GraphType >::~GeoJsonWriter () inline
Definition at line 65 of file GeojsonWriter.hpp.
Member Function Documentation
Indent()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::Indent (std::ostream & os, Types::count depth = 1) inline private
Add indent to the output stream.
Parameters
os The output stream.
[in] depth The indent number.
Definition at line 104 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Readable().
NewLine()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::NewLine (std::ostream & os) inline private
Add new line to the output stream.
Parameters
os The output stream.
Definition at line 119 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Readable().
PropertyTemplate()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> template<typename T > void egoa::IO::GeoJsonWriter< GraphType >::PropertyTemplate (std::ostream & os, std::string lhs, T const & rhs, bool last = false, Types::count indent = 2) inline private
Standard JSON key : value pair template.
Precondition
The right hand-side object has to support the output stream operator.
Parameters
os The output stream.
[in] lhs The left hand side.
rhs The right hand side.
[in] last The last.
[in] indent The indent.
Template Parameters
T Type of the right hand-side.
Definition at line 326 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), and egoa::IO::GeoJsonWriter< GraphType >::NewLine().
Readable()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> bool egoa::IO::GeoJsonWriter< GraphType >::Readable () inline private
Write a readable GeoJson.
Returns
@true if the GeoJson will have indents and newlines, @false compact representation without any indents and newlines.
Definition at line 134 of file GeojsonWriter.hpp.
write() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> bool egoa::IO::GeoJsonWriter< GraphType >::write (TNetwork const & network, std::ostream & outputStream) inline
Write GeoJSON using the output stream.
Parameters
network The network.
OutputStream The output stream to write data.
Returns
true if the writing was successful, false otherwise.
Definition at line 726 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WriteGraph().
write() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> bool egoa::IO::GeoJsonWriter< GraphType >::write (TNetwork const & network, std::string const & filename) inline
Write GeoJSON using the filename.
Parameters
network The network.
filename The filename.
Returns
true if the writing was successful, false otherwise.
Definition at line 706 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WriteGraph().
WriteEdgeProperties()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteEdgeProperties (std::ostream & os, TEdgeProperties const & edgeProperty, Types::count indent = 2) inline private
Writes edge properties.
Parameters
os The output stream.
edgeProperty The edge property.
[in] indent The indent.
Definition at line 268 of file GeojsonWriter.hpp.
WriteFeatureBegin()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteFeatureBegin (std::ostream & os, Types::count indent = 1) inline private
Writes a feature begin.
Parameters
os The output stream.
[in] indent The indent.
Definition at line 175 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), and egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteFeatureCollection()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteFeatureCollection (std::ostream & os) inline private
Writes a feature collection.
Parameters
os The output stream.
Definition at line 368 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteFeatureEnd()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteFeatureEnd (std::ostream & os, bool last = false, Types::count indent = 1) inline private
Writes a feature end.
Parameters
os The output stream.
[in] last The last.
[in] indent The indent.
Definition at line 194 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), and egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteFeaturesBegin()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteFeaturesBegin (std::ostream & os) inline private
Writes a features begin.
Parameters
os The output stream.
Definition at line 379 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteFeaturesEnd()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteFeaturesEnd (std::ostream & os, bool last = false, Types::count indent = 0) inline private
Writes a features end.
Parameters
os The output stream.
[in] last The last.
[in] indent The indent.
Definition at line 392 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), and egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteFooter()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteFooter (std::ostream & os, Types::count indent = 0) inline private
Writes a footer.
Parameters
os The operating system
[in] indent The indent
Definition at line 161 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), and egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteGenerators()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteGenerators (std::ostream & os, TNetwork const & network, bool last = false, Types::count indent = 1) inline private
Writes points.
Parameters
os The output stream.
graph The graph.
[in] last The last.
[in] indent The indent.
Definition at line 452 of file GeojsonWriter.hpp.
WriteGeometry()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteGeometry (std::ostream & os, Types::count indent = 2) inline private
Writes a geometry.
Parameters
os The output stream.
[in] indent The indent.
Definition at line 409 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent().
WriteGraph()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> bool egoa::IO::GeoJsonWriter< GraphType >::WriteGraph (std::ostream & os, TGraph const & graph) inline
Writes a graph.
Parameters
os The output stream.
graph The graph.
Returns
true if the writing was successful, false otherwise.
Definition at line 79 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WriteFeatureCollection(), egoa::IO::GeoJsonWriter< GraphType >::WriteFeaturesBegin(), egoa::IO::GeoJsonWriter< GraphType >::WriteFeaturesEnd(), egoa::IO::GeoJsonWriter< GraphType >::WriteFooter(), egoa::IO::GeoJsonWriter< GraphType >::WriteHeader(), egoa::IO::GeoJsonWriter< GraphType >::WriteLines(), and egoa::IO::GeoJsonWriter< GraphType >::WriteVertices().
WriteHeader()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteHeader (std::ostream & os) inline private
Writes a header.
Parameters
os The output stream.
Definition at line 149 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteLineContent()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteLineContent (std::ostream & os, TVertex const & sourceVertex, TVertex const & targetVertex, Types::count indent = 4) inline private
Writes a line content.
Parameters
os The output stream.
graph The graph.
[in] indent The indent.
Definition at line 659 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), egoa::IO::GeoJsonWriter< GraphType >::NewLine(), and egoa::IO::GeoJsonWriter< GraphType >::WritePointCoordinate().
WriteLineFooter()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteLineFooter (std::ostream & os, Types::count indent = 2) inline private
Writes a line footer.
Parameters
os The output stream.
[in] indent The indent.
Definition at line 683 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), and egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteLineHeader()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteLineHeader (std::ostream & os, Types::count indent = 3) inline private
Writes a line header.
Parameters
os The output stream.
[in] indent The indent.
Definition at line 639 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), and egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteLines()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteLines (std::ostream & os, TGraph const & graph, bool last = false, Types::count indent = 2) inline private
Writes lines.
Parameters
os The output stream.
graph The graph.
[in] last The last.
[in] indent The indent.
Definition at line 594 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WriteEdgeProperties(), egoa::IO::GeoJsonWriter< GraphType >::WriteFeatureBegin(), egoa::IO::GeoJsonWriter< GraphType >::WriteFeatureEnd(), egoa::IO::GeoJsonWriter< GraphType >::WriteLinesGeometryObject(), egoa::IO::GeoJsonWriter< GraphType >::WritePropertiesBegin(), and egoa::IO::GeoJsonWriter< GraphType >::WritePropertiesEnd().
WriteLinesGeometryObject()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteLinesGeometryObject (std::ostream & os, TVertex const & sourceVertex, TVertex const & targetVertex, Types::count indent = 2) inline private
Writes a lines geometry object.
Parameters
os The output stream.
graph The graph.
[in] indent The indent.
Definition at line 622 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WriteGeometry(), egoa::IO::GeoJsonWriter< GraphType >::WriteLineContent(), egoa::IO::GeoJsonWriter< GraphType >::WriteLineFooter(), and egoa::IO::GeoJsonWriter< GraphType >::WriteLineHeader().
WritePoint() [1/3]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WritePoint (std::ostream & os, TGraph const & graph, Types::vertexId vertexId, Types::count indent = 2) inline private
Writes a GeoJson point.
Parameters
os The output stream.
graph The graph.
[in] vertexId The vertex identifier.
Definition at line 503 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WritePoint().
WritePoint() [2/3]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WritePoint (std::ostream & os, TVertex const & vertex, Types::count indent = 2) inline private
Writes a GeoJson point.
Parameters
os The output stream.
vertex The vertex.
Definition at line 520 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WritePoint().
WritePoint() [3/3]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WritePoint (std::ostream & os, Types::real xCoordinate, Types::real yCoordinate, Types::count indent = 2) inline private
Writes a GeoJson point.
Parameters
os The output stream.
[in] xCoordinate The coordinate.
[in] yCoordinate The y coordinate.
Definition at line 474 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), egoa::IO::GeoJsonWriter< GraphType >::NewLine(), egoa::IO::GeoJsonWriter< GraphType >::WriteGeometry(), and egoa::IO::GeoJsonWriter< GraphType >::WritePointCoordinate().
WritePointCoordinate() [1/3]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WritePointCoordinate (std::ostream & os, TGraph const & graph, Types::vertexId vertexId) inline private
Writes a point coordinate.
Parameters
os The output stream.
graph The graph
[in] vertexId The vertex identifier
Definition at line 558 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WritePointCoordinate().
WritePointCoordinate() [2/3]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WritePointCoordinate (std::ostream & os, TVertex const & vertex) inline private
Writes a point coordinate.
Parameters
os The output stream.
vertex The vertex
Definition at line 573 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WritePointCoordinate().
WritePointCoordinate() [3/3]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WritePointCoordinate (std::ostream & os, Types::real xCoordinate, Types::real yCoordinate, Types::count indent = 2) inline private
Writes a point coordinate.
Parameters
os The output stream.
[in] xCoordinate The coordinate
[in] yCoordinate The y coordinate
Definition at line 537 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent().
WritePropertiesBegin()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WritePropertiesBegin (std::ostream & os, Types::count indent = 2) inline private
Writes a properties begin.
Parameters
os The output stream.
[in] indent The indent.
Definition at line 211 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), and egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WritePropertiesEnd()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WritePropertiesEnd (std::ostream & os, bool last = false, Types::count indent = 2) inline private
Writes a properties end.
Parameters
os The output stream.
[in] last The last.
[in] indent The indent.
Definition at line 351 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::Indent(), and egoa::IO::GeoJsonWriter< GraphType >::NewLine().
WriteVertexProperties()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteVertexProperties (std::ostream & os, TVertexProperties const & vertexProperty, Types::count indent = 2) inline private
Writes vertex properties.
Parameters
os The output stream.
vertexProperty The vertex property.
[in] indent The indent.
Definition at line 227 of file GeojsonWriter.hpp.
WriteVertices()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> void egoa::IO::GeoJsonWriter< GraphType >::WriteVertices (std::ostream & os, TGraph const & graph, bool last = false, Types::count indent = 1) inline private
Writes points.
Parameters
os The output stream.
graph The graph.
[in] last The last.
[in] indent The indent.
Definition at line 429 of file GeojsonWriter.hpp.
References egoa::IO::GeoJsonWriter< GraphType >::WriteFeatureBegin(), egoa::IO::GeoJsonWriter< GraphType >::WriteFeatureEnd(), egoa::IO::GeoJsonWriter< GraphType >::WritePoint(), egoa::IO::GeoJsonWriter< GraphType >::WritePropertiesBegin(), egoa::IO::GeoJsonWriter< GraphType >::WritePropertiesEnd(), and egoa::IO::GeoJsonWriter< GraphType >::WriteVertexProperties().
Member Data Documentation
indent_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> Types::count const egoa::IO::GeoJsonWriter< GraphType >::indent_ private
Definition at line 734 of file GeojsonWriter.hpp.
readable_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType> , Edges::ElectricalProperties >> bool egoa::IO::GeoJsonWriter< GraphType >::readable_ private
Definition at line 735 of file GeojsonWriter.hpp.
The documentation for this class was generated from the following file:
include/IO/Writer/GeojsonWriter.hpp