Energy Grid Optimization & Analysis (EGOA): egoa::BlockCutTreeTraversal< GraphType > Class Template Reference
egoa::BlockCutTreeTraversal< GraphType > Class Template Reference
Block-cut tree related classes and functions
Traverses a block-cut tree in a post-order traversal, i.e., a node of the tree is visited directly after all its child nodes have been visited.
#include <BlockCutTreeTraversal.hpp>
Public Types
using TGraph = GraphType
using TTree = BlockCutTree< TGraph >
using Block = typename TTree::Block
using CutVertex = typename TTree::CutVertex
using TNode = std::variant< std::reference_wrapper< Block const >, std::reference_wrapper< CutVertex const > >
Public Member Functions
Constructors
BlockCutTreeTraversal (BlockCutTree< TGraph > const &bcTree)
A constructor.
BlockCutTreeTraversal (BlockCutTree< TGraph > const &bcTree, TNode root)
A constructor.
BlockCutTreeTraversal (BlockCutTree< TGraph > const &bcTree, CutVertex const &root)
A constructor.
Accessors
TNode & Root ()
TNode const & Root () const
Algorithm Execution
void Run ()
Runs the algorithm.
Protected Member Functions
Visiting
virtual void VisitLeaf (Block const &block)
This function is called for each leaf.
virtual void VisitCutVertex (CutVertex const &cutVertex)
This function is called for each cut-vertex.
virtual void VisitBlock (Block const &block)
This function is called for each inner block.
virtual void VisitRoot (TNode root)
This function is called for the root.
Private Member Functions
Auxiliary
bool IsBlock (Types::index id) const
bool IsCutVertex (Types::index id) const
Types::index NodeToId (TNode const &node) const
Block const & BlockAt (Types::index identifier) const
CutVertex const & CutVertexAt (Types::index identifier) const
Private Attributes
Input Members
BlockCutTree< TGraph > const & bcTree_
TNode root_
Types::index rootId_
Members for Traversal
std::stack< Types::index, std::vector< Types::index > > nodeStack_
The identifiers of the nodes on the stack.
std::vector< bool > visited_ = std::vector<bool>(bcTree_.Graph().NumberOfVertices() + bcTree_.NumberOfBlocks(), false)
Whether the node with the given identifier has been visited.
Detailed Description
template<typename GraphType>
class egoa::BlockCutTreeTraversal< GraphType >
Traverses a block-cut tree in a post-order traversal, i.e., a node of the tree is visited directly after all its child nodes have been visited.
This base implementation does nothing for each node. To do something useful, implement the corresponding member function:
VisitLeaf
VisitCutVertex
VisitBlock
VisitRoot
Template Parameters
GraphType The type of the graph for which the block-cut tree was computed.
Definition at line 39 of file BlockCutTreeTraversal.hpp.
Member Typedef Documentation
Block
template<typename GraphType > using egoa::BlockCutTreeTraversal< GraphType >::Block = typename TTree::Block
Definition at line 43 of file BlockCutTreeTraversal.hpp.
CutVertex
template<typename GraphType > using egoa::BlockCutTreeTraversal< GraphType >::CutVertex = typename TTree::CutVertex
Definition at line 44 of file BlockCutTreeTraversal.hpp.
TGraph
template<typename GraphType > using egoa::BlockCutTreeTraversal< GraphType >::TGraph = GraphType
Definition at line 41 of file BlockCutTreeTraversal.hpp.
TNode
template<typename GraphType > using egoa::BlockCutTreeTraversal< GraphType >::TNode = std::variant<std::reference_wrapper<Block const>, std::reference_wrapper<CutVertex const> >
Definition at line 45 of file BlockCutTreeTraversal.hpp.
TTree
template<typename GraphType > using egoa::BlockCutTreeTraversal< GraphType >::TTree = BlockCutTree<TGraph>
Definition at line 42 of file BlockCutTreeTraversal.hpp.
Constructor & Destructor Documentation
BlockCutTreeTraversal() [1/3]
template<typename GraphType > egoa::BlockCutTreeTraversal< GraphType >::BlockCutTreeTraversal (BlockCutTree< TGraph > const & bcTree) inline
A constructor.
The root is set to the first block.
Parameters
bcTree The block-cut tree.
visitor The visitor.
Definition at line 60 of file BlockCutTreeTraversal.hpp.
BlockCutTreeTraversal() [2/3]
template<typename GraphType > egoa::BlockCutTreeTraversal< GraphType >::BlockCutTreeTraversal (BlockCutTree< TGraph > const & bcTree, TNode root) inline
A constructor.
Parameters
bcTree The block-cut tree.
root The root.
visitor The visitor.
Definition at line 71 of file BlockCutTreeTraversal.hpp.
BlockCutTreeTraversal() [3/3]
template<typename GraphType > egoa::BlockCutTreeTraversal< GraphType >::BlockCutTreeTraversal (BlockCutTree< TGraph > const & bcTree, CutVertex const & root) inline
A constructor.
Parameters
bcTree The block-cut tree.
root The root.
visitor The visitor.
Definition at line 85 of file BlockCutTreeTraversal.hpp.
Member Function Documentation
BlockAt()
template<typename GraphType > Block const & egoa::BlockCutTreeTraversal< GraphType >::BlockAt (Types::index identifier) const inline private
Definition at line 221 of file BlockCutTreeTraversal.hpp.
CutVertexAt()
template<typename GraphType > CutVertex const & egoa::BlockCutTreeTraversal< GraphType >::CutVertexAt (Types::index identifier) const inline private
Definition at line 226 of file BlockCutTreeTraversal.hpp.
IsBlock()
template<typename GraphType > bool egoa::BlockCutTreeTraversal< GraphType >::IsBlock (Types::index id) const inline private
Definition at line 202 of file BlockCutTreeTraversal.hpp.
IsCutVertex()
template<typename GraphType > bool egoa::BlockCutTreeTraversal< GraphType >::IsCutVertex (Types::index id) const inline private
Definition at line 207 of file BlockCutTreeTraversal.hpp.
NodeToId()
template<typename GraphType > Types::index egoa::BlockCutTreeTraversal< GraphType >::NodeToId (TNode const & node) const inline private
Definition at line 212 of file BlockCutTreeTraversal.hpp.
Root() [1/2]
template<typename GraphType > TNode & egoa::BlockCutTreeTraversal< GraphType >::Root () inline
Definition at line 95 of file BlockCutTreeTraversal.hpp.
Root() [2/2]
template<typename GraphType > TNode const & egoa::BlockCutTreeTraversal< GraphType >::Root () const inline
Definition at line 99 of file BlockCutTreeTraversal.hpp.
Run()
template<typename GraphType > void egoa::BlockCutTreeTraversal< GraphType >::Run () inline
Runs the algorithm.
Definition at line 110 of file BlockCutTreeTraversal.hpp.
References egoa::BlockCutTree< GraphType >::Graph(), egoa::BlockCutTreeTraversal< GraphType >::nodeStack_, egoa::BlockCutTreeTraversal< GraphType >::VisitBlock(), egoa::BlockCutTreeTraversal< GraphType >::VisitCutVertex(), egoa::BlockCutTreeTraversal< GraphType >::visited_, egoa::BlockCutTreeTraversal< GraphType >::VisitLeaf(), and egoa::BlockCutTreeTraversal< GraphType >::VisitRoot().
VisitBlock()
template<typename GraphType > virtual void egoa::BlockCutTreeTraversal< GraphType >::VisitBlock (Block const & block) inline protected virtual
This function is called for each inner block.
This function is not called for the root even if the root is a block.
Parameters
block The block.
Definition at line 187 of file BlockCutTreeTraversal.hpp.
VisitCutVertex()
template<typename GraphType > virtual void egoa::BlockCutTreeTraversal< GraphType >::VisitCutVertex (CutVertex const & cutVertex) inline protected virtual
This function is called for each cut-vertex.
This function is not called for the root even if the root is a cut-vertex.
Parameters
cutVertex The cut-vertex.
Definition at line 177 of file BlockCutTreeTraversal.hpp.
VisitLeaf()
template<typename GraphType > virtual void egoa::BlockCutTreeTraversal< GraphType >::VisitLeaf (Block const & block) inline protected virtual
This function is called for each leaf.
VisitBlock is not called for the block. This function is not called for the root even if the root has degree 1.
Parameters
block The block.
Definition at line 167 of file BlockCutTreeTraversal.hpp.
VisitRoot()
template<typename GraphType > virtual void egoa::BlockCutTreeTraversal< GraphType >::VisitRoot (TNode root) inline protected virtual
This function is called for the root.
Parameters
root The root.
Definition at line 194 of file BlockCutTreeTraversal.hpp.
Member Data Documentation
bcTree_
template<typename GraphType > BlockCutTree<TGraph> const& egoa::BlockCutTreeTraversal< GraphType >::bcTree_ private
Definition at line 235 of file BlockCutTreeTraversal.hpp.
nodeStack_
template<typename GraphType > std::stack<Types::index, std::vector<Types::index> > egoa::BlockCutTreeTraversal< GraphType >::nodeStack_ private
The identifiers of the nodes on the stack.
To distiguish between block and cut-vertex identifiers, the block identifiers have an added offset of bcTree_.Graph().NumberOfVertices().
Definition at line 250 of file BlockCutTreeTraversal.hpp.
root_
template<typename GraphType > TNode egoa::BlockCutTreeTraversal< GraphType >::root_ private
Definition at line 236 of file BlockCutTreeTraversal.hpp.
rootId_
template<typename GraphType > Types::index egoa::BlockCutTreeTraversal< GraphType >::rootId_ private
Definition at line 237 of file BlockCutTreeTraversal.hpp.
visited_
template<typename GraphType > std::vector<bool> egoa::BlockCutTreeTraversal< GraphType >::visited_ = std::vector<bool>(bcTree_.Graph().NumberOfVertices() + bcTree_.NumberOfBlocks(), false) private
Whether the node with the given identifier has been visited.
Definition at line 254 of file BlockCutTreeTraversal.hpp.
The documentation for this class was generated from the following file:
include/Algorithms/BlockCutTreeTraversal.hpp