Energy Grid Optimization & Analysis (EGOA): egoa::DepthFirstSearch< GraphType, IsDirected, Recursive > Class Template Reference
egoa::DepthFirstSearch< GraphType, IsDirected, Recursive > Class Template Reference
Class for the Depth-First Search (DFS).
#include <DepthFirstSearch.hpp>
Public Types
using TGraph = GraphType
using TVertexId = typename TGraph::TVertexId
using TTime = Types::count
Public Types inherited from egoa::Traversal< GraphType, IsDirected >
using TGraph = GraphType
using TVertexId = typename GraphType::TVertexId
Public Member Functions
void Run ()
DfsEdgeType TypifyEdge (TVertexId source, TVertexId target)
Determine DFS edge type.
bool Terminate () const
Terminate the DFS.
void SetTerminate ()
TTime EntryTimeAt (TVertexId vertexId) const
{ function_description }
TTime ExitTimeAt (TVertexId const vertexId) const
Returns the exit time of a vertex.
virtual void PreprocessingVertexWith (TVertexId vertexId)
Preprocessing the vertex with vertexId.
virtual void PostprocessingVertexWith (TVertexId vertexId)
Post processing the vertex with vertexId.
virtual void ProcessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId)
virtual void PostprocessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId)
Post processing the edge with edgeId.
Constructors and destructor
DepthFirstSearch (TGraph const &graph, TVertexId source)
Constructs a new DFS instance.
Public Member Functions inherited from egoa::Traversal< GraphType, IsDirected >
virtual void Result (std::vector< TVertexId > parent)
Traversal (TGraph const &graph, TVertexId source)
Constructs a new instance.
TVertexId Source () const
Getter and setter for the source vertex.
TVertexId & Source ()
TVertexId & ParentOf (TVertexId vertexId)
Getter and setter for the parent relation.
TVertexId ParentOf (TVertexId vertexId) const
Private Member Functions
TTime Time () const
Modify time counter.
TTime & Time ()
Private Attributes
TTime time_
bool terminate_
std::vector< TTime > entryTime_
std::vector< TTime > exitTime_
Additional Inherited Members
Protected Member Functions inherited from egoa::Traversal< GraphType, IsDirected >
void Clear ()
Clear and resize all vectors.
bool VertexExists (TVertexId vertexId)
bool NumberOfVertices ()
void SetVertexVisitedAt (TVertexId vertexId)
Sets the vertex at vertexId to visited.
bool VisitedVertexAt (TVertexId vertexId) const
Getter and setter to access the visited field.
void SetVertexProcessedAt (TVertexId vertexId)
Sets the vertex at vertexId to processed.
bool ProcessedVertexAt (TVertexId vertexId) const
Getter and setter to access the process field.
template<typename FUNCTION >
void breakable_for_all_edges_at (TVertexId const &vertexId, FUNCTION function) const
The for loop over all (outgoing) edges that is breakable.
template<typename FUNCTION >
void for_all_edges_at (TVertexId const &vertexId, FUNCTION function) const
The for loop over all (outgoing) edges.
Detailed Description
template<typename GraphType, bool IsDirected = false, bool Recursive = true>
class egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >
Class for the Depth-First Search (DFS).
Template Parameters
GraphType The graph should at least provide the same interface as the StaticGraph.
IsDirected If true the graph is treated as a directed graph, if false the graph is treated as an undirected graph.
Definition at line 35 of file DepthFirstSearch.hpp.
Member Typedef Documentation
TGraph
template<typename GraphType , bool IsDirected = false, bool Recursive = true> using egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::TGraph = GraphType
Definition at line 37 of file DepthFirstSearch.hpp.
TTime
template<typename GraphType , bool IsDirected = false, bool Recursive = true> using egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::TTime = Types::count
Definition at line 39 of file DepthFirstSearch.hpp.
TVertexId
template<typename GraphType , bool IsDirected = false, bool Recursive = true> using egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::TVertexId = typename TGraph::TVertexId
Definition at line 38 of file DepthFirstSearch.hpp.
Constructor & Destructor Documentation
DepthFirstSearch()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::DepthFirstSearch (TGraph const & graph, TVertexId source) inline
Constructs a new DFS instance.
Parameters
graph The graph
[in] source The source
Definition at line 51 of file DepthFirstSearch.hpp.
~DepthFirstSearch()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> virtual egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::~DepthFirstSearch () inline virtual
Definition at line 60 of file DepthFirstSearch.hpp.
Member Function Documentation
EntryTimeAt()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> TTime egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::EntryTimeAt (TVertexId vertexId) const inline
{ function_description }
Parameters
vertex The vertex
Returns
{ description_of_the_return_value }
Definition at line 188 of file DepthFirstSearch.hpp.
References egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::entryTime_.
ExitTimeAt()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> TTime egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::ExitTimeAt (TVertexId const vertexId) const inline
Returns the exit time of a vertex.
Parameters
vertexId The vertex identifier.
Returns
The exit time for a vertex during the DFS.
Definition at line 200 of file DepthFirstSearch.hpp.
References egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::exitTime_.
PostprocessingEdgeWith()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> virtual void egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::PostprocessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId) inline virtual
Post processing the edge with edgeId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for the vertexId, e.g., a lambda function.
Template Parameters
FUNCTION The function object that is called for the edge identifiers edgeId.
Reimplemented in egoa::ArticulationVertexDetection< GraphType, IsDirected >, and egoa::ArticulationVertexDetection< GraphType, false >.
Definition at line 274 of file DepthFirstSearch.hpp.
PostprocessingVertexWith()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> virtual void egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::PostprocessingVertexWith (TVertexId vertexId) inline virtual
Post processing the vertex with vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for the vertexId, e.g., a lambda function.
Template Parameters
FUNCTION The function object that is called for the vertex identifiers vertexId.
Reimplemented in egoa::ArticulationVertexDetection< GraphType, IsDirected >, and egoa::ArticulationVertexDetection< GraphType, false >.
Definition at line 242 of file DepthFirstSearch.hpp.
PreprocessingVertexWith()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> virtual void egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::PreprocessingVertexWith (TVertexId vertexId) inline virtual
Preprocessing the vertex with vertexId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for the vertexId, e.g., a lambda function.
Template Parameters
FUNCTION The function object that is called for the vertex identifiers vertexId.
Reimplemented in egoa::ArticulationVertexDetection< GraphType, IsDirected >, and egoa::ArticulationVertexDetection< GraphType, false >.
Definition at line 222 of file DepthFirstSearch.hpp.
ProcessingEdgeWith()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> virtual void egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::ProcessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId) inline virtual
Reimplemented in egoa::ArticulationVertexDetection< GraphType, IsDirected >, and egoa::ArticulationVertexDetection< GraphType, false >.
Definition at line 252 of file DepthFirstSearch.hpp.
Run()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> void egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::Run () inline
Definition at line 64 of file DepthFirstSearch.hpp.
SetTerminate()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> void egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::SetTerminate () inline
Definition at line 165 of file DepthFirstSearch.hpp.
Terminate()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> bool egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::Terminate () const inline
Terminate the DFS.
Returns
TRUE if the DFS
Definition at line 164 of file DepthFirstSearch.hpp.
References egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::terminate_.
Time() [1/2]
template<typename GraphType , bool IsDirected = false, bool Recursive = true> TTime & egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::Time () inline private
Definition at line 177 of file DepthFirstSearch.hpp.
Time() [2/2]
template<typename GraphType , bool IsDirected = false, bool Recursive = true> TTime egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::Time () const inline private
Modify time counter.
Returns
Current time
Definition at line 176 of file DepthFirstSearch.hpp.
References egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::time_.
TypifyEdge()
template<typename GraphType , bool IsDirected = false, bool Recursive = true> DfsEdgeType egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::TypifyEdge (TVertexId source, TVertexId target) inline
Determine DFS edge type.
Parameters
[in] source The source identifier.
[in] target The target identifier.
Returns
The DFS edge type.
Todo:
Cross edge is only possible in directed case -> check for graph type
Definition at line 127 of file DepthFirstSearch.hpp.
References egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::EntryTimeAt(), egoa::Traversal< GraphType, IsDirected >::ParentOf(), egoa::Traversal< GraphType, IsDirected >::ProcessedVertexAt(), and egoa::Traversal< GraphType, IsDirected >::VisitedVertexAt().
Member Data Documentation
entryTime_
template<typename GraphType , bool IsDirected = false, bool Recursive = true> std::vector<TTime> egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::entryTime_ private
Entry time at a vertex
Definition at line 288 of file DepthFirstSearch.hpp.
exitTime_
template<typename GraphType , bool IsDirected = false, bool Recursive = true> std::vector<TTime> egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::exitTime_ private
Exit time at a vertex
Definition at line 289 of file DepthFirstSearch.hpp.
terminate_
template<typename GraphType , bool IsDirected = false, bool Recursive = true> bool egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::terminate_ private
Terminate search
Definition at line 286 of file DepthFirstSearch.hpp.
time_
template<typename GraphType , bool IsDirected = false, bool Recursive = true> TTime egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::time_ private
Current time counter
Definition at line 285 of file DepthFirstSearch.hpp.
The documentation for this class was generated from the following file:
include/Algorithms/GraphTraversal/DepthFirstSearch.hpp