Energy Grid Optimization & Analysis (EGOA): egoa::Vertices::GeneratorProperties< VertexType > Class Template Reference
egoa::Vertices::GeneratorProperties< VertexType > Class Template Reference
Class having all generator properties.
#include <GeneratorProperties.hpp>
Public Types
Bound Specific Types
using TBound = Bound< Types::real >
Type Specific Types
using TVertexType = VertexType
using TControlType = Vertices::ControlType
using TGeneratorType = Vertices::GeneratorType
using TBusStatus = Vertices::BusStatus
using TPowerSign = Vertices::PowerSign
Public Member Functions
Constructors and Destructor
void Reset ()
Reset to default values.
bool operator!= (GeneratorProperties const &rhs) const
Inequality comparator of two generator properties.
bool operator== (GeneratorProperties const &rhs) const
Comparison of two generator properties.
Basic Properties
Types::name Name () const
Types::name & Name ()
TVertexType Type () const
TVertexType & Type ()
Types::real X () const
Types::real & X ()
Types::real Y () const
Types::real & Y ()
Voltage
Types::real VoltageMagnitude () const
Getter for the voltage magnitude setpoint in per unit (p.u.) of the nominal voltage.
Types::real & VoltageMagnitude ()
Getter and setter for the voltage magnitude setpoint in per unit (p.u.) of the nominal voltage.
Nominal Power Information
bool IsExtendable () const
Determines if the generator is extendable (used for production expansion).
bool & IsExtendable ()
Setter and determines if the generator is extendable (used for production expansion).
Types::real NominalPower () const
Getter for the nominal power base.
Types::real & NominalPower ()
Getter and setter for the nominal power base.
TBound NominalRealPowerBound () const
Getter for the nominal real power bound with while the generator is extendable.
TBound & NominalRealPowerBound ()
Getter and setter for the nominal real power bound with while the generator is extendable.
TPowerSign PowerSign () const
Getter for the power sign.
TPowerSign & PowerSign ()
Getter for the power sign.
Real Power Information
Types::real RealPower () const
Getter for the real power .
Types::real & RealPower ()
Getter and setter for the real power set point .
TBound RealPowerBound () const
Getter for the real power bound .
TBound & RealPowerBound ()
Getter and setter for the real power bound .
Types::real Pc1 () const
Getter for the lower real power output of PQ capability curve (MW) at PC1.
Types::real & Pc1 ()
Getter and setter for the lower real power output of PQ capability curve (MW) at PC1.
Types::real Pc2 () const
Getter for the upper real power output of PQ capability curve (MW) at PC2.
Types::real & Pc2 ()
Getter and setter for the upper real power output of PQ capability curve (MW) at PC2.
Reactive Power Information
Types::real ReactivePower () const
Getter for the reactive power .
Types::real & ReactivePower ()
Getter and setter for the reactive power .
TBound ReactivePowerBound () const
Getter for the reactive power bound .
TBound & ReactivePowerBound ()
Getter and setter for the reactive power bound .
TBound Qc1Bound () const
Getter for the reactive power output bound at PC1.
TBound & Qc1Bound ()
Getter and setter for the reactive power output bound at PC1.
TBound Qc2Bound () const
Getter for the reactive power output bound at PC2.
TBound & Qc2Bound ()
Getter and setter for the reactive power output bound at PC2.
Status Specific Information
bool IsActive () const
Determines if the electrical vertex is active.
TBusStatus Status () const
Status of the electrical vertex.
TBusStatus & Status ()
Status of the electrical vertex.
bool Committable () const
Getter for the unit commitment.
bool & Committable ()
Getter and setter for the unit commitment.
Type Specific Information
Vertices::ControlType Control () const
Getter for the control strategy.
Vertices::ControlType & Control ()
Getter and setter for the control strategy.
Vertices::GeneratorType GeneratorType () const
Getter for the generator type.
Vertices::GeneratorType & GeneratorType ()
Getter and setter for the generator type.
Types::real Efficiency () const
Getter for the efficiency of the generator.
Types::real & Efficiency ()
Getter and setter for the efficiency of the generator.
Cost Specific Information
Types::real MarginalCost () const
Getter for the marginal cost.
Types::real & MarginalCost ()
Getter and setter for the marginal cost.
Types::real CapitalCost () const
Getter for the capital cost.
Types::real & CapitalCost ()
Getter and setter for the capital cost.
Types::real StartUpCost () const
Getter for the startup costs for the generator.
Types::real & StartUpCost ()
Getter and setter for the startup costs for the generator.
Types::real ShutDownCost () const
Getter for the shutdown costs for the generator.
Types::real & ShutDownCost ()
Getter and setter for the shutdown costs for the generator.
Ramp Specific Information
Ramp Limits: The inner dynamic of generators does not always allow to change the production level, i.e., a maximum possible change is set by ramp limits.
Ramp rate: Describes how fast generator outputs can be changed. There are usually ramping up (increasing) and down (decreasing), i.e., the unit is in units of power over time (here MW/min).
Types::real MinimumUpTime () const
Getter for the minimum availability (active) time.
Types::real & MinimumUpTime ()
Getter and setter for the minimum availability (active) time.
Types::real MinimumDownTime () const
Getter for the minimum time to be inactive.
Types::real & MinimumDownTime ()
Getter and setter for the minimum time to be inactive.
Types::real RampAgc () const
Getter for the ramp rate for load following AGC.
Types::real & RampAgc ()
Getter and setter for the ramp rate for load following AGC.
Types::real Ramp10 () const
Getter for the ramp rate for a 10 minute reserve.
Types::real & Ramp10 ()
Getter and setter for the ramp rate for a 10 minute reserve.
Types::real Ramp30 () const
Getter for the ramp rate for a 30 minute reserve.
Types::real & Ramp30 ()
Getter and setter for the ramp rate for a 30 minute reserve.
Types::real RampQ () const
Getter for the ramp rate for the reactive power (2 sec timescale).
Types::real & RampQ ()
Getter and setter for the ramp rate for the reactive power (2 sec timescale).
Types::real Apf () const
Getter for the area participation factor (APF).
Types::real & Apf ()
Getter and setter for the area participation factor (APF).
Types::real RampLimitUp () const
Getter for the maximum increase in power.
Types::real & RampLimitUp ()
Getter and setter for the maximum increase in power.
Types::real RampLimitDown () const
Getter for the maximum decrease in power.
Types::real & RampLimitDown ()
Getter and setter for the maximum decrease in power.
Types::real RampLimitStartUp () const
Getter for the maximum increase in power at startup.
Types::real & RampLimitStartUp ()
Getter and setter for the maximum increase in power at start-up.
Types::real RampLimitShutDown () const
Getter for the maximum decrease in power at shut-down.
Types::real & RampLimitShutDown ()
Getter and setter for the maximum decrease in power at shut-down.
Private Attributes
Basic Property Members
Types::name name_
TVertexType type_
Types::real xCoordinate_
Types::real yCoordinate_
Voltage Related Members
Types::real voltageMagnitudeSnapshot_
Nominal Power Members
Types::real nominalPower_
bool pNomExtendable_
TBound nominalRealPowerBound_
TPowerSign sign_
Real Power Members
Types::real realPower_
TBound realPowerBound_
Types::real pc1_
Types::real pc2_
Types::real reactivePower_
TBound reactivePowerBound_
TBound qc1Bound_
TBound qc2Bound_
Status Members
TBusStatus status_
bool committable_
Type Members
TControlType control_
TGeneratorType generatorType_
Types::real efficiency_
Cost Specific Members
Types::real marginalCost_
Types::real capitalCost_
Types::real startUpCost_
Types::real shutDownCost_
Ramp Members
Ramp Limits: The inner dynamic of generators does not always allow to change the production level, i.e., a maximum possible change is set by ramp limits.
Ramp rate: Describes how fast generator outputs can be changed. There are usually ramping up (increasing) and down (decreasing), i.e., the unit is in units of power over time (here MW/min).
Types::real minUpTime_
Types::real minDownTime_
Types::real rampAgc_
Types::real ramp10_
Types::real ramp30_
Types::real rampQ_
Types::real apf_
Types::real rampLimitUp_
Types::real rampLimitDown_
Types::real rampLimitStartUp_
Types::real rampLimitShutDown_
Friends
void swap (GeneratorProperties &lhs, GeneratorProperties &rhs)
Swapping the members of two generator properties.
Output
void Line (std::ostream &outputStream, Types::real baseMva=1) const
Write the values of the generator property.
void Line (std::ostream &outputStream, Types::vertexId identifier, Types::real baseMva=1) const
Writes the values including the identifier of the generator property.
void Line (std::ostream &outputStream, Types::name busName, Types::real baseMva=1) const
Writes the values including the name of the generator property.
std::ostream & operator<< (std::ostream &outputStream, GeneratorProperties const &rhs)
Writes the generator property to an output stream.
static void Header (std::ostream &outputStream)
Write the header to the output stream.
static void HeaderBusGeneratorName (std::ostream &outputStream)
Detailed Description
template<class VertexType = Vertices::IeeeBusType>
class egoa::Vertices::GeneratorProperties< VertexType >
Class having all generator properties.
Template Parameters
VertexType The vertex type is used to categorize the vertex, e.g., as slack bus.
Definition at line 28 of file GeneratorProperties.hpp.
Member Typedef Documentation
TBound
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::GeneratorProperties< VertexType >::TBound = Bound<Types::real>
Definition at line 32 of file GeneratorProperties.hpp.
TBusStatus
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::GeneratorProperties< VertexType >::TBusStatus = Vertices::BusStatus
Definition at line 40 of file GeneratorProperties.hpp.
TControlType
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::GeneratorProperties< VertexType >::TControlType = Vertices::ControlType
Definition at line 38 of file GeneratorProperties.hpp.
TGeneratorType
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::GeneratorProperties< VertexType >::TGeneratorType = Vertices::GeneratorType
Definition at line 39 of file GeneratorProperties.hpp.
TPowerSign
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::GeneratorProperties< VertexType >::TPowerSign = Vertices::PowerSign
Definition at line 41 of file GeneratorProperties.hpp.
TVertexType
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::GeneratorProperties< VertexType >::TVertexType = VertexType
Definition at line 37 of file GeneratorProperties.hpp.
Constructor & Destructor Documentation
GeneratorProperties()
template<class VertexType = Vertices::IeeeBusType> egoa::Vertices::GeneratorProperties< VertexType >::GeneratorProperties () inline
Definition at line 49 of file GeneratorProperties.hpp.
Member Function Documentation
Apf() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::Apf () inline
Getter and setter for the area participation factor (APF).
Returns
The area participation factor (APF).
Definition at line 1245 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::apf_.
Apf() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::Apf () const inline
Getter for the area participation factor (APF).
Returns
The area participation factor (APF).
Definition at line 1234 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::apf_.
CapitalCost() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::CapitalCost () inline
Getter and setter for the capital cost.
The capital cost by extending the generator's nominal power by 1 MW.
Returns
The capital cost.
Definition at line 987 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::capitalCost_.
CapitalCost() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::CapitalCost () const inline
Getter for the capital cost.
The capital cost by extending the generator's nominal power by 1 MW.
Returns
The capital cost.
Definition at line 975 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::capitalCost_.
Committable() [1/2]
template<class VertexType = Vertices::IeeeBusType> bool & egoa::Vertices::GeneratorProperties< VertexType >::Committable () inline
Getter and setter for the unit commitment.
Precondition
This can only be true if the generator is not extendable.
Returns
true if unit commitment, false otherwise.
Definition at line 846 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::committable_.
Committable() [2/2]
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::GeneratorProperties< VertexType >::Committable () const inline
Getter for the unit commitment.
Precondition
This can only be true if the generator is not extendable.
Returns
true if unit commitment, false otherwise.
Definition at line 833 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::committable_.
Control() [1/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::ControlType & egoa::Vertices::GeneratorProperties< VertexType >::Control () inline
Getter and setter for the control strategy.
The control strategy must be either PQ, PV, or Slack. The slack vertex represents a reference vertex used to set a voltage angle for example to 0 and thus, determine the other voltage angle.
See also
Vertices::ControlType
Returns
The control strategy.
Definition at line 883 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::control_.
Control() [2/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::ControlType egoa::Vertices::GeneratorProperties< VertexType >::Control () const inline
Getter for the control strategy.
The control strategy must be either PQ, PV, or Slack. The slack vertex represents a reference vertex used to set a voltage angle for example to 0 and thus, determine the other voltage angle.
See also
Vertices::ControlType
Returns
The control strategy.
Definition at line 867 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::control_.
Efficiency() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::Efficiency () inline
Getter and setter for the efficiency of the generator.
The efficiency of a generator is calculated by the ratio between primary and electrical energy.
Returns
The efficiency of the generator.
Definition at line 936 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::efficiency_.
Efficiency() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::Efficiency () const inline
Getter for the efficiency of the generator.
The efficiency of a generator is calculated by the ratio between primary and electrical energy.
Returns
The efficiency of the generator.
Definition at line 923 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::efficiency_.
GeneratorType() [1/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::GeneratorType & egoa::Vertices::GeneratorProperties< VertexType >::GeneratorType () inline
Getter and setter for the generator type.
The generator type determines if it is a conventional or renewable generator.
See also
Vertices::GeneratorType
Returns
The generator type.
Definition at line 911 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::generatorType_.
GeneratorType() [2/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::GeneratorType egoa::Vertices::GeneratorProperties< VertexType >::GeneratorType () const inline
Getter for the generator type.
The generator type determines if it is a conventional or renewable generator.
See also
Vertices::GeneratorType
Returns
The generator type.
Definition at line 897 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::generatorType_.
Header()
template<class VertexType = Vertices::IeeeBusType> static void egoa::Vertices::GeneratorProperties< VertexType >::Header (std::ostream & outputStream) inline static
Write the header to the output stream.
List all IEEE standard input data.
Parameters
outputStream The stream to write data to, e.g., std::cout.
Definition at line 1402 of file GeneratorProperties.hpp.
HeaderBusGeneratorName()
template<class VertexType = Vertices::IeeeBusType> static void egoa::Vertices::GeneratorProperties< VertexType >::HeaderBusGeneratorName (std::ostream & outputStream) inline static
Definition at line 1428 of file GeneratorProperties.hpp.
IsActive()
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::GeneratorProperties< VertexType >::IsActive () const inline
Determines if the electrical vertex is active.
See also
Status
Returns
true if active (on), false otherwise (unknown).
Definition at line 787 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::Status().
IsExtendable() [1/2]
template<class VertexType = Vertices::IeeeBusType> bool & egoa::Vertices::GeneratorProperties< VertexType >::IsExtendable () inline
Setter and determines if the generator is extendable (used for production expansion).
This is mainly used for renewable energy sources to determine how much the new energy source is expanded. For already existing energy sources this is usually set to False. However, in some cases it makes sense to extend already existing energy sources, too, and the flag might be True, too.
generator.IsExtendable() = true;
Precondition
Default is false.
Note
If it is true the extendable generator then the generator's nominal real power lies between and meaning
Otherwise, the generator's nominal real power is defined by a fixed value. Thus, use by using Mbase when IsExtendable is false, and and by using NominalRealPower if IsExtendable is true.
See also
NominalPower
IsExtendable
NominalRealPowerBound
Returns
true if the generator is extendable, false otherwise.
Definition at line 433 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::pNomExtendable_.
IsExtendable() [2/2]
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::GeneratorProperties< VertexType >::IsExtendable () const inline
Determines if the generator is extendable (used for production expansion).
This is mainly used for renewable energy sources to determine how much the new energy source is expanded. For already existing energy sources this is usually set to False. However, in some cases it makes sense to extend already existing energy sources, too, and the flag might be True, too.
Precondition
Default is false.
Note
If it is true the extendable generator then the generator's nominal real power lies between and meaning
Otherwise, the generator's nominal real power is defined by a fixed value. Thus, use by using Mbase when IsExtendable is false, and and by using NominalRealPower if IsExtendable is true.
See also
NominalPower
NominalRealPowerBound
Returns
True if the generator is extendable, false otherwise.
Definition at line 391 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::pNomExtendable_.
Line() [1/3]
template<class VertexType = Vertices::IeeeBusType> void egoa::Vertices::GeneratorProperties< VertexType >::Line (std::ostream & outputStream, Types::name busName, Types::real baseMva = 1) const inline
Writes the values including the name of the generator property.
List all IEEE standard input data.
Parameters
outputStream The stream to write data to
[in] busName The bus name
[in] baseMva The base mva
Definition at line 1537 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::Apf(), egoa::Vertices::GeneratorProperties< VertexType >::IsActive(), egoa::Bound< BoundType >::Maximum(), egoa::Bound< BoundType >::Minimum(), egoa::Vertices::GeneratorProperties< VertexType >::NominalPower(), egoa::Vertices::GeneratorProperties< VertexType >::Pc1(), egoa::Vertices::GeneratorProperties< VertexType >::Pc2(), egoa::Vertices::GeneratorProperties< VertexType >::Qc1Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Qc2Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp10(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp30(), egoa::Vertices::GeneratorProperties< VertexType >::RampAgc(), egoa::Vertices::GeneratorProperties< VertexType >::RampQ(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePower(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePowerBound(), egoa::Vertices::GeneratorProperties< VertexType >::RealPower(), egoa::Vertices::GeneratorProperties< VertexType >::RealPowerBound(), and egoa::Vertices::GeneratorProperties< VertexType >::VoltageMagnitude().
Line() [2/3]
template<class VertexType = Vertices::IeeeBusType> void egoa::Vertices::GeneratorProperties< VertexType >::Line (std::ostream & outputStream, Types::real baseMva = 1) const inline
Write the values of the generator property.
List all IEEE standard input data.
Parameters
outputStream The stream to write data to, e.g., std::cout.
[in] baseMva The base MVA.
Definition at line 1462 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::Apf(), egoa::Vertices::GeneratorProperties< VertexType >::IsActive(), egoa::Bound< BoundType >::Maximum(), egoa::Bound< BoundType >::Minimum(), egoa::Vertices::GeneratorProperties< VertexType >::NominalPower(), egoa::Vertices::GeneratorProperties< VertexType >::Pc1(), egoa::Vertices::GeneratorProperties< VertexType >::Pc2(), egoa::Vertices::GeneratorProperties< VertexType >::Qc1Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Qc2Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp10(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp30(), egoa::Vertices::GeneratorProperties< VertexType >::RampAgc(), egoa::Vertices::GeneratorProperties< VertexType >::RampQ(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePower(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePowerBound(), egoa::Vertices::GeneratorProperties< VertexType >::RealPower(), egoa::Vertices::GeneratorProperties< VertexType >::RealPowerBound(), and egoa::Vertices::GeneratorProperties< VertexType >::VoltageMagnitude().
Line() [3/3]
template<class VertexType = Vertices::IeeeBusType> void egoa::Vertices::GeneratorProperties< VertexType >::Line (std::ostream & outputStream, Types::vertexId identifier, Types::real baseMva = 1) const inline
Writes the values including the identifier of the generator property.
List all IEEE standard input data.
Parameters
outputStream The stream to write data to, e.g., std::cout.
[in] identifier The identifier.
[in] baseMva The base MVA.
Definition at line 1499 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::Apf(), egoa::Vertices::GeneratorProperties< VertexType >::IsActive(), egoa::Bound< BoundType >::Maximum(), egoa::Bound< BoundType >::Minimum(), egoa::Vertices::GeneratorProperties< VertexType >::NominalPower(), egoa::Vertices::GeneratorProperties< VertexType >::Pc1(), egoa::Vertices::GeneratorProperties< VertexType >::Pc2(), egoa::Vertices::GeneratorProperties< VertexType >::Qc1Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Qc2Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp10(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp30(), egoa::Vertices::GeneratorProperties< VertexType >::RampAgc(), egoa::Vertices::GeneratorProperties< VertexType >::RampQ(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePower(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePowerBound(), egoa::Vertices::GeneratorProperties< VertexType >::RealPower(), egoa::Vertices::GeneratorProperties< VertexType >::RealPowerBound(), and egoa::Vertices::GeneratorProperties< VertexType >::VoltageMagnitude().
MarginalCost() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::MarginalCost () inline
Getter and setter for the marginal cost.
The marginal cost for the production of 1 MW.
Returns
The marginal cost.
Definition at line 963 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::marginalCost_.
MarginalCost() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::MarginalCost () const inline
Getter for the marginal cost.
The marginal cost for the production of 1 MW.
Returns
The marginal cost.
Definition at line 952 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::marginalCost_.
MinimumDownTime() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::MinimumDownTime () inline
Getter and setter for the minimum time to be inactive.
This is measured in number of snapshots. This represents the minimum number of snapshots to be in inactive status until a startup is possible again, i.e., being in active status.
Precondition
Only if Committable() is true.
Returns
The minimum time to be inactive of the generator.
Definition at line 1119 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::minDownTime_.
MinimumDownTime() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::MinimumDownTime () const inline
Getter for the minimum time to be inactive.
This is measured in number of snapshots. This represents the minimum number of snapshots to be in inactive status until a startup is possible again, i.e., being in active status.
Precondition
Only if Committable() is true.
Returns
The minimum time to be inactive of the generator.
Definition at line 1102 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::minDownTime_.
MinimumUpTime() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::MinimumUpTime () inline
Getter and setter for the minimum availability (active) time.
This is measured in number of snapshots. This represents the minimum number of snapshots to be in active status until a shutdown is possible, i.e., being in inactive status.
Precondition
Only if Committable() is true.
Returns
The minimum active time of the generator.
Definition at line 1086 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::minUpTime_.
MinimumUpTime() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::MinimumUpTime () const inline
Getter for the minimum availability (active) time.
This is measured in number of snapshots. This represents the minimum number of snapshots to be in active status until a shutdown is possible, i.e., being in inactive status.
Precondition
Only if Committable() is true.
Returns
The minimum active time of the generator.
Definition at line 1069 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::minUpTime_.
Name() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::name & egoa::Vertices::GeneratorProperties< VertexType >::Name () inline
Definition at line 313 of file GeneratorProperties.hpp.
Name() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::name egoa::Vertices::GeneratorProperties< VertexType >::Name () const inline
Definition at line 312 of file GeneratorProperties.hpp.
NominalPower() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::NominalPower () inline
Getter and setter for the nominal power base.
If the generator is NOT extendable—meaning IsExtendable is False---and thus, fixed the nominal power is used to normalize or to denormalize into/from the p.u. units.
if (!generator.IsExtendable())
{ // nominal real power is a value and thus, is fixed.
    generator.Mbase() = 11.11;
}
See also
NominalPower
IsExtendable
NominalRealPowerBound
Returns
The nominal power base.
Definition at line 485 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::nominalPower_.
NominalPower() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::NominalPower () const inline
Getter for the nominal power base.
If the generator is NOT extendable—meaning IsExtendable is false---and thus, fixed the nominal power is used to normalize or to denormalize into/from the p.u. units.
GeneratorProperties const & generator;
...
if (!generator.IsExtendable())
{ // nominal real power is a value and thus, is fixed.
    std::cout << "p_nom = " << generator.Mbase() << std::endl;
}
See also
NominalPower
IsExtendable
NominalRealPowerBound
Returns
The nominal power base.
Definition at line 460 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::nominalPower_.
NominalRealPowerBound() [1/2]
template<class VertexType = Vertices::IeeeBusType> TBound & egoa::Vertices::GeneratorProperties< VertexType >::NominalRealPowerBound () inline
Getter and setter for the nominal real power bound with while the generator is extendable.
Precondition
Check if the is extendable meaning IsExtendable is true.
if (generator.IsExtendable())
{ // nominal real power lies in between a bound and thus, is flexible.
    generator.NominalRealPower().Minimum() = 0.0;
    generator.NominalRealPower().Maximum() = 11.11;
}
See also
NominalPower
IsExtendable
NominalRealPowerBound
Returns
The nominal real power bound .
Definition at line 547 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::nominalRealPowerBound_.
NominalRealPowerBound() [2/2]
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::NominalRealPowerBound () const inline
Getter for the nominal real power bound with while the generator is extendable.
Precondition
Check if the is extendable meaning IsExtendable is true.
if (generator.IsExtendable())
{ // nominal real power lies in between a bound and thus, is flexible.
    std::cout << "p_nom_min = " << generator.NominalRealPower().Minimum()
              << "p_nom_max = " << generator.NominalRealPower().Maximum() << std::endl;
} else
{ // nominal real power is a value and thus, is fixed.
    std::cout << "p_nom = " << generator.Mbase() << std::endl;
}
See also
NominalPower
IsExtendable
NominalRealPowerBound
Returns
The nominal real power bound .
Definition at line 517 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::nominalRealPowerBound_.
operator!=()
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::GeneratorProperties< VertexType >::operator!= (GeneratorProperties< VertexType > const & rhs) const inline
Inequality comparator of two generator properties.
@Name Comparators
Parameters
rhs The right hand side generator properties.
Returns
true if both vertices are not equal, false otherwise.
Definition at line 163 of file GeneratorProperties.hpp.
operator==()
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::GeneratorProperties< VertexType >::operator== (GeneratorProperties< VertexType > const & rhs) const inline
Comparison of two generator properties.
Parameters
rhs The right hand side generator properties.
Returns
true if both vertices are equal, false otherwise.
Definition at line 176 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::Apf(), egoa::Vertices::GeneratorProperties< VertexType >::CapitalCost(), egoa::Vertices::GeneratorProperties< VertexType >::Committable(), egoa::Vertices::GeneratorProperties< VertexType >::Control(), egoa::Vertices::GeneratorProperties< VertexType >::Efficiency(), egoa::Vertices::GeneratorProperties< VertexType >::GeneratorType(), egoa::Vertices::GeneratorProperties< VertexType >::IsExtendable(), egoa::Vertices::GeneratorProperties< VertexType >::MarginalCost(), egoa::Bound< BoundType >::Maximum(), egoa::Bound< BoundType >::Minimum(), egoa::Vertices::GeneratorProperties< VertexType >::MinimumDownTime(), egoa::Vertices::GeneratorProperties< VertexType >::MinimumUpTime(), egoa::Vertices::GeneratorProperties< VertexType >::NominalPower(), egoa::Vertices::GeneratorProperties< VertexType >::NominalRealPowerBound(), egoa::Vertices::GeneratorProperties< VertexType >::Pc1(), egoa::Vertices::GeneratorProperties< VertexType >::Pc2(), egoa::Vertices::GeneratorProperties< VertexType >::PowerSign(), egoa::Vertices::GeneratorProperties< VertexType >::Qc1Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Qc2Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp10(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp30(), egoa::Vertices::GeneratorProperties< VertexType >::RampAgc(), egoa::Vertices::GeneratorProperties< VertexType >::RampLimitDown(), egoa::Vertices::GeneratorProperties< VertexType >::RampLimitShutDown(), egoa::Vertices::GeneratorProperties< VertexType >::RampLimitStartUp(), egoa::Vertices::GeneratorProperties< VertexType >::RampLimitUp(), egoa::Vertices::GeneratorProperties< VertexType >::RampQ(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePower(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePowerBound(), egoa::Vertices::GeneratorProperties< VertexType >::RealPower(), egoa::Vertices::GeneratorProperties< VertexType >::RealPowerBound(), egoa::Vertices::GeneratorProperties< VertexType >::ShutDownCost(), egoa::Vertices::GeneratorProperties< VertexType >::StartUpCost(), egoa::Vertices::GeneratorProperties< VertexType >::Status(), and egoa::Vertices::GeneratorProperties< VertexType >::VoltageMagnitude().
Pc1() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::Pc1 () inline
Getter and setter for the lower real power output of PQ capability curve (MW) at PC1.
Returns
The lower real power output of PQ capability curve (MW).
Definition at line 647 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::pc1_.
Pc1() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::Pc1 () const inline
Getter for the lower real power output of PQ capability curve (MW) at PC1.
Returns
The lower real power output of PQ capability curve (MW).
Definition at line 635 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::pc1_.
Pc2() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::Pc2 () inline
Getter and setter for the upper real power output of PQ capability curve (MW) at PC2.
Returns
The upper real power output of PQ capability curve (MW).
Definition at line 671 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::pc2_.
Pc2() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::Pc2 () const inline
Getter for the upper real power output of PQ capability curve (MW) at PC2.
Returns
The upper real power output of PQ capability curve (MW).
Definition at line 659 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::pc2_.
PowerSign() [1/2]
template<class VertexType = Vertices::IeeeBusType> TPowerSign & egoa::Vertices::GeneratorProperties< VertexType >::PowerSign () inline
Getter for the power sign.
Returns
The power sign, if 1 the generator produces energy, otherwise if -1 it consumes energy.
Todo:
make enum
Definition at line 573 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::sign_.
PowerSign() [2/2]
template<class VertexType = Vertices::IeeeBusType> TPowerSign egoa::Vertices::GeneratorProperties< VertexType >::PowerSign () const inline
Getter for the power sign.
Returns
The power sign, if 1 the generator produces energy, otherwise if -1 it consumes energy.
Todo:
make enum
Definition at line 560 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::sign_.
Qc1Bound() [1/2]
template<class VertexType = Vertices::IeeeBusType> TBound & egoa::Vertices::GeneratorProperties< VertexType >::Qc1Bound () inline
Getter and setter for the reactive power output bound at PC1.
This is measured in MVAr.
Returns
The reactive power output bound at PC1.
Definition at line 746 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::qc1Bound_.
Qc1Bound() [2/2]
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::Qc1Bound () const inline
Getter for the reactive power output bound at PC1.
This is measured in MVAr.
Returns
The reactive power output bound at PC1.
Definition at line 734 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::qc1Bound_.
Qc2Bound() [1/2]
template<class VertexType = Vertices::IeeeBusType> TBound & egoa::Vertices::GeneratorProperties< VertexType >::Qc2Bound () inline
Getter and setter for the reactive power output bound at PC2.
This is measured in MVAr.
Returns
The reactive power output bound at PC2.
Definition at line 770 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::qc2Bound_.
Qc2Bound() [2/2]
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::Qc2Bound () const inline
Getter for the reactive power output bound at PC2.
This is measured in MVAr.
Returns
The reactive power output bound at PC2.
Definition at line 758 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::qc2Bound_.
Ramp10() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::Ramp10 () inline
Getter and setter for the ramp rate for a 10 minute reserve.
The ramp rate is measured in MW and is part of the IEEE data.
Returns
The ramp rate for a 10 minute reserve.
Definition at line 1173 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::ramp10_.
Ramp10() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::Ramp10 () const inline
Getter for the ramp rate for a 10 minute reserve.
The ramp rate is measured in MW and is part of the IEEE data.
Returns
The ramp rate for a 10 minute reserve.
Definition at line 1160 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::ramp10_.
Ramp30() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::Ramp30 () inline
Getter and setter for the ramp rate for a 30 minute reserve.
The ramp rate is measured in MW and is part of the IEEE data.
Returns
The ramp rate for a 30 minute reserve.
Definition at line 1198 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::ramp30_.
Ramp30() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::Ramp30 () const inline
Getter for the ramp rate for a 30 minute reserve.
The ramp rate is measured in MW and is part of the IEEE data.
Returns
The ramp rate for a 30 minute reserve.
Definition at line 1185 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::ramp30_.
RampAgc() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::RampAgc () inline
Getter and setter for the ramp rate for load following AGC.
The ramp rate is measured in MW/min and is part of the IEEE data.
Note
AGC stands for Automatic Generation Control.
Returns
The ramp rate for load following AGC.
Definition at line 1148 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampAgc_.
RampAgc() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::RampAgc () const inline
Getter for the ramp rate for load following AGC.
The ramp rate is measured in MW/min and is part of the IEEE data.
Note
AGC stands for Automatic Generation Control.
Returns
The ramp rate for load following AGC.
Definition at line 1133 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampAgc_.
RampLimitDown() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::RampLimitDown () inline
Getter and setter for the maximum decrease in power.
The maximum decrease in power is measured in per snapshot.
Note
Ignore if infinity.
Returns
The maximum decrease in power.
Definition at line 1301 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampLimitDown_.
RampLimitDown() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::RampLimitDown () const inline
Getter for the maximum decrease in power.
The maximum decrease in power is measured in per snapshot.
Note
Ignore if infinity.
Returns
The maximum decrease in power.
Definition at line 1287 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampLimitDown_.
RampLimitShutDown() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::RampLimitShutDown () inline
Getter and setter for the maximum decrease in power at shut-down.
The maximum decrease in power at shutdown is measured in per unit of nominal power .
Precondition
Only if Committable() is true.
Returns
The maximum decrease in power at shutdown.
Definition at line 1359 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampLimitShutDown_.
RampLimitShutDown() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::RampLimitShutDown () const inline
Getter for the maximum decrease in power at shut-down.
The maximum decrease in power at shutdown is measured in per unit of nominal power .
Precondition
Only if Committable() is true.
Returns
The maximum decrease in power at shutdown.
Definition at line 1344 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampLimitShutDown_.
RampLimitStartUp() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::RampLimitStartUp () inline
Getter and setter for the maximum increase in power at start-up.
The maximum increase in power at startup is measured in per unit of nominal power .
Precondition
Only if Committable() is true.
Returns
The maximum increase in power at startup.
Definition at line 1330 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampLimitStartUp_.
RampLimitStartUp() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::RampLimitStartUp () const inline
Getter for the maximum increase in power at startup.
The maximum increase in power at startup is measured in per unit of nominal power .
Precondition
Only if Committable() is true.
Returns
The maximum increase in power at startup.
Definition at line 1315 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampLimitStartUp_.
RampLimitUp() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::RampLimitUp () inline
Getter and setter for the maximum increase in power.
The maximum increase in power is measured in per snapshot.
Note
Ignore if infinity.
Returns
The maximum increase in power.
Definition at line 1273 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampLimitUp_.
RampLimitUp() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::RampLimitUp () const inline
Getter for the maximum increase in power.
The maximum increase in power is measured in per snapshot.
Note
Ignore if infinity.
Returns
The maximum increase in power.
Definition at line 1259 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampLimitUp_.
RampQ() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::RampQ () inline
Getter and setter for the ramp rate for the reactive power (2 sec timescale).
The ramp rate is measured in MVAr/min and is part of the IEEE data.
Returns
The ramp rate for the reactive power.
Definition at line 1224 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampQ_.
RampQ() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::RampQ () const inline
Getter for the ramp rate for the reactive power (2 sec timescale).
The ramp rate is measured in MVAr/min and is part of the IEEE data.
Returns
The ramp rate for the reactive power.
Definition at line 1211 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::rampQ_.
ReactivePower() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::ReactivePower () inline
Getter and setter for the reactive power .
Returns
The real power .
Definition at line 698 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::reactivePower_.
ReactivePower() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::ReactivePower () const inline
Getter for the reactive power .
Returns
The real power .
Definition at line 687 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::reactivePower_.
ReactivePowerBound() [1/2]
template<class VertexType = Vertices::IeeeBusType> TBound & egoa::Vertices::GeneratorProperties< VertexType >::ReactivePowerBound () inline
Getter and setter for the reactive power bound .
Returns
The reactive power bound .
Definition at line 722 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::reactivePowerBound_.
ReactivePowerBound() [2/2]
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::ReactivePowerBound () const inline
Getter for the reactive power bound .
Returns
The reactive power bound .
Definition at line 710 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::reactivePowerBound_.
RealPower() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::RealPower () inline
Getter and setter for the real power set point .
Returns
The real power set point .
Definition at line 599 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::realPower_.
RealPower() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::RealPower () const inline
Getter for the real power .
Returns
The real power .
Definition at line 588 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::realPower_.
RealPowerBound() [1/2]
template<class VertexType = Vertices::IeeeBusType> TBound & egoa::Vertices::GeneratorProperties< VertexType >::RealPowerBound () inline
Getter and setter for the real power bound .
Returns
The real power bound .
Definition at line 623 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::realPowerBound_.
RealPowerBound() [2/2]
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::RealPowerBound () const inline
Getter for the real power bound .
Returns
The real power bound .
Definition at line 611 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::realPowerBound_.
Reset()
template<class VertexType = Vertices::IeeeBusType> void egoa::Vertices::GeneratorProperties< VertexType >::Reset () inline
Reset to default values.
Definition at line 100 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::Apf(), egoa::Vertices::GeneratorProperties< VertexType >::CapitalCost(), egoa::Vertices::GeneratorProperties< VertexType >::Committable(), egoa::Vertices::GeneratorProperties< VertexType >::Control(), egoa::Vertices::GeneratorProperties< VertexType >::Efficiency(), egoa::Vertices::GeneratorProperties< VertexType >::GeneratorType(), egoa::Vertices::GeneratorProperties< VertexType >::IsExtendable(), egoa::Vertices::GeneratorProperties< VertexType >::MarginalCost(), egoa::Vertices::GeneratorProperties< VertexType >::MinimumDownTime(), egoa::Vertices::GeneratorProperties< VertexType >::MinimumUpTime(), egoa::Vertices::GeneratorProperties< VertexType >::NominalPower(), egoa::Vertices::GeneratorProperties< VertexType >::NominalRealPowerBound(), egoa::Vertices::GeneratorProperties< VertexType >::Pc1(), egoa::Vertices::GeneratorProperties< VertexType >::Pc2(), egoa::Vertices::GeneratorProperties< VertexType >::PowerSign(), egoa::Vertices::GeneratorProperties< VertexType >::Qc1Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Qc2Bound(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp10(), egoa::Vertices::GeneratorProperties< VertexType >::Ramp30(), egoa::Vertices::GeneratorProperties< VertexType >::RampAgc(), egoa::Vertices::GeneratorProperties< VertexType >::RampLimitDown(), egoa::Vertices::GeneratorProperties< VertexType >::RampLimitShutDown(), egoa::Vertices::GeneratorProperties< VertexType >::RampLimitStartUp(), egoa::Vertices::GeneratorProperties< VertexType >::RampLimitUp(), egoa::Vertices::GeneratorProperties< VertexType >::RampQ(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePower(), egoa::Vertices::GeneratorProperties< VertexType >::ReactivePowerBound(), egoa::Vertices::GeneratorProperties< VertexType >::RealPower(), egoa::Vertices::GeneratorProperties< VertexType >::RealPowerBound(), egoa::Vertices::GeneratorProperties< VertexType >::ShutDownCost(), egoa::Vertices::GeneratorProperties< VertexType >::StartUpCost(), egoa::Vertices::GeneratorProperties< VertexType >::Status(), and egoa::Vertices::GeneratorProperties< VertexType >::VoltageMagnitude().
ShutDownCost() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::ShutDownCost () inline
Getter and setter for the shutdown costs for the generator.
Precondition
Only if Committable() is true.
Returns
The shut-down cost for the generator.
Definition at line 1037 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::shutDownCost_.
ShutDownCost() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::ShutDownCost () const inline
Getter for the shutdown costs for the generator.
Precondition
Only if Committable() is true.
Returns
The shut-down cost for the generator.
Definition at line 1024 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::shutDownCost_.
StartUpCost() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::StartUpCost () inline
Getter and setter for the startup costs for the generator.
Precondition
Only if Committable() is true.
Returns
The startup cost for the generator.
Definition at line 1012 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::startUpCost_.
StartUpCost() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::StartUpCost () const inline
Getter for the startup costs for the generator.
Precondition
Only if Committable() is true.
Returns
The startup cost for the generator.
Definition at line 999 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::startUpCost_.
Status() [1/2]
template<class VertexType = Vertices::IeeeBusType> TBusStatus & egoa::Vertices::GeneratorProperties< VertexType >::Status () inline
Status of the electrical vertex.
The status of the generator/machine is described by active (in-service) or inactive (out-of-service).
See also
Type::Vertex::BusStatus
Returns
The status can have a different status.
Todo:
USE DIFFERENT TYPE see bus
Definition at line 820 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::status_.
Status() [2/2]
template<class VertexType = Vertices::IeeeBusType> TBusStatus egoa::Vertices::GeneratorProperties< VertexType >::Status () const inline
Status of the electrical vertex.
The status of the generator/machine is described by active (in-service) or inactive (out-of-service).
See also
Type::Vertex::BusStatus
Returns
The status can have a different status.
Todo:
USE DIFFERENT TYPE see bus
Definition at line 805 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::status_.
Type() [1/2]
template<class VertexType = Vertices::IeeeBusType> TVertexType & egoa::Vertices::GeneratorProperties< VertexType >::Type () inline
Definition at line 316 of file GeneratorProperties.hpp.
Type() [2/2]
template<class VertexType = Vertices::IeeeBusType> TVertexType egoa::Vertices::GeneratorProperties< VertexType >::Type () const inline
Definition at line 315 of file GeneratorProperties.hpp.
VoltageMagnitude() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::VoltageMagnitude () inline
Getter and setter for the voltage magnitude setpoint in per unit (p.u.) of the nominal voltage.
Returns
The voltage magnitude .
Definition at line 348 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::voltageMagnitudeSnapshot_.
VoltageMagnitude() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::VoltageMagnitude () const inline
Getter for the voltage magnitude setpoint in per unit (p.u.) of the nominal voltage.
Returns
The voltage magnitude .
Definition at line 336 of file GeneratorProperties.hpp.
References egoa::Vertices::GeneratorProperties< VertexType >::voltageMagnitudeSnapshot_.
X() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::X () inline
Definition at line 319 of file GeneratorProperties.hpp.
X() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::X () const inline
Definition at line 318 of file GeneratorProperties.hpp.
Y() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::GeneratorProperties< VertexType >::Y () inline
Definition at line 322 of file GeneratorProperties.hpp.
Y() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::Y () const inline
Definition at line 321 of file GeneratorProperties.hpp.
Friends And Related Symbol Documentation
operator<<
template<class VertexType = Vertices::IeeeBusType> std::ostream & operator<< (std::ostream & outputStream, GeneratorProperties< VertexType > const & rhs) friend
Writes the generator property to an output stream.
Parameters
outputStream The stream to write data to, e.g., std::cout.
[in] rhs The right hand side of the generator property.
Returns
The output stream.
Definition at line 1376 of file GeneratorProperties.hpp.
swap
template<class VertexType = Vertices::IeeeBusType> void swap (GeneratorProperties< VertexType > & lhs, GeneratorProperties< VertexType > & rhs) friend
Swapping the members of two generator properties.
Parameters
lhs The left hand side generator property.
rhs The right hand side generator property.
Definition at line 248 of file GeneratorProperties.hpp.
Member Data Documentation
apf_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::apf_ private
The area participation factor (APF).
Definition at line 1683 of file GeneratorProperties.hpp.
capitalCost_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::capitalCost_ private
The Capital cost of extending p_nom by 1 MW.
Definition at line 1658 of file GeneratorProperties.hpp.
committable_
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::GeneratorProperties< VertexType >::committable_ private
Decides whether unit commitment is active (while not being extendable) or inactive.
Definition at line 1639 of file GeneratorProperties.hpp.
control_
template<class VertexType = Vertices::IeeeBusType> TControlType egoa::Vertices::GeneratorProperties< VertexType >::control_ private
The control strategy, must be either PQ, PV or Slack.
Definition at line 1646 of file GeneratorProperties.hpp.
efficiency_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::efficiency_ private
The efficiency representing the ratio between primary and electrical energy.
Definition at line 1650 of file GeneratorProperties.hpp.
generatorType_
template<class VertexType = Vertices::IeeeBusType> TGeneratorType egoa::Vertices::GeneratorProperties< VertexType >::generatorType_ private
The generator type, i.e., solar.
Definition at line 1649 of file GeneratorProperties.hpp.
marginalCost_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::marginalCost_ private
The marginal cost for production of 1 MW.
Definition at line 1657 of file GeneratorProperties.hpp.
minDownTime_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::minDownTime_ private
The minimum number of snapshots to be inactive.
Definition at line 1677 of file GeneratorProperties.hpp.
minUpTime_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::minUpTime_ private
The minimum number of snapshots to be active.
Definition at line 1676 of file GeneratorProperties.hpp.
name_
template<class VertexType = Vertices::IeeeBusType> Types::name egoa::Vertices::GeneratorProperties< VertexType >::name_ private
name of the vertex
Definition at line 1573 of file GeneratorProperties.hpp.
nominalPower_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::nominalPower_ private
The total nominal power of machine (also known as MVA base or mBase), defaults set to baseMVA.
Definition at line 1588 of file GeneratorProperties.hpp.
nominalRealPowerBound_
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::nominalRealPowerBound_ private
If the generator is extendable the nominal real power can be in the interval .
Definition at line 1600 of file GeneratorProperties.hpp.
pc1_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::pc1_ private
The lower real power output of PQ capability curve at PC1 in MW.
Definition at line 1616 of file GeneratorProperties.hpp.
pc2_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::pc2_ private
The upper real power output of PQ capability curve at PC2 in MW.
Definition at line 1619 of file GeneratorProperties.hpp.
pNomExtendable_
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::GeneratorProperties< VertexType >::pNomExtendable_ private
Determines if the generator is extendable and thus, uses nominalRealPowerBound_ bounds. If the generator is not extendable mBase_ is used. Thus, the extension/upgrade level is unknown and can be decided by, e.g., a MILP. However, generators that are not build are not interesting for standard problems such as MTSF or MFF. Note that for PyPsa this are often renewable energies.
Definition at line 1591 of file GeneratorProperties.hpp.
qc1Bound_
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::qc1Bound_ private
The reactive power output bound at PC1 in MVAr.
Definition at line 1632 of file GeneratorProperties.hpp.
qc2Bound_
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::qc2Bound_ private
The reactive power output bound at PC2 in MVAr.
Definition at line 1633 of file GeneratorProperties.hpp.
ramp10_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::ramp10_ private
The ramp rate for 10 minute reserves (in MW).
Definition at line 1680 of file GeneratorProperties.hpp.
ramp30_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::ramp30_ private
The ramp rate for 30 minute reserves (in MW).
Definition at line 1681 of file GeneratorProperties.hpp.
rampAgc_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::rampAgc_ private
The ramp rate for load following AGC, where AGC stands for automatic generation control (in MW/min).
Definition at line 1679 of file GeneratorProperties.hpp.
rampLimitDown_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::rampLimitDown_ private
The maximum decrease in power per snapshot.
Definition at line 1686 of file GeneratorProperties.hpp.
rampLimitShutDown_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::rampLimitShutDown_ private
The maximum decrease at shutdown in per unit of nominal power.
Definition at line 1688 of file GeneratorProperties.hpp.
rampLimitStartUp_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::rampLimitStartUp_ private
The maximum increase at startup in per unit of nominal power.
Definition at line 1687 of file GeneratorProperties.hpp.
rampLimitUp_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::rampLimitUp_ private
The maximum increase in power per snapshot.
Definition at line 1685 of file GeneratorProperties.hpp.
rampQ_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::rampQ_ private
The ramp rate for reactive power (2 sec timescale) (in MVAr/min).
Definition at line 1682 of file GeneratorProperties.hpp.
reactivePower_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::reactivePower_ private
The reactive power generation in MVAr.
Definition at line 1626 of file GeneratorProperties.hpp.
reactivePowerBound_
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::reactivePowerBound_ private
The reactive power output bound in MVAr.
Definition at line 1629 of file GeneratorProperties.hpp.
realPower_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::realPower_ private
The real power generation in MW.
Definition at line 1610 of file GeneratorProperties.hpp.
realPowerBound_
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::GeneratorProperties< VertexType >::realPowerBound_ private
The real power output bound in MW.
Definition at line 1613 of file GeneratorProperties.hpp.
shutDownCost_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::shutDownCost_ private
The shutdown cost of the generator.
Definition at line 1661 of file GeneratorProperties.hpp.
sign_
template<class VertexType = Vertices::IeeeBusType> TPowerSign egoa::Vertices::GeneratorProperties< VertexType >::sign_ private
The power sign (1 means generation, -1 means load)
Definition at line 1605 of file GeneratorProperties.hpp.
startUpCost_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::startUpCost_ private
The startup cost of the generator.
Definition at line 1660 of file GeneratorProperties.hpp.
status_
template<class VertexType = Vertices::IeeeBusType> TBusStatus egoa::Vertices::GeneratorProperties< VertexType >::status_ private
Describes the status of the generator.
Definition at line 1638 of file GeneratorProperties.hpp.
type_
template<class VertexType = Vertices::IeeeBusType> TVertexType egoa::Vertices::GeneratorProperties< VertexType >::type_ private
vertex type representing either source, sink or intermediate
Definition at line 1574 of file GeneratorProperties.hpp.
voltageMagnitudeSnapshot_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::voltageMagnitudeSnapshot_ private
The voltage magnitude set point in per unit (p.u.) of the nominal voltage .
Definition at line 1581 of file GeneratorProperties.hpp.
xCoordinate_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::xCoordinate_ private
x-coordinate of the point if available
Definition at line 1575 of file GeneratorProperties.hpp.
yCoordinate_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::GeneratorProperties< VertexType >::yCoordinate_ private
y-coordinate of the point if available
Definition at line 1576 of file GeneratorProperties.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Graphs/Vertices/GeneratorProperties.hpp