Energy Grid Optimization & Analysis (EGOA): egoa::internal::BlockCutTreeBuilder< GraphType > Class Template Reference
egoa::internal::BlockCutTreeBuilder< GraphType > Class Template Reference
Block-cut tree related classes and functions
A class to build BlockCutTree objects for a graph.
Classes
struct BlockUnderConstruction
Public Member Functions
BlockCutTreeBuilder (TGraph const &graph)
The constructor.
BlockCutTree< TGraph > && Build ()
Builds the block-cut tree.
Protected Member Functions
Traversal
virtual void PostprocessingEdgeWith (TVertexId source, TVertexId target, TEdgeId edgeId) override
virtual void PostprocessingVertexWith (Types::vertexId vertex) override
Private Types
using TGraph = GraphType
using TVertexId = typename TGraph::TVertexId
using TEdgeId = typename TGraph::TEdgeId
using TDetection = ::egoa::ArticulationVertexDetection< TGraph, false >
using TTime = typename DepthFirstSearch< GraphType, false >::TTime
template<typename T >
using VectorStack = std::stack< T, std::vector< T > >
Private Types inherited from egoa::ArticulationVertexDetection< GraphType, false >
using TGraph = GraphType
using TVertexId = typename TGraph::TVertexId
Private Types inherited from egoa::DepthFirstSearch< GraphType, IsDirected >
using TGraph = GraphType
using TVertexId = typename TGraph::TVertexId
using TTime = Types::count
Private Types inherited from egoa::Traversal< GraphType, IsDirected >
using TGraph = GraphType
using TVertexId = typename GraphType::TVertexId
Private Member Functions
Steps of the Algorithm
void SortBlocks ()
Sort all blocks in bcTree_.blocks_.
Adding Blocks
void PushNextBlock (TTime time)
Initializes the next block.
void PopBlock ()
Pops a block and adds it to the block-cut tree.
void AddEdgeToCurrentBlock (TEdgeId edge)
Adds an edge to the current block.
void AddVertexToCurrentBlock (TVertexId vertex)
Adds a vertex to the current block.
void AddCutVertexToBlock (TVertexId vertex)
Types::index CurrentBlockId () const
The identifier of the current block.
BlockUnderConstruction & CurrentBlock ()
Private Member Functions inherited from egoa::ArticulationVertexDetection< GraphType, false >
ArticulationVertexDetection (TGraph const &graph, TVertexId source)
bool IsRootArticulationVertexAt (TVertexId const vertex) const
Determines if vertex is a root articulation vertex .
bool IsParentArticulationVertexAt (TVertexId const vertex) const
Determines if vertex is a parent articulation vertex .
std::pair< bool, bool > IsBridgeArticulationVertexAt (TVertexId const vertex) const
Determines if vertex and thus, its parent is a bridge articulation vertex .
bool IsArticulationVertexAt (TVertexId const vertex) const
Whether the vertex is an articulation vertex.
bool IsRoot (TVertexId const vertex) const
Determines if vertex is a root.
TTime & TimeOfOldestReachableAncestor (TVertexId vertex)
virtual void PreprocessingVertexWith (TVertexId const vertex) override
Preprocessing vertex with vertexId.
virtual void ProcessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId) override
Update the oldest reachable ancestor.
virtual void PostprocessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId) override
Post processing the edge with edgeId.
virtual void PostprocessingVertexWith (TVertexId vertexId) override
Decide which vertices are articulation vertices.
Types::count TreeOutDegree (TVertexId const vertex) const
Accessors for the tree out degree.
Types::count & TreeOutDegree (TVertexId const vertex)
Private Member Functions inherited from egoa::DepthFirstSearch< GraphType, IsDirected >
void Run ()
DfsEdgeType TypifyEdge (TVertexId source, TVertexId target)
Determine DFS edge type.
bool Terminate () const
Terminate the DFS.
void SetTerminate ()
TTime EntryTimeAt (TVertexId vertexId) const
{ function_description }
TTime ExitTimeAt (TVertexId const vertexId) const
Returns the exit time of a vertex.
DepthFirstSearch (TGraph const &graph, TVertexId source)
Constructs a new DFS instance.
Private Member Functions inherited from egoa::Traversal< GraphType, IsDirected >
virtual void Result (std::vector< TVertexId > parent)
Traversal (TGraph const &graph, TVertexId source)
Constructs a new instance.
TVertexId Source () const
Getter and setter for the source vertex.
TVertexId & Source ()
TVertexId & ParentOf (TVertexId vertexId)
Getter and setter for the parent relation.
TVertexId ParentOf (TVertexId vertexId) const
void Clear ()
Clear and resize all vectors.
bool VertexExists (TVertexId vertexId)
bool NumberOfVertices ()
void SetVertexVisitedAt (TVertexId vertexId)
Sets the vertex at vertexId to visited.
bool VisitedVertexAt (TVertexId vertexId) const
Getter and setter to access the visited field.
void SetVertexProcessedAt (TVertexId vertexId)
Sets the vertex at vertexId to processed.
bool ProcessedVertexAt (TVertexId vertexId) const
Getter and setter to access the process field.
void breakable_for_all_edges_at (TVertexId const &vertexId, FUNCTION function) const
The for loop over all (outgoing) edges that is breakable.
void for_all_edges_at (TVertexId const &vertexId, FUNCTION function) const
The for loop over all (outgoing) edges.
Private Attributes
TGraph const & graph_
egoa::BlockCutTree< TGraph > bcTree_
Types::index nextBlockId_ = 0
VectorStack< BlockUnderConstruction > blockStack_
Detailed Description
template<typename GraphType>
class egoa::internal::BlockCutTreeBuilder< GraphType >
A class to build BlockCutTree objects for a graph.
Template Parameters
GraphType The type of the graph.
Definition at line 377 of file BlockCutTree.hpp.
Member Typedef Documentation
TDetection
template<typename GraphType > using egoa::internal::BlockCutTreeBuilder< GraphType >::TDetection = ::egoa::ArticulationVertexDetection<TGraph, false> private
Definition at line 383 of file BlockCutTree.hpp.
TEdgeId
template<typename GraphType > using egoa::internal::BlockCutTreeBuilder< GraphType >::TEdgeId = typename TGraph::TEdgeId private
Definition at line 382 of file BlockCutTree.hpp.
TGraph
template<typename GraphType > using egoa::internal::BlockCutTreeBuilder< GraphType >::TGraph = GraphType private
Definition at line 380 of file BlockCutTree.hpp.
TTime
template<typename GraphType > using egoa::internal::BlockCutTreeBuilder< GraphType >::TTime = typename DepthFirstSearch<GraphType, false>::TTime private
Definition at line 384 of file BlockCutTree.hpp.
TVertexId
template<typename GraphType > using egoa::internal::BlockCutTreeBuilder< GraphType >::TVertexId = typename TGraph::TVertexId private
Definition at line 381 of file BlockCutTree.hpp.
VectorStack
template<typename GraphType > template<typename T > using egoa::internal::BlockCutTreeBuilder< GraphType >::VectorStack = std::stack<T, std::vector<T> > private
Definition at line 387 of file BlockCutTree.hpp.
Constructor & Destructor Documentation
BlockCutTreeBuilder()
template<typename GraphType > egoa::internal::BlockCutTreeBuilder< GraphType >::BlockCutTreeBuilder (TGraph const & graph) inline
The constructor.
Parameters
graph The graph for which a block-cut tree shall be built.
Definition at line 396 of file BlockCutTree.hpp.
Member Function Documentation
AddCutVertexToBlock()
template<typename GraphType > void egoa::internal::BlockCutTreeBuilder< GraphType >::AddCutVertexToBlock (TVertexId vertex) inline private
Definition at line 541 of file BlockCutTree.hpp.
AddEdgeToCurrentBlock()
template<typename GraphType > void egoa::internal::BlockCutTreeBuilder< GraphType >::AddEdgeToCurrentBlock (TEdgeId edge) inline private
Adds an edge to the current block.
Parameters
[in] edge The identifier of the edge to add.
Definition at line 526 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::blockOfEdge_, and egoa::internal::BlockCutTreeBuilder< GraphType >::CurrentBlockId().
AddVertexToCurrentBlock()
template<typename GraphType > void egoa::internal::BlockCutTreeBuilder< GraphType >::AddVertexToCurrentBlock (TVertexId vertex) inline private
Adds a vertex to the current block.
Parameters
[in] vertex The identifier of the vertex to add.
Definition at line 536 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::blocksOfVertex_, and egoa::internal::BlockCutTreeBuilder< GraphType >::CurrentBlockId().
Build()
template<typename GraphType > BlockCutTree< TGraph > && egoa::internal::BlockCutTreeBuilder< GraphType >::Build () inline
Builds the block-cut tree.
Returns
The BlockCutTree-object.
Definition at line 407 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::blocks_, egoa::BlockCutTree< GraphType >::cutVertices_, and egoa::internal::BlockCutTreeBuilder< GraphType >::SortBlocks().
CurrentBlock()
template<typename GraphType > BlockUnderConstruction & egoa::internal::BlockCutTreeBuilder< GraphType >::CurrentBlock () inline private
Definition at line 558 of file BlockCutTree.hpp.
CurrentBlockId()
template<typename GraphType > Types::index egoa::internal::BlockCutTreeBuilder< GraphType >::CurrentBlockId () const inline private
The identifier of the current block.
Returns
The identifier of the current block.
Definition at line 553 of file BlockCutTree.hpp.
PopBlock()
template<typename GraphType > void egoa::internal::BlockCutTreeBuilder< GraphType >::PopBlock () inline private
Pops a block and adds it to the block-cut tree.
Definition at line 516 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::blocks_.
PostprocessingEdgeWith()
template<typename GraphType > virtual void egoa::internal::BlockCutTreeBuilder< GraphType >::PostprocessingEdgeWith (TVertexId source, TVertexId target, TEdgeId edgeId) inline override protected virtual
Definition at line 439 of file BlockCutTree.hpp.
PostprocessingVertexWith()
template<typename GraphType > virtual void egoa::internal::BlockCutTreeBuilder< GraphType >::PostprocessingVertexWith (Types::vertexId vertex) inline override protected virtual
Definition at line 493 of file BlockCutTree.hpp.
PushNextBlock()
template<typename GraphType > void egoa::internal::BlockCutTreeBuilder< GraphType >::PushNextBlock (TTime time) inline private
Initializes the next block.
Definition at line 509 of file BlockCutTree.hpp.
SortBlocks()
template<typename GraphType > void egoa::internal::BlockCutTreeBuilder< GraphType >::SortBlocks () inline private
Sort all blocks in bcTree_.blocks_.
Definition at line 426 of file BlockCutTree.hpp.
References egoa::BlockCutTree< GraphType >::blocks_.
Member Data Documentation
bcTree_
template<typename GraphType > egoa::BlockCutTree<TGraph> egoa::internal::BlockCutTreeBuilder< GraphType >::bcTree_ private
Definition at line 588 of file BlockCutTree.hpp.
blockStack_
template<typename GraphType > VectorStack<BlockUnderConstruction> egoa::internal::BlockCutTreeBuilder< GraphType >::blockStack_ private
Definition at line 590 of file BlockCutTree.hpp.
graph_
template<typename GraphType > TGraph const& egoa::internal::BlockCutTreeBuilder< GraphType >::graph_ private
Definition at line 587 of file BlockCutTree.hpp.
nextBlockId_
template<typename GraphType > Types::index egoa::internal::BlockCutTreeBuilder< GraphType >::nextBlockId_ = 0 private
Definition at line 589 of file BlockCutTree.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Graphs/BlockCutTree.hpp