Energy Grid Optimization & Analysis (EGOA): egoa::ArticulationVertexDetection< GraphType, IsDirected > Class Template Reference
egoa::ArticulationVertexDetection< GraphType, IsDirected > Class Template Reference
Class to find articulation vertices.
#include <ArticulationVertexDetection.hpp>
Public Types
using TGraph = GraphType
using TVertexId = typename TGraph::TVertexId
Public Types inherited from egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >
using TGraph = GraphType
using TVertexId = typename TGraph::TVertexId
using TTime = Types::count
Public Types inherited from egoa::Traversal< GraphType, IsDirected >
using TGraph = GraphType
using TVertexId = typename GraphType::TVertexId
Public Member Functions
ArticulationVertexDetection (TGraph const &graph, TVertexId source)
bool IsRootArticulationVertexAt (TVertexId const vertex) const
Determines if vertex is a root articulation vertex .
bool IsParentArticulationVertexAt (TVertexId const vertex) const
Determines if vertex is a parent articulation vertex .
std::pair< bool, bool > IsBridgeArticulationVertexAt (TVertexId const vertex) const
Determines if vertex and thus, its parent is a bridge articulation vertex .
bool IsArticulationVertexAt (TVertexId const vertex) const
Whether the vertex is an articulation vertex.
bool IsRoot (TVertexId const vertex) const
Determines if vertex is a root.
Public Member Functions inherited from egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >
void Run ()
DfsEdgeType TypifyEdge (TVertexId source, TVertexId target)
Determine DFS edge type.
bool Terminate () const
Terminate the DFS.
void SetTerminate ()
TTime EntryTimeAt (TVertexId vertexId) const
{ function_description }
TTime ExitTimeAt (TVertexId const vertexId) const
Returns the exit time of a vertex.
DepthFirstSearch (TGraph const &graph, TVertexId source)
Constructs a new DFS instance.
Public Member Functions inherited from egoa::Traversal< GraphType, IsDirected >
virtual void Result (std::vector< TVertexId > parent)
Traversal (TGraph const &graph, TVertexId source)
Constructs a new instance.
TVertexId Source () const
Getter and setter for the source vertex.
TVertexId & Source ()
TVertexId & ParentOf (TVertexId vertexId)
Getter and setter for the parent relation.
TVertexId ParentOf (TVertexId vertexId) const
Protected Member Functions
TTime & TimeOfOldestReachableAncestor (TVertexId vertex)
virtual void PreprocessingVertexWith (TVertexId const vertex) override
Preprocessing vertex with vertexId.
virtual void ProcessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId) override
Update the oldest reachable ancestor.
virtual void PostprocessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId) override
Post processing the edge with edgeId.
virtual void PostprocessingVertexWith (TVertexId vertexId) override
Decide which vertices are articulation vertices.
Types::count TreeOutDegree (TVertexId const vertex) const
Accessors for the tree out degree.
Types::count & TreeOutDegree (TVertexId const vertex)
Protected Member Functions inherited from egoa::Traversal< GraphType, IsDirected >
void Clear ()
Clear and resize all vectors.
bool VertexExists (TVertexId vertexId)
bool NumberOfVertices ()
void SetVertexVisitedAt (TVertexId vertexId)
Sets the vertex at vertexId to visited.
bool VisitedVertexAt (TVertexId vertexId) const
Getter and setter to access the visited field.
void SetVertexProcessedAt (TVertexId vertexId)
Sets the vertex at vertexId to processed.
bool ProcessedVertexAt (TVertexId vertexId) const
Getter and setter to access the process field.
template<typename FUNCTION >
void breakable_for_all_edges_at (TVertexId const &vertexId, FUNCTION function) const
The for loop over all (outgoing) edges that is breakable.
template<typename FUNCTION >
void for_all_edges_at (TVertexId const &vertexId, FUNCTION function) const
The for loop over all (outgoing) edges.
Private Types
using TTime = typename DepthFirstSearch< GraphType, IsDirected >::TTime
Private Attributes
std::vector< TTime > timeOfOldestReachableAncestor_
std::vector< Types::count > treeOutDegree_
std::vector< bool > isArticulationVertex_
Detailed Description
template<typename GraphType, bool IsDirected = false>
class egoa::ArticulationVertexDetection< GraphType, IsDirected >
Class to find articulation vertices.
Key thing of the DFS is that it distinguish the edges into tree edges and back edges.
Template Parameters
GraphType The graph should at least provide the same interface as the StaticGraph().
IsDirected If true the graph is treated as a directed graph, if false the graph is treated as an undirected graph.
Definition at line 26 of file ArticulationVertexDetection.hpp.
Member Typedef Documentation
TGraph
template<typename GraphType , bool IsDirected = false> using egoa::ArticulationVertexDetection< GraphType, IsDirected >::TGraph = GraphType
Definition at line 29 of file ArticulationVertexDetection.hpp.
TTime
template<typename GraphType , bool IsDirected = false> using egoa::ArticulationVertexDetection< GraphType, IsDirected >::TTime = typename DepthFirstSearch<GraphType, IsDirected>::TTime private
Definition at line 27 of file ArticulationVertexDetection.hpp.
TVertexId
template<typename GraphType , bool IsDirected = false> using egoa::ArticulationVertexDetection< GraphType, IsDirected >::TVertexId = typename TGraph::TVertexId
Definition at line 30 of file ArticulationVertexDetection.hpp.
Constructor & Destructor Documentation
ArticulationVertexDetection()
template<typename GraphType , bool IsDirected = false> egoa::ArticulationVertexDetection< GraphType, IsDirected >::ArticulationVertexDetection (TGraph const & graph, TVertexId source) inline
Definition at line 33 of file ArticulationVertexDetection.hpp.
~ArticulationVertexDetection()
template<typename GraphType , bool IsDirected = false> virtual egoa::ArticulationVertexDetection< GraphType, IsDirected >::~ArticulationVertexDetection () inline virtual
Definition at line 40 of file ArticulationVertexDetection.hpp.
Member Function Documentation
IsArticulationVertexAt()
template<typename GraphType , bool IsDirected = false> bool egoa::ArticulationVertexDetection< GraphType, IsDirected >::IsArticulationVertexAt (TVertexId const vertex) const inline
Whether the vertex is an articulation vertex.
Parameters
[in] vertex The identifier of the vertex.
Returns
true if it is an articulation vertex, false otherwise.
Definition at line 218 of file ArticulationVertexDetection.hpp.
References egoa::ArticulationVertexDetection< GraphType, IsDirected >::isArticulationVertex_.
IsBridgeArticulationVertexAt()
template<typename GraphType , bool IsDirected = false> std::pair< bool, bool > egoa::ArticulationVertexDetection< GraphType, IsDirected >::IsBridgeArticulationVertexAt (TVertexId const vertex) const inline
Determines if vertex and thus, its parent is a bridge articulation vertex .
If the oldest reachable vertex from vertex is the vertex itself, the edge (ParentOf(vertex), vertex) is a bridge unless vertex is a leaf. If it is a bridge both vertices are articulation vertices.
Parameters
[in] vertex The vertex identifier.
Returns
(True, True) if the vertex's parent and vertex are bridge articulation vertex, (True, False) if the parent is articulation vertex and vertex is a leaf, False otherwise.
Definition at line 199 of file ArticulationVertexDetection.hpp.
References egoa::ArticulationVertexDetection< GraphType, IsDirected >::TreeOutDegree().
IsParentArticulationVertexAt()
template<typename GraphType , bool IsDirected = false> bool egoa::ArticulationVertexDetection< GraphType, IsDirected >::IsParentArticulationVertexAt (TVertexId const vertex) const inline
Determines if vertex is a parent articulation vertex .
If the oldest reachable vertex of vertex is the parent and the parent is not a root, i.e., the parent of vertex is an articulation vertex.
Parameters
[in] vertex The vertex identifier.
Returns
True if vertex is a parent articulation vertex, False otherwise.
Definition at line 174 of file ArticulationVertexDetection.hpp.
References egoa::ArticulationVertexDetection< GraphType, IsDirected >::IsRoot(), and egoa::Traversal< GraphType, IsDirected >::ParentOf().
IsRoot()
template<typename GraphType , bool IsDirected = false> bool egoa::ArticulationVertexDetection< GraphType, IsDirected >::IsRoot (TVertexId const vertex) const inline
Determines if vertex is a root.
Note that infty represents the non-existence of a parent.
Parameters
[in] vertex The vertex identifier.
Returns
True if vertex is a root, False otherwise.
Definition at line 231 of file ArticulationVertexDetection.hpp.
References egoa::Traversal< GraphType, IsDirected >::ParentOf().
IsRootArticulationVertexAt()
template<typename GraphType , bool IsDirected = false> bool egoa::ArticulationVertexDetection< GraphType, IsDirected >::IsRootArticulationVertexAt (TVertexId const vertex) const inline
Determines if vertex is a root articulation vertex .
If the root has two or more vertices it is—by the definition of DFS—an articulation vertex. Note that for undirected graphs there can be know crossing edge connecting two subtrees of G.
Parameters
[in] vertex The vertex identifier.
Returns
True if vertex is a root articulation vertex, False otherwise.
Definition at line 152 of file ArticulationVertexDetection.hpp.
References egoa::ArticulationVertexDetection< GraphType, IsDirected >::IsRoot(), and egoa::ArticulationVertexDetection< GraphType, IsDirected >::TreeOutDegree().
PostprocessingEdgeWith()
template<typename GraphType , bool IsDirected = false> virtual void egoa::ArticulationVertexDetection< GraphType, IsDirected >::PostprocessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId) inline override protected virtual
Post processing the edge with edgeId.
Parameters
[in] vertexId The vertex identifier.
[in] function The function object that is called for the vertexId, e.g., a lambda function.
Template Parameters
FUNCTION The function object that is called for the edge identifiers edgeId.
Reimplemented from egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >.
Definition at line 100 of file ArticulationVertexDetection.hpp.
References egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::EntryTimeAt(), egoa::ArticulationVertexDetection< GraphType, IsDirected >::isArticulationVertex_, egoa::ArticulationVertexDetection< GraphType, IsDirected >::IsRoot(), and egoa::Traversal< GraphType, IsDirected >::ParentOf().
PostprocessingVertexWith()
template<typename GraphType , bool IsDirected = false> virtual void egoa::ArticulationVertexDetection< GraphType, IsDirected >::PostprocessingVertexWith (TVertexId vertexId) inline override protected virtual
Decide which vertices are articulation vertices.
Parameters
[in] vertexId The vertex identifier.
Reimplemented from egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >.
Definition at line 131 of file ArticulationVertexDetection.hpp.
References egoa::ArticulationVertexDetection< GraphType, IsDirected >::isArticulationVertex_, egoa::ArticulationVertexDetection< GraphType, IsDirected >::IsRoot(), and egoa::ArticulationVertexDetection< GraphType, IsDirected >::TreeOutDegree().
PreprocessingVertexWith()
template<typename GraphType , bool IsDirected = false> virtual void egoa::ArticulationVertexDetection< GraphType, IsDirected >::PreprocessingVertexWith (TVertexId const vertex) inline override protected virtual
Preprocessing vertex with vertexId.
Sets the time of the oldest reachable vertex to the current entry time.
Parameters
[in] vertex The vertex identifier.
Reimplemented from egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >.
Definition at line 69 of file ArticulationVertexDetection.hpp.
References egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::EntryTimeAt().
ProcessingEdgeWith()
template<typename GraphType , bool IsDirected = false> virtual void egoa::ArticulationVertexDetection< GraphType, IsDirected >::ProcessingEdgeWith (TVertexId source, TVertexId target, Types::edgeId edgeId) inline override protected virtual
Update the oldest reachable ancestor.
The oldest reachable ancestor is updated whenever a backward edge is detected that goes to a older vertex than the previous detected one. Note that the age can be easily determined by the time counter.
Parameters
[in] source The source identifier.
[in] target The target identifier.
Reimplemented from egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >.
Definition at line 84 of file ArticulationVertexDetection.hpp.
References egoa::Traversal< GraphType, IsDirected >::ParentOf(), egoa::ArticulationVertexDetection< GraphType, IsDirected >::TreeOutDegree(), and egoa::DepthFirstSearch< GraphType, IsDirected, Recursive >::TypifyEdge().
TimeOfOldestReachableAncestor()
template<typename GraphType , bool IsDirected = false> TTime & egoa::ArticulationVertexDetection< GraphType, IsDirected >::TimeOfOldestReachableAncestor (TVertexId vertex) inline protected
Definition at line 56 of file ArticulationVertexDetection.hpp.
TreeOutDegree() [1/2]
template<typename GraphType , bool IsDirected = false> Types::count & egoa::ArticulationVertexDetection< GraphType, IsDirected >::TreeOutDegree (TVertexId const vertex) inline protected
Definition at line 53 of file ArticulationVertexDetection.hpp.
TreeOutDegree() [2/2]
template<typename GraphType , bool IsDirected = false> Types::count egoa::ArticulationVertexDetection< GraphType, IsDirected >::TreeOutDegree (TVertexId const vertex) const inline protected
Accessors for the tree out degree.
Parameters
[in] vertex The vertex identifier.
Returns
Todo:
description
Definition at line 52 of file ArticulationVertexDetection.hpp.
References egoa::ArticulationVertexDetection< GraphType, IsDirected >::treeOutDegree_.
Member Data Documentation
isArticulationVertex_
template<typename GraphType , bool IsDirected = false> std::vector<bool> egoa::ArticulationVertexDetection< GraphType, IsDirected >::isArticulationVertex_ private
Whether the vertex is an articulation vertex
Definition at line 241 of file ArticulationVertexDetection.hpp.
timeOfOldestReachableAncestor_
template<typename GraphType , bool IsDirected = false> std::vector<TTime> egoa::ArticulationVertexDetection< GraphType, IsDirected >::timeOfOldestReachableAncestor_ private
Oldest reachable ancestor representing the vertex closest to the root
Definition at line 239 of file ArticulationVertexDetection.hpp.
treeOutDegree_
template<typename GraphType , bool IsDirected = false> std::vector<Types::count> egoa::ArticulationVertexDetection< GraphType, IsDirected >::treeOutDegree_ private
Number of outgoing DFS tree edges per vertex
Definition at line 240 of file ArticulationVertexDetection.hpp.
The documentation for this class was generated from the following file:
include/Algorithms/GraphTraversal/ArticulationVertexDetection.hpp