Energy Grid Optimization & Analysis (EGOA): egoa::PyPsaParser< GraphType > Class Template Reference
egoa::PyPsaParser< GraphType > Class Template Reference
Public Member Functions
Constructors and destructor
PyPsaParser (std::string const &filename)
PyPsaParser (std::string filenameBuses, std::string filenameCarriers, std::string filenameGenerators, std::string filenameGeneratorsPMaxPu, std::string filenameGlobalConstraints, std::string filenameLines, std::string filenameLinesNew, std::string filenameLoads, std::string filenameLoadsPSet, std::string filenameNetwork, std::string filenameSnapshots, std::string filenameStorageUnits, std::string filenameStorageUnitsInflow)
Reader Methods
bool ReadStorageUnitsInflows ()
Read storage units in flow.
bool ReadStorageUnits ()
Reads storage units.
bool ReadBuses (TNetwork &network, std::string const &filename)
Read the bus matrix.
bool ReadCarriers ()
Reads carriers.
bool ReadGeneratorsRealPowerMaxPu (TNetwork &network, std::string const &filename)
Read generators maximum real power production snapshot in p.u.
bool ReadGenerators (TNetwork &network, std::string const &filename)
Read the generator matrix.
bool ReadGlobalConstraints ()
Sets the generator default values.
template<typename Graph = TNetwork>
bool ReadLines (Graph &network, const std::string &filename)
Reads branch (lines) matrix.
void SetLineDefaultValues (TIoEdge &edge)
Sets the branch default values.
bool ReadLoadsPset (TNetwork &network, std::string const &filename)
Read loads real power set.
bool ReadLoads (TNetwork &network, std::string const &filename)
Read the load matrix that is a mapping of load to bus.
void SetLoadDefaultValues (TLoadProperties &vertex)
Sets the load default values.
bool ReadNetwork (TNetwork &network)
Reads a network.
bool ReadSnapshots (TNetwork &network)
Reads snapshots.
bool ReadCompleteNetwork (TNetwork &network, std::string const &filename)
Reads a complete network.
bool ReadCompleteNetwork (TNetwork &network, TGraph &candidateNetwork, std::string const &filename)
Reads a complete network and a candidate network.
Reader
bool read (TNetwork &network, std::string const &filename)
Read network from file.
bool read (TNetwork &network, TGraph &candidateNetwork, std::string const &filename)
Read network and candidate network from file.
Private Types
using TGraph = GraphType
using TNetwork = PowerGrid< GraphType >
using TVertex = typename TGraph::TVertex
using TVertexProperties = typename TGraph::TVertexProperties
using TVertexType = typename TVertexProperties::TVertexType
using TGeneratorProperties = typename TNetwork::TGeneratorProperties
using TLoadProperties = typename TNetwork::TLoadProperties
using TEdge = typename TGraph::TEdge
using TEdgeProperties = typename TGraph::TEdgeProperties
using TIoEdge = io::Edge< TEdgeProperties >
using TBound = Bound<>
Function pointer types
using ElectricalVertexFunc = void(PyPsaParser::*)(Types::name const &, TVertexProperties &)
using GeneratorVertexFunc = void(PyPsaParser::*)(Types::name const &, TGeneratorProperties &)
using GeneratorMaximumRealPowerPuFunc = std::function< void(Types::string const &, TNetwork &)>
using LoadVertexFunc = void(PyPsaParser::*)(Types::name const &, TLoadProperties &)
using LoadMaximumRealPowerPuFunc = std::function< void(Types::string const &, TNetwork &)>
using ElectricalEdgeFunc = void(PyPsaParser::*)(Types::name const &, TIoEdge &)
Private Member Functions
Auxiliary
template<typename Graph = TNetwork>
Types::vertexId AddVertex (Graph &network, TVertexProperties const &vertexProperties)
Wrapper for adding a vertex.
template<typename Graph = TNetwork>
Types::edgeId AddEdge (Graph &network, TIoEdge const &ioEdge)
Wrapper for adding an edge.
QList< QByteArray > ReadLine (QFile &file, bool compress=true)
Reads a line.
void CompressString (QByteArray &list)
Compress the string by removing spaces.
bool OpenFile (QFile &file)
Opens a file.
bool HasCorrectSnapshotSizes ()
Check if the snapshot size maps.
Header extraction
bool ExtractBusHeader (QList< QByteArray > const &splitted)
Extract the bus header.
bool ExtractLineHeader (QList< QByteArray > const &splitted)
Extract the line (branch) header.
bool ExtractGeneratorHeader (QList< QByteArray > const &splitted)
Extract the generator header.
bool ExtractGeneratorMaximumRealPowerPuHeader (QList< QByteArray > const &splitted)
Extract the existing generator maximum real power p.u. header.
bool ExtractLoadHeader (QList< QByteArray > const &splitted, Types::index &column)
Extract the existing load header data.
bool ExtractLoadMaximumRealPowerPuHeader (QList< QByteArray > const &splitted)
Extract load maximum real power p.u.
Bus (also known as vertex) data
void AddBusName (Types::name const &name, TVertexProperties &vertexProperty)
Add bus name to the vertex property.
void AddNominalVoltageToVertexProperty (Types::name const &voltageNominal, TVertexProperties &vertexProperty)
Add the nominal voltage to the vertex property.
void AddBusTypeToVertexProperty (Types::name const &type, TVertexProperties &vertexProperty)
Add the bus type to the vertex property.
void AddXcoordinateToVertexProperty (Types::name const &xCoordinate, TVertexProperties &vertexProperty)
Add x-coordinate to the vertex property.
void AddYcoordinateToVertexProperty (Types::name const &yCoordinate, TVertexProperties &vertexProperty)
Add y-coordinate to the vertex property.
void AddCarrierToVertexProperty (Types::name const &carrier, TVertexProperties &vertexProperty)
Add carrier to the vertex property.
void AddCountryToVertexProperty (Types::name const &country, TVertexProperties &vertexProperty)
Add data country to the vertex property.
void AddVoltageMagnitudePuSetPointToVertexProperty (Types::name const &voltageMagnitudePuSetpoint, TVertexProperties &vertexProperty)
Add voltage magnitude set point to the vertex property.
void AddMinimumVoltageMagnitudePuToVertexProperty (Types::name const &voltageMagnitudePuMinimum, TVertexProperties &vertexProperty)
Add minimum voltage magnitude to the vertex property.
void AddMaximumVoltageMagnitudePuToVertexProperty (Types::name const &voltageMagnitudePuMaximum, TVertexProperties &vertexProperty)
Add maximum voltage to the vertex property.
Vertex data output
void AddControlTypeToVertexProperty (Types::string const &control, TVertexProperties &vertexProperty)
Add the control type to the vertex property.
void AddSubnetworkToVertexProperty (Types::name const &subnetwork, TVertexProperties &vertexProperty)
Add the subnetwork to the vertex property.
void AddRealPowerToVertexProperty (Types::name const &realPower, TVertexProperties &vertexProperty)
Add the real power to the vertex property.
void AddReactivePowerToVertexProperty (Types::name const &reactivePower, TVertexProperties &vertexProperty)
Add reactive power to the vertex property.
void AddVoltageMagnitudePuToVertexProperty (Types::name const &voltageMagnitudePu, TVertexProperties &vertexProperty)
Add the voltage magnitude in p.u. to the vertex property.
void AddVoltageAngleToVertexProperty (Types::name const &voltageAngle, TVertexProperties &vertexProperty)
Add voltage angle to the vertex property.
void AddMarginalPriceToVertexProperty (Types::name const &marginalPrice, TVertexProperties &vertex)
Add the marginal price to the vertex property.
Generator (also known as source) data
void AddControlTypeToGenerator (Types::string const &control, TGeneratorProperties &generatorProperty)
Adds a control type to the generator.
void AddNominalRealPowerToGenerator (Types::string const &pNom, TGeneratorProperties &generatorProperty)
Adds a nominal real power to the generator.
void AddNominalRealPowerToGeneratorExtendable (Types::string const &pNomExtendable, TGeneratorProperties &generatorProperty)
Changes whether the generator is extendable or not.
void AddNameToGenerator (Types::name const &name, TGeneratorProperties &generatorProperty)
Adds a name to the generator.
void AssociateGeneratorWithBus (Types::name const &bus, TGeneratorProperties &generatorProperty)
Associate the generator with a bus.
void AddTypeToGenerator (Types::string const &type, TGeneratorProperties &generatorProperty)
Adds a type to the generator.
void AddGeneratorEfficiencyToGenerator (Types::string const &efficiency, TGeneratorProperties &generatorProperty)
Adds a generator efficiency to generator.
void AddNominalRealPowerToGeneratorMin (Types::string const &pNomMin, TGeneratorProperties &generatorProperty)
Adds a minimum nominal real power to the generator.
void AddNominalRealPowerToGeneratorMax (Types::string const &pNomMax, TGeneratorProperties &generatorProperty)
Adds a maximum nominal real power to the generator.
void AddMinimumRealPowerPuToGenerator (Types::string const &pMinPu, TGeneratorProperties &generatorProperty)
Adds a minimum real power in p.u. to the generator.
void AddMaximumRealPowerPuToGenerator (Types::string const &pMaxPu, TGeneratorProperties &generatorProperty)
Adds a maximum real power in p.u.
void AddRealPowerSetPointToGenerator (Types::string const &pSet, TGeneratorProperties &generatorProperty)
Adds a real power set point to the generator.
void AddReactivePowerSetPointToGenerator (Types::string const &qSet, TGeneratorProperties &generatorProperty)
Adds a reactive power set point to the generator.
void AddGeneratorSignToGenerator (Types::string const &sign, TGeneratorProperties &generatorProperty)
Add the generator's sign to the generator.
void AddCarrierToGenerator (Types::string const &carrier, TGeneratorProperties &generatorProperty)
Adds a carrier to the generator.
void AddMarginalCostToGenerator (Types::string const &marginalCost, TGeneratorProperties &generatorProperty)
Adds a marginal cost to the generator.
void AddCapitalCostToGenerator (Types::string const &capitalCost, TGeneratorProperties &generatorProperty)
Adds a capital cost to the generator.
void AddCommittabilityToGenerator (Types::string const &committable, TGeneratorProperties &generatorProperty)
Add if the generator is committable or not.
void AddStartUpCostToGenerator (Types::string const &startUpCost, TGeneratorProperties &generatorProperty)
Adds a start up cost to the generator.
void AddShutDownCostToGenerator (Types::string const &shutDownCost, TGeneratorProperties &generatorProperty)
Adds a shut down cost to the generator.
void AddMinimumUpTimeToGenerator (Types::string const &minUpTime, TGeneratorProperties &generatorProperty)
Adds a minimum up time to the generator.
void AddMinimumDownTimeToGenerator (Types::string const &minDownTime, TGeneratorProperties &generatorProperty)
Adds a minimum down time to the generator.
void AddInitialStatusToGenerator (Types::string const &initialStatus, TGeneratorProperties &generatorProperty)
Adds an initial status to the generator.
void AddRampLimitUpToGenerator (Types::string const &rampLimitUp, TGeneratorProperties &generatorProperty)
Adds a ramp up time limit to the generator.
void AddRampLimitDownToGenerator (Types::string const &rampLimitDown, TGeneratorProperties &generatorProperty)
Adds a ramp down time limit to the generator.
void AddRampLimitStartUpToGenerator (Types::string const &rampLimitStartUp, TGeneratorProperties &generatorProperty)
Adds a ramp start up time limit to the generator.
void AddRampLimitShutDownToGenerator (Types::string const &rampLimitShutDown, TGeneratorProperties &generatorProperty)
Adds a ramp limit shut down to the generator.
Generator data output
void AddRealPowerToGenerator (Types::name const &realPower, TGeneratorProperties &generatorProperty)
Adds a real power to the generator.
void AddReactivePowerToGenerator (Types::name const &reactivePower, TGeneratorProperties &generatorProperty)
Adds a reactive power to the generator.
void AddNominalRealPowerToGeneratorOpt (Types::name const &pNomOpt, TGeneratorProperties &generatorProperty)
Adds a optimal nominal real power to the generator.
void AddStatusToGenerator (Types::name const &status, TGeneratorProperties &generatorProperty)
Adds a status to the generator .
void AddWeightToGenerator (Types::name const &weight, TGeneratorProperties &generatorProperty)
Adds a weight to the generator .
Generator snapshot extraction
void AddTimestampOfGenerator (Types::name const &name, TNetwork &network)
Add the time stamp of the maximum real power.
void AddMaximumRealPowerSnapshotPuToGenerator (Types::name const &maximumRealPowerPu, TNetwork &network, Types::vertexId generatorId)
Add the maximum real power generation snapshot in p.u. to a generator.
Line (also known as Branch or Circuit) Data
void AddNameToEdge (Types::name const &name, TIoEdge &edge)
Add the name to the line.
void AddSourceVertexToEdge (Types::name const &source, TIoEdge &edge)
Associate the line with the source vertex.
void AddTargetVertexToEdge (Types::name const &target, TIoEdge &edge)
Associate the line with the target bus.
void AddCapitalCostToEdge (Types::name const &capitalCost, TIoEdge &edge)
Add the capital cost to the line.
void AddLengthToEdge (Types::name const &length, TIoEdge &edge)
Add the length to the line.
void AddNumberOfParallelLinesToEdge (Types::name const &numberParallelLines, TIoEdge &edge)
Add the number of parallel lines to the line.
void AddMaximumApparentPowerPuToEdge (Types::name const &apparentPowerMaximumPu, TIoEdge &edge)
Add the maximum apparent power in p.u. to the line.
void AddNominalApparentPowerToEdge (Types::name const &apparentPowerNominal, TIoEdge &edge)
Add the nominal apparent power to the line.
void AddLineTypeToEdge (Types::name const &type, TIoEdge &edge)
Add the line type to the line.
void AddNominalVoltageToEdge (Types::name const &voltageNominal, TIoEdge &edge)
Add the nominal voltage to the line.
void AddMinimumNominalApparentPowerToEdge (Types::name const &apparentPowerNominalMinimum, TIoEdge &edge)
Add the minimum nominal apparent power.
void AddMaximalNominalApparentPowerToEdge (Types::name const &apparentPowerNominalMaximum, TIoEdge &edge)
Add the maximum nominal apparent power to the line.
void AddResistanceToEdge (Types::name const &resistance, TIoEdge &edge)
Add the resistance to the line.
void AddReactanceToEdge (Types::name const &reactance, TIoEdge &edge)
Add the reactance to the line.
void AddConductanceToEdge (Types::name const &conductance, TIoEdge &edge)
Add the conductance to the line.
void AddSusceptanceToEdge (Types::name const &susceptance, TIoEdge &edge)
Add the susceptance to the line.
void AddNominalExtendableApparentPowerToEdge (Types::name const &apparentPowerNominalExtendable, TIoEdge &edge)
Add the nominal extendable apparent power to the line.
void AddTerrainFactorToEdge (Types::name const &terrainFactor, TIoEdge &edge)
Add the terrain factor to the line.
void AddMinimumVoltageAngleToEdge (Types::name const &voltageAngleMin, TIoEdge &edge)
Add the minimum voltage angle to the line.
void AddMaximumVoltageAngleToEdge (Types::name const &voltageAngleMax, TIoEdge &edge)
Add maximum voltage angle to the line.
Line data output.
Each row in the line data creates an edge.
Note
Currently only used for output.
void AddSubnetworkToEdge (Types::name const &subnetwork, TIoEdge &edge)
Add the subnetwork.
void AddP0ToEdge (Types::name const &p0, TIoEdge &edge)
Add the real power P0.
void AddQ0ToEdge (Types::name const &q0, TIoEdge &edge)
Add the reactive power Q0.
void AddP1ToEdge (Types::name const &p1, TIoEdge &edge)
Add the real power P1.
void AddQ1ToEdge (Types::name const &q1, TIoEdge &edge)
Add the reactive power Q1.
void AddReactancePuToEdge (Types::name const &reactancePu, TIoEdge &edge)
Add the reactance in p.u.
void AddResistancePuToEdge (Types::name const &resistancePu, TIoEdge &edge)
Add the resistance in p.u.
void AddConductancePuToEdge (Types::name const &conductancePu, TIoEdge &edge)
Add the conductance G in p.u.
void AddSusceptancePuToEdge (Types::name const &susceptancePu, TIoEdge &edge)
Add the susceptance in p.u.
void AddEffectiveReactancePuToEdge (Types::name const &reactancePuEffective, TIoEdge &edge)
Add the effective reactance in p.u.
void AddEffectiveResistancePuToEdge (Types::name const &resistancePuEffective, TIoEdge &edge)
Add the effective resistance in p.u.
void AddOptimalNominalApparentPowerToEdge (Types::name const &apparentPowerNominalOptimal, TIoEdge &edge)
Add the optimal nominal apparent power.
void AddMuLowerToEdge (Types::name const &muLower, TIoEdge &edge)
Add mu lower of a line.
void AddMuUpperToEdge (Types::name const &muUpper, TIoEdge &edge)
Add mu upper of a line.
Load Data.
Each row in the load data creates an load vertex.
Note
Currently only the name and type is set.
void AddNameToLoad (Types::string const &name, TLoadProperties &vertexProperty)
Add the name of the load.
void AssociateLoadWithVertex (Types::string const &bus, TLoadProperties &vertexProperty)
Associating the load with a bus.
void AddTypeToLoad (Types::string const &type, TLoadProperties &vertexProperty)
Add the load type.
void AddRealPowerSetPointToLoad (Types::string const &pset, TLoadProperties &vertexProperty)
Add the real power load set point.
void AddReactivePowerSetPointToLoad (Types::string const &qset, TLoadProperties &vertexProperty)
Add the reactive power set point.
void AddSignToLoad (Types::string const &sign, TLoadProperties &vertexProperty)
Add the data sign of the load.
void AddRealPowerToLoad (Types::string const &realPower, TLoadProperties &vertexProperty)
Add the real power load to the vertex property.
void AddReactivePowerToLoad (Types::string const &reactivePower, TLoadProperties &vertexProperty)
Add the reactive power loads.
Load's Real Power Data Snapshot per Timestamp.
Each row in the load's real power set data creates an snapshot entry.
Note
The snapshots are managed in the network and not in the load.
void AddLoadTimestampName (Types::name const &name, TNetwork &network)
Add a maximum real power load time stamp in p.u.
void AddMaximumRealPowerSnapshotPuToLoad (Types::name const &maximumRealPowerPu, TNetwork &network, Types::vertexId loadId)
Add a maximum real power load in p.u.
Private Attributes
std::vector< TGeneratorProperties * > headerGeneratorMaximumRealPowerPu_
Mappers for Reading Data
std::vector< ElectricalVertexFunc > dataMapperBuses_
std::vector< GeneratorMaximumRealPowerPuFunc > dataMapperGeneratorsRealPowerMaxPu_
std::vector< GeneratorVertexFunc > dataMapperGenerators_
std::vector< ElectricalEdgeFunc > dataMapperCandidateNetwork_
std::vector< ElectricalEdgeFunc > dataMapperLines_
std::vector< LoadVertexFunc > dataMapperLoads_
std::vector< LoadMaximumRealPowerPuFunc > dataMapperLoadsRealPowerMaxPu_
File and Directory Information
Types::name path2FileDirectory_
Types::name const filenameBuses_
Types::name const filenameCarriers_
Types::name const filenameGenerators_
Types::name const filenameGeneratorsPMaxPu_
Types::name const filenameGlobalConstraints_
Types::name const filenameLines_
Types::name const filenameLinesNew_
Types::name const filenameLoads_
Types::name const filenameLoadsPSet_
Types::name const filenameNetwork_
Types::name const filenameSnapshots_
Types::name const filenameStorageUnits_
Types::name const filenameStorageUnitsInflow_
Mapping of Different Inputs
std::unordered_map< Types::name, Types::vertexId > mapBusName2VertexId_
std::unordered_map< Types::name, TGeneratorProperties > mapGeneratorName2Generator_
std::unordered_map< Types::name, Types::vertexId > mapGeneratorName2Identifier_
std::unordered_map< Types::name, Types::name > mapGeneratorName2BusName_
std::unordered_map< Types::name, Types::vertexId > mapLoadName2Identifier_
Counter
Types::count generatorSnapshotsSize
Types::count loadSnapshotsSize
Detailed Description
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >>
class egoa::PyPsaParser< GraphType >
Definition at line 38 of file PyPsaParser.hpp.
Member Typedef Documentation
ElectricalEdgeFunc
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::ElectricalEdgeFunc = void (PyPsaParser::*)(Types::name const &, TIoEdge&) private
Definition at line 1226 of file PyPsaParser.hpp.
ElectricalVertexFunc
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::ElectricalVertexFunc = void (PyPsaParser::*)(Types::name const &, TVertexProperties&) private
Definition at line 1218 of file PyPsaParser.hpp.
GeneratorMaximumRealPowerPuFunc
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::GeneratorMaximumRealPowerPuFunc = std::function<void(Types::string const &, TNetwork&)> private
Definition at line 1221 of file PyPsaParser.hpp.
GeneratorVertexFunc
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::GeneratorVertexFunc = void (PyPsaParser::*)(Types::name const &, TGeneratorProperties&) private
Definition at line 1220 of file PyPsaParser.hpp.
LoadMaximumRealPowerPuFunc
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::LoadMaximumRealPowerPuFunc = std::function<void(Types::string const &, TNetwork&)> private
Definition at line 1224 of file PyPsaParser.hpp.
LoadVertexFunc
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::LoadVertexFunc = void (PyPsaParser::*)(Types::name const &, TLoadProperties&) private
Definition at line 1223 of file PyPsaParser.hpp.
TBound
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TBound = Bound<> private
Definition at line 55 of file PyPsaParser.hpp.
TEdge
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TEdge = typename TGraph::TEdge private
Definition at line 51 of file PyPsaParser.hpp.
TEdgeProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TEdgeProperties = typename TGraph::TEdgeProperties private
Definition at line 52 of file PyPsaParser.hpp.
TGeneratorProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TGeneratorProperties = typename TNetwork::TGeneratorProperties private
Definition at line 48 of file PyPsaParser.hpp.
TGraph
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TGraph = GraphType private
Definition at line 42 of file PyPsaParser.hpp.
TIoEdge
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TIoEdge = io::Edge<TEdgeProperties> private
Definition at line 53 of file PyPsaParser.hpp.
TLoadProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TLoadProperties = typename TNetwork::TLoadProperties private
Definition at line 49 of file PyPsaParser.hpp.
TNetwork
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TNetwork = PowerGrid<GraphType> private
Definition at line 43 of file PyPsaParser.hpp.
TVertex
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TVertex = typename TGraph::TVertex private
Definition at line 45 of file PyPsaParser.hpp.
TVertexProperties
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TVertexProperties = typename TGraph::TVertexProperties private
Definition at line 46 of file PyPsaParser.hpp.
TVertexType
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> using egoa::PyPsaParser< GraphType >::TVertexType = typename TVertexProperties::TVertexType private
Definition at line 47 of file PyPsaParser.hpp.
Constructor & Destructor Documentation
PyPsaParser() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> egoa::PyPsaParser< GraphType >::PyPsaParser (std::string const & filename) inline explicit
Definition at line 63 of file PyPsaParser.hpp.
PyPsaParser() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> egoa::PyPsaParser< GraphType >::PyPsaParser (std::string filenameBuses, std::string filenameCarriers, std::string filenameGenerators, std::string filenameGeneratorsPMaxPu, std::string filenameGlobalConstraints, std::string filenameLines, std::string filenameLinesNew, std::string filenameLoads, std::string filenameLoadsPSet, std::string filenameNetwork, std::string filenameSnapshots, std::string filenameStorageUnits, std::string filenameStorageUnitsInflow) inline
Definition at line 82 of file PyPsaParser.hpp.
~PyPsaParser()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> egoa::PyPsaParser< GraphType >::~PyPsaParser () inline
Definition at line 112 of file PyPsaParser.hpp.
Member Function Documentation
AddBusName()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddBusName (Types::name const & name, TVertexProperties & vertexProperty) inline private
Add bus name to the vertex property.
Parameters
name The name.
vertex The vertex property.
Definition at line 1258 of file PyPsaParser.hpp.
AddBusTypeToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddBusTypeToVertexProperty (Types::name const & type, TVertexProperties & vertexProperty) inline private
Add the bus type to the vertex property.
Precondition
Assume IEEE type.
Parameters
type The type.
vertexProperty The vertex property.
Note
Placeholder in PyPsa data, i.e., not used yet.
Definition at line 1294 of file PyPsaParser.hpp.
AddCapitalCostToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddCapitalCostToEdge (Types::name const & capitalCost, TIoEdge & edge) inline private
Add the capital cost to the line.
Parameters
capitalCost The capital cost.
edge The edge.
Definition at line 2320 of file PyPsaParser.hpp.
AddCapitalCostToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddCapitalCostToGenerator (Types::string const & capitalCost, TGeneratorProperties & generatorProperty) inline private
Adds a capital cost to the generator.
Parameters
capitalCost The capital cost.
generatorProperty The generator property.
Definition at line 1892 of file PyPsaParser.hpp.
AddCarrierToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddCarrierToGenerator (Types::string const & carrier, TGeneratorProperties & generatorProperty) inline private
Adds a carrier to the generator.
Parameters
carrier The carrier.
generatorProperty The generator property.
Definition at line 1857 of file PyPsaParser.hpp.
AddCarrierToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddCarrierToVertexProperty (Types::name const & carrier, TVertexProperties & vertexProperty) inline private
Add carrier to the vertex property.
Parameters
carrier The carrier.
vertexProperty The vertex property.
Definition at line 1339 of file PyPsaParser.hpp.
AddCommittabilityToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddCommittabilityToGenerator (Types::string const & committable, TGeneratorProperties & generatorProperty) inline private
Add if the generator is committable or not.
Parameters
committable The committable.
generator The generator.
Changes the committability property of the generator.
Parameters
committable The committable property.
generatorProperty The generator property.
Definition at line 1919 of file PyPsaParser.hpp.
AddConductancePuToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddConductancePuToEdge (Types::name const & conductancePu, TIoEdge & edge) inline private
Add the conductance G in p.u.
Parameters
conductancePu The conductance in p.u.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2816 of file PyPsaParser.hpp.
AddConductanceToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddConductanceToEdge (Types::name const & conductance, TIoEdge & edge) inline private
Add the conductance to the line.
Parameters
conductance The conductance.
edge The edge.
Definition at line 2535 of file PyPsaParser.hpp.
AddControlTypeToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddControlTypeToGenerator (Types::string const & control, TGeneratorProperties & generatorProperty) inline private
Adds a control type to the generator.
Parameters
control The control type.
generatorProperty The generator property.
Definition at line 1588 of file PyPsaParser.hpp.
AddControlTypeToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddControlTypeToVertexProperty (Types::string const & control, TVertexProperties & vertexProperty) inline private
Add the control type to the vertex property.
Parameters
control The control type of the bus.
vertexProperty The vertex property.
Note
Currently only output and not used yet.
Definition at line 1436 of file PyPsaParser.hpp.
AddCountryToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddCountryToVertexProperty (Types::name const & country, TVertexProperties & vertexProperty) inline private
Add data country to the vertex property.
Parameters
country The country.
vertexProperty The vertex property.
Definition at line 1354 of file PyPsaParser.hpp.
AddEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> template<typename Graph = TNetwork> Types::edgeId egoa::PyPsaParser< GraphType >::AddEdge (Graph & network, TIoEdge const & ioEdge) inline private
Wrapper for adding an edge.
Parameters
network The network .
ioEdge The i/o edge
Template Parameters
Graph The graph type, e.g., PowerGrid.
Returns
The edge identifier of a edge.
Definition at line 697 of file PyPsaParser.hpp.
AddEffectiveReactancePuToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddEffectiveReactancePuToEdge (Types::name const & reactancePuEffective, TIoEdge & edge) inline private
Add the effective reactance in p.u.
Parameters
reactancePuEffective The effective reactance in p.u.
edge The edge
Note
Currently only output and not used yet.
Definition at line 2860 of file PyPsaParser.hpp.
AddEffectiveResistancePuToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddEffectiveResistancePuToEdge (Types::name const & resistancePuEffective, TIoEdge & edge) inline private
Add the effective resistance in p.u.
Parameters
resistancePuEffective The effective resistance in p.u.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2882 of file PyPsaParser.hpp.
AddGeneratorEfficiencyToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddGeneratorEfficiencyToGenerator (Types::string const & efficiency, TGeneratorProperties & generatorProperty) inline private
Adds a generator efficiency to generator.
Parameters
efficiency The generator's efficiency.
generatorProperty The generator property.
Definition at line 1695 of file PyPsaParser.hpp.
AddGeneratorSignToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddGeneratorSignToGenerator (Types::string const & sign, TGeneratorProperties & generatorProperty) inline private
Add the generator's sign to the generator.
Parameters
sign The sign.
generatorProperty The generator property.
Definition at line 1835 of file PyPsaParser.hpp.
AddInitialStatusToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddInitialStatusToGenerator (Types::string const & initialStatus, TGeneratorProperties & generatorProperty) inline private
Adds an initial status to the generator.
Parameters
initialStatus The initial status.
generatorProperty The generator property.
Definition at line 2016 of file PyPsaParser.hpp.
AddLengthToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddLengthToEdge (Types::name const & length, TIoEdge & edge) inline private
Add the length to the line.
Parameters
length The length.
edge The edge.
Definition at line 2340 of file PyPsaParser.hpp.
AddLineTypeToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddLineTypeToEdge (Types::name const & type, TIoEdge & edge) inline private
Add the line type to the line.
Parameters
type The line type.
edge The edge.
Definition at line 2420 of file PyPsaParser.hpp.
AddLoadTimestampName()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddLoadTimestampName (Types::name const & name, TNetwork & network) inline private
Add a maximum real power load time stamp in p.u.
Parameters
name The real power load time stamp in p.u.
network The network .
Definition at line 3137 of file PyPsaParser.hpp.
AddMarginalCostToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMarginalCostToGenerator (Types::string const & marginalCost, TGeneratorProperties & generatorProperty) inline private
Adds a marginal cost to the generator.
Parameters
marginalCost The marginal cost.
generatorProperty The generator property.
Definition at line 1872 of file PyPsaParser.hpp.
AddMarginalPriceToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMarginalPriceToVertexProperty (Types::name const & marginalPrice, TVertexProperties & vertex) inline private
Add the marginal price to the vertex property.
Parameters
marginalPrice The marginal price.
vertex The vertex property.
Note
Currently only output and not used yet.
Definition at line 1563 of file PyPsaParser.hpp.
AddMaximalNominalApparentPowerToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMaximalNominalApparentPowerToEdge (Types::name const & apparentPowerNominalMaximum, TIoEdge & edge) inline private
Add the maximum nominal apparent power to the line.
Parameters
apparentPowerNominalMaximum The maximum nominal apparent power.
edge The edge.
Definition at line 2475 of file PyPsaParser.hpp.
AddMaximumApparentPowerPuToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMaximumApparentPowerPuToEdge (Types::name const & apparentPowerMaximumPu, TIoEdge & edge) inline private
Add the maximum apparent power in p.u. to the line.
Parameters
apparentPowerMaximumPu The maximum apparent power in p.u.
edge The edge.
Definition at line 2380 of file PyPsaParser.hpp.
AddMaximumRealPowerPuToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMaximumRealPowerPuToGenerator (Types::string const & pMaxPu, TGeneratorProperties & generatorProperty) inline private
Adds a maximum real power in p.u.
Parameters
pMaxPu The maximum real power in p.u.
generatorProperty The generator property.
Definition at line 1775 of file PyPsaParser.hpp.
AddMaximumRealPowerSnapshotPuToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMaximumRealPowerSnapshotPuToGenerator (Types::name const & maximumRealPowerPu, TNetwork & network, Types::vertexId generatorId) inline private
Add the maximum real power generation snapshot in p.u. to a generator.
Parameters
maximumRealPowerPu The maximum real power in p.u.
network The network .
[in] generatorId The generator identifier.
Todo:
Check if the number of timestamps are correct
Definition at line 2243 of file PyPsaParser.hpp.
AddMaximumRealPowerSnapshotPuToLoad()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMaximumRealPowerSnapshotPuToLoad (Types::name const & maximumRealPowerPu, TNetwork & network, Types::vertexId loadId) inline private
Add a maximum real power load in p.u.
Parameters
maximumRealPowerPu The maximum real power load in p.u.
network The network .
[in] loadId The load identifier.
Definition at line 3150 of file PyPsaParser.hpp.
AddMaximumVoltageAngleToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMaximumVoltageAngleToEdge (Types::name const & voltageAngleMax, TIoEdge & edge) inline private
Add maximum voltage angle to the line.
Parameters
voltageAngleMax The maximum voltage angle.
edge The edge.
Definition at line 2630 of file PyPsaParser.hpp.
AddMaximumVoltageMagnitudePuToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMaximumVoltageMagnitudePuToVertexProperty (Types::name const & voltageMagnitudePuMaximum, TVertexProperties & vertexProperty) inline private
Add maximum voltage to the vertex property.
Parameters
voltageMagnitudePuMaximum The maximum voltage magnitude in p.u.
vertexProperty The vertex property.
Definition at line 1409 of file PyPsaParser.hpp.
References egoa::PyPsaParser< GraphType >::AddNameToLoad(), egoa::PyPsaParser< GraphType >::AddReactivePowerSetPointToLoad(), egoa::PyPsaParser< GraphType >::AddReactivePowerToLoad(), egoa::PyPsaParser< GraphType >::AddRealPowerSetPointToLoad(), egoa::PyPsaParser< GraphType >::AddRealPowerToLoad(), egoa::PyPsaParser< GraphType >::AddSignToLoad(), egoa::PyPsaParser< GraphType >::AddTypeToLoad(), and egoa::PyPsaParser< GraphType >::AssociateLoadWithVertex().
AddMinimumDownTimeToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMinimumDownTimeToGenerator (Types::string const & minDownTime, TGeneratorProperties & generatorProperty) inline private
Adds a minimum down time to the generator.
Parameters
minDownTime The minimum down time.
generatorProperty The generator property.
Definition at line 1996 of file PyPsaParser.hpp.
AddMinimumNominalApparentPowerToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMinimumNominalApparentPowerToEdge (Types::name const & apparentPowerNominalMinimum, TIoEdge & edge) inline private
Add the minimum nominal apparent power.
Parameters
apparentPowerNominalMinimum The minimum nominal apparent power.
edge The edge.
Definition at line 2455 of file PyPsaParser.hpp.
AddMinimumRealPowerPuToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMinimumRealPowerPuToGenerator (Types::string const & pMinPu, TGeneratorProperties & generatorProperty) inline private
Adds a minimum real power in p.u. to the generator.
Parameters
pMinPu The minimum real power in p.u.
generatorProperty The generator property.
Definition at line 1755 of file PyPsaParser.hpp.
AddMinimumUpTimeToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMinimumUpTimeToGenerator (Types::string const & minUpTime, TGeneratorProperties & generatorProperty) inline private
Adds a minimum up time to the generator.
Parameters
minUpTime The minimum up time.
generatorProperty The generator property.
Definition at line 1976 of file PyPsaParser.hpp.
AddMinimumVoltageAngleToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMinimumVoltageAngleToEdge (Types::name const & voltageAngleMin, TIoEdge & edge) inline private
Add the minimum voltage angle to the line.
Parameters
voltageAngleMin The minimum voltage angle.
edge The edge.
Definition at line 2610 of file PyPsaParser.hpp.
AddMinimumVoltageMagnitudePuToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMinimumVoltageMagnitudePuToVertexProperty (Types::name const & voltageMagnitudePuMinimum, TVertexProperties & vertexProperty) inline private
Add minimum voltage magnitude to the vertex property.
Parameters
voltageMagnitudePuMinimum The minimum voltage magnitude in p.u.
vertexProperty The vertex property.
Definition at line 1389 of file PyPsaParser.hpp.
AddMuLowerToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMuLowerToEdge (Types::name const & muLower, TIoEdge & edge) inline private
Add mu lower of a line.
Parameters
muLower The mu lower.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2926 of file PyPsaParser.hpp.
AddMuUpperToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddMuUpperToEdge (Types::name const & muUpper, TIoEdge & edge) inline private
Add mu upper of a line.
Parameters
muUpper The mu upper.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2948 of file PyPsaParser.hpp.
AddNameToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNameToEdge (Types::name const & name, TIoEdge & edge) inline private
Add the name to the line.
Parameters
name The name of the line.
edge The edge.
Definition at line 2272 of file PyPsaParser.hpp.
AddNameToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNameToGenerator (Types::name const & name, TGeneratorProperties & generatorProperty) inline private
Adds a name to the generator.
Parameters
name The name.
generatorProperty The generator property.
Definition at line 1638 of file PyPsaParser.hpp.
AddNameToLoad()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNameToLoad (Types::string const & name, TLoadProperties & vertexProperty) inline private
Add the name of the load.
Parameters
name The name.
vertexProperty The vertex property.
Definition at line 2979 of file PyPsaParser.hpp.
AddNominalApparentPowerToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNominalApparentPowerToEdge (Types::name const & apparentPowerNominal, TIoEdge & edge) inline private
Add the nominal apparent power to the line.
Parameters
apparentPowerNominal The nominal apparent power.
edge The edge.
Definition at line 2400 of file PyPsaParser.hpp.
AddNominalExtendableApparentPowerToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNominalExtendableApparentPowerToEdge (Types::name const & apparentPowerNominalExtendable, TIoEdge & edge) inline private
Add the nominal extendable apparent power to the line.
Parameters
apparentPowerNominalExtendable The nominal extendable apparent power.
edge The edge.
Definition at line 2575 of file PyPsaParser.hpp.
References egoa::PyPsaParser< GraphType >::mapBusName2VertexId_.
AddNominalRealPowerToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNominalRealPowerToGenerator (Types::string const & pNom, TGeneratorProperties & generatorProperty) inline private
Adds a nominal real power to the generator.
Parameters
pNom The nominal real power.
generatorProperty The generator property.
Definition at line 1604 of file PyPsaParser.hpp.
AddNominalRealPowerToGeneratorExtendable()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNominalRealPowerToGeneratorExtendable (Types::string const & pNomExtendable, TGeneratorProperties & generatorProperty) inline private
Changes whether the generator is extendable or not.
Parameters
pNomExtendable The nominal extendable boolean.
generatorProperty The generator property.
Definition at line 1621 of file PyPsaParser.hpp.
AddNominalRealPowerToGeneratorMax()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNominalRealPowerToGeneratorMax (Types::string const & pNomMax, TGeneratorProperties & generatorProperty) inline private
Adds a maximum nominal real power to the generator.
Parameters
pNomMax The maximum nominal real power.
generatorProperty The generator property.
Definition at line 1735 of file PyPsaParser.hpp.
AddNominalRealPowerToGeneratorMin()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNominalRealPowerToGeneratorMin (Types::string const & pNomMin, TGeneratorProperties & generatorProperty) inline private
Adds a minimum nominal real power to the generator.
Parameters
pNomMin The nominal minimum real power.
generatorProperty The generator property.
Definition at line 1715 of file PyPsaParser.hpp.
AddNominalRealPowerToGeneratorOpt()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNominalRealPowerToGeneratorOpt (Types::name const & pNomOpt, TGeneratorProperties & generatorProperty) inline private
Adds a optimal nominal real power to the generator.
Parameters
pNomOpt The optimal nominal real power.
generatorProperty The generator property.
Definition at line 2160 of file PyPsaParser.hpp.
AddNominalVoltageToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNominalVoltageToEdge (Types::name const & voltageNominal, TIoEdge & edge) inline private
Add the nominal voltage to the line.
Parameters
voltageNominal The nominal voltage.
edge The edge.
Definition at line 2435 of file PyPsaParser.hpp.
AddNominalVoltageToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNominalVoltageToVertexProperty (Types::name const & voltageNominal, TVertexProperties & vertexProperty) inline private
Add the nominal voltage to the vertex property.
Parameters
voltageNominal The nominal voltage.
vertexProperty The vertex property.
Definition at line 1270 of file PyPsaParser.hpp.
AddNumberOfParallelLinesToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddNumberOfParallelLinesToEdge (Types::name const & numberParallelLines, TIoEdge & edge) inline private
Add the number of parallel lines to the line.
Parameters
numberParallelLines The number parallel lines.
edge The edge.
Definition at line 2360 of file PyPsaParser.hpp.
AddOptimalNominalApparentPowerToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddOptimalNominalApparentPowerToEdge (Types::name const & apparentPowerNominalOptimal, TIoEdge & edge) inline private
Add the optimal nominal apparent power.
Parameters
apparentPowerNominalOptimal The optimal nominal apparent power.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2904 of file PyPsaParser.hpp.
AddP0ToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddP0ToEdge (Types::name const & p0, TIoEdge & edge) inline private
Add the real power P0.
Parameters
p0 The real power P0.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2685 of file PyPsaParser.hpp.
AddP1ToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddP1ToEdge (Types::name const & p1, TIoEdge & edge) inline private
Add the real power P1.
Parameters
p1 The real power P1.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2729 of file PyPsaParser.hpp.
AddQ0ToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddQ0ToEdge (Types::name const & q0, TIoEdge & edge) inline private
Add the reactive power Q0.
Parameters
q0 The reactive power Q0.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2707 of file PyPsaParser.hpp.
AddQ1ToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddQ1ToEdge (Types::name const & q1, TIoEdge & edge) inline private
Add the reactive power Q1.
Parameters
q1 The reactive power Q1.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2751 of file PyPsaParser.hpp.
AddRampLimitDownToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddRampLimitDownToGenerator (Types::string const & rampLimitDown, TGeneratorProperties & generatorProperty) inline private
Adds a ramp down time limit to the generator.
Parameters
rampLimitDown The ramp limit down.
generatorProperty The generator property.
Definition at line 2055 of file PyPsaParser.hpp.
AddRampLimitShutDownToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddRampLimitShutDownToGenerator (Types::string const & rampLimitShutDown, TGeneratorProperties & generatorProperty) inline private
Adds a ramp limit shut down to the generator.
Parameters
rampLimitShutDown The ramp limit shut down.
generatorProperty The generator property.
Definition at line 2095 of file PyPsaParser.hpp.
AddRampLimitStartUpToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddRampLimitStartUpToGenerator (Types::string const & rampLimitStartUp, TGeneratorProperties & generatorProperty) inline private
Adds a ramp start up time limit to the generator.
Parameters
rampLimitStartUp The ramp start up time limit.
generatorProperty The generator property.
Definition at line 2075 of file PyPsaParser.hpp.
AddRampLimitUpToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddRampLimitUpToGenerator (Types::string const & rampLimitUp, TGeneratorProperties & generatorProperty) inline private
Adds a ramp up time limit to the generator.
Parameters
rampLimitUp The ramp limit up.
generatorProperty The generator property.
Definition at line 2035 of file PyPsaParser.hpp.
AddReactancePuToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddReactancePuToEdge (Types::name const & reactancePu, TIoEdge & edge) inline private
Add the reactance in p.u.
Parameters
reactancePu The reactance in p.u.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2773 of file PyPsaParser.hpp.
AddReactanceToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddReactanceToEdge (Types::name const & reactance, TIoEdge & edge) inline private
Add the reactance to the line.
Parameters
reactance The reactance.
edge The edge.
Definition at line 2515 of file PyPsaParser.hpp.
AddReactivePowerSetPointToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddReactivePowerSetPointToGenerator (Types::string const & qSet, TGeneratorProperties & generatorProperty) inline private
Adds a reactive power set point to the generator.
Parameters
qSet The reactive power set point.
generatorProperty The generator property.
Definition at line 1815 of file PyPsaParser.hpp.
AddReactivePowerSetPointToLoad()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddReactivePowerSetPointToLoad (Types::string const & qset, TLoadProperties & vertexProperty) inline private
Add the reactive power set point.
Parameters
qset The reactive power set point.
vertexProperty The vertex property.
Definition at line 3044 of file PyPsaParser.hpp.
AddReactivePowerToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddReactivePowerToGenerator (Types::name const & reactivePower, TGeneratorProperties & generatorProperty) inline private
Adds a reactive power to the generator.
Parameters
reactivePower The reactive power.
generatorProperty The generator property.
Definition at line 2140 of file PyPsaParser.hpp.
AddReactivePowerToLoad()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddReactivePowerToLoad (Types::string const & reactivePower, TLoadProperties & vertexProperty) inline private
Add the reactive power loads.
Parameters
reactivePower The reactive power.
vertexProperty The vertex property.
Definition at line 3104 of file PyPsaParser.hpp.
AddReactivePowerToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddReactivePowerToVertexProperty (Types::name const & reactivePower, TVertexProperties & vertexProperty) inline private
Add reactive power to the vertex property.
Parameters
reactivePower The reactive power
vertexProperty The vertex property
Note
Currently only output and not used yet.
Definition at line 1497 of file PyPsaParser.hpp.
AddRealPowerSetPointToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddRealPowerSetPointToGenerator (Types::string const & pSet, TGeneratorProperties & generatorProperty) inline private
Adds a real power set point to the generator.
Parameters
pSet The real power set point.
generatorProperty The generator property.
Definition at line 1795 of file PyPsaParser.hpp.
AddRealPowerSetPointToLoad()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddRealPowerSetPointToLoad (Types::string const & pset, TLoadProperties & vertexProperty) inline private
Add the real power load set point.
Parameters
pset The real power set point.
vertexProperty The vertex property.
Definition at line 3024 of file PyPsaParser.hpp.
AddRealPowerToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddRealPowerToGenerator (Types::name const & realPower, TGeneratorProperties & generatorProperty) inline private
Adds a real power to the generator.
Parameters
realPower The real power.
generatorProperty The generator property.
Definition at line 2120 of file PyPsaParser.hpp.
AddRealPowerToLoad()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddRealPowerToLoad (Types::string const & realPower, TLoadProperties & vertexProperty) inline private
Add the real power load to the vertex property.
Parameters
realPower The real power.
vertexProperty The vertex property.
Definition at line 3084 of file PyPsaParser.hpp.
AddRealPowerToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddRealPowerToVertexProperty (Types::name const & realPower, TVertexProperties & vertexProperty) inline private
Add the real power to the vertex property.
Parameters
realPower The real power.
vertexProperty The vertex property.
Note
Currently only output and not used yet.
Definition at line 1475 of file PyPsaParser.hpp.
AddResistancePuToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddResistancePuToEdge (Types::name const & resistancePu, TIoEdge & edge) inline private
Add the resistance in p.u.
Parameters
resistancePu The resistance in p.u.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2794 of file PyPsaParser.hpp.
AddResistanceToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddResistanceToEdge (Types::name const & resistance, TIoEdge & edge) inline private
Add the resistance to the line.
Parameters
resistance The resistance.
edge The edge.
Definition at line 2495 of file PyPsaParser.hpp.
AddShutDownCostToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddShutDownCostToGenerator (Types::string const & shutDownCost, TGeneratorProperties & generatorProperty) inline private
Adds a shut down cost to the generator.
Parameters
shutDownCost The shut down cost.
generatorProperty The generator property.
Definition at line 1956 of file PyPsaParser.hpp.
AddSignToLoad()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddSignToLoad (Types::string const & sign, TLoadProperties & vertexProperty) inline private
Add the data sign of the load.
Parameters
sign The sign.
vertexProperty The vertex property.
Definition at line 3064 of file PyPsaParser.hpp.
AddSourceVertexToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddSourceVertexToEdge (Types::name const & source, TIoEdge & edge) inline private
Associate the line with the source vertex.
Parameters
source The source vertex.
edge The edge.
Definition at line 2284 of file PyPsaParser.hpp.
AddStartUpCostToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddStartUpCostToGenerator (Types::string const & startUpCost, TGeneratorProperties & generatorProperty) inline private
Adds a start up cost to the generator.
Parameters
startUpCost The start up cost.
generatorProperty The generator property.
Definition at line 1936 of file PyPsaParser.hpp.
AddStatusToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddStatusToGenerator (Types::name const & status, TGeneratorProperties & generatorProperty) inline private
Adds a status to the generator .
Parameters
status The status.
generatorProperty The generator property.
Definition at line 2180 of file PyPsaParser.hpp.
AddSubnetworkToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddSubnetworkToEdge (Types::name const & subnetwork, TIoEdge & edge) inline private
Add the subnetwork.
Parameters
subnetwork The subnetwork.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2663 of file PyPsaParser.hpp.
AddSubnetworkToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddSubnetworkToVertexProperty (Types::name const & subnetwork, TVertexProperties & vertexProperty) inline private
Add the subnetwork to the vertex property.
Parameters
subnetwork The subnetwork.
vertexProperty The vertex property.
Note
Currently only output and not used yet.
Definition at line 1453 of file PyPsaParser.hpp.
References egoa::PyPsaParser< GraphType >::AddLoadTimestampName().
AddSusceptancePuToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddSusceptancePuToEdge (Types::name const & susceptancePu, TIoEdge & edge) inline private
Add the susceptance in p.u.
Parameters
susceptancePu The susceptance in p.u.
edge The edge.
Note
Currently only output and not used yet.
Definition at line 2838 of file PyPsaParser.hpp.
AddSusceptanceToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddSusceptanceToEdge (Types::name const & susceptance, TIoEdge & edge) inline private
Add the susceptance to the line.
Parameters
susceptance The susceptance.
edge The edge.
Definition at line 2555 of file PyPsaParser.hpp.
References egoa::PyPsaParser< GraphType >::mapBusName2VertexId_.
AddTargetVertexToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddTargetVertexToEdge (Types::name const & target, TIoEdge & edge) inline private
Associate the line with the target bus.
Parameters
target The target bus.
edge The edge.
Definition at line 2302 of file PyPsaParser.hpp.
AddTerrainFactorToEdge()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddTerrainFactorToEdge (Types::name const & terrainFactor, TIoEdge & edge) inline private
Add the terrain factor to the line.
Parameters
terrainFactor The terrain factor.
edge The edge.
Definition at line 2590 of file PyPsaParser.hpp.
AddTimestampOfGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddTimestampOfGenerator (Types::name const & name, TNetwork & network) inline private
Add the time stamp of the maximum real power.
Parameters
name The name.
network The network .
Todo:
What happens if load timestamps does not exist?
Definition at line 2228 of file PyPsaParser.hpp.
AddTypeToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddTypeToGenerator (Types::string const & type, TGeneratorProperties & generatorProperty) inline private
Adds a type to the generator.
Parameters
type The type.
generatorProperty The generator property.
Definition at line 1680 of file PyPsaParser.hpp.
AddTypeToLoad()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddTypeToLoad (Types::string const & type, TLoadProperties & vertexProperty) inline private
Add the load type.
Parameters
type The load type.
vertexProperty The vertex property.
Definition at line 3006 of file PyPsaParser.hpp.
AddVertex()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> template<typename Graph = TNetwork> Types::vertexId egoa::PyPsaParser< GraphType >::AddVertex (Graph & network, TVertexProperties const & vertexProperties) inline private
Wrapper for adding a vertex.
Parameters
network The network .
vertexProperties The vertex properties.
Template Parameters
Graph The graph type, e.g., PowerGrid.
Returns
The vertex identifier of a vertex.
Definition at line 679 of file PyPsaParser.hpp.
AddVoltageAngleToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddVoltageAngleToVertexProperty (Types::name const & voltageAngle, TVertexProperties & vertexProperty) inline private
Add voltage angle to the vertex property.
Parameters
voltageAngle The voltage angle.
vertexProperty The vertex property.
Note
Currently only output and not used yet.
Definition at line 1541 of file PyPsaParser.hpp.
AddVoltageMagnitudePuSetPointToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddVoltageMagnitudePuSetPointToVertexProperty (Types::name const & voltageMagnitudePuSetpoint, TVertexProperties & vertexProperty) inline private
Add voltage magnitude set point to the vertex property.
Parameters
voltageMagnitudePuSetpoint The voltage magnitude set point in p.u.
vertexProperty The vertex property.
Definition at line 1369 of file PyPsaParser.hpp.
AddVoltageMagnitudePuToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddVoltageMagnitudePuToVertexProperty (Types::name const & voltageMagnitudePu, TVertexProperties & vertexProperty) inline private
Add the voltage magnitude in p.u. to the vertex property.
Parameters
voltageMagnitudePu The voltage magnitude in p.u.
vertexProperty The vertex property.
Note
Currently only output and not used yet.
Definition at line 1519 of file PyPsaParser.hpp.
AddWeightToGenerator()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddWeightToGenerator (Types::name const & weight, TGeneratorProperties & generatorProperty) inline private
Adds a weight to the generator .
Parameters
weight The weight.
generatorProperty The generator property.
Definition at line 2200 of file PyPsaParser.hpp.
AddXcoordinateToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddXcoordinateToVertexProperty (Types::name const & xCoordinate, TVertexProperties & vertexProperty) inline private
Add x-coordinate to the vertex property.
Parameters
xCoordinate The x-coordinate or the bus.
vertexProperty The vertex property.
Definition at line 1309 of file PyPsaParser.hpp.
AddYcoordinateToVertexProperty()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AddYcoordinateToVertexProperty (Types::name const & yCoordinate, TVertexProperties & vertexProperty) inline private
Add y-coordinate to the vertex property.
Parameters
yCoordinate The y-coordinate or the bus.
vertexProperty The vertex property.
Definition at line 1324 of file PyPsaParser.hpp.
AssociateGeneratorWithBus()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AssociateGeneratorWithBus (Types::name const & bus, TGeneratorProperties & generatorProperty) inline private
Associate the generator with a bus.
Parameters
bus The bus.
generatorProperty The generator property.
Definition at line 1657 of file PyPsaParser.hpp.
AssociateLoadWithVertex()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::AssociateLoadWithVertex (Types::string const & bus, TLoadProperties & vertexProperty) inline private
Associating the load with a bus.
Parameters
bus The bus.
vertexProperty The vertex property.
Definition at line 2991 of file PyPsaParser.hpp.
CompressString()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::CompressString (QByteArray & list) inline private
Compress the string by removing spaces.
Parameters
list The list.
Definition at line 727 of file PyPsaParser.hpp.
ExtractBusHeader()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ExtractBusHeader (QList< QByteArray > const & splitted) inline private
Extract the bus header.
Dependent on the data some columns exist and some are missing. This method dynamically extracts the existing data.
Parameters
splitted The splitted line.
Returns
true if the extraction was successful, false otherwise.
Definition at line 775 of file PyPsaParser.hpp.
ExtractGeneratorHeader()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ExtractGeneratorHeader (QList< QByteArray > const & splitted) inline private
Extract the generator header.
Dependent on the data some columns exist and some are missing. This method dynamically extracts the existing data.
Parameters
splitted The splitted line.
Returns
true if the extraction was successful, false otherwise.
Definition at line 970 of file PyPsaParser.hpp.
ExtractGeneratorMaximumRealPowerPuHeader()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ExtractGeneratorMaximumRealPowerPuHeader (QList< QByteArray > const & splitted) inline private
Extract the existing generator maximum real power p.u. header.
Parameters
splitted The splitted string of one row/line.
Returns
true if the header could be extracted, false otherwise.
Definition at line 1087 of file PyPsaParser.hpp.
ExtractLineHeader()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ExtractLineHeader (QList< QByteArray > const & splitted) inline private
Extract the line (branch) header.
Dependent on the data some columns exist and some are missing. This method dynamically extracts the existing data.
Parameters
splitted The splitted line.
Returns
true if the extraction was successful, false otherwise.
Definition at line 845 of file PyPsaParser.hpp.
References egoa::PyPsaParser< GraphType >::HasCorrectSnapshotSizes(), egoa::PyPsaParser< GraphType >::ReadBuses(), egoa::PyPsaParser< GraphType >::ReadGenerators(), egoa::PyPsaParser< GraphType >::ReadGeneratorsRealPowerMaxPu(), egoa::PyPsaParser< GraphType >::ReadLines(), egoa::PyPsaParser< GraphType >::ReadLoads(), and egoa::PyPsaParser< GraphType >::ReadLoadsPset().
ExtractLoadHeader()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ExtractLoadHeader (QList< QByteArray > const & splitted, Types::index & column) inline private
Extract the existing load header data.
Parameters
splitted The splitted string of one row/line.
column The column
Returns
true if the header could be extracted, false otherwise.
Definition at line 1132 of file PyPsaParser.hpp.
References egoa::PyPsaParser< GraphType >::AddCapitalCostToEdge().
ExtractLoadMaximumRealPowerPuHeader()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ExtractLoadMaximumRealPowerPuHeader (QList< QByteArray > const & splitted) inline private
Extract load maximum real power p.u.
Parameters
splitted The splitted string of one row/line.
Returns
true if the header could be extracted, false otherwise.
Definition at line 1176 of file PyPsaParser.hpp.
HasCorrectSnapshotSizes()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::HasCorrectSnapshotSizes () inline private
Check if the snapshot size maps.
Returns
true the snapshot size maps, false otherwise.
Definition at line 754 of file PyPsaParser.hpp.
OpenFile()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::OpenFile (QFile & file) inline private
Opens a file.
Parameters
file The file.
Returns
true file could be opened, false otherwise.
Definition at line 739 of file PyPsaParser.hpp.
read() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::read (TNetwork & network, std::string const & filename) inline
Read network from file.
Parameters
network The network network .
filename The filename .
Returns
true if the parsing was successful, false otherwise.
Definition at line 640 of file PyPsaParser.hpp.
read() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::read (TNetwork & network, TGraph & candidateNetwork, std::string const & filename) inline
Read network and candidate network from file.
Parameters
network The network .
candidateNetwork The candidate network
filename The filename.
Returns
true if the parsing was successful, false otherwise.
Definition at line 655 of file PyPsaParser.hpp.
ReadBuses()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadBuses (TNetwork & network, std::string const & filename) inline
Read the bus matrix.
While reading each line of the matrix a vertex is created and added to the network (see the bus section of https://pypsa.org/doc/components.html for more information).
Parameters
network The network .
filename The filename.
Returns
True if the parsing was successful, False otherwise.
Definition at line 171 of file PyPsaParser.hpp.
ReadCarriers()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadCarriers () inline
Reads carriers.
For more information see the carrier section under https://pypsa.org/doc/components.html.
Returns
True if the parsing was successful, False otherwise.
Definition at line 211 of file PyPsaParser.hpp.
ReadCompleteNetwork() [1/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadCompleteNetwork (TNetwork & network, std::string const & filename) inline
Reads a complete network.
Parameters
network The network .
[in] filename The filename.
Returns
true if the parsing was successful, false otherwise.
Definition at line 583 of file PyPsaParser.hpp.
ReadCompleteNetwork() [2/2]
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadCompleteNetwork (TNetwork & network, TGraph & candidateNetwork, std::string const & filename) inline
Reads a complete network and a candidate network.
Parameters
network The network .
candidateNetwork The candidate network .
[in] filename The filename.
Returns
true if the parsing was successful, false otherwise.
Definition at line 606 of file PyPsaParser.hpp.
ReadGenerators()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadGenerators (TNetwork & network, std::string const & filename) inline
Read the generator matrix.
While reading each row of the matrix a generator is created and added to the network. The description of the elements is as in https://pypsa.org/doc/components.html.
Parameters
network The network .
filename The filename.
Returns
True if the parsing was successful, False otherwise.
Definition at line 276 of file PyPsaParser.hpp.
ReadGeneratorsRealPowerMaxPu()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadGeneratorsRealPowerMaxPu (TNetwork & network, std::string const & filename) inline
Read generators maximum real power production snapshot in p.u.
For more information see the generator section under https://pypsa.org/doc/components.html.
Parameters
network The network .
filename The filename
Returns
True if the parsing was successful, False otherwise.
Definition at line 230 of file PyPsaParser.hpp.
References egoa::PyPsaParser< GraphType >::ExtractBusHeader(), egoa::PyPsaParser< GraphType >::filenameBuses_, egoa::PyPsaParser< GraphType >::mapBusName2VertexId_, egoa::PyPsaParser< GraphType >::OpenFile(), and egoa::PyPsaParser< GraphType >::ReadLine().
ReadGlobalConstraints()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadGlobalConstraints () inline
Sets the generator default values.
The description of the elements is as in https://pypsa.org/doc/components.html.
Returns
True if the parsing was successful, False otherwise.
Definition at line 334 of file PyPsaParser.hpp.
ReadLine()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> QList< QByteArray > egoa::PyPsaParser< GraphType >::ReadLine (QFile & file, bool compress = true) inline private
Reads a line.
Parameters
file The file.
[in] compress The compress.
Returns
The line as array, where each field represents a column entry.
Definition at line 713 of file PyPsaParser.hpp.
ReadLines()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> template<typename Graph = TNetwork> bool egoa::PyPsaParser< GraphType >::ReadLines (Graph & network, const std::string & filename) inline
Reads branch (lines) matrix.
While reading each row of the matrix an arc is created and added to the network.
Parameters
network The network .
[in] filename The filename.
Template Parameters
Graph A graph type such as PowerGrid or StaticGraph.
Returns
True if the parsing was successful, False otherwise.
Definition at line 355 of file PyPsaParser.hpp.
ReadLoads()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadLoads (TNetwork & network, std::string const & filename) inline
Read the load matrix that is a mapping of load to bus.
While reading each row of the matrix a mapping between load and bus is made and thus, the load is added to the network.
Parameters
network The network .
filename The filename.
Returns
True if the parsing was successful, False otherwise.
Definition at line 476 of file PyPsaParser.hpp.
ReadLoadsPset()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadLoadsPset (TNetwork & network, std::string const & filename) inline
Read loads real power set.
While reading each row of the matrix a real power load is added to the network.
Parameters
network The network .
filename The filename.
Returns
True if the parsing was successful, False otherwise.
Definition at line 432 of file PyPsaParser.hpp.
ReadNetwork()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadNetwork (TNetwork & network) inline
Reads a network.
The description of the elements is as in https://pypsa.org/doc/components.html.
Parameters
network The network .
Returns
True if the parsing was successful, False otherwise.
Definition at line 548 of file PyPsaParser.hpp.
ReadSnapshots()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadSnapshots (TNetwork & network) inline
Reads snapshots.
The description of the elements is as in https://pypsa.org/doc/components.html.
Parameters
network The network .
Returns
True if the parsing was successful, False otherwise.
Definition at line 565 of file PyPsaParser.hpp.
ReadStorageUnits()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadStorageUnits () inline
Reads storage units.
For more information see the storage unit section under https://pypsa.org/doc/components.html.
Returns
True if the parsing was successful, False otherwise.
Definition at line 151 of file PyPsaParser.hpp.
ReadStorageUnitsInflows()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> bool egoa::PyPsaParser< GraphType >::ReadStorageUnitsInflows () inline
Read storage units in flow.
For more information see the storage unit section under https://pypsa.org/doc/components.html.
Returns
Returns true if the parsing was successful, false otherwise.
Definition at line 136 of file PyPsaParser.hpp.
SetLineDefaultValues()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::SetLineDefaultValues (TIoEdge & edge) inline
Sets the branch default values.
The description of the elements is as in https://pypsa.org/doc/components.html.
Parameters
edge The edge object.
Definition at line 395 of file PyPsaParser.hpp.
References egoa::PyPsaParser< GraphType >::mapBusName2VertexId_, egoa::PyPsaParser< GraphType >::mapGeneratorName2BusName_, egoa::PyPsaParser< GraphType >::mapGeneratorName2Identifier_, and egoa::PyPsaParser< GraphType >::ReadLine().
SetLoadDefaultValues()
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> void egoa::PyPsaParser< GraphType >::SetLoadDefaultValues (TLoadProperties & vertex) inline
Sets the load default values.
The description of the elements is as in https://pypsa.org/doc/components.html.
Parameters
vertex The load vertex object.
Definition at line 532 of file PyPsaParser.hpp.
Member Data Documentation
dataMapperBuses_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::vector<ElectricalVertexFunc> egoa::PyPsaParser< GraphType >::dataMapperBuses_ private
Definition at line 1233 of file PyPsaParser.hpp.
dataMapperCandidateNetwork_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::vector<ElectricalEdgeFunc> egoa::PyPsaParser< GraphType >::dataMapperCandidateNetwork_ private
Definition at line 1239 of file PyPsaParser.hpp.
dataMapperGenerators_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::vector<GeneratorVertexFunc> egoa::PyPsaParser< GraphType >::dataMapperGenerators_ private
Definition at line 1236 of file PyPsaParser.hpp.
dataMapperGeneratorsRealPowerMaxPu_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::vector<GeneratorMaximumRealPowerPuFunc> egoa::PyPsaParser< GraphType >::dataMapperGeneratorsRealPowerMaxPu_ private
Definition at line 1235 of file PyPsaParser.hpp.
dataMapperLines_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::vector<ElectricalEdgeFunc> egoa::PyPsaParser< GraphType >::dataMapperLines_ private
Definition at line 1240 of file PyPsaParser.hpp.
dataMapperLoads_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::vector<LoadVertexFunc> egoa::PyPsaParser< GraphType >::dataMapperLoads_ private
Definition at line 1242 of file PyPsaParser.hpp.
dataMapperLoadsRealPowerMaxPu_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::vector<LoadMaximumRealPowerPuFunc> egoa::PyPsaParser< GraphType >::dataMapperLoadsRealPowerMaxPu_ private
Definition at line 1243 of file PyPsaParser.hpp.
filenameBuses_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameBuses_ private
Name of the bus file, e.g., buses.csv
Definition at line 3173 of file PyPsaParser.hpp.
filenameCarriers_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameCarriers_ private
Name of the carriers file, e.g., carriers.csv
Definition at line 3174 of file PyPsaParser.hpp.
filenameGenerators_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameGenerators_ private
Name of the generators file, e.g., generators.csv
Definition at line 3175 of file PyPsaParser.hpp.
filenameGeneratorsPMaxPu_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameGeneratorsPMaxPu_ private
Name of the generators real power (in p.u.) snapshot file, e.g., generators-p_max_pu.csv
Definition at line 3176 of file PyPsaParser.hpp.
filenameGlobalConstraints_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameGlobalConstraints_ private
Name of the global constraints file, e.g., global_constraints.csv
Definition at line 3177 of file PyPsaParser.hpp.
filenameLines_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameLines_ private
Name of the branches file, e.g., lines.csv
Definition at line 3178 of file PyPsaParser.hpp.
filenameLinesNew_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameLinesNew_ private
Name of the new branches file, e.g., lines_new.csv
Definition at line 3179 of file PyPsaParser.hpp.
filenameLoads_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameLoads_ private
Name of the loads file, e.g., loads.csv
Definition at line 3180 of file PyPsaParser.hpp.
filenameLoadsPSet_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameLoadsPSet_ private
Name of the loads real power set point snapshot file, e.g., loads-p_set.csv
Definition at line 3181 of file PyPsaParser.hpp.
filenameNetwork_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameNetwork_ private
Name of the network file, e.g., network.csv
Definition at line 3182 of file PyPsaParser.hpp.
filenameSnapshots_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameSnapshots_ private
Name of the file with the weighting of a snapshot, e.g., snapshot.csv
Definition at line 3183 of file PyPsaParser.hpp.
filenameStorageUnits_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameStorageUnits_ private
Name of the file with the storage units, e.g., storage_units.csv
Definition at line 3184 of file PyPsaParser.hpp.
filenameStorageUnitsInflow_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name const egoa::PyPsaParser< GraphType >::filenameStorageUnitsInflow_ private
Name of the file with the storage units inflow, e.g., storage_units-inflow.csv
Definition at line 3185 of file PyPsaParser.hpp.
generatorSnapshotsSize
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::count egoa::PyPsaParser< GraphType >::generatorSnapshotsSize private
Definition at line 3202 of file PyPsaParser.hpp.
headerGeneratorMaximumRealPowerPu_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::vector<TGeneratorProperties*> egoa::PyPsaParser< GraphType >::headerGeneratorMaximumRealPowerPu_ private
Definition at line 1214 of file PyPsaParser.hpp.
loadSnapshotsSize
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::count egoa::PyPsaParser< GraphType >::loadSnapshotsSize private
Definition at line 3203 of file PyPsaParser.hpp.
mapBusName2VertexId_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::unordered_map<Types::name, Types::vertexId> egoa::PyPsaParser< GraphType >::mapBusName2VertexId_ private
Mapping the bus name to the vertex identifier
Definition at line 3192 of file PyPsaParser.hpp.
mapGeneratorName2BusName_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::unordered_map<Types::name, Types::name> egoa::PyPsaParser< GraphType >::mapGeneratorName2BusName_ private
Mapping the generator name to the vertex name
Definition at line 3195 of file PyPsaParser.hpp.
mapGeneratorName2Generator_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::unordered_map<Types::name, TGeneratorProperties> egoa::PyPsaParser< GraphType >::mapGeneratorName2Generator_ private
Mapping the generator name to the generator
Definition at line 3193 of file PyPsaParser.hpp.
mapGeneratorName2Identifier_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::unordered_map<Types::name, Types::vertexId> egoa::PyPsaParser< GraphType >::mapGeneratorName2Identifier_ private
Mapping the generator name to the vertex identifier
Definition at line 3194 of file PyPsaParser.hpp.
mapLoadName2Identifier_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> std::unordered_map<Types::name, Types::vertexId> egoa::PyPsaParser< GraphType >::mapLoadName2Identifier_ private
Mapping the load name to the vertex identifier
Definition at line 3196 of file PyPsaParser.hpp.
path2FileDirectory_
template<typename GraphType = StaticGraph< Vertices::ElectricalProperties<Vertices::IeeeBusType>, Edges::ElectricalProperties >> Types::name egoa::PyPsaParser< GraphType >::path2FileDirectory_ private
The path to the PyPsa file directory, e.g., elec_s1024_AT
Definition at line 3172 of file PyPsaParser.hpp.
The documentation for this class was generated from the following file:
include/IO/Parser/PyPsaParser.hpp