Energy Grid Optimization & Analysis (EGOA): egoa::Vertices::ElectricalProperties< VertexType > Class Template Reference
egoa::Vertices::ElectricalProperties< VertexType > Class Template Reference
Class for electrical properties.
#include <ElectricalProperties.hpp>
Public Types
using TVertexType = VertexType
using TProperties = ElectricalProperties< TVertexType >
Public Member Functions
Constructors and Destructor
ElectricalProperties ()
Default constructs the object.
void Reset ()
Reset values to default.
bool operator!= (ElectricalProperties const &rhs) const
Inequality comparator.
bool operator== (ElectricalProperties const &rhs) const
Equality comparator.
Basic Properties
Types::name Name () const
Types::name & Name ()
TVertexType Type () const
TVertexType & Type ()
Types::real X () const
Types::real & X ()
Types::real Y () const
Types::real & Y ()
Admittance
Types::real ShuntSusceptance () const
Getter for the shunt susceptance .
Types::real & ShuntSusceptance ()
Getter and setter for the shunt susceptance .
Types::real ShuntConductance () const
Getter for the shunt conductance .
Types::real & ShuntConductance ()
Getter and setter for the shunt conductance .
Voltage
Types::real NominalVoltage () const
Getter for the nominal voltage (also known as base voltage; in kV).
Types::real & NominalVoltage ()
Getter and setter for the nominal voltage (also known as base voltage; in kV).
Types::real VoltageMagnitude () const
Getter for the voltage magnitude .
Types::real & VoltageMagnitude ()
Getter and setter for the voltage magnitude .
Types::real VoltageAngle () const
Getter for the voltage angle .
Types::real & VoltageAngle ()
Getter for the voltage angle .
Types::real MinimumVoltage () const
Getter for the minimum voltage magnitude .
Types::real & MinimumVoltage ()
Getter and setter for the minimum voltage magnitude .
Types::real MaximumVoltage () const
Getter for the maximum voltage magnitude .
Types::real & MaximumVoltage ()
Getter and setter for the maximum voltage magnitude .
Type specific information
Types::name Country () const
Getter for the country.
Types::name & Country ()
Getter and setter for the country.
Types::index Area () const
Getter for the bus area number.
Types::index & Area ()
Getter and setter for the bus area number.
Types::index Zone () const
Getter for the loss zone.
Types::index & Zone ()
Getter and setter for the loss zone.
Vertices::ControlType Control () const
Getter for the bus control type strategy.
Vertices::ControlType & Control ()
Getter and setter for the bus control type strategy.
Vertices::EnergyCarrier Carrier () const
Getter for the energy carrier type.
Vertices::EnergyCarrier & Carrier ()
Getter and setter for the energy carrier type.
Status
bool IsActive () const
Determines if the electrical vertex is active.
Vertices::BusStatus & Status ()
Status of the electrical vertex.
Vertices::BusStatus const & Status () const
Status of the electrical vertex.
Private Types
using TBound = Bound< Types::real >
Private Attributes
Basic Property Members
Types::name name_
TVertexType type_
Types::real xCoordinate_
Types::real yCoordinate_
Admittance Related Members
Types::real shuntSusceptance_
Types::real shuntConductance_
Voltage Related Members
Types::real nominalVoltage_
Types::real voltageAngle_
Types::real voltageMagnitude_
Types::real voltageMagnitudeSq_
TBound voltageBound_
Location Specific Members
Types::name country_
Types::index area_
Types::index zone_
Vertices::ControlType control_
Vertices::EnergyCarrier carrier_
Status Members
Vertices::BusStatus status_
Friends
Copy and swap idiom
void swap (ElectricalProperties &lhs, ElectricalProperties &rhs)
Swapping the members of two ElectricalVertices.
Output
void Line (std::ostream &outputStream, Types::real baseMva=1) const
Line out stream.
void Line (std::ostream &outputStream, Types::vertexId identifier, Types::real baseMva=1) const
Writes the electrical property as a line.
std::ostream & operator<< (std::ostream &outputStream, TProperties const &rhs)
Write the electrical property to an output stream.
static void HeaderLong (std::ostream &outputStream)
Header out stream.
static void Header (std::ostream &outputStream)
Header out stream.
Detailed Description
template<class VertexType = Vertices::IeeeBusType>
class egoa::Vertices::ElectricalProperties< VertexType >
Class for electrical properties.
Template Parameters
VertexType The vertex type, e.g., Vertices::IeeeBusType.
Definition at line 28 of file ElectricalProperties.hpp.
Member Typedef Documentation
TBound
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::ElectricalProperties< VertexType >::TBound = Bound<Types::real> private
Definition at line 34 of file ElectricalProperties.hpp.
TProperties
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::ElectricalProperties< VertexType >::TProperties = ElectricalProperties<TVertexType>
Definition at line 32 of file ElectricalProperties.hpp.
TVertexType
template<class VertexType = Vertices::IeeeBusType> using egoa::Vertices::ElectricalProperties< VertexType >::TVertexType = VertexType
Definition at line 31 of file ElectricalProperties.hpp.
Constructor & Destructor Documentation
ElectricalProperties()
template<class VertexType = Vertices::IeeeBusType> egoa::Vertices::ElectricalProperties< VertexType >::ElectricalProperties () inline
Default constructs the object.
The values are set to the default values.
Definition at line 45 of file ElectricalProperties.hpp.
Member Function Documentation
Area() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::index & egoa::Vertices::ElectricalProperties< VertexType >::Area () inline
Getter and setter for the bus area number.
Bus area (1 - 99) indicates in which company/region the station is located. A two digit integer from 0 to 99 indicating the company or region in which the line is located. This area number should be the same as the area of one of the two terminal vertices. Tie line it indicates the ownership or area to which the losses should be assigned. This area is not related to the meter bus location.
Note
If the value is 0 this means that there is no data available or there is no area.
ElectricalProperties vertex;
vertex.Area() = 11;
Returns
The bus area number.
Definition at line 505 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::area_.
Area() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::index egoa::Vertices::ElectricalProperties< VertexType >::Area () const inline
Getter for the bus area number.
Bus area (1 - 99) indicates in which company/region the station is located. A two digit integer from 0 to 99 indicating the company or region in which the line is located. This area number should be the same as the area of one of the two terminal vertices. Tie line it indicates the ownership or area to which the losses should be assigned. This area is not related to the meter bus location.
Note
If the value is 0 this means that there is no data available or there is no area.
Returns
The bus area number.
Definition at line 480 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::area_.
Carrier() [1/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::EnergyCarrier & egoa::Vertices::ElectricalProperties< VertexType >::Carrier () inline
Getter and setter for the energy carrier type.
The energy carrier type describes if the electrical vertex is connected to or . If the vertex is not an electrical bus it might be heat or gas.
ElectricalProperties vertex;
vertex.Carrier() = Vertices::EnergyCarrier::DC;
See also
Type::Vertices::EnergyCarrier
Returns
The energy carrier type.
Definition at line 609 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::carrier_.
Carrier() [2/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::EnergyCarrier egoa::Vertices::ElectricalProperties< VertexType >::Carrier () const inline
Getter for the energy carrier type.
The energy carrier type describes the vertex is for example connected to or .
See also
Type::Vertices::EnergyCarrier
Returns
The energy carrier type.
Definition at line 588 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::carrier_.
Control() [1/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::ControlType & egoa::Vertices::ElectricalProperties< VertexType >::Control () inline
Getter and setter for the bus control type strategy.
The bus control type strategy can be either PQ, PV, or slack. The latter represents the reference bus. The voltage angle of the reference bus is usually set to 0.
ElectricalProperties vertex;
vertex.Control() = Vertices::ControlType::PQ;
See also
Type::Vertices::ControlType
Returns
The bus control type strategy.
Definition at line 574 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::control_.
Control() [2/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::ControlType egoa::Vertices::ElectricalProperties< VertexType >::Control () const inline
Getter for the bus control type strategy.
The bus control type strategy can be either PQ, PV, or slack. The latter represents the reference bus. The voltage angle of the reference bus is usually set to 0.
See also
Type::Vertices::ControlType
Returns
The bus control type strategy.
Definition at line 553 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::control_.
Country() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::name & egoa::Vertices::ElectricalProperties< VertexType >::Country () inline
Getter and setter for the country.
Used in PyPSA for example to specify the location of the vertex.
Returns
The country of the vertex.
Definition at line 460 of file ElectricalProperties.hpp.
Country() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::name egoa::Vertices::ElectricalProperties< VertexType >::Country () const inline
Getter for the country.
Used in PyPSA for example to specify the location of the vertex.
Returns
The country of the vertex.
Definition at line 448 of file ElectricalProperties.hpp.
Header()
template<class VertexType = Vertices::IeeeBusType> static void egoa::Vertices::ElectricalProperties< VertexType >::Header (std::ostream & outputStream) inline static
Header out stream.
List all IEEE standard input data.
Parameters
outputStream The stream to write data to, e.g., std::cout.
Definition at line 690 of file ElectricalProperties.hpp.
HeaderLong()
template<class VertexType = Vertices::IeeeBusType> static void egoa::Vertices::ElectricalProperties< VertexType >::HeaderLong (std::ostream & outputStream) inline static
Header out stream.
List all IEEE standard input data.
Parameters
outputStream The stream to write data to, e.g., std::cout.
Definition at line 665 of file ElectricalProperties.hpp.
IsActive()
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::ElectricalProperties< VertexType >::IsActive () const inline
Determines if the electrical vertex is active.
See also
Status
Returns
True if active (on), False otherwise (unknown).
Definition at line 626 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::Status().
Line() [1/2]
template<class VertexType = Vertices::IeeeBusType> void egoa::Vertices::ElectricalProperties< VertexType >::Line (std::ostream & outputStream, Types::real baseMva = 1) const inline
Line out stream.
List all IEEE standard input data.
Parameters
outputStream The stream to write data to, e.g., std::cout.
[in] baseMva The base MVA.
Definition at line 716 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::Area(), egoa::Vertices::ElectricalProperties< VertexType >::MaximumVoltage(), egoa::Vertices::ElectricalProperties< VertexType >::MinimumVoltage(), egoa::Vertices::ElectricalProperties< VertexType >::NominalVoltage(), egoa::Vertices::ElectricalProperties< VertexType >::ShuntConductance(), egoa::Vertices::ElectricalProperties< VertexType >::ShuntSusceptance(), egoa::Vertices::ElectricalProperties< VertexType >::VoltageAngle(), egoa::Vertices::ElectricalProperties< VertexType >::VoltageMagnitude(), and egoa::Vertices::ElectricalProperties< VertexType >::Zone().
Line() [2/2]
template<class VertexType = Vertices::IeeeBusType> void egoa::Vertices::ElectricalProperties< VertexType >::Line (std::ostream & outputStream, Types::vertexId identifier, Types::real baseMva = 1) const inline
Writes the electrical property as a line.
List all IEEE standard input data.
Parameters
outputStream The stream to write data to, e.g., std::cout.
[in] identifier The identifier.
[in] baseMva The base MVA.
Definition at line 744 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::Area(), egoa::Vertices::ElectricalProperties< VertexType >::MaximumVoltage(), egoa::Vertices::ElectricalProperties< VertexType >::MinimumVoltage(), egoa::Vertices::ElectricalProperties< VertexType >::NominalVoltage(), egoa::Vertices::ElectricalProperties< VertexType >::ShuntConductance(), egoa::Vertices::ElectricalProperties< VertexType >::ShuntSusceptance(), egoa::Vertices::ElectricalProperties< VertexType >::VoltageAngle(), egoa::Vertices::ElectricalProperties< VertexType >::VoltageMagnitude(), and egoa::Vertices::ElectricalProperties< VertexType >::Zone().
MaximumVoltage() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::ElectricalProperties< VertexType >::MaximumVoltage () inline
Getter and setter for the maximum voltage magnitude .
The voltage magnitude is in p.u.
ElectricalProperties vertex;
vertex.MaximumVoltage() = 111;
Returns
The maximum voltage magnitude .
Definition at line 431 of file ElectricalProperties.hpp.
References egoa::Bound< BoundType >::Maximum(), and egoa::Vertices::ElectricalProperties< VertexType >::voltageBound_.
MaximumVoltage() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::MaximumVoltage () const inline
Getter for the maximum voltage magnitude .
The voltage magnitude is in per unit (p.u.) of the nominal voltage .
Returns
The maximum voltage magnitude .
Definition at line 414 of file ElectricalProperties.hpp.
References egoa::Bound< BoundType >::Maximum(), and egoa::Vertices::ElectricalProperties< VertexType >::voltageBound_.
MinimumVoltage() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::ElectricalProperties< VertexType >::MinimumVoltage () inline
Getter and setter for the minimum voltage magnitude .
The voltage magnitude is in per unit (p.u.) of the nominal voltage .
ElectricalProperties vertex;
vertex.MinimumVoltage() = 0;
Returns
The minimum voltage magnitude .
Definition at line 401 of file ElectricalProperties.hpp.
References egoa::Bound< BoundType >::Minimum(), and egoa::Vertices::ElectricalProperties< VertexType >::voltageBound_.
MinimumVoltage() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::MinimumVoltage () const inline
Getter for the minimum voltage magnitude .
The voltage magnitude is in per unit (p.u.) of the nominal voltage .
Returns
The minimum voltage magnitude .
Definition at line 383 of file ElectricalProperties.hpp.
References egoa::Bound< BoundType >::Minimum(), and egoa::Vertices::ElectricalProperties< VertexType >::voltageBound_.
Name() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::name & egoa::Vertices::ElectricalProperties< VertexType >::Name () inline
Definition at line 196 of file ElectricalProperties.hpp.
Name() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::name egoa::Vertices::ElectricalProperties< VertexType >::Name () const inline
Definition at line 195 of file ElectricalProperties.hpp.
NominalVoltage() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::ElectricalProperties< VertexType >::NominalVoltage () inline
Getter and setter for the nominal voltage (also known as base voltage; in kV).
Returns
The nominal voltage in kV.
Definition at line 304 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::nominalVoltage_.
NominalVoltage() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::NominalVoltage () const inline
Getter for the nominal voltage (also known as base voltage; in kV).
Returns
The nominal voltage in kV.
Definition at line 293 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::nominalVoltage_.
operator!=()
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::ElectricalProperties< VertexType >::operator!= (ElectricalProperties< VertexType > const & rhs) const inline
Inequality comparator.
@Name Comparators
Parameters
rhs The right hand side GeneratorProperties.
Returns
True if both vertices are not equal, False otherwise.
Definition at line 118 of file ElectricalProperties.hpp.
operator==()
template<class VertexType = Vertices::IeeeBusType> bool egoa::Vertices::ElectricalProperties< VertexType >::operator== (ElectricalProperties< VertexType > const & rhs) const inline
Equality comparator.
Parameters
rhs The right hand side GeneratorProperties.
Returns
True if both vertices are equal, False otherwise.
Definition at line 131 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::Area(), egoa::Vertices::ElectricalProperties< VertexType >::Carrier(), egoa::Vertices::ElectricalProperties< VertexType >::Control(), egoa::Vertices::ElectricalProperties< VertexType >::NominalVoltage(), egoa::Vertices::ElectricalProperties< VertexType >::ShuntConductance(), egoa::Vertices::ElectricalProperties< VertexType >::ShuntSusceptance(), egoa::Vertices::ElectricalProperties< VertexType >::Status(), egoa::Vertices::ElectricalProperties< VertexType >::VoltageAngle(), egoa::Vertices::ElectricalProperties< VertexType >::voltageBound_, egoa::Vertices::ElectricalProperties< VertexType >::VoltageMagnitude(), egoa::Vertices::ElectricalProperties< VertexType >::voltageMagnitudeSq_, and egoa::Vertices::ElectricalProperties< VertexType >::Zone().
Reset()
template<class VertexType = Vertices::IeeeBusType> void egoa::Vertices::ElectricalProperties< VertexType >::Reset () inline
Reset values to default.
Definition at line 74 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::Area(), egoa::Vertices::ElectricalProperties< VertexType >::Carrier(), egoa::Vertices::ElectricalProperties< VertexType >::Control(), egoa::Vertices::ElectricalProperties< VertexType >::Country(), egoa::Vertices::ElectricalProperties< VertexType >::NominalVoltage(), egoa::Vertices::ElectricalProperties< VertexType >::ShuntConductance(), egoa::Vertices::ElectricalProperties< VertexType >::ShuntSusceptance(), egoa::Vertices::ElectricalProperties< VertexType >::Status(), egoa::Vertices::ElectricalProperties< VertexType >::VoltageAngle(), egoa::Vertices::ElectricalProperties< VertexType >::voltageBound_, egoa::Vertices::ElectricalProperties< VertexType >::VoltageMagnitude(), egoa::Vertices::ElectricalProperties< VertexType >::voltageMagnitudeSq_, and egoa::Vertices::ElectricalProperties< VertexType >::Zone().
ShuntConductance() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::ElectricalProperties< VertexType >::ShuntConductance () inline
Getter and setter for the shunt conductance .
The shunt conductance is a function . It is measured in MW demanded at a voltage of 1.0 p.u.
ElectricalProperties vertex;
vertex.ShuntConductance() = 0.11;
Returns
The shunt conductance of .
Definition at line 278 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::shuntConductance_.
ShuntConductance() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::ShuntConductance () const inline
Getter for the shunt conductance .
The shunt conductance is a function . It is measured in MW demanded at a voltage of 1.0 p.u.
Returns
The shunt conductance of .
Definition at line 258 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::shuntConductance_.
ShuntSusceptance() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::ElectricalProperties< VertexType >::ShuntSusceptance () inline
Getter and setter for the shunt susceptance .
The shunt susceptance is a function . It is measured in MVAr injected at a voltage of 1.0 p.u.
ElectricalProperties vertex;
vertex.ShuntSusceptance() = 0.11;
Returns
The shunt susceptance of .
Definition at line 243 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::shuntSusceptance_.
ShuntSusceptance() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::ShuntSusceptance () const inline
Getter for the shunt susceptance .
The shunt susceptance is a function . It is measured in MVAr injected at a voltage of 1.0 p.u.
Returns
The shunt susceptance of .
Definition at line 222 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::shuntSusceptance_.
Status() [1/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::BusStatus & egoa::Vertices::ElectricalProperties< VertexType >::Status () inline
Status of the electrical vertex.
See also
Type::Vertices::BusStatus
Returns
The status can have a different status.
Definition at line 638 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::status_.
Status() [2/2]
template<class VertexType = Vertices::IeeeBusType> Vertices::BusStatus const & egoa::Vertices::ElectricalProperties< VertexType >::Status () const inline
Status of the electrical vertex.
See also
Type::Vertices::BusStatus
Returns
The status can have a different status.
Definition at line 650 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::status_.
Type() [1/2]
template<class VertexType = Vertices::IeeeBusType> TVertexType & egoa::Vertices::ElectricalProperties< VertexType >::Type () inline
Definition at line 199 of file ElectricalProperties.hpp.
Type() [2/2]
template<class VertexType = Vertices::IeeeBusType> TVertexType egoa::Vertices::ElectricalProperties< VertexType >::Type () const inline
Definition at line 198 of file ElectricalProperties.hpp.
VoltageAngle() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::ElectricalProperties< VertexType >::VoltageAngle () inline
Getter for the voltage angle .
The voltage angle is a function . It is measured in degree.
ElectricalProperties vertex;
vertex.ShuntConductance() = 0.11;
Note
It is used for the data's snapshot and/or optimization's result.
Returns
The voltage angle at vertex .
Definition at line 370 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::voltageAngle_.
VoltageAngle() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::VoltageAngle () const inline
Getter for the voltage angle .
The voltage angle is a function . It is measured in degree.
Note
It is used for the data's snapshot and/or optimization's result.
Returns
The voltage angle at vertex .
Definition at line 348 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::voltageAngle_.
VoltageMagnitude() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::ElectricalProperties< VertexType >::VoltageMagnitude () inline
Getter and setter for the voltage magnitude .
The voltage magnitude is in per unit (p.u.) of the nominal voltage . It represents a set point.
Returns
The voltage magnitude .
Definition at line 331 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::voltageMagnitude_.
VoltageMagnitude() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::VoltageMagnitude () const inline
Getter for the voltage magnitude .
The voltage magnitude is in per unit (p.u.) of the nominal voltage . It represents a set point.
Returns
The voltage magnitude .
Definition at line 317 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::voltageMagnitude_.
X() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::ElectricalProperties< VertexType >::X () inline
Definition at line 202 of file ElectricalProperties.hpp.
X() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::X () const inline
Definition at line 201 of file ElectricalProperties.hpp.
Y() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::real & egoa::Vertices::ElectricalProperties< VertexType >::Y () inline
Definition at line 205 of file ElectricalProperties.hpp.
Y() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::Y () const inline
Definition at line 204 of file ElectricalProperties.hpp.
Zone() [1/2]
template<class VertexType = Vertices::IeeeBusType> Types::index & egoa::Vertices::ElectricalProperties< VertexType >::Zone () inline
Getter and setter for the loss zone.
A three digit integer from 0 to 999 for defining zones of loss calculation.
Note
If the value is 0 this means that there is no zone.
ElectricalProperties vertex;
vertex.Zone() = 11;
Returns
The loss zone.
Definition at line 538 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::zone_.
Zone() [2/2]
template<class VertexType = Vertices::IeeeBusType> Types::index egoa::Vertices::ElectricalProperties< VertexType >::Zone () const inline
Getter for the loss zone.
A three digit integer from 0 to 999 for defining zones of loss calculation.
Note
If the value is 0 this means that there is no zone.
Returns
The loss zone.
Definition at line 519 of file ElectricalProperties.hpp.
References egoa::Vertices::ElectricalProperties< VertexType >::zone_.
Friends And Related Symbol Documentation
operator<<
template<class VertexType = Vertices::IeeeBusType> std::ostream & operator<< (std::ostream & outputStream, TProperties const & rhs) friend
Write the electrical property to an output stream.
Parameters
outputStream The stream to write data to, e.g., std::cout.
rhs The right hand side electrical property.
Returns
The output stream.
Definition at line 776 of file ElectricalProperties.hpp.
swap
template<class VertexType = Vertices::IeeeBusType> void swap (ElectricalProperties< VertexType > & lhs, ElectricalProperties< VertexType > & rhs) friend
Swapping the members of two ElectricalVertices.
Parameters
lhs Left ElectricalProperties
rhs Right ElectricalProperties
Definition at line 161 of file ElectricalProperties.hpp.
Member Data Documentation
area_
template<class VertexType = Vertices::IeeeBusType> Types::index egoa::Vertices::ElectricalProperties< VertexType >::area_ private
Country Bus area (1 - 99) indicates in which company/region the station is located, 0 means data unavailable. A two digit integer from 0 to 99 indicating the company or region in which the line is located. This area number should be the same as the area of one of the two terminal vertices. Tie line it indicates the ownership or area to which the losses should be assigned. This area is not related to the meter bus location.
Definition at line 841 of file ElectricalProperties.hpp.
carrier_
template<class VertexType = Vertices::IeeeBusType> Vertices::EnergyCarrier egoa::Vertices::ElectricalProperties< VertexType >::carrier_ private
The energy carrier used at this bus such as AC.
Definition at line 855 of file ElectricalProperties.hpp.
control_
template<class VertexType = Vertices::IeeeBusType> Vertices::ControlType egoa::Vertices::ElectricalProperties< VertexType >::control_ private
The control type such as PV.
Definition at line 854 of file ElectricalProperties.hpp.
country_
template<class VertexType = Vertices::IeeeBusType> Types::name egoa::Vertices::ElectricalProperties< VertexType >::country_ private
Definition at line 840 of file ElectricalProperties.hpp.
name_
template<class VertexType = Vertices::IeeeBusType> Types::name egoa::Vertices::ElectricalProperties< VertexType >::name_ private
name of the vertex
Definition at line 805 of file ElectricalProperties.hpp.
nominalVoltage_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::nominalVoltage_ private
The nominal voltage also known as base voltage measured in kV.
Definition at line 819 of file ElectricalProperties.hpp.
shuntConductance_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::shuntConductance_ private
The shunt conductance .
Definition at line 814 of file ElectricalProperties.hpp.
shuntSusceptance_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::shuntSusceptance_ private
The shunt susceptance .
Definition at line 813 of file ElectricalProperties.hpp.
status_
template<class VertexType = Vertices::IeeeBusType> Vertices::BusStatus egoa::Vertices::ElectricalProperties< VertexType >::status_ private
Station status: active - true, inactive - false
Definition at line 860 of file ElectricalProperties.hpp.
type_
template<class VertexType = Vertices::IeeeBusType> TVertexType egoa::Vertices::ElectricalProperties< VertexType >::type_ private
vertex type representing either source, sink or intermediate
Definition at line 806 of file ElectricalProperties.hpp.
voltageAngle_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::voltageAngle_ private
The voltage angle that represents a snapshot of the voltage angle, i.e., final voltage angle from data.
Definition at line 822 of file ElectricalProperties.hpp.
voltageBound_
template<class VertexType = Vertices::IeeeBusType> TBound egoa::Vertices::ElectricalProperties< VertexType >::voltageBound_ private
The voltage limits in per unit (p.u.) of the nominal voltage .
Definition at line 833 of file ElectricalProperties.hpp.
voltageMagnitude_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::voltageMagnitude_ private
Voltage magnitude including a snapshot (p.u. set point), i.e., final voltage from data.
Definition at line 826 of file ElectricalProperties.hpp.
voltageMagnitudeSq_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::voltageMagnitudeSq_ private
Voltage magnitude squared variable
Definition at line 830 of file ElectricalProperties.hpp.
xCoordinate_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::xCoordinate_ private
x-coordinate of the point if available
Definition at line 807 of file ElectricalProperties.hpp.
yCoordinate_
template<class VertexType = Vertices::IeeeBusType> Types::real egoa::Vertices::ElectricalProperties< VertexType >::yCoordinate_ private
y-coordinate of the point if available
Definition at line 808 of file ElectricalProperties.hpp.
zone_
template<class VertexType = Vertices::IeeeBusType> Types::index egoa::Vertices::ElectricalProperties< VertexType >::zone_ private
Three digit integer from 0 to 999 for defining zones of loss calculation. A 0 means no zone.
Definition at line 851 of file ElectricalProperties.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Graphs/Vertices/ElectricalProperties.hpp