Energy Grid Optimization & Analysis (EGOA): egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > Class Template Reference
egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > Class Template Reference
Class for Susceptance norm label.
#include <SusceptanceNormLabel.hpp>
Public Types
using TVertexId = Types::vertexId
using TElement = ElementType
using TVertexSet = VertexSetContainer
Public Types inherited from egoa::Label< ElementType, VertexSetContainer, PointerType >
using TVertexId = Types::vertexId
using TElement = ElementType
using TVertexSet = VertexSetContainer
using TPointer = PointerType
using TLabel = Label< TElement, TVertexSet, TPointer >
Public Member Functions
Constructors and Destructor
SusceptanceNormLabel ()
Constructs the Susceptance Norm label object.
SusceptanceNormLabel (Types::vertexId vertexId)
Constructs the Susceptance Norm label object.
SusceptanceNormLabel (Types::vertexId vertexId, Types::real susceptanceNorm)
Constructs the Susceptance Norm label object.
SusceptanceNormLabel (Types::vertexId vertexId, Types::real susceptanceNorm, TVertexSet vertexSet)
Constructs the Susceptance Norm label object.
SusceptanceNormLabel (SusceptanceNormLabel const &label)=default
Copy constructor.
~SusceptanceNormLabel ()
Destroys the susceptance norm label object.
Getter and Setter
TVertexSet const & VertexSet () const
Getter of the set of all visited vertices from the source.
TVertexSet & VertexSet ()
Getter of the set of all visited vertices from the source.
Types::real SusceptanceNorm () const
Getter and setter for the susceptance norm.
Types::real & SusceptanceNorm ()
Getter and setter for the susceptance norm.
Types::real Value () const
Susceptance norm label value.
Domination Operators
bool operator< (SusceptanceNormLabel const &rhs) const
Strict domination using less than.
bool operator<= (SusceptanceNormLabel const &rhs) const
Weak domination using less or equal than.
bool operator> (SusceptanceNormLabel const &rhs) const
Strict domination using greater than.
bool operator>= (SusceptanceNormLabel const &rhs) const
Weak domination using greater or equal than.
Comparison Operators
bool operator== (SusceptanceNormLabel const &rhs) const
Equality check.
bool operator!= (SusceptanceNormLabel const &rhs) const
Inequality check.
Public Member Functions inherited from egoa::Label< ElementType, VertexSetContainer, PointerType >
Label (Types::vertexId vertexId)
Constructs the label object.
Label (Label const &label)=default
Copy constructor.
~Label ()
Destroys the label object.
Types::labelId Index () const
Getter for the label identifier.
Types::labelId & Index ()
Setter for the label identifier.
bool Valid () const
Getter for the valid flag.
bool & Valid ()
Setter for the valid flag.
Types::vertexId Vertex () const
Getter for the value of the label.
Types::vertexId & Vertex ()
Setter for the vertex identifier.
TPointer PreviousVertex () const
Getter for the previous vertex.
TPointer & PreviousVertex ()
Setter for the previous vertex.
TPointer PreviousLabel () const
Getter and setter for the previous label.
TPointer & PreviousLabel ()
Setter for the previous label.
Static Public Member Functions
static SusceptanceNormLabel SourceLabel (Types::vertexId vertexId)
Generate source label.
Private Attributes
Types::real susceptanceNorm_
TVertexSet vertexSet_
Friends
std::ostream & operator<< (std::ostream &os, SusceptanceNormLabel const &rhs)
Output stream.
Concatenation Operators
SusceptanceNormLabel & operator+= (TElement const &rhs)
In place addition.
bool operator+ (SusceptanceNormLabel const &lhs, TVertexId const &vertexId)
Addition operators testing for cycles.
std::pair< TVertexSet, bool > operator+ (TVertexId const &vertexId, SusceptanceNormLabel const &rhs)
Addition operators testing for cycles.
std::pair< SusceptanceNormLabel, bool > operator+ (TElement const &edge, SusceptanceNormLabel const &rhs)
Addition operators testing for cycles.
std::pair< SusceptanceNormLabel, bool > operator+ (SusceptanceNormLabel const &lhs, TElement const &edge)
Addition operators testing for cycles.
Detailed Description
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId>
class egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >
Class for Susceptance norm label.
The susceptance norm is defined by
where is the susceptance defined for all . For more information see Section 3 in the paper The Maximum Transmission Switching Flow Problem.
Template Parameters
ElementType An edge providing access to the susceptance, e.g., an electrical edge.
Todo:
What are the formal requirements for ElementType? From what I can see below, the following expressions must be valid:
Types::real b = element.template Susceptance<Edge::CarrierDifferentiationType::DC>();
Types::vertexId id = ...;
element.Other(id);
See also
Edge::ElectricalEdge representing an ElementType interface.
BucketElement representing an minimum interface requirement for a bucket.
Label representing the base class.
VoltageAngleDifferenceLabel representing an extension of this label.
Definition at line 44 of file SusceptanceNormLabel.hpp.
Member Typedef Documentation
TElement
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> using egoa::Label< ElementType, VertexSetContainer, PointerType >::TElement = ElementType
Some element to cover such as an edge.
Definition at line 39 of file Label.hpp.
TVertexId
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> using egoa::Label< ElementType, VertexSetContainer, PointerType >::TVertexId = Types::vertexId
The vertex identifier type used in LabelStruct.
Definition at line 37 of file Label.hpp.
TVertexSet
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> using egoa::Label< ElementType, VertexSetContainer, PointerType >::TVertexSet = VertexSetContainer
A hash map of TVertex.
Definition at line 40 of file Label.hpp.
Constructor & Destructor Documentation
SusceptanceNormLabel() [1/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNormLabel () inline
Constructs the Susceptance Norm label object.
The label and vertex identifier and previous label and vertex identifiers are set to Const::NONE. The valid flag is set to true. Note that the susceptance norm is set to infinity.
Parameters
[in] vertexId The vertex identifier.
Definition at line 66 of file SusceptanceNormLabel.hpp.
SusceptanceNormLabel() [2/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNormLabel (Types::vertexId vertexId) inline
Constructs the Susceptance Norm label object.
The label identifier and previous label/vertex identifiers are set to Const::NONE. The valid flag is set to true. Note that the susceptance norm is set to infinity.
Parameters
[in] vertexId The vertex identifier.
Definition at line 79 of file SusceptanceNormLabel.hpp.
SusceptanceNormLabel() [3/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNormLabel (Types::vertexId vertexId, Types::real susceptanceNorm) inline
Constructs the Susceptance Norm label object.
The label identifier and previous label and vertex identifiers are set to Const::NONE. The valid flag is set to true.
Parameters
[in] vertexId The vertex identifier.
[in] susceptanceNorm The susceptance norm .
Definition at line 92 of file SusceptanceNormLabel.hpp.
SusceptanceNormLabel() [4/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNormLabel (Types::vertexId vertexId, Types::real susceptanceNorm, TVertexSet vertexSet) inline
Constructs the Susceptance Norm label object.
The label identifier and previous label and vertex identifiers are set to Const::NONE. The valid flag is set to true.
Parameters
[in] vertexId The vertex identifier.
[in] susceptanceNorm The susceptance norm .
[in] vertexSet The vertex set of visited vertices.
Definition at line 107 of file SusceptanceNormLabel.hpp.
SusceptanceNormLabel() [5/5]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNormLabel (SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & label) default
Copy constructor.
Constructs the susceptance norm label object.
Parameters
label The susceptance norm label.
~SusceptanceNormLabel()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::~SusceptanceNormLabel () inline
Destroys the susceptance norm label object.
Definition at line 126 of file SusceptanceNormLabel.hpp.
Member Function Documentation
operator!=()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::operator!= (SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Inequality check.
Parameters
rhs The right hand side.
Returns
true if lhs != rhs, false otherwise.
Definition at line 242 of file SusceptanceNormLabel.hpp.
operator+=()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> SusceptanceNormLabel & egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::operator+= (TElement const & rhs) inline
In place addition.
Parameters
rhs The right hand side.
Returns
The susceptance norm label with added TElement.
Definition at line 353 of file SusceptanceNormLabel.hpp.
References egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm(), and egoa::Label< ElementType, VertexSetContainer, PointerType >::Vertex().
operator<()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::operator< (SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Strict domination using less than.
Parameters
rhs The right hand side.
Returns
true if lhs < rhs, false otherwise.
Definition at line 177 of file SusceptanceNormLabel.hpp.
References egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
operator<=()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::operator<= (SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Weak domination using less or equal than.
Parameters
rhs The right hand side.
Returns
true if lhs <= rhs, false otherwise.
Definition at line 189 of file SusceptanceNormLabel.hpp.
operator==()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::operator== (SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Equality check.
Parameters
rhs The right hand side.
Returns
true if lhs == rhs, false otherwise.
Definition at line 230 of file SusceptanceNormLabel.hpp.
References egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
operator>()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::operator> (SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Strict domination using greater than.
Parameters
rhs The right hand side.
Returns
true if lhs > rhs, false otherwise.
Definition at line 201 of file SusceptanceNormLabel.hpp.
operator>=()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::operator>= (SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & rhs) const inline
Weak domination using greater or equal than.
Parameters
rhs The right hand side.
Returns
true if lhs >= rhs, false otherwise.
Definition at line 213 of file SusceptanceNormLabel.hpp.
SourceLabel()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> static SusceptanceNormLabel egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SourceLabel (Types::vertexId vertexId) inline static
Generate source label.
Parameters
[in] vertexId The vertex identifier.
Returns
The susceptance norm source label.
Definition at line 136 of file SusceptanceNormLabel.hpp.
References egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNormLabel().
SusceptanceNorm() [1/2]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> Types::real & egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm () inline
Getter and setter for the susceptance norm.
Returns
The susceptance norm value on a path of the label.
Definition at line 388 of file SusceptanceNormLabel.hpp.
References egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::susceptanceNorm_.
SusceptanceNorm() [2/2]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> Types::real egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm () const inline
Getter and setter for the susceptance norm.
Returns
The susceptance norm value on a path of the label.
Definition at line 376 of file SusceptanceNormLabel.hpp.
References egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::susceptanceNorm_.
Value()
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> Types::real egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::Value () const inline
Susceptance norm label value.
Represents the objective of this label that is the total susceptance norm of the path.
Returns
The susceptance norm label value .
Definition at line 401 of file SusceptanceNormLabel.hpp.
References egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::SusceptanceNorm().
VertexSet() [1/2]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> TVertexSet & egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::VertexSet () inline
Getter of the set of all visited vertices from the source.
Returns
Set of all visited vertices.
Definition at line 160 of file SusceptanceNormLabel.hpp.
References egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::vertexSet_.
VertexSet() [2/2]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> TVertexSet const & egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::VertexSet () const inline
Getter of the set of all visited vertices from the source.
Returns
Set of all visited vertices.
Definition at line 150 of file SusceptanceNormLabel.hpp.
References egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::vertexSet_.
Friends And Related Symbol Documentation
operator+ [1/4]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> std::pair< SusceptanceNormLabel, bool > operator+ (SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & lhs, TElement const & edge) friend
Addition operators testing for cycles.
Parameters
lhs The susceptance norm label SusceptanceNormLabel.
edge The edge.
Returns
A pair of a LabelStruct and boolean. The boolean is true if the element could be added without creating a cycle, false otherwise.
Definition at line 337 of file SusceptanceNormLabel.hpp.
operator+ [2/4]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> bool operator+ (SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & lhs, TVertexId const & vertexId) friend
Addition operators testing for cycles.
A cycle is created if and only if the vertex is already in the set of visited vertices vertexSet.
Parameters
lhs The left hand side representing a SusceptanceNormLabel.
vertexId The vertex identifier.
Returns
true if the element could be added without creating a cycle, false otherwise.
Definition at line 263 of file SusceptanceNormLabel.hpp.
operator+ [3/4]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> std::pair< SusceptanceNormLabel, bool > operator+ (TElement const & edge, SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & rhs) friend
Addition operators testing for cycles.
Parameters
edge The edge.
rhs The susceptance norm label SusceptanceNormLabel.
Returns
A pair of a SusceptanceNormLabel and boolean. The boolean is true if the element could be added without creating a cycle, false otherwise.
Definition at line 308 of file SusceptanceNormLabel.hpp.
operator+ [4/4]
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> std::pair< TVertexSet, bool > operator+ (TVertexId const & vertexId, SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & rhs) friend
Addition operators testing for cycles.
Parameters
vertexId The vertex identifier.
rhs The right hand side representing a SusceptanceNormLabel.
Returns
A pair of a hash map and boolean. The boolean is True if the element could be added without creating a cycle, False otherwise.
Definition at line 284 of file SusceptanceNormLabel.hpp.
operator<<
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> std::ostream & operator<< (std::ostream & os, SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType > const & rhs) friend
Output stream.
Parameters
os The output stream such as std::cout.
rhs The right hand side susceptance norm label.
Returns
The output stream.
Definition at line 416 of file SusceptanceNormLabel.hpp.
Member Data Documentation
susceptanceNorm_
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> Types::real egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::susceptanceNorm_ private
The susceptance norm value on a path .
Definition at line 424 of file SusceptanceNormLabel.hpp.
vertexSet_
template<typename ElementType = Edges::Edge<Edges::ElectricalProperties>, typename VertexSetContainer = std::unordered_set<Types::vertexId>, typename PointerType = Types::vertexId> TVertexSet egoa::SusceptanceNormLabel< ElementType, VertexSetContainer, PointerType >::vertexSet_ private
The vertex set representing the set of visited vertices.
Definition at line 425 of file SusceptanceNormLabel.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Labels/SusceptanceNormLabel.hpp