Energy Grid Optimization & Analysis (EGOA): egoa::MappingBinaryHeap< ElementType, KeyType, MapType > Class Template Reference
egoa::MappingBinaryHeap< ElementType, KeyType, MapType > Class Template Reference
Class for binary heap data structure, in which elements are sorted by keys.
#include <MappingBinaryHeap.hpp>
Public Types
using TElement = ElementType
The type of the elements in the heap.
using TKey = KeyType
The type of the keys.
using TMap = MapType
The type of the mapping from elements to indices.
using TIterator = typename std::vector< std::pair< TElement, TKey > >::const_iterator
The type of the iterators.
using TComparator = std::function< bool(TKey const &, TKey const &)>
The type of the comparator.
Public Member Functions
template<ExecutionPolicy Policy, typename FUNCTION >
void for_all_elements (FUNCTION function) const
Iterates over all elements in the heap.
Constructors
MappingBinaryHeap (TComparator comparator=std::less< TKey >(), TMap map=TMap())
Constructs an empty heap, in which the elements are sorted by their keys in increasing order.
MappingBinaryHeap (std::vector< std::pair< TElement, TKey > > elementsKeyPairs, TComparator comparator=std::less< TKey >(), TMap map=TMap())
Constructs an heap containing the given elements.
template<typename It >
MappingBinaryHeap (It first, It last, TComparator comparator=std::less< TKey >(), TMap map=TMap())
Constructs the heap filled with the element-key-pairs.
Element Access
std::pair< TElement, TKey > const & Top () const
The element and the key at the top of the heap.
TElement const & TopElement () const
The element at the top of the heap.
TKey const & TopKey () const
The key of the element at the top of the heap.
TKey const & KeyOf (TElement const &element) const
The key of the element.
bool HasKeyOf (TElement const &element) const
Determines if the element exist in the heap.
Inserting Elements
void Insert (TElement element, TKey key)
Inserts the element with the given key.
void Insert (std::pair< TElement, TKey > pair)
Inserts the element with the given key.
MappingBinaryHeap & operator+= (std::pair< TElement, TKey > pair)
Inserts the element with the given key.
template<typename... Args>
void Emplace (Args &&... args)
Constructs an element-key-pair inplace.
Removing Elements
std::pair< TElement, TKey > DeleteTop ()
Deletes the top element and returns it and its key.
void Pop ()
Deletes the top element.
std::pair< TElement, TKey > Delete (TElement const &element)
Deletes an element from the heap.
void Clear ()
Removes all elements from the heap.
Updating Elements
void ChangeKey (const TElement &element, TKey newKey)
Changes the key of the element.
Capacity
bool Empty () const
Whether the heap is empty.
Types::count Size () const
The number of elements in the heap.
Comparator
std::function< bool(TKey const &, TKey const &)> const & Comparator () const
The comparator.
void Comparator (std::function< bool(TKey const &, TKey const &)> comparator)
Changes the comparator.
Iteration
TIterator begin () const
TIterator end () const
Private Member Functions
TElement & ElementAt (Types::index index)
TElement const & ElementAt (Types::index index) const
TKey & KeyAt (Types::index index)
TKey const & KeyAt (Types::index index) const
Types::index LeftChildIdOf (Types::index index) const
Types::index RightChildIdOf (Types::index index) const
bool HasChildren (Types::index index) const
bool HasLeftChild (Types::index index) const
bool HasRightChild (Types::index index) const
Types::index ParentIdOf (Types::index index) const
bool HasParent (Types::index index) const
Types::index IndexOf (TElement const &element) const
Types::index MaximumIndex () const
The largest index of elements in the heap.
void SiftUp ()
Sifts the last element in the heap up.
void SiftUp (Types::index index)
Sifts the element at index up.
void SiftDown ()
Sifts the first element in the heap down.
void SiftDown (Types::index index)
Sifts the element at index down.
void Swap (Types::index first, Types::index second)
Swaps the elements and keys at the indices first and second and updates the mapping.
Types::index SelectSwappableChildAt (Types::index index) const
Selects the smallest child, where smallest is measured according to the comparator.
bool ComplyHeapProperty () const
Whether the heap property is fulfilled.
bool ComplyHeapProperty (Types::index index) const
Whether the element at position index is smaller than its childred.
void MakeHeapProperty ()
Ensures that the heap property is satisfied.
Private Attributes
std::vector< std::pair< TElement, TKey > > elementKeyPairs_
Pairs of elements and their keys; ordered such that the heap property is satisfied.
TMap map_
The mapping from elements to indices in elementKeyPairs_.
TComparator comparator_
The comparator used to compare the keys.
Friends
void swap (MappingBinaryHeap &first, MappingBinaryHeap &second)
Swaps the contents of two heaps.
Detailed Description
template<typename ElementType, typename KeyType, typename MapType = std::unordered_map<ElementType, Types::index>>
class egoa::MappingBinaryHeap< ElementType, KeyType, MapType >
Class for binary heap data structure, in which elements are sorted by keys.
The elements and the keys are represented as separate objects. The heap supports changing the key of an element. The heap does not support having multiple keys for the same element.
Both the elements and the keys are stored in the heap.
A possible application is to store labels at the vertices of a graph. In this use case the elements are the vertices (or vertex identifiers) and the keys are the labels.
The map must support the following operations, where element is of type ElementType and i is of type Types::index.
Operation Effect
map[element] = i;
map maps element to i.
Types::index i = map.at(element);
i is set to the index of the element stored in the map.
map.erase(element);
The mapping for element is removed from map.
map.clear();
map does not contain any elements.
The methods have the following worst case time complexities:
Function Time Complexity
Top
Insert, Emplace, operator+=
DeleteTop, Pop
Delete
Clear + 1 call to map.clear()
ChangeKey + 1 call to map.at()
The comparator must implement a strict order on the keys. The smallest element according to the comparator is the top element of the heap. For example, if the comparator is std::less<TKey>(), the smallest element is at the top, and if the comparator is std::greater<TKey>, the largest element is at the top.
Template Parameters
ElementType The type of the elements
KeyType The type of the keys
MapType A mapping from elements to indices. The default is std::unordered_map<KeyType, Types::index>. To use the default KeyType must satisfy all requirements to be used as the key of a std::unordered_map.
Definition at line 72 of file MappingBinaryHeap.hpp.
Member Typedef Documentation
TComparator
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> using egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::TComparator = std::function<bool(TKey const &, TKey const &)>
The type of the comparator.
Definition at line 93 of file MappingBinaryHeap.hpp.
TElement
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> using egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::TElement = ElementType
The type of the elements in the heap.
Definition at line 77 of file MappingBinaryHeap.hpp.
TIterator
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> using egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::TIterator = typename std::vector<std::pair<TElement, TKey> >::const_iterator
The type of the iterators.
Definition at line 89 of file MappingBinaryHeap.hpp.
TKey
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> using egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::TKey = KeyType
The type of the keys.
Definition at line 81 of file MappingBinaryHeap.hpp.
TMap
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> using egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::TMap = MapType
The type of the mapping from elements to indices.
Definition at line 85 of file MappingBinaryHeap.hpp.
Constructor & Destructor Documentation
MappingBinaryHeap() [1/3]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MappingBinaryHeap (TComparator comparator = std::less<TKey>(), TMap map = TMap()) inline
Constructs an empty heap, in which the elements are sorted by their keys in increasing order.
Parameters
[in] comparator The comparator used to compare the elements.
[in] map The mapping from elements to positions in the heap.
Definition at line 104 of file MappingBinaryHeap.hpp.
MappingBinaryHeap() [2/3]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MappingBinaryHeap (std::vector< std::pair< TElement, TKey > > elementsKeyPairs, TComparator comparator = std::less<TKey>(), TMap map = TMap()) inline
Constructs an heap containing the given elements.
Parameters
[in] elementsKeyPairs The element-key-pairs.
[in] comparator The comparator used to compare the elements.
[in] map The map.
Definition at line 118 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MakeHeapProperty().
MappingBinaryHeap() [3/3]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> template<typename It > egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MappingBinaryHeap (It first, It last, TComparator comparator = std::less<TKey>(), TMap map = TMap()) inline
Constructs the heap filled with the element-key-pairs.
Parameters
[in] first The first An iterator pointing to the first element-key-pair.
[in] last The last An iterator pointing behind the last element-key-pair.
[in] comparator The comparator used to compare the elements.
[in] map The map.
Template Parameters
It An iterator pointing to std::pair<TElement, TKey>.
Definition at line 139 of file MappingBinaryHeap.hpp.
Member Function Documentation
begin()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TIterator egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::begin () const inline
Definition at line 452 of file MappingBinaryHeap.hpp.
ChangeKey()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ChangeKey (const TElement & element, TKey newKey) inline
Changes the key of the element.
Precondition
The heap contains the element.
Parameters
[in] element The element.
[in] newKey The new key.
Definition at line 380 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ComplyHeapProperty(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasKeyOf(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftDown(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftUp().
Clear()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Clear () inline
Removes all elements from the heap.
Definition at line 363 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_, and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::map_.
Comparator() [1/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> std::function< bool(TKey const &, TKey const &)> const & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Comparator () const inline
The comparator.
Returns
The comparator.
Definition at line 425 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::comparator_.
Comparator() [2/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Comparator (std::function< bool(TKey const &, TKey const &)> comparator) inline
Changes the comparator.
The heap is updated to reflect the change of the comparator.
...
heap_.Comparator([](int a, int b) { return a < b; });
...
Parameters
[in] comparator The comparator.
Definition at line 442 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::comparator_, and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MakeHeapProperty().
ComplyHeapProperty() [1/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> bool egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ComplyHeapProperty () const inline private
Whether the heap property is fulfilled.
Returns
true if the heap property is fulfilled, false otherwise.
Definition at line 617 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ComplyHeapProperty(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Size().
ComplyHeapProperty() [2/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> bool egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ComplyHeapProperty (Types::index index) const inline private
Whether the element at position index is smaller than its childred.
Parameters
[in] index The index.
Returns
true if the element is smaller than all of its children, false otherwise.
Definition at line 635 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Comparator().
Delete()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> std::pair< TElement, TKey > egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Delete (TElement const & element) inline
Deletes an element from the heap.
Parameters
element The element to delete.
Returns
A pair containing the deleted element and its key.
Definition at line 342 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasKeyOf(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::map_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MaximumIndex(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftDown(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftUp(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Swap().
DeleteTop()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> std::pair< TElement, TKey > egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::DeleteTop () inline
Deletes the top element and returns it and its key.
Precondition
The heap is not empty.
Returns
A pair containing the former top element and its key.
Definition at line 303 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ComplyHeapProperty(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::map_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MaximumIndex(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftDown(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Swap().
ElementAt() [1/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TElement & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ElementAt (Types::index index) inline private
Definition at line 491 of file MappingBinaryHeap.hpp.
ElementAt() [2/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TElement const & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ElementAt (Types::index index) const inline private
Definition at line 492 of file MappingBinaryHeap.hpp.
Emplace()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> template<typename... Args> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Emplace (Args &&... args) inline
Constructs an element-key-pair inplace.
Depending on the implementation of the map, inserting the mapping from the element to the index may create a copy of the element.
To construct both the element and the key in-place, one can use the constructor of std::pair that allows piecewise construction.
#include <tuple>
...
Emplace(std::piecewise_construct,
        std::forward_as_tuple(/* constructor arguments of element */),
        std::forward_as_tuple(/* constructor arguments of key */));
Parameters
args The arguments of the constructor of std::pair.
Template Parameters
Args The types of the constructor arguments.
Definition at line 284 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::map_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MaximumIndex(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftUp().
Empty()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> bool egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty () const inline
Whether the heap is empty.
Returns
true if the heap is empty, false otherwise.
Definition at line 401 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_.
end()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TIterator egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::end () const inline
Definition at line 453 of file MappingBinaryHeap.hpp.
for_all_elements()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> template<ExecutionPolicy Policy, typename FUNCTION > void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::for_all_elements (FUNCTION function) const inline
Iterates over all elements in the heap.
Parameters
[in] function The function object that is called for all elements in the heap. It must accept one argument of type std::pair<TElement, TKey>, e.g.,
[](std::pair<TElement, TKey> const & element) { ... }
Template Parameters
Policy The execution policy.
FUNCTION The type of the function object.
Definition at line 472 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_.
HasChildren()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> bool egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasChildren (Types::index index) const inline private
Definition at line 498 of file MappingBinaryHeap.hpp.
HasKeyOf()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> bool egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasKeyOf (TElement const & element) const inline
Determines if the element exist in the heap.
Parameters
element The element.
Returns
True if the element exists, False otherwise.
Definition at line 209 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::map_.
HasLeftChild()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> bool egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasLeftChild (Types::index index) const inline private
Definition at line 499 of file MappingBinaryHeap.hpp.
HasParent()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> bool egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasParent (Types::index index) const inline private
Definition at line 502 of file MappingBinaryHeap.hpp.
HasRightChild()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> bool egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasRightChild (Types::index index) const inline private
Definition at line 500 of file MappingBinaryHeap.hpp.
IndexOf()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> Types::index egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::IndexOf (TElement const & element) const inline private
Definition at line 504 of file MappingBinaryHeap.hpp.
Insert() [1/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Insert (std::pair< TElement, TKey > pair) inline
Inserts the element with the given key.
Precondition
The heap does not contain the element.
Parameters
[in] pair The pair containing the element (first position) and the key (second position).
Definition at line 238 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasKeyOf(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::map_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MaximumIndex(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftUp().
Insert() [2/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Insert (TElement element, TKey key) inline
Inserts the element with the given key.
Precondition
The heap does not contain the element.
Parameters
element The element.
key The key.
Definition at line 225 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasKeyOf(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Insert().
KeyAt() [1/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TKey & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::KeyAt (Types::index index) inline private
Definition at line 493 of file MappingBinaryHeap.hpp.
KeyAt() [2/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TKey const & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::KeyAt (Types::index index) const inline private
Definition at line 494 of file MappingBinaryHeap.hpp.
KeyOf()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TKey const & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::KeyOf (TElement const & element) const inline
The key of the element.
Precondition
The heap must contain the element.
Parameters
element The element.
Returns
The key of the element.
Definition at line 197 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::HasKeyOf().
LeftChildIdOf()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> Types::index egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::LeftChildIdOf (Types::index index) const inline private
Definition at line 496 of file MappingBinaryHeap.hpp.
MakeHeapProperty()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MakeHeapProperty () inline private
Ensures that the heap property is satisfied.
Definition at line 645 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ComplyHeapProperty(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftDown(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Size().
MaximumIndex()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> Types::index egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MaximumIndex () const inline private
The largest index of elements in the heap.
Returns
The largest index of elements in the heap.
Definition at line 513 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_.
operator+=()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> MappingBinaryHeap & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::operator+= (std::pair< TElement, TKey > pair) inline
Inserts the element with the given key.
Equivalent to Insert(pair).
Precondition
The heap does not contain the element.
Parameters
[in] pair The pair containing the element (first position) and the key (second position).
Returns
The heap.
Definition at line 258 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Insert().
ParentIdOf()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> Types::index egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ParentIdOf (Types::index index) const inline private
Definition at line 501 of file MappingBinaryHeap.hpp.
Pop()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Pop () inline
Deletes the top element.
Precondition
The heap is not empty.
Definition at line 323 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::ComplyHeapProperty(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::map_, egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MaximumIndex(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftDown(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Swap().
RightChildIdOf()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> Types::index egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::RightChildIdOf (Types::index index) const inline private
Definition at line 497 of file MappingBinaryHeap.hpp.
SelectSwappableChildAt()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> Types::index egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SelectSwappableChildAt (Types::index index) const inline private
Selects the smallest child, where smallest is measured according to the comparator.
Parameters
[in] index The current index.
Returns
The index of the child that has the smallest key.
Definition at line 596 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Comparator().
SiftDown() [1/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftDown () inline private
Sifts the first element in the heap down.
Precondition
The heap is not empty.
Definition at line 548 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftDown().
SiftDown() [2/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftDown (Types::index index) inline private
Sifts the element at index down.
Precondition
The index is valid.
Parameters
[in] index The index.
Definition at line 560 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Comparator(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SelectSwappableChildAt(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Size(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Swap().
SiftUp() [1/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftUp () inline private
Sifts the last element in the heap up.
Precondition
The heap is not empty.
Definition at line 522 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::MaximumIndex(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftUp().
SiftUp() [2/2]
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::SiftUp (Types::index index) inline private
Sifts the element at index up.
Precondition
The index is valid.
Parameters
[in] index The index.
Definition at line 534 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Comparator(), egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Size(), and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Swap().
Size()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> Types::count egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Size () const inline
The number of elements in the heap.
Returns
The number of elements in the heap.
Definition at line 410 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_.
Swap()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Swap (Types::index first, Types::index second) inline private
Swaps the elements and keys at the indices first and second and updates the mapping.
Parameters
[in] first The first index.
[in] second The second index.
Definition at line 579 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::map_, and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::swap.
Top()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> std::pair< TElement, TKey > const & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Top () const inline
The element and the key at the top of the heap.
Precondition
The heap is not empty.
Returns
A pair containing the element and the key at the top of the heap.
Definition at line 159 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_, and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty().
TopElement()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TElement const & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::TopElement () const inline
The element at the top of the heap.
Precondition
The heap is not empty.
Returns
The element at the top of the heap.
Definition at line 171 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_, and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty().
TopKey()
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TKey const & egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::TopKey () const inline
The key of the element at the top of the heap.
Precondition
The heap is not empty.
Returns
The key of the element at the top of the heap.
Definition at line 183 of file MappingBinaryHeap.hpp.
References egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_, and egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::Empty().
Friends And Related Symbol Documentation
swap
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> void swap (MappingBinaryHeap< ElementType, KeyType, MapType > & first, MappingBinaryHeap< ElementType, KeyType, MapType > & second) friend
Swaps the contents of two heaps.
Parameters
first The first heap.
second The second heap.
Definition at line 483 of file MappingBinaryHeap.hpp.
Member Data Documentation
comparator_
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TComparator egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::comparator_ private
The comparator used to compare the keys.
Definition at line 668 of file MappingBinaryHeap.hpp.
elementKeyPairs_
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> std::vector<std::pair<TElement, TKey> > egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::elementKeyPairs_ private
Pairs of elements and their keys; ordered such that the heap property is satisfied.
Definition at line 660 of file MappingBinaryHeap.hpp.
map_
template<typename ElementType , typename KeyType , typename MapType = std::unordered_map<ElementType, Types::index>> TMap egoa::MappingBinaryHeap< ElementType, KeyType, MapType >::map_ private
The mapping from elements to indices in elementKeyPairs_.
Definition at line 664 of file MappingBinaryHeap.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Container/Queues/MappingBinaryHeap.hpp