Energy Grid Optimization & Analysis (EGOA): egoa::BFS< GraphType, QueueType, IsDirected > Class Template Reference
egoa::BFS< GraphType, QueueType, IsDirected > Class Template Reference final
Class for the Breadth-First Search (BFS).
#include <BreadthFirstSearch.hpp>
Public Types
using TQueue = QueueType
Public Member Functions
BFS (TGraph const &graph, TVertex source)
virtual void Run ()
Run Breadth-First search (BFS).
Private Member Functions
void EnqueueVertexWith (TVertex vertexId)
Add a vertex to the queue.
TVertex DequeueVertex ()
Get the next unprocessed vertex.
virtual void PreprocessingVertexWith (TVertex vertexId) override
virtual void PostprocessingVertexWith (TVertex vertexId) override
virtual void ProcessingEdgeWith (TVertex sourceId, TVertex targetId) override
Private Member Functions inherited from egoa::Traversal< GraphType, IsDirected >
virtual void Result (std::vector< TVertexId > parent)
Traversal (TGraph const &graph, TVertexId source)
Constructs a new instance.
TVertexId Source () const
Getter and setter for the source vertex.
TVertexId & Source ()
TVertexId & ParentOf (TVertexId vertexId)
Getter and setter for the parent relation.
TVertexId ParentOf (TVertexId vertexId) const
void Clear ()
Clear and resize all vectors.
bool VertexExists (TVertexId vertexId)
bool NumberOfVertices ()
void SetVertexVisitedAt (TVertexId vertexId)
Sets the vertex at vertexId to visited.
bool VisitedVertexAt (TVertexId vertexId) const
Getter and setter to access the visited field.
void SetVertexProcessedAt (TVertexId vertexId)
Sets the vertex at vertexId to processed.
bool ProcessedVertexAt (TVertexId vertexId) const
Getter and setter to access the process field.
template<typename FUNCTION >
void breakable_for_all_edges_at (TVertexId const &vertexId, FUNCTION function) const
The for loop over all (outgoing) edges that is breakable.
template<typename FUNCTION >
void for_all_edges_at (TVertexId const &vertexId, FUNCTION function) const
The for loop over all (outgoing) edges.
Private Attributes
TQueue queue_
Additional Inherited Members
Private Types inherited from egoa::Traversal< GraphType, IsDirected >
using TGraph = GraphType
using TVertexId = typename GraphType::TVertexId
Detailed Description
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false>
class egoa::BFS< GraphType, QueueType, IsDirected >
Class for the Breadth-First Search (BFS).
BFS uses a queue that processes the vertices in First-in, First-out (FiFo) order. Thus, the traversal of a graph is level-wise. Not that if the graph G=(V,E) is undirected chords (non-tree edges) can only be between vertices on the same level or one level below (as the vertex would have been visited in the next step). For directed graphs, an chord (u,v) in E can only exists if v's level is higher (closer to the source vertex s) than u's.
The run time is in O(n + m).
Precondition
The queue uses the Type Types::vertexId. Note that the queue does not need to implement the element-wise loops.
Template Parameters
GraphType The graph should at least provide the same interface as the StaticGraph().
QueueType The queue should provide the same interface as Queue().
IsDirected If true the graph is treated as a directed graph, if false the graph is treated as an undirected graph.
Definition at line 39 of file BreadthFirstSearch.hpp.
Member Typedef Documentation
TQueue
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> using egoa::BFS< GraphType, QueueType, IsDirected >::TQueue = QueueType
Definition at line 42 of file BreadthFirstSearch.hpp.
Constructor & Destructor Documentation
BFS()
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> egoa::BFS< GraphType, QueueType, IsDirected >::BFS (TGraph const & graph, TVertex source) inline
Definition at line 46 of file BreadthFirstSearch.hpp.
~BFS()
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> virtual egoa::BFS< GraphType, QueueType, IsDirected >::~BFS () inline virtual
Definition at line 51 of file BreadthFirstSearch.hpp.
Member Function Documentation
DequeueVertex()
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> TVertex egoa::BFS< GraphType, QueueType, IsDirected >::DequeueVertex () inline private
Get the next unprocessed vertex.
A vertex can only be dequeued if it is was marked as visited.
Returns
The next unprocessed but visited vertex.
Definition at line 110 of file BreadthFirstSearch.hpp.
References egoa::Traversal< GraphType, IsDirected >::graph_, and egoa::BFS< GraphType, QueueType, IsDirected >::queue_.
EnqueueVertexWith()
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> void egoa::BFS< GraphType, QueueType, IsDirected >::EnqueueVertexWith (TVertex vertexId) inline private
Add a vertex to the queue.
Precondition
Only visited vertices that are unprocessed should be add to the queue.
Parameters
[in] vertexId The vertex identifier.
Definition at line 98 of file BreadthFirstSearch.hpp.
References egoa::Traversal< GraphType, IsDirected >::graph_, and egoa::BFS< GraphType, QueueType, IsDirected >::queue_.
PostprocessingVertexWith()
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> virtual void egoa::BFS< GraphType, QueueType, IsDirected >::PostprocessingVertexWith (TVertex vertexId) inline override private virtual
Definition at line 120 of file BreadthFirstSearch.hpp.
PreprocessingVertexWith()
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> virtual void egoa::BFS< GraphType, QueueType, IsDirected >::PreprocessingVertexWith (TVertex vertexId) inline override private virtual
Definition at line 119 of file BreadthFirstSearch.hpp.
ProcessingEdgeWith()
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> virtual void egoa::BFS< GraphType, QueueType, IsDirected >::ProcessingEdgeWith (TVertex sourceId, TVertex targetId) inline override private virtual
Definition at line 121 of file BreadthFirstSearch.hpp.
Run()
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> virtual void egoa::BFS< GraphType, QueueType, IsDirected >::Run () inline virtual
Run Breadth-First search (BFS).
Definition at line 57 of file BreadthFirstSearch.hpp.
References egoa::BFS< GraphType, QueueType, IsDirected >::DequeueVertex(), egoa::BFS< GraphType, QueueType, IsDirected >::EnqueueVertexWith(), egoa::Traversal< GraphType, IsDirected >::for_all_edges_at(), egoa::Traversal< GraphType, IsDirected >::graph_, egoa::Traversal< GraphType, IsDirected >::ParentOf(), egoa::Traversal< GraphType, IsDirected >::ProcessedVertexAt(), egoa::BFS< GraphType, QueueType, IsDirected >::queue_, egoa::Traversal< GraphType, IsDirected >::SetVertexProcessedAt(), egoa::Traversal< GraphType, IsDirected >::SetVertexVisitedAt(), egoa::Traversal< GraphType, IsDirected >::source_, and egoa::Traversal< GraphType, IsDirected >::VisitedVertexAt().
Member Data Documentation
queue_
template<typename GraphType = StaticGraph<Vertices::ElectricalProperties<>,Edges::ElectricalProperties>, typename QueueType = StdQueue<GraphType::TVertexId>, bool IsDirected = false> TQueue egoa::BFS< GraphType, QueueType, IsDirected >::queue_ private
The FIFO queue
Definition at line 126 of file BreadthFirstSearch.hpp.
The documentation for this class was generated from the following file:
include/Algorithms/GraphTraversal/BreadthFirstSearch.hpp