Energy Grid Optimization & Analysis (EGOA): egoa::UnionFind Class Reference
egoa::UnionFind Class Reference
This class describes an union find.
#include <UnionFind.hpp>
Public Member Functions
UnionFind (Types::count numberOfVertices)
Types::vertexId Find (Types::vertexId vertex)
Find the root of the vertex @detail Find the tree root of element vertex and return the root's identifier.
void Union (Types::vertexId u, Types::vertexId v)
Merges the two subtrees—if exist—of both components together.
bool InSameComponent (Types::vertexId u, Types::vertexId v)
Are both vertices in the same component.
Types::count NumberOfVertices ()
Types::vertexId & Parent (Types::vertexId vertex)
Types::vertexId Parent (Types::vertexId vertex) const
Types::count & SubtreeSize (Types::vertexId vertex)
Types::count SubtreeSize (Types::vertexId vertex) const
Private Attributes
std::vector< Types::vertexId > parent_
std::vector< Types::count > numberOfVerticesInSubtree_
Types::count numberOfVertices_
Detailed Description
This class describes an union find.
Definition at line 19 of file UnionFind.hpp.
Constructor & Destructor Documentation
UnionFind()
egoa::UnionFind::UnionFind (Types::count numberOfVertices) inline
Definition at line 21 of file UnionFind.hpp.
Member Function Documentation
Find()
Types::vertexId egoa::UnionFind::Find (Types::vertexId vertex) inline
Find the root of the vertex @detail Find the tree root of element vertex and return the root's identifier.
Parameters
[in] vertex The vertex identifier.
Returns
The root's identifier.
Definition at line 44 of file UnionFind.hpp.
References Find().
InSameComponent()
bool egoa::UnionFind::InSameComponent (Types::vertexId u, Types::vertexId v) inline
Are both vertices in the same component.
Parameters
[in] u The vertex u.
[in] v The vertex v.
Returns
If they are in the same component
Definition at line 82 of file UnionFind.hpp.
References Find().
NumberOfVertices()
Types::count egoa::UnionFind::NumberOfVertices () inline
@Name Getter and setter
Definition at line 89 of file UnionFind.hpp.
Parent() [1/2]
Types::vertexId & egoa::UnionFind::Parent (Types::vertexId vertex) inline
Definition at line 94 of file UnionFind.hpp.
Parent() [2/2]
Types::vertexId egoa::UnionFind::Parent (Types::vertexId vertex) const inline
Definition at line 101 of file UnionFind.hpp.
SubtreeSize() [1/2]
Types::count & egoa::UnionFind::SubtreeSize (Types::vertexId vertex) inline
Definition at line 108 of file UnionFind.hpp.
SubtreeSize() [2/2]
Types::count egoa::UnionFind::SubtreeSize (Types::vertexId vertex) const inline
Definition at line 114 of file UnionFind.hpp.
Union()
void egoa::UnionFind::Union (Types::vertexId u, Types::vertexId v) inline
Merges the two subtrees—if exist—of both components together.
Parameters
[in] u The vertex u
[in] v The vertex v
Definition at line 57 of file UnionFind.hpp.
References Find().
Member Data Documentation
numberOfVertices_
Types::count egoa::UnionFind::numberOfVertices_ private
Definition at line 124 of file UnionFind.hpp.
numberOfVerticesInSubtree_
std::vector<Types::count> egoa::UnionFind::numberOfVerticesInSubtree_ private
Definition at line 123 of file UnionFind.hpp.
parent_
std::vector<Types::vertexId> egoa::UnionFind::parent_ private
Definition at line 122 of file UnionFind.hpp.
The documentation for this class was generated from the following file:
include/DataStructures/Container/UnionFind.hpp