# Doxygen.cmake
#
#   Created on: 30.01.2019
#       Author: Franziska Wegner
#
# If EGOA_ENABLE_DOCUMENTATION is ON the script add target to generate API
# documentation with Doxygen. The documentation can then be generated by the
# command "make doc".
#

####################################################################
# Find Doxygen #####################################################
####################################################################
if(EGOA_ENABLE_DOCUMENTATION)
    find_package(Doxygen)
    if(NOT DOXYGEN_FOUND)
        message(FATAL_ERROR "Doxygen is needed to build the documentation.")
    endif()
    message("SRC=${CMAKE_CURRENT_SOURCE_DIR} and Binary=${CMAKE_CURRENT_BINARY_DIR}")
    set(doxyfile_in ${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile.in)
    set(doxyfile ${CMAKE_CURRENT_SOURCE_DIR}/documentation/Doxyfile)

    configure_file(${doxyfile_in} ${doxyfile} @ONLY)
    add_custom_target(doc ALL
                COMMAND ${DOXYGEN_EXECUTABLE} ${doxyfile_in}
                WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
                COMMENT "Generating API documentation with Doxygen"
                VERBATIM)
endif(EGOA_ENABLE_DOCUMENTATION)

####################################################################
# Output ###########################################################
####################################################################
message(STATUS "${MY_SPACE}Doxygen:\t\t\t${DOXYGEN_EXECUTABLE}")
